// Lexicon Haftarot — partea 2 (restul cuvintelor din Isaia 42:5-43:10)
module.exports = {
  H589: { d: 'eu.', x: 'Ani, „eu”, pus înaintea numelui divin („Eu sunt DOMNUL”), formează o declarație solemnă de identitate, ca la începutul celor Zece Porunci (Exodul 20:2, unde apare forma mai lungă anohi). Isaia 42-45 o repetă de multe ori, ca răspuns la pretențiile zeilor neamurilor.', g: 'ἐγώ', gd: 'eu.' },
  H8478: { d: 'sub, dedesubt; în locul, în schimbul.', x: 'Tahat înseamnă „sub” și, prin extensie, „în locul, în schimbul”. Isaia 43:3-4 îl folosește de trei ori la rând: Dumnezeu dă popoare „în locul” lui Israel — limbajul răscumpărării, în care un preț ține locul celui eliberat.', g: 'ὑπέρ', gd: 'pentru, în locul, în folosul.' },
  H3816: { d: 'neam, popor (cuvânt poetic).', x: 'Leom, „neam, popor”, e un cuvânt poetic, folosit mai ales în paralel cu am sau goi. În Isaia 43:4, dăruirea de popoare „în schimbul” lui Israel arată cât de mult își prețuiește Dumnezeu poporul.', g: 'ἄρχων', gd: 'căpetenie, conducător.' },
  H4310: { d: 'cine?', x: 'Mi, „cine?”, deschide în Isaia 40-48 multe întrebări retorice prin care Dumnezeu Își arată unicitatea: „Cine a vestit acestea de la început?”. Răspunsul așteptat e mereu același — numai DOMNUL.', g: 'τίς', gd: 'cine?' },
  H2388: { d: 'a fi tare; la forma hifil, a apuca, a ține strâns, a întări.', x: 'Hazak înseamnă „a fi tare”; la forma hifil, „a apuca cu putere, a ține strâns”. Din aceeași rădăcină vine urarea hazak, „fii tare”, rostită în sinagogă la încheierea citirii fiecărei cărți a Torei.', g: 'κρατέω', gd: 'a apuca, a ține cu putere.' },
  H7892: { d: 'cântare, cântec.', x: 'Șir, „cântarea”, e numele dat marilor cântări ale Scripturii: Cântarea Mării (Exodul 15:1), Cântarea cântărilor (Șir hașirim). „Cântarea nouă” e cea stârnită de o faptă nouă a lui Dumnezeu.', g: 'ὕμνος', gd: 'imn, cântare de laudă.' },
  H7891: { g: 'ὑμνέω', gd: 'a cânta imnuri, a lăuda prin cântare.' },
  H3381: { d: 'a coborî.', x: 'Iarad, „a coborî”; „cei ce coboară la mare” (iordei haiam) e expresia ebraică pentru navigatori (Psalmul 107:23), pentru că drumul spre porturi cobora de pe dealurile locuite. Din aceeași rădăcină e explicat de obicei numele Iordanului, „cel ce coboară”.', g: 'καταβαίνω', gd: 'a coborî.' },
  H3220: { d: 'mare; uneori, apus (în direcția mării).', x: 'Iam, „marea”; pentru Israel, mai ales Mediterana, „Marea cea Mare”, aflată la apus — de aceea iam înseamnă și „apus”. În poezia biblică, marea e și imaginea forțelor haotice pe care numai Dumnezeu le stăpânește.', g: 'θάλασσα', gd: 'mare.' },
  H5782: { d: 'a se trezi; la forma hifil, a trezi, a stârni.', x: 'Ur, „a se trezi”; la forma hifil, „a trezi, a stârni”. Isaia folosește verbul și pentru Cirus, pe care Dumnezeu îl „stârnește” de la răsărit (Isaia 41:2).', g: 'ἐπεγείρω', gd: 'a stârni, a ridica împotriva cuiva.' },
  H7068: { g: 'ζῆλος', gd: 'râvnă, gelozie.' },
  H1368: { g: 'δύναμις', gd: 'putere; la plural, oștiri.' },
  H341: { g: 'ἐχθρός', gd: 'dușman.' },
  H1396: { g: 'ἰσχύς', gd: 'putere, tărie.' },
  H7321: { d: 'a striga, a da semnalul de luptă; a chiui.', g: 'βοάω', gd: 'a striga.' },
  H6873: { d: 'a striga cu glas puternic.' },
  H5769: { d: 'veșnicie; timp îndelungat, din vechime.', x: 'Olam desemnează un timp foarte lung, a cărui margine nu se vede — „veșnicie” înainte, „vechime” înapoi. Aici, meolam înseamnă „de multă vreme”: Dumnezeu a tăcut îndelung față de suferința poporului Său.', g: 'ἀεί', gd: 'mereu, totdeauna.' },
  H2790: { d: 'a tăcea; a fi surd; (altă rădăcină) a ara, a grava.', x: 'Hareș are două sensuri înrudite: „a tăcea” și „a fi surd” (de aici heres, „surd”); o rădăcină cu aceleași litere înseamnă „a ara, a grava”. Aici, în paralel cu heheșeti, subliniază tăcerea îndelungată a lui Dumnezeu.', g: 'σιωπάω', gd: 'a tăcea.' },
  H2814: { g: 'σιωπάω', gd: 'a tăcea.' },
  H662: { g: 'ἀνέχω', gd: 'a răbda, a se stăpâni.' },
  H3205: { g: 'τίκτω', gd: 'a naște.' },
  H5395: { d: 'a gâfâi, a sufla greu.', x: 'Nașam, „a gâfâi”, apare numai aici în Biblia ebraică; e înrudit cu neșama, „suflarea”. Descrie respirația sacadată a femeii care naște — imaginea lui Dumnezeu care nu Își mai poate stăpâni reacția față de suferința poporului.' },
  H7602: { g: 'ξηραίνω', gd: 'a usca.' },
  H1389: { d: 'deal, colină.', x: 'Givea, „colina”; munții și dealurile apar adesea în pereche în poezia biblică. Pe coline se aflau „înălțimile”, locurile de cult idolatru pe care profeții le osândesc.', g: 'βουνός', gd: 'colină, deal.' },
  H4625: { g: 'σκολιός', gd: 'strâmb, întortocheat.' },
  H4334: { g: 'εὐθύς', gd: 'drept, neted.' },
  H5800: { g: 'ἐγκαταλείπω', gd: 'a părăsi, a lăsa în urmă.' },
  H268: { d: 'partea din spate; înapoi, în urmă; (despre timp) după, mai târziu.', x: 'Ahor, „partea din spate”; ca adverb, „înapoi”. „A se da înapoi” (nasog ahor) e imaginea înfrângerii, a armatei care fuge (Isaia 42:17); iar leahor înseamnă „pentru vremea ce vine” (Isaia 42:23).', g: 'ὀπίσω', gd: 'înapoi, în urmă.' },
  H5027: { g: 'ἀναβλέπω', gd: 'a-și ridica privirea; a-și recăpăta vederea.' },
  H7999: { d: 'a fi întreg, a fi în pace; la pual, desăvârșit, cel răsplătit.' },
  H7227: { d: 'mult, numeros; mare.', x: 'Rav, „mult, mare”, e rădăcina din care vine titlul rav (și rabi), „învățătorul”, literal „cel mare”. Aici, rabot, „multe”, subliniază că poporul a văzut destule semne ca să înțeleagă.', g: 'πλεονάκις', gd: 'de multe ori.' },
  H142: { d: 'a fi măreț; la forma hifil, a face glorios.' },
  H962: { g: 'προνομεύω', gd: 'a prăda, a jefui.' },
  H8154: { d: 'a jefui, a prăda.', x: 'Șasa, „a jefui”, e un verb rar (de 11 ori în Biblia ebraică); aici e pus alături de baz, „a prăda”, iar perechea de verbe descrie un popor lăsat fără apărare în mâna dușmanilor.', g: 'διαρπάζω', gd: 'a jefui, a răpi.' },
  H6351: { d: 'a prinde în laț; la forma hifil, a fi prins ca într-o capcană.', x: 'Verbul vine de la pah, „lațul” păsărarului: a fi prins în laț e imaginea omului prins fără scăpare. Septuaginta a înțeles cuvântul ca substantiv, „lațul” (παγίς).', g: 'παγίς', gd: 'laț, capcană.' },
  H2352: { d: 'gaură, groapă; temniță săpată în pământ.', x: 'Hur înseamnă „gaură, groapă”; bahurim, „în gropi”, descrie temnițele săpate în pământ în care erau ținuți prizonierii. Cuvântul apare numai de două ori în Biblia ebraică, amândouă în Isaia.', g: 'ταμιεῖον', gd: 'cămară, încăpere ascunsă.' },
  H3608: { g: 'φυλακή', gd: 'pază; închisoare.' },
  H2244: { d: 'a ascunde; la forma hofal, a fi ascuns, a fi ținut închis.', x: 'Hava înseamnă „a ascunde”; la forma hofal, „a fi ascuns”, aici despre prizonierii ținuți departe de ochii lumii. Același verb descrie pe Adam și Eva, care se ascund de Dumnezeu după păcat (Geneza 3:8).', g: 'κρύπτω', gd: 'a ascunde.' },
  H957: { d: 'pradă, jaf.', x: 'Baz, „prada”; expresia „a fi de pradă” (haia lavaz) descrie un popor predat dușmanului. Profeții o folosesc des pentru urmările părăsirii lui Dumnezeu (Ieremia 2:14).', g: 'προνομή', gd: 'pradă, jaf.' },
  H5337: { d: 'a scoate, a smulge; a izbăvi, a salva.', x: 'Națal înseamnă propriu-zis „a smulge” pe cineva din mâna altuia; la forma hifil, „a izbăvi”. Participiul mațil, „izbăvitorul”, apare mai ales în formula „și nu e nimeni care să izbăvească” (Deuteronomul 32:39).', g: 'ἐξαιρέω', gd: 'a scoate afară, a izbăvi.' },
  H4933: { d: 'jaf, pradă.', x: 'Meșisa, „jaful”, din rădăcina șasa, „a jefui”, e un cuvânt rar (de șase ori în Biblia ebraică), folosit de profeți pentru soarta unui popor lăsat fără ocrotire. În Isaia 42:22-24 apare de două ori, iar întrebarea „Cine l-a dat pe Iacov pradă?” primește chiar răspunsul: DOMNUL, din pricina păcatului.', g: 'διαρπαγή', gd: 'jaf, jefuire.' },
  H7725: { g: 'ἀποδίδωμι', gd: 'a da înapoi, a restitui.' },
  H238: { g: 'ἐνωτίζομαι', gd: 'a asculta cu atenție (literal, „a primi în ureche”).' },
  H7181: { d: 'a lua aminte, a asculta cu atenție.', g: 'εἰσακούω', gd: 'a asculta, a da ascultare.' },
  H14: { d: 'a voi, a consimți; cu negație, a refuza.', x: 'Ava înseamnă „a voi, a consimți”; aproape întotdeauna apare însoțit de negație — „n-au vrut”. Același verb descrie refuzul lui Israel de a primi chemarea lui Dumnezeu la liniște și încredere (Isaia 30:15).', g: 'βούλομαι', gd: 'a voi.' },
  H8210: { d: 'a vărsa, a revărsa.' },
  H2534: { g: 'ὀργή', gd: 'mânie.' },
  H5807: { d: 'putere, tărie, violență.', x: 'Ezuz, „tăria, violența”, e un cuvânt rar (de trei ori în Biblia ebraică), din rădăcina azaz, „a fi tare”; „tăria războiului” e toată forța distrugătoare a luptei.' },
  H3857: { g: 'συμφλέγω', gd: 'a arde de jur împrejur, a aprinde deodată.' },
  H5439: { g: 'κύκλος', gd: 'cerc; κύκλῳ — de jur împrejur.' },
  H854: { d: 'cu, lângă, alături de.', x: 'Et (aici itha, „cu tine”) exprimă prezența ocrotitoare; formula „Eu sunt cu tine” revine de două ori în această profeție (Isaia 43:2; 43:5) ca temei al îndemnului „nu te teme”.', g: 'μετά', gd: 'cu, împreună cu.' },
  H7857: { d: 'a inunda, a potopi; a spăla.', x: 'Șataf, „a inunda”, descrie puhoiul care mătură totul în cale; la Isaia 8:8, apele care „inundă” sunt armata asiriană. Făgăduința „râurile nu te vor inunda” (Isaia 43:2) răspunde tocmai acestei amenințări.', g: 'συγκλύζω', gd: 'a inunda, a acoperi cu valuri.' },
  H3554: { d: 'a se arde, a se pârli.', x: 'Kava, „a arde, a pârli”, e înrudit cu kevia, „arsura” (Exodul 21:25). Făgăduința „nu vei fi ars” (Isaia 43:2) arată că focul încercării nu îl va nimici pe cel ocrotit de Dumnezeu.', g: 'κατακαίω', gd: 'a arde de tot.' },
  H3852: { d: 'flacără; tăișul lucitor al unei arme.', x: 'Lehava, „flacăra”, înseamnă și tăișul care strălucește ca focul (1 Samuel 17:7). În Isaia 43:2, flacăra completează imaginea focului prin care trece poporul fără să fie mistuit.', g: 'φλόξ', gd: 'flacără.' },
  H3724: { d: 'preț de răscumpărare; (în alte contexte) smoală, sat.', x: 'Kofer e prețul plătit ca să răscumpere o viață (Exodul 21:30), din rădăcina kafar, „a acoperi, a ispăși” — aceeași din care vine Iom Kipur. Isaia 43:3 spune că Dumnezeu a dat Egiptul drept „kofer” pentru Israel.', g: 'ἄλλαγμα', gd: 'lucru dat în schimb, preț de schimb.' },
  H5434: { d: 'Seva (Saba) — popor din neamul lui Cuș, în Africa.', x: 'Seva a fost un fiu al lui Cuș (Geneza 10:7), iar numele desemnează un popor din Africa, înrudit cu Cușul (Nubia). Nu trebuie confundat cu Șeva, regatul Reginei din Saba (1 Împărați 10:1), din sudul Arabiei.', g: 'Σοήνη', gd: 'Syene — oraș din sudul Egiptului (Assuanul de azi).' },
  H3365: { g: 'ἔντιμος', gd: 'prețuit, cinstit.' },
  H3513: { g: 'δοξάζω', gd: 'a slăvi; la pasiv, a fi slăvit.' },
  H3607: { d: 'a opri, a reține, a închide.', g: 'κωλύω', gd: 'a împiedica, a opri.' },
  H616: { g: 'δεδεμένος', gd: 'cel legat, prizonier.' },
  H4525: { g: 'δεσμός', gd: 'legătură, lanț; la plural, închisoare.' },
  H2822: { g: 'σκότος', gd: 'întuneric.' },
  H312: { g: 'ἕτερος', gd: 'altul, un altul.' },
  H7223: { g: 'ἀρχή', gd: 'început.' },
  H2009: { g: 'ἰδού', gd: 'iată!' },
  H2962: { d: 'încă nu; beterem — înainte ca.', x: 'Terem, „încă nu”, cu prepoziția be, „înainte ca”. Isaia subliniază că Dumnezeu vestește lucrurile înainte ca ele să înceapă să se arate — semnul care Îl deosebește pe Dumnezeul adevărat de idoli (Isaia 42:9).', g: 'πρό', gd: 'înainte de.' },
  H6779: { g: 'ἀνατέλλω', gd: 'a răsări, a încolți.' },
  H5186: { g: 'πήγνυμι', gd: 'a înfige, a fixa (ca țărușii unui cort).' },
  H7554: { g: 'στερεόω', gd: 'a întări, a face tare.' },
  H5397: { g: 'πνοή', gd: 'suflare.' },
  H7307: { g: 'πνεῦμα', gd: 'suflare, vânt, duh.' },
  H2691: { d: 'curte îngrădită; sat, cătun fără ziduri.', x: 'Hațer înseamnă o curte îngrădită și, prin extensie, un sat fără ziduri, o tabără de corturi — potrivit pentru nomazii din Kedar. Același cuvânt desemnează curțile Templului.', g: 'ἔπαυλις', gd: 'cătun, adăpost pentru turme.' },
  H6938: { g: 'Κηδάρ', gd: 'Kedar — transcrierea numelui ebraic.' },
  H5553: { g: 'πέτρα', gd: 'stâncă.' },
  H7442: { g: 'εὐφραίνω', gd: 'a (se) bucura.' },
  H6681: { d: 'a striga tare, a chiui de bucurie.', x: 'Țavah, „a striga tare, a chiui”, apare numai aici în Biblia ebraică; e înrudit cu țevaha, „strigătul” (Ieremia 14:2). Traducerea Rosen îl redă prin „să vestească”, iar Septuaginta prin „vor striga” (βοήσουσιν).', g: 'βοάω', gd: 'a striga.' },
  H310: { d: 'după, în urmă.', x: 'Ahar, „după”; formula „înaintea Mea… și după Mine” (Isaia 43:10) cuprinde tot timpul, de la început până la sfârșit: nu a existat dumnezeu înaintea lui DOMNUL și nici nu va exista după El.', g: 'μετά', gd: 'după.' },
  H6440: { d: 'față; lifnei — înaintea (în spațiu sau în timp).', x: 'Panim, „fața”, are formă de plural; cu prepoziția le formează lifnei, „înaintea”, literal „la fața”. În Isaia 43:10, lefanai, „înaintea Mea”, are sens de timp: înainte de Dumnezeu nu a fost plăsmuit niciun alt dumnezeu.', g: 'ἔμπροσθεν', gd: 'înainte, în fața.' },
  H859: { g: 'σύ', gd: 'tu; voi.' }
};
