const ASA_A_SPUS = {heb:"כֹּה אָמַר אֲדֹנָי יֱהוִה", translit:"ko amar adonai Adonai", strong:"H3541", pos:"adverb + verb, qal perfect + substantiv construct + sufix + nume propriu", def_ro:"așa a spus Stăpânul meu, Domnul DUMNEZEU.", dict_ro:"Formula introductivă standard a oracolelor lui Ezechiel, repetată identic la fiecare etapă a profeției împotriva Egiptului (29:3, 29:8, 29:13, 29:19) — un sigiliu de autenticitate care marchează fiecare secțiune ca discurs divin direct."};
const VOR_STI_CA_EU_SUNT = {heb:"וְיָדְעוּ כִּי אֲנִי יְהוָה", translit:"veiadu ki ani Adonai", strong:"H3045", pos:"verb, qal perfect consecutiv + conjuncție + pronume personal + nume propriu", def_ro:"și vor ști că Eu sunt DOMNUL.", dict_ro:"Formula-refren a cărții lui Ezechiel, repetată la finalul fiecărei etape a judecății asupra Egiptului — recunoașterea universală a DOMNULUI, de către egipteni deopotrivă cu Israel, rămâne scopul ultim al întregii profeții."};
const CUVANTUL_DOMNULUI_A_VENIT = {heb:"הָיָה דְבַר יְהוָה אֵלַי", translit:"haia devar Adonai ēlai", strong:"H1697", pos:"verb, qal perfect + substantiv construct + nume propriu + prepoziție + sufix", def_ro:"a fost cuvântul DOMNULUI către mine.", dict_ro:"Formula de introducere a unei noi etape profetice — Radak explică faptul că profeția despre Egipt a venit lui Ezechiel în etape succesive, legate de evenimentele reale ale asediului Tirului și ale cuceririi Egiptului de către Nabucodonosor."};

module.exports = [
{v:"28:25", newTags:[
  ["și ei vor locui pe pământul lor", {heb:"וְיָשְׁבוּ עַל אַדְמָתָם", translit:"veiașvu al admatam", strong:"H3427", pos:"verb, qal perfect consecutiv + prepoziție + substantiv construct + sufix", def_ro:"și vor locui pe pământul lor.", dict_ro:"Restaurarea promisă lui Israel se încheie cu reinstalarea efectivă pe pământul strămoșesc — contrastul deliberat cu pustiirea promisă Egiptului în oracolul care urmează imediat arată cele două destine opuse ale celor două popoare."}]
]},
{v:"28:26", newTags:[
  ["și vor construi case", {heb:"וּבָנוּ בָתִּים", translit:"uvanu vatim", strong:"H1129", pos:"verb, qal perfect consecutiv + substantiv", def_ro:"și vor construi case.", dict_ro:"Imaginea construirii caselor și plantării viilor exprimă stabilitatea și normalitatea vieții restaurate — opusul exact al dezrădăcinării exilului, o viață așezată, nu una provizorie."}],
  ["atunci vor ști că Eu sunt DOMNUL, Dumnezeul lor", {heb:"וְיָדְעוּ כִּי אֲנִי יְהוָה אֱלֹהֵיהֶם", translit:"veiadu ki ani Adonai elohēhem", strong:"H3045", pos:"verb, qal perfect consecutiv + conjuncție + pronume personal + nume propriu + substantiv construct + sufix", def_ro:"și vor ști că Eu sunt DOMNUL, Dumnezeul lor.", dict_ro:"Formula de recunoaștere, aici cu sufixul posesiv («Dumnezeul lor»), subliniază relația specială de legământ dintre DOMNUL și Israel — distinctă de formula mai generală «Eu sunt DOMNUL» folosită față de Egipt în capitolul următor."}]
]},
{v:"29:1", newTags:[
  ["cuvântul DOMNULUI a venit la mine", CUVANTUL_DOMNULUI_A_VENIT]
]},
{v:"29:2", newTags:[
  ["regele Egiptului", {heb:"מֶלֶךְ מִצְרָיִם", translit:"meleh mițraim", strong:"H4428", pos:"substantiv construct + nume propriu", def_ro:"regele Egiptului.", dict_ro:"Titlul regal standard al lui Faraon, identificat de Metzudat David cu regele contemporan lui Țedechia, cel care promisese ajutor militar Ierusalimului asediat, dar ale cărui trupe s-au retras fără luptă reală."}],
  ["împotriva lui și împotriva întregului Egipt", {heb:"עָלָיו וְעַל מִצְרַיִם כֻּלָּהּ", translit:"alaiv veal mițraim kulah", strong:"H5921", pos:"prepoziție + sufix + prepoziție + nume propriu + substantiv construct + sufix", def_ro:"împotriva lui și împotriva întregului Egipt.", dict_ro:"Extinderea explicită a oracolului de la persoana lui Faraon la «întregul Egipt» (kulah) arată că judecația nu se limitează la rege, ci cuprinde întreaga națiune responsabilă de mândria și de alianța înșelătoare cu Iuda."}]
]},
{v:"29:3", newTags:[
  ["Vorbește și spune-le", {heb:"דַּבֵּר וְאָמַרְתָּ", translit:"dabēr veamarta", strong:"H1696", pos:"verb, piel imperativ + verb, qal perfect consecutiv", def_ro:"vorbește și spune.", dict_ro:"Dubla poruncă verbală, de a vorbi și de a spune, pregătește citarea exactă a oracolului — structură identică celei din chemarea lui Ieremia, confirmând transmiterea fidelă a cuvântului divin."}],
  ["Așa a spus Stăpânul meu, Domnul DUMNEZEU", ASA_A_SPUS],
  ["Iată-Mă, Eu sunt împotriva ta, Faraon, rege al Egiptului", {heb:"הִנְנִי עָלֶיךָ פַּרְעֹה מֶלֶךְ מִצְרַיִם", translit:"hinni aleha paro meleh mițraim", strong:"H2005", pos:"particulă demonstrativă + sufix + prepoziție + sufix + nume propriu + substantiv construct + nume propriu", def_ro:"iată-Mă [sunt] împotriva ta, Faraon, rege al Egiptului.", dict_ro:"Formula de confruntare directă — DOMNUL Se adresează personal lui Faraon, nu printr-un intermediar — pregătește identificarea lui cu crocodilul cel mare: Rashi explică faptul că toată mărirea Egiptului vine prin brațele Nilului, de aceea profetul îl asemănă pe rege cu un crocodil."}]
]},
{v:"29:4", newTags:[
  ["toți peștii râurilor tale ți se vor lipi de solzi", {heb:"וְאֵת כָּל דְּגַת יְאֹרֶיךָ בְּקַשְׂקְשֹׂתֶיךָ תִּדְבָּק", translit:"veēt kal degat ieoreha bekaskesoteha tidbak", strong:"H1710", pos:"marcă a complementului direct + substantiv construct + substantiv construct + sufix + substantiv construct + sufix + verb, qal imperfect", def_ro:"și toți peștii râurilor tale se vor lipi de solzii tăi.", dict_ro:"Repetarea exactă a imaginii de mai sus, la finalul versetului, întărește ideea lui Rashi: DOMNUL va pune în inima tuturor vitejilor Egiptului să iasă cu regele lor la război, ca să cadă toți împreună — «peștii lipiți de solzi» fiind, de fapt, poporul alipit indisolubil de soarta conducătorului său."}]
]},
{v:"29:5", newTags:[
  ["pe fața câmpiei vei cădea", {heb:"עַל פְּנֵי הַשָּׂדֶה תִּפּוֹל", translit:"al penē hasade tipol", strong:"H6440", pos:"prepoziție + substantiv construct + substantiv + verb, qal imperfect", def_ro:"pe fața câmpului vei cădea.", dict_ro:"Metzudat David citește versetul ca încheierea logică a metaforei crocodilului scos din apă: nu doar capturat, ci abandonat complet, lăsat neîngropat pe câmp — soarta cea mai de rușine posibilă pentru un rege care se pretinsese propriul său creator."}]
]},
{v:"29:6", newTags:[
  ["Și toți cei care locuiesc în Egipt vor ști că Eu sunt DOMNUL", {heb:"וְיָדְעוּ כָּל יֹשְׁבֵי מִצְרַיִם כִּי אֲנִי יְהוָה", translit:"veiadu kal ioșvē mițraim ki ani Adonai", strong:"H3045", pos:"verb, qal perfect consecutiv + substantiv construct + verb, qal participiu + nume propriu + conjuncție + pronume personal + nume propriu", def_ro:"și vor ști toți locuitorii Egiptului că Eu sunt DOMNUL.", dict_ro:"Recunoașterea DOMNULUI se extinde aici, pentru prima dată în capitol, la toți locuitorii Egiptului — nu doar Faraon, ci întreaga națiune va fi martoră a adevărului pe care alianța cu «sprijinul de trestie» nu l-a putut oferi lui Iuda."}]
]},
{v:"29:7", newTags:[
  ["și le vei străpunge orice umăr", {heb:"וּבָקַעְתָּ לָהֶם כָּל כָּתֵף", translit:"uvakata lahem kal katēf", strong:"H1234", pos:"verb, qal perfect consecutiv + prepoziție + sufix + substantiv construct + substantiv", def_ro:"și le vei despica tot umărul.", dict_ro:"Metzudat David explică imaginea completă: cel ce se sprijină pe o trestie subțire nu doar rămâne fără sprijinul căutat, ci e activ rănit de ea, atât în mâna cu care o apucă, cât și în umărul pe care îl străpunge."}],
  ["și tot mijlocul lor va trebui să stea drept", {heb:"וְהַעֲמַדְתָּ לָהֶם כָּל מָתְנָיִם", translit:"vehaamadta lahem kal matnaim", strong:"H5976", pos:"verb, hifil perfect consecutiv + prepoziție + sufix + substantiv construct + substantiv", def_ro:"și le vei face tot mijlocul să tremure/să nu se poată ține drept.", dict_ro:"A doua vătămare din dubla imagine a lui Metzudat David — mijlocul care se sprijinea pe trestie se frânge la rândul lui, completând soarta exact a lui Iuda în relația cu Egiptul: rănit în ambele puncte de contact cu sprijinul căutat."}]
]},
{v:"29:8", newTags:[
  ["De aceea, așa a spus Stăpânul meu, Domnul DUMNEZEU", {heb:"לָכֵן כֹּה אָמַר אֲדֹנָי יֱהוִה", translit:"lahēn ko amar adonai Adonai", strong:"H3651", pos:"adverb + adverb + verb, qal perfect + substantiv construct + sufix + nume propriu", def_ro:"de aceea, așa a spus Stăpânul meu, Domnul DUMNEZEU.", dict_ro:"Particula «lahen» («de aceea») leagă explicit judecata care urmează de declarația de auto-divinizare a lui Faraon rostită la v.3 — pedeapsa e consecința directă, nu una arbitrară."}],
  ["Iată-Mă, voi aduce împotriva ta", {heb:"הִנְנִי מֵבִיא עָלַיִךְ", translit:"hinni mēvi alaih", strong:"H2005", pos:"particulă demonstrativă + sufix + verb, hifil participiu + prepoziție + sufix", def_ro:"iată-Mă, aduc împotriva ta.", dict_ro:"Formula de intervenție divină directă introduce sabia ca instrument concret al judecății — trecerea de la cuvânt (oracolul) la faptă (sabia care va nimici om și dobitoc)."}]
]},
{v:"29:9", newTags:[
  ["și ei vor ști că Eu sunt DOMNUL", VOR_STI_CA_EU_SUNT],
  ["din pricină că a spus: ‘Râul este al meu și eu am creat.’", {heb:"יַעַן אָמַר יְאֹר לִי וַאֲנִי עָשִׂיתִי", translit:"iaan amar ieor li vaani asiti", strong:"H3282", pos:"conjuncție + verb, qal perfect + nume propriu + prepoziție + sufix + pronume personal + verb, qal perfect", def_ro:"pentru că a spus: râul [este] al meu și eu l-am făcut.", dict_ro:"Metzudat David observă repetiția deliberată a formulei aroganței lui Faraon, identică celei de la v.3 — pedeapsa nu e arbitrară, ci răspunsul precis la declarația de auto-suficiență și auto-divinizare rostită la începutul oracolului."}]
]},
{v:"29:10", newTags:[
  ["De aceea, iată-Mă, Eu sunt împotriva ta și împotriva râurilor tale", {heb:"לָכֵן הִנְנִי אֵלֶיךָ וְאֶל יְאֹרֶיךָ", translit:"lahēn hinni ēleha veel ieoreha", strong:"H3651", pos:"adverb + particulă demonstrativă + sufix + prepoziție + sufix + prepoziție + substantiv construct + sufix", def_ro:"de aceea, iată-Mă, [sunt] împotriva ta și împotriva râurilor tale.", dict_ro:"Repetarea formulei de confruntare, extinsă acum explicit la «râurile tale» — sursa exactă a mândriei lui Faraon (v.3, v.9) devine ea însăși obiectul direct al judecății divine."}],
  ["și voi preface țara Egiptului în ruină, într-o pustietate dezolantă", {heb:"וְנָתַתִּי אֶת אֶרֶץ מִצְרַיִם לְחָרְבוֹת חֹרֶב שְׁמָמָה", translit:"venatati et ereț mițraim leharvot horev șemama", strong:"H5414", pos:"verb, qal perfect consecutiv + marcă a complementului direct + substantiv construct + nume propriu + substantiv construct + substantiv + substantiv", def_ro:"și voi face țara Egiptului ruine, pustiire, dezolare.", dict_ro:"Metzudat David identifică Migdol și Sevene ca hotare geografice nordic și sudic ale Egiptului antic, iar Cuș ca regiunea de dincolo de granița sudică — expresia «de la Migdol la Cuș» desemnează, prin merism geografic, întregul teritoriu al țării, fără nicio parte cruțată de pustiire."}]
]},
{v:"29:11", newTags:[
  ["picior de om", {heb:"רֶגֶל אָדָם", translit:"regel adam", strong:"H7272", pos:"substantiv construct + substantiv", def_ro:"picior de om.", dict_ro:"Imaginea completei dezertificări a Egiptului — nici omul, nici animalul nu vor mai traversa țara, imagine extremă de pustiire totală, fără urmă de viață care s-o traverseze."}],
  ["și nici picior de dobitoc nu va trece prin ea", {heb:"וְרֶגֶל בְּהֵמָה לֹא תַעֲבָר בָּהּ", translit:"veregel behēma lo taavar bah", strong:"H7272", pos:"substantiv construct + substantiv + particulă negativă + verb, qal imperfect + prepoziție + sufix", def_ro:"și picior de dobitoc nu va trece prin ea.", dict_ro:"Repetarea paralelă — nici omul, nici animalul — subliniază lipsa totală de viață din țara pustiită, confirmată de durata precisă de patruzeci de ani notată imediat după."}]
]},
{v:"29:12", newTags:[
  ["Și voi face ca țara Egiptului să fie pustiită în mijlocul [altor] țări pustiite", {heb:"וְנָתַתִּי אֶת אֶרֶץ מִצְרַיִם שְׁמָמָה בְּתוֹךְ אֲרָצוֹת נְשַׁמּוֹת", translit:"venatati et ereț mițraim șemama betoh arațot neșamot", strong:"H5414", pos:"verb, qal perfect consecutiv + marcă a complementului direct + substantiv construct + nume propriu + substantiv + substantiv construct + substantiv + verb, nifal participiu", def_ro:"și voi face țara Egiptului pustiire în mijlocul țărilor pustiite.", dict_ro:"Metzudat David observă paralela structurală cu 28:25: la fel cum Israel a fost împrăștiat printre neamuri, tot așa va fi și Egiptul — dar cu diferența esențială că Israel va fi adunat înapoi la măreția lui deplină, pe când Egiptul va rămâne, după restaurare, «un regat neînsemnat»."}]
]},
{v:"29:13", newTags:[
  ["Căci așa a spus Stăpânul meu, Domnul DUMNEZEU", {heb:"כִּי כֹה אָמַר אֲדֹנָי יֱהוִה", translit:"ki ko amar adonai Adonai", strong:"H3541", pos:"conjuncție + adverb + verb, qal perfect + substantiv construct + sufix + nume propriu", def_ro:"căci așa a spus Stăpânul meu, Domnul DUMNEZEU.", dict_ro:"Repetarea formulei introductive marchează trecerea de la oracolul de distrugere (v.1-12) la cel de restaurare limitată (v.13-16), după modelul exact al tranziției similare din 28:25-26 pentru Israel."}],
  ["La capătul a patruzeci de ani", {heb:"מִקֵּץ אַרְבָּעִים שָׁנָה", translit:"mikēț arbaim șana", strong:"H7093", pos:"substantiv construct + numeral + substantiv", def_ro:"la sfârșitul a patruzeci de ani.", dict_ro:"Metzudat David precizează sensul exact: «de la sfârșitul celor patruzeci de ani îi voi aduna, și nu în cursul acestei vremi» — restaurarea nu e graduală, ci survine brusc, după împlinirea completă a termenului de pedeapsă."}]
]},
{v:"29:14", newTags:[
  ["și îi voi aduce înapoi în țara", {heb:"וַהֲשִׁבֹתִי אֹתָם אֶרֶץ", translit:"vahașivoti otam ereț", strong:"H7725", pos:"verb, hifil perfect consecutiv + marcă a complementului direct + sufix + substantiv construct", def_ro:"și îi voi întoarce [în] țara.", dict_ro:"Dubla folosire a rădăcinii șuv («a se întoarce») — «voi întoarce captivitatea» și «îi voi aduce înapoi» — insistă asupra caracterului de restaurare completă, nu doar de eliberare parțială."}]
]},
{v:"29:15", newTags:[
  ["Dintre regate, va fi cel mai neînsemnat", {heb:"מִן הַמַּמְלָכוֹת תִּהְיֶה שְׁפָלָה", translit:"min hamamlahot tihie șefala", strong:"H4467", pos:"prepoziție + substantiv + verb, qal imperfect + adjectiv", def_ro:"dintre regate va fi [cel mai] smerit.", dict_ro:"Radak explică: aceasta e opusul exact al promisiunii «te voi face să crești și te voi înmulți» (Geneza 48:4) — restaurarea Egiptului nu e o revenire la măreția antică, ci o permanentă diminuare a statutului său printre neamuri."}]
]},
{v:"29:16", newTags:[
  ["și așa vor cunoaște că Eu sunt Stăpânul, Domnul DUMNEZEU", {heb:"וְיָדְעוּ כִּי אֲנִי אֲדֹנָי יֱהוִה", translit:"veiadu ki ani adonai Adonai", strong:"H3045", pos:"verb, qal perfect consecutiv + conjuncție + pronume personal + substantiv construct + sufix + nume propriu", def_ro:"și vor cunoaște că Eu sunt Stăpânul, Domnul DUMNEZEU.", dict_ro:"Metzudat David încheie secțiunea principală a oracolului: umilirea Egiptului nu e doar o pedeapsă pentru propria lui arogantă auto-divinizare, ci și un beneficiu spiritual permanent pentru Israel — eliminarea unei tentații politice recurente de a căuta sprijin într-o alianță pământească."}]
]},
{v:"29:17", newTags:[
  ["cuvântul DOMNULUI a venit la mine", CUVANTUL_DOMNULUI_A_VENIT]
]},
{v:"29:18", newTags:[
  ["regele Babilonului", {heb:"מֶלֶךְ בָּבֶל", translit:"meleh bavel", strong:"H4428", pos:"substantiv construct + nume propriu", def_ro:"regele Babilonului.", dict_ro:"Titlul lui Nabucodonosor, menționat explicit pe nume la începutul acestui oracol final, cel mai tardiv din toată cartea lui Ezechiel, datat de Metzudat David după încheierea asediului îndelungat al Tirului."}],
  ["și-a pus oștirea să facă un lucru mare", {heb:"הֶעֱבִיד אֶת חֵילוֹ עֲבֹדָה גְדֹלָה", translit:"heevid et hēlo avoda gedola", strong:"H5647", pos:"verb, hifil perfect + marcă a complementului direct + substantiv construct + sufix + substantiv + adjectiv", def_ro:"a pus la muncă oastea lui, o muncă mare.", dict_ro:"Metzudat David explică imaginea capetelor pleșuve și umerilor jupuiți drept efectul fizic direct al muncii istovitoare de asediu — coifurile purtate constant și cărarea materialelor pentru rampele de asalt, timp de treisprezece ani."}]
]},
{v:"29:19", newTags:[
  ["regele Babilonului", {heb:"מֶלֶךְ בָּבֶל", translit:"meleh bavel", strong:"H4428", pos:"substantiv construct + nume propriu", def_ro:"regele Babilonului.", dict_ro:"A doua apariție a titlului, aici alături de numele complet al lui Nabucodonosor — Egiptul îi este dat drept compensație pentru efortul neprofitabil al asediului Tirului."}],
  ["Iată-Mă, îi voi da țara Egiptului", {heb:"הִנְנִי נֹתֵן... אֶת אֶרֶץ מִצְרָיִם", translit:"hinni notēn... et ereț mițraim", strong:"H2005", pos:"particulă demonstrativă + sufix + verb, qal participiu + marcă a complementului direct + substantiv construct + nume propriu", def_ro:"iată-Mă, dau țara Egiptului.", dict_ro:"Formula de dăruire divină directă — DOMNUL Însuși decide soarta Egiptului ca despăgubire pentru Nabucodonosor, deși regele babilonian acționează din ambiție proprie, fără să știe că îndeplinește, de fapt, un scop divin."}]
]},
{v:"29:20", newTags:[
  ["i-am dat lui țara Egiptului", {heb:"נָתַתִּי לוֹ אֶת אֶרֶץ מִצְרָיִם", translit:"natati lo et ereț mițraim", strong:"H5414", pos:"verb, qal perfect + prepoziție + sufix + marcă a complementului direct + substantiv construct + nume propriu", def_ro:"i-am dat lui țara Egiptului.", dict_ro:"Metzudat David subliniază cuvântul final al versetului, «pentru Mine» — deși Nabucodonosor a acționat din propria ambiție politică, fără nicio intenție de a-L sluji pe DOMNUL, Dumnezeu privește efortul lui ca îndeplinind, în cele din urmă, un scop pe care Însuși l-a rânduit."}]
]},
{v:"29:21", newTags:[
  ["În acea zi", {heb:"בַּיּוֹם הַהוּא", translit:"baiom hahu", strong:"H3117", pos:"substantiv + pronume demonstrativ", def_ro:"în ziua aceea.", dict_ro:"Rashi recunoaște deschis dificultatea acestui verset: răsărirea «cornului» lui Israel la căderea Egiptului nu poate fi literală, de vreme ce Israel fusese deja exilat cu opt ani înainte — el leagă «ziua aceea» de împlinirea celor patruzeci de ani ai Egiptului (v.13), calculați să coincidă cu ridicarea Persiei și eliberarea exilaților prin Cirus."}],
  ["și vor ști că Eu sunt DOMNUL", VOR_STI_CA_EU_SUNT]
]}
];
