module.exports = [
{v:"6:1", newTags:[
  ["L-am văzut pe Stăpânul meu așezat pe", {heb:"וָאֶרְאֶה אֶת אֲדֹנָי יֹשֵׁב עַל", translit:"vaere et adonai ioșēv al", strong:"H7200", pos:"verb, qal imperfect consecutiv + marcă a complementului direct + substantiv construct + sufix + verb, qal participiu + prepoziție", def_ro:"și am văzut pe Stăpânul meu șezând pe.", dict_ro:"Verbul «a vedea» deschide direct viziunea profetică a lui Isaia — contemplarea directă a Șechinei, resimțită mai târziu (v.5) ca primejdie mortală, paralelă spaimei lui Manoah din Judecători 13:22."}]
]},
{v:"6:2", newTags:[
  ["stăteau în picioare deasupra Lui", {heb:"עֹמְדִים מִמַּעַל לוֹ", translit:"omdim mimaal lo", strong:"H5975", pos:"verb, qal participiu + adverb + prepoziție + sufix", def_ro:"stăteau mai sus de El.", dict_ro:"Poziția serafimilor, «mai sus» de tron, nu alături de el, respectă distanța ierarhică absolută dintre creaturile cerești și Cel așezat pe tron — niciun serafim nu se află la același nivel cu Șechina."}]
]},
{v:"6:3", newTags:[
  ["către celălalt și spunea", {heb:"זֶה אֶל זֶה וְאָמַר", translit:"ze el ze veamar", strong:"H2088", pos:"pronume demonstrativ + prepoziție + pronume demonstrativ + verb, qal perfect consecutiv", def_ro:"unul către altul și spunea.", dict_ro:"Rashi explică faptul că serafimii «își cereau îngăduință unul de la altul», ca nu cumva unul să înceapă înaintea celorlalți și să se facă vinovat, ci numai dacă rostesc sfințenia toți ca unul — ecou direct al formulei liturgice «Cel ce a întocmit lumina»."}]
]},
{v:"6:5", newTags:[
  ["care locuiesc în mijlocul unui popor [de oameni] cu buze necurate", {heb:"וּבְתוֹךְ עַם טְמֵא שְׂפָתַיִם אָנֹכִי יוֹשֵׁב", translit:"uvtoh am temē sefataim anohi ioșēv", strong:"H8432", pos:"substantiv construct + substantiv + adjectiv + substantiv + pronume personal + verb, qal participiu", def_ro:"și locuiesc în mijlocul unui popor cu buze necurate.", dict_ro:"Repetarea exactă a expresiei «buze necurate», folosită mai întâi despre sine, apoi despre tot poporul, pregătește ispășirea specifică de la v.7 — Rashi citește purificarea buzelor lui Isaia ca disciplină legată direct de această mustrare aspră adusă propriului popor."}],
  ["ochii mei L-au văzut", {heb:"רָאוּ עֵינָי", translit:"rau ēnai", strong:"H7200", pos:"verb, qal perfect + substantiv construct + sufix", def_ro:"au văzut ochii mei.", dict_ro:"Confirmarea vederii directe, cu proprii ochi, a Regelui — DOMNUL Oștirilor — motivează teama de moarte a profetului, resimțită universal în tradiția biblică drept primejdie a vederii nemijlocite a slavei divine."}]
]},
{v:"7:1", newTags:[
  ["a purtat război împotriva sa", {heb:"לַמִּלְחָמָה עָלֶיהָ", translit:"lamilhama aleha", strong:"H4421", pos:"substantiv + prepoziție + sufix", def_ro:"la război împotriva ei.", dict_ro:"Rashi explică faptul că Scriptura arată genealogia lui Ahaz tocmai pentru a contrasta cu rezultatul: deși regele era nelegiuit, meritul părinților săi drepți, Iotam și Uzia, l-a ocrotit de înfrângere."}]
]},
{v:"7:2", newTags:[
  ["Inima lui și inima poporului lui", {heb:"לְבָבוֹ וּלְבַב עַמּוֹ", translit:"levavo ulvav amo", strong:"H3824", pos:"substantiv construct + sufix + substantiv construct + substantiv construct + sufix", def_ro:"inima lui și inima poporului lui.", dict_ro:"Rashi explică teama dublă a lui Ahaz prin experiența sa anterioară reală: fiecare dintre cei doi regi aliați îl biruise deja separat în luptă (2 Cronici 28:5-6), ceea ce face amenințarea unită cu atât mai înspăimântătoare."}]
]},
{v:"7:3", newTags:[
  ["DOMNUL i-a spus lui Isaia", {heb:"וַיֹּאמֶר יְהוָה אֶל יְשַׁעְיָהוּ", translit:"vaiomer Adonai el ieșaiahu", strong:"H559", pos:"verb, qal imperfect consecutiv + nume propriu + prepoziție + nume propriu", def_ro:"și a spus DOMNUL către Isaia.", dict_ro:"Formula de poruncă divină directă introduce misiunea precisă a profetului — ieșirea în întâmpinarea regelui înspăimântat, cu fiul său Șear-Iașuv, al cărui nume însuși («rămășița se va întoarce») e un mesaj profetic întrupat."}],
  ["Ieși acum în întâmpinarea lui Ahaz, tu și fiul tău", {heb:"צֵא נָא לִקְרַאת אָחָז אַתָּה", translit:"țē na likrat ahaz ata", strong:"H3318", pos:"verb, qal imperativ + interjecție + verb, qal infinitiv + nume propriu + pronume personal", def_ro:"ieși, te rog, în întâmpinarea lui Ahaz, tu.", dict_ro:"Porunca precisă a locului de întâlnire — la capătul canalului iazului de sus — arată că DOMNUL cunoaște exact unde se află regele îngrozit, pregătit, potrivit Talmudului (Sanhedrin 104a), să se umilească înaintea profetului."}]
]},
{v:"7:4", newTags:[
  ["Și spune-i", {heb:"וְאָמַרְתָּ אֵלָיו", translit:"veamarta ēlaiv", strong:"H559", pos:"verb, qal perfect consecutiv + prepoziție + sufix", def_ro:"și spune-i lui.", dict_ro:"Formula pregătește mesajul central de liniștire — «păzește-te și stai liniștit» — adresat direct regelui, nu transmis printr-un intermediar."}]
]},
{v:"9:6", newTags:[
  ["un fiu ne-a fost dăruit", {heb:"בֵּן נִתַּן לָנוּ", translit:"bēn nitan lanu", strong:"H1121", pos:"substantiv + verb, nifal perfect + prepoziție + sufix", def_ro:"un fiu ne-a fost dat.", dict_ro:"Rashi citește întregul verset ca aplicat lui Ezechia, fiul lui Ahaz, deși acesta era rege nelegiuit: «măcar că Ahaz e rău, fiul lui [deja] născut ne va fi, în locul lui, rege drept»."}],
  ["va fi pe umărul lui", {heb:"וַתְּהִי... עַל שִׁכְמוֹ", translit:"vathi... al șihmo", strong:"H1961", pos:"verb, qal imperfect consecutiv + prepoziție + substantiv construct + sufix", def_ro:"și va fi... pe umărul lui.", dict_ro:"Imaginea autorității ca sarcină pusă pe umăr — Rashi explică faptul că misiunea Celui Sfânt și jugul Lui vor fi pe umărul tânărului rege drept, nu o putere arbitrară, ci o răspundere primită de la Dumnezeu."}],
  ["i-a dat numele de", {heb:"וַיִּקְרָא שְׁמוֹ", translit:"vaikra șemo", strong:"H7121", pos:"verb, qal imperfect consecutiv + substantiv construct + sufix", def_ro:"și i-a chemat numele.", dict_ro:"Rashi explică faptul că titlurile care urmează — Sfătuitor minunat, Dumnezeu puternic, Tată veșnic — desemnează pe Dumnezeu Însuși, Cel care «a chemat numele lui Hezechia Prinț al păcii», nu titluri divine aplicate direct copilului."}]
]},
{v:"9:7", newTags:[
  ["va fi mare în autoritate", {heb:"לְמַרְבֵּה הַמִּשְׂרָה", translit:"lemarbē hamisra", strong:"H4766", pos:"substantiv construct + substantiv", def_ro:"pentru mărirea autorității.", dict_ro:"Rashi explică «misra» ca «cuvânt de stăpânire» — regele care mărește asupra lui însuși stăpânirea Sfântului, binecuvântat fie, ca să se teamă de El, nu o mărire a propriei puteri personale."}],
  ["pe tronul lui David și peste regatul său", {heb:"עַל כִּסֵּא דָוִד וְעַל מַמְלַכְתּוֹ", translit:"al kisē david veal mamlahto", strong:"H3678", pos:"prepoziție + substantiv construct + nume propriu + prepoziție + substantiv construct + sufix", def_ro:"pe tronul lui David și peste regatul lui.", dict_ro:"Legarea explicită a acestei păci fără sfârșit de tronul davidic ancorează promisiunea mesianică în linia dinastică a lui David, confirmată prin «judecata și dreptatea» pe care regele o înfăptuiește."}],
  ["ca să-l întemeieze și să-l susțină", {heb:"לְהָכִין אֹתָהּ וּלְסַעֲדָהּ", translit:"lehahin otah ulsaadah", strong:"H3559", pos:"verb, hifil infinitiv + marcă a complementului direct + sufix + verb, qal infinitiv + sufix", def_ro:"ca să o întemeieze și să o sprijine.", dict_ro:"Dubla acțiune — întemeiere și susținere — arată caracterul durabil al domniei promise: nu doar o instaurare inițială, ci o întreținere continuă prin judecată și dreptate, «de acum și până în veac»."}],
  ["DOMNULUI Oștirilor va împlini aceasta", {heb:"יְהוָה צְבָאוֹת תַּעֲשֶׂה זֹּאת", translit:"Adonai țevaot taase zot", strong:"H3068", pos:"nume propriu + substantiv + verb, qal imperfect + pronume demonstrativ", def_ro:"DOMNUL Oștirilor va face aceasta.", dict_ro:"Rashi explică faptul că râvna DOMNULUI Oștirilor pentru Sion, nu meritul lui Ahaz — al cărui merit părintesc se sfârșise deja — este cea care garantează împlinirea promisiunii de pace și dreptate pentru casa lui David."}]
]}
];
