module.exports = [
{v:"34:8", newTags:[
  ["Cuvântul care a venit la Ieremia a fost de la DOMNUL, după ce regele Țedekia a", {heb:"הַדָּבָר אֲשֶׁר הָיָה אֶל יִרְמְיָהוּ מֵאֵת יְהוָה אַחֲרֵי כְּרֹת הַמֶּלֶךְ צִדְקִיָּהוּ", translit:"hadavar așer haia el irmeiahu mēēt Adonai aharē kerot hameleh țidkiahu", strong:"H1697", pos:"substantiv + particulă relativă + verb, qal perfect + nume propriu + prepoziție + nume propriu + prepoziție + verb, qal infinitiv + substantiv + nume propriu", def_ro:"cuvântul care a fost către Ieremia de la DOMNUL, după ce regele Țedechia a încheiat.", dict_ro:"Rashi datează acest legământ în anul al șaptelea al domniei lui Țedechia, legând momentul de o întrebare adresată lui Ezechiel de bătrânii lui Iuda despre statutul ritual al unui sclav preot eliberat — dovadă indirectă că poporul căuta să arate că nu fusese pedepsit din pricina neglijării poruncilor."}],
  ["cu tot poporul care era în Ierusalim, ca să proclame", {heb:"אֶת כָּל הָעָם אֲשֶׁר בִּירוּשָׁלִַם לִקְרֹא", translit:"et kal haam așer birușalam likro", strong:"H3605", pos:"marcă a complementului direct + substantiv construct + substantiv + particulă relativă + nume propriu + verb, qal infinitiv", def_ro:"cu tot poporul care era în Ierusalim, ca să proclame.", dict_ro:"Legământul implică întreg poporul capitalei, nu doar o clasă socială restrânsă — amploarea participării face cu atât mai gravă răzgândirea ulterioară descrisă la v.11."}]
]},
{v:"34:9", newTags:[
  ["ca fiecare om să-și", {heb:"לְשַׁלַּח אִישׁ", translit:"leșalah iș", strong:"H7971", pos:"verb, piel infinitiv + substantiv", def_ro:"ca să elibereze fiecare om.", dict_ro:"Verbul «șalah» («a trimite, a elibera») deschide descrierea legământului de eliberare, aceeași rădăcină folosită constant pentru eliberarea sclavilor ebrei în tot capitolul."}],
  ["și fiecare [să-și elibereze] slujnica, evreul și evreica, astfel ca nimeni să nu-l [mai]", {heb:"וְאִישׁ אֶת שִׁפְחָתוֹ הָעִבְרִי וְהָעִבְרִיָּה חָפְשִׁים לְבִלְתִּי עֲבָד בָּם", translit:"veiș et șifhato haivri vehaivria hafșim levilti avad bam", strong:"H376", pos:"substantiv + marcă a complementului direct + substantiv construct + sufix + nume de neam + nume de neam + adjectiv + conjuncție + verb, qal infinitiv + prepoziție + sufix", def_ro:"și fiecare, pe slujnica lui, evreul și evreica, [să-i facă] liberi, ca nimeni să nu-i mai pună la muncă.", dict_ro:"Radak explică faptul că ordinea versetului e răsturnată, după obiceiul stilistic biblic: sensul e ca nimeni să nu-l mai înrobească pe fratele său iudeu, nu doar o enumerare simplă a genurilor eliberate."}],
  ["pe fratele său evreu", {heb:"בִּיהוּדִי אָחִיהוּ אִישׁ", translit:"bihudi ahihu iș", strong:"H3064", pos:"nume de neam + substantiv construct + sufix + substantiv", def_ro:"pe iudeul, fratele său, fiecare om.", dict_ro:"Metzudat David explică faptul că fraza lămurește exact scopul legământului: ca nimeni să nu-l mai pună la muncă pe fratele său iudeu, după ce acesta slujise deja cei șase ani ceruți de legea Torei."}]
]},
{v:"34:10", newTags:[
  ["poporul care a intrat în legământ au ascultat", {heb:"וְכָל הָעָם אֲשֶׁר בָּאוּ בַבְּרִית", translit:"vehal haam așer bau vabrit", strong:"H5971", pos:"substantiv construct + substantiv + particulă relativă + verb, qal perfect + substantiv", def_ro:"și tot poporul care a intrat în legământ.", dict_ro:"Metzudat David explică faptul că Scriptura repetă «și au ascultat» de două ori în acest verset, pentru că relatarea s-a lungit cu detaliile eliberării — o repetare stilistică obișnuită, nu o dublă acțiune separată."}]
]},
{v:"34:11", newTags:[
  ["Însă după aceea", {heb:"וַיָּשׁוּבוּ אַחֲרֵי כֵן", translit:"vaiașuvu aharē hēn", strong:"H7725", pos:"verb, qal imperfect consecutiv + prepoziție + adverb", def_ro:"dar s-au întors după aceea.", dict_ro:"Verbul «a se întoarce» (șuv) marchează aici o revenire negativă — răzgândirea poporului, întorcându-se de la propria lor faptă dreaptă, în contrast cu folosirea pozitivă a aceluiași verb la restaurarea finală din 33:26."}]
]},
{v:"34:13", newTags:[
  ["Așa a spus DOMNUL, Dumnezeul lui Israel. Eu am pecetluit un legământ cu strămoșii voștri", {heb:"כֹּה אָמַר יְהוָה אֱלֹהֵי יִשְׂרָאֵל אָנֹכִי כָּרַתִּי בְרִית אֶת אֲבוֹתֵיכֶם", translit:"ko amar Adonai elohē israēl anohi karati verit et avotēhem", strong:"H3541", pos:"adverb + verb, qal perfect + nume propriu + substantiv construct + nume propriu + pronume personal + verb, qal perfect + substantiv + prepoziție + substantiv construct + sufix", def_ro:"așa a spus DOMNUL, Dumnezeul lui Israel: Eu am încheiat un legământ cu strămoșii voștri.", dict_ro:"Metzudat David explică faptul că acest verset se referă la adunarea de la muntele Sinai, căci atunci DOMNUL a încheiat legământul pentru toate poruncile deodată — legământul actual al eliberării sclavilor se leagă astfel direct de legământul originar al Exodului."}]
]},
{v:"34:14", newTags:[
  ["fiecare dintre voi să își elibereze fratele evreu care vă va fi fost vândut", {heb:"תְּשַׁלְּחוּ אִישׁ אֶת אָחִיו הָעִבְרִי אֲשֶׁר יִמָּכֵר לְךָ", translit:"teșalhu iș et ahiv haivri așer imahēr leha", strong:"H7971", pos:"verb, piel imperfect + substantiv + marcă a complementului direct + substantiv construct + sufix + nume de neam + particulă relativă + verb, nifal imperfect + prepoziție + sufix", def_ro:"veți elibera fiecare pe fratele său evreu care îi va fi fost vândut.", dict_ro:"Talmudul (Arahin 33a) discută această poruncă în relație cu numărarea anilor sabatici — profetul mustră poporul exact pentru nerespectarea acestei legi exprese a lui Moise despre eliberarea sclavilor după șase ani."}],
  ["Dar părinții tăi n-au ascultat de Mine", {heb:"וְלֹא שָׁמְעוּ אֲבוֹתֵיכֶם אֵלַי", translit:"velo șamu avotēhem ēlai", strong:"H3808", pos:"particulă negativă + verb, qal perfect + substantiv construct + sufix + prepoziție + sufix", def_ro:"și nu au ascultat strămoșii voștri de Mine.", dict_ro:"Nerespectarea cronică a acestei legi, de generații, pregătește contrastul ironic cu generația actuală: ei «s-au căit» pentru scurt timp (v.15), dar s-au răzgândit mai rapid decât strămoșii lor nesupuși."}]
]},
{v:"34:15", newTags:[
  ["și ați făcut ceea ce este drept în ochii Mei", {heb:"וַתַּעֲשׂוּ אֶת הַיָּשָׁר בְּעֵינַי", translit:"vataasu et haiașar beēnai", strong:"H6213", pos:"verb, qal imperfect consecutiv + marcă a complementului direct + adjectiv + substantiv construct + sufix", def_ro:"și ați făcut ceea ce e drept în ochii Mei.", dict_ro:"Recunoașterea explicită a faptei bune a poporului, chiar temporară, arată că DOMNUL apreciază sincer pocăința inițială, oricât de scurtă s-ar fi dovedit — judecata care urmează nu ignoră acest moment real de dreptate."}],
  ["ca fiecare să proclame libertatea pentru semenul său", {heb:"לִקְרֹא דְרוֹר אִישׁ לְרֵעֵהוּ", translit:"likro deror iș lerēēhu", strong:"H7121", pos:"verb, qal infinitiv + substantiv + substantiv + substantiv construct + sufix", def_ro:"ca să proclame libertate fiecare pentru semenul său.", dict_ro:"Metzudat David explică faptul că «semenul său» desemnează aici robul evreu — formula reia exact termenul «deror» («libertate deplină») folosit și în legea originară a Sinaiului, confirmând legitimitatea deplină a actului de eliberare."}]
]},
{v:"34:16", newTags:[
  ["și fiecare și-a adus înapoi sclavul și fiecare sclava pe care îi lăsaseți să meargă", {heb:"וַתָּשִׁבוּ אִישׁ אֶת עַבְדּוֹ וְאִישׁ אֶת שִׁפְחָתוֹ אֲשֶׁר שִׁלַּחְתֶּם חָפְשִׁים", translit:"vatașivu iș et avdo veiș et șifhato așer șilahtem hafșim", strong:"H7725", pos:"verb, hifil imperfect consecutiv + substantiv + marcă a complementului direct + substantiv construct + sufix (repetat) + particulă relativă + verb, piel perfect + adjectiv", def_ro:"și ați adus înapoi fiecare pe robul lui și fiecare pe roaba lui, pe care îi lăsaserăți liberi.", dict_ro:"Metzudat David explică faptul că poporul s-a întors să-și recapete fiecare robul, apucându-i cu sila — răzgândirea nu e doar o schimbare de gând, ci o acțiune activă de recapturare a celor deja eliberați legal."}]
]},
{v:"34:17", newTags:[
  ["De aceea, așa a spus DOMNUL", {heb:"לָכֵן כֹּה אָמַר יְהוָה", translit:"lahēn ko amar Adonai", strong:"H3651", pos:"adverb + adverb + verb, qal perfect + nume propriu", def_ro:"de aceea, așa a spus DOMNUL.", dict_ro:"Particula «lahen» leagă explicit sentința care urmează de răzgândirea descrisă anterior — judecata e consecința directă, proporțională, a încălcării legământului."}],
  ["«Voi nu ați ascultat de Mine, ca să proclamați libertate, fiecare pentru fratele său și fiecare pentru semenul său.", {heb:"אַתֶּם לֹא שְׁמַעְתֶּם אֵלַי לִקְרֹא דְרוֹר אִישׁ לְאָחִיו וְאִישׁ לְרֵעֵהוּ", translit:"atem lo șematem ēlai likro deror iș leahiv veiș lerēēhu", strong:"H859", pos:"pronume personal + particulă negativă + verb, qal perfect + prepoziție + sufix + verb, qal infinitiv + substantiv + substantiv + substantiv construct + sufix (repetat)", def_ro:"voi nu ați ascultat de Mine, ca să proclamați libertate, fiecare fratelui său și fiecare semenului său.", dict_ro:"Rashi explică formula de judecată care urmează imediat («Iată, vă vestesc slobozire... de la Mine») ca o răsturnare ironică exactă: pentru că poporul n-a dat libertate reală fraților lor, DOMNUL le «dă» o altă formă de libertate — libertatea de a fi pradă sabiei, molimei și foametei."}]
]},
{v:"34:18", newTags:[
  ["Voi hărăzi oamenilor care Mi-au", {heb:"וְנָתַתִּי אֶת הָאֲנָשִׁים הָעֹבְרִים אֶת בְּרִתִי אֲשֶׁר", translit:"venatati et haanașim haovrim et beriti așer", strong:"H5414", pos:"verb, qal perfect consecutiv + marcă a complementului direct + substantiv + verb, qal participiu + marcă a complementului direct + substantiv construct + sufix + particulă relativă", def_ro:"și voi da pe oamenii care au trecut peste legământul Meu, care.", dict_ro:"Rashi propune o lectură surprinzătoare a vițelului tăiat în două care urmează: nu aparține legământului inițial de eliberare, ci unui al doilea legământ, de nesupunere, încheiat DUPĂ recapturarea sclavilor, prin care poporul a jurat unii altora solidaritate în păcat."}],
  ["celor care nu au împlinit cuvintele legământului pe care l-au pecetluit înaintea Mea", {heb:"לֹא הֵקִימוּ אֶת דִּבְרֵי הַבְּרִית אֲשֶׁר כָּרְתוּ לְפָנָי", translit:"lo hēkimu et divrē habrit așer kartu lefanai", strong:"H6965", pos:"particulă negativă + verb, hifil perfect + marcă a complementului direct + substantiv construct + substantiv + particulă relativă + verb, qal perfect + substantiv construct + sufix", def_ro:"nu au împlinit cuvintele legământului pe care l-au încheiat înaintea Mea.", dict_ro:"Repetarea verbului «a încheia legământ» (karat) de două ori în același verset, în legătură cu vițelul tăiat, leagă explicit ritualul jurământului de imaginea sacrificiului despicat — a nu respecta cuvântul e echivalent, simbolic, cu soarta animalului tăiat în două."}]
]},
{v:"34:19", newTags:[
  ["conducătorii lui Iuda și conducătorii Ierusalimului", {heb:"שָׂרֵי יְהוּדָה וְשָׂרֵי יְרוּשָׁלִַם", translit:"sarē iehuda vesarē ierușalam", strong:"H8269", pos:"substantiv plural construct + nume propriu + substantiv plural construct + nume propriu", def_ro:"căpeteniile lui Iuda și căpeteniile Ierusalimului.", dict_ro:"Radak distinge cele două categorii: căpeteniile lui Iuda sunt conducătorii cetăților de afară de Ierusalim, pe când cei ai Ierusalimului sunt dregătorii din capitală — enumerarea completă arată participarea întregii structuri de conducere la ritualul vițelului despicat."}]
]},
{v:"34:21", newTags:[
  ["regelui Babilonului", {heb:"מֶלֶךְ בָּבֶל", translit:"meleh bavel", strong:"H4428", pos:"substantiv construct + nume propriu", def_ro:"regele Babilonului.", dict_ro:"Rashi explică faptul că armata regelui Babilonului se retrăsese temporar «din pricina oștii lui Faraon, care a ieșit din Egipt» (Ieremia 37:5) — o retragere provizorie, nu o eliberare definitivă, cum avea să confirme imediat judecata din versetul următor."}]
]},
{v:"34:22", newTags:[
  ["Mă voi întoarce la acest oraș și voi purta război împotriva lui", {heb:"וַהֲשִׁבֹתִים אֶל הָעִיר הַזֹּאת וְנִלְחֲמוּ עָלֶיהָ", translit:"vahașivotim el hair hazot venilhamu aleha", strong:"H7725", pos:"verb, hifil perfect consecutiv + sufix + prepoziție + substantiv + pronume demonstrativ + verb, nifal perfect consecutiv + prepoziție + sufix", def_ro:"și îi voi aduce înapoi la cetatea aceasta și vor purta război împotriva ei.", dict_ro:"Rashi rezumă simplu împlinirea sentinței: armata lui Faraon se va întoarce în Egipt, iar caldeenii se vor întoarce asupra lui Iuda — porunca divină reia asediul suspendat temporar, ducând la cucerirea completă a Ierusalimului."}],
  ["voi preface în pustiu orașele din Iuda", {heb:"וְאֶת עָרֵי יְהוּדָה אֶתֵּן שְׁמָמָה", translit:"veet arē iehuda etēn șemama", strong:"H5892", pos:"marcă a complementului direct + substantiv plural construct + nume propriu + verb, qal imperfect + substantiv", def_ro:"și cetățile lui Iuda le voi face pustiire.", dict_ro:"Extinderea judecății dincolo de capitală, la toate cetățile lui Iuda, confirmă amploarea totală a dezastrului prezis, împlinind toate avertismentele rostite de-a lungul întregului capitol."}]
]},
{v:"33:25", newTags:[
  ["Așa a spus DOMNUL: „Dacă n-ar fi fost legământul Meu,", {heb:"כֹּה אָמַר יְהוָה אִם לֹא בְרִיתִי", translit:"ko amar Adonai im lo veriti", strong:"H3541", pos:"adverb + verb, qal perfect + nume propriu + conjuncție + particulă negativă + substantiv construct + sufix", def_ro:"așa a spus DOMNUL: dacă nu [ar fi] legământul Meu.", dict_ro:"Rashi explică faptul că acest legământ se referă la legământul cu ziua și noaptea, ca ele să vină la vremea lor — nu la Tora, cum au tâlcuit unii învățători (Nedarim 32a), tâlcuire pe care Rashi o consideră nepotrivită cu șirul versetelor."}],
  ["legi pentru ceruri și pământ", {heb:"חֻקּוֹת שָׁמַיִם וָאָרֶץ", translit:"hukot șamaim vaareț", strong:"H2708", pos:"substantiv plural construct + substantiv + substantiv", def_ro:"legile cerului și pământului.", dict_ro:"Comparația dintre legile fixe ale cosmosului și legământul cu sămânța lui Iacov — la fel de imposibil de desființat cum e rânduiala zilei și nopții — încheie oracolul cu cea mai solidă garanție posibilă a restaurării finale."}]
]},
{v:"33:26", newTags:[
  ["și [pe cei] ai slujitorului Meu David i-aș fi", {heb:"וְדָוִד עַבְדִּי", translit:"vedavid avdi", strong:"H1732", pos:"nume propriu + substantiv construct + sufix", def_ro:"și pe David, slujitorul Meu.", dict_ro:"Metzudat David explică faptul că, dacă rânduiala zilei și a nopții s-ar putea desființa, abia atunci DOMNUL ar lepăda și sămânța lui Iacov și a lui David, robul Său — imposibilitatea primei condiții garantează imposibilitatea celei de-a doua."}],
  ["neluând pe urmașii conducătorilor peste urmașii lui Avraham, Isaac și Iacov. Căci le voi", {heb:"מִקַּחַת מִזַּרְעוֹ מֹשְׁלִים אֶל זֶרַע אַבְרָהָם יִשְׂחָק וְיַעֲקֹב כִּי", translit:"mikahat mizaro moșlim el zera avraham ishak veiaakov ki", strong:"H3947", pos:"verb, qal infinitiv + substantiv construct + sufix + verb, qal participiu + prepoziție + substantiv construct + nume propriu (repetat) + conjuncție", def_ro:"neluând din sămânța lui stăpânitori peste sămânța lui Avraam, Isaac și Iacov. Căci.", dict_ro:"Radak explică faptul că Ibn Ezra distinge aici două trepte ale promisiunii: regele trebuie să fie din sămânța lui Iacov, și, pe deasupra, din familia lui David — o dublă garanție dinastică pentru restaurarea finală a domniei."}]
]}
];
