module.exports = [
{v:"5:12", newTags:[
  ["DOMNUL i-a dat", {heb:"וַיהוָה נָתַן", translit:"va'Adonai natan", strong:"H3068", pos:"nume propriu + verb, qal perfect", def_ro:"și DOMNUL a dat.", dict_ro:"Radak explică faptul că rostul acestei povestiri despre înțelepciunea lui Solomon e arătat chiar prin mulțimea clădirilor pe care le-a zidit — se vede înțelepciunea lui, așa cum avea să o vadă mai târziu și împărăteasa din Saba."}],
  ["după cum îi vorbise", {heb:"כַּאֲשֶׁר דִּבֶּר לוֹ", translit:"kaașer diber lo", strong:"H834", pos:"particulă relativă + verb, piel perfect + prepoziție + sufix", def_ro:"după cum îi vorbise lui.", dict_ro:"Promisiunea înțelepciunii, deja făcută lui Solomon (1 Împărați 3:12), se împlinește aici vizibil — nu o dăruire nouă, ci confirmarea publică a unei făgăduințe anterioare."}]
]},
{v:"5:13", newTags:[
  ["Regele Solomon a", {heb:"וַיַּעַל הַמֶּלֶךְ שְׁלֹמֹה", translit:"vaiaal hameleh șelomo", strong:"H5927", pos:"verb, hifil imperfect consecutiv + substantiv + nume propriu", def_ro:"și a ridicat regele Solomon.", dict_ro:"Rashi explică faptul că această «robie» (mas) se ridica la o plată pentru treizeci de mii de oameni — un sistem de corvoadă organizată, nu o sclavie propriu-zisă."}],
  ["asupra întregului Israel", {heb:"מִכָּל יִשְׂרָאֵל", translit:"mikal israēl", strong:"H3605", pos:"substantiv construct + nume propriu", def_ro:"din tot Israelul.", dict_ro:"Taxa de muncă se aplică întregii națiuni, nu doar unei regiuni — proiectul Templului devine, prin această mobilizare generală, o lucrare cu adevărat națională."}]
]},
{v:"5:14", newTags:[
  ["Și i-a trimis în Liban în", {heb:"וַיִּשְׁלָחֵם לְבָנוֹנָה", translit:"vaișlahēm levanona", strong:"H7971", pos:"verb, qal imperfect consecutiv + sufix + nume propriu", def_ro:"și i-a trimis la Liban.", dict_ro:"Rashi detaliază precis sistemul de rotație lunară: zece mii plecau la Liban, revenind pentru a fi înlocuiți de a doua grupă, apoi a treia, ciclul repetându-se astfel încât fiecare bărbat servea o lună urmată de două luni de odihnă acasă."}],
  ["o lună erau detașați în Liban și două luni erau [fiecare] la casa lui. Și", {heb:"חֹדֶשׁ יִהְיוּ בַלְּבָנוֹן שְׁנַיִם חֳדָשִׁים בְּבֵיתוֹ וַ", translit:"hodeș ihiu valvanon șenaim hodașim bevēto va", strong:"H2320", pos:"substantiv + verb, qal imperfect + nume propriu + numeral + substantiv plural + substantiv construct + sufix", def_ro:"o lună erau în Liban, două luni în casa lui, și.", dict_ro:"Aranjamentul administrativ echitabil — o lună de corvoadă pentru două de odihnă — arată o organizare chibzuită a muncii obligatorii, nu o exploatare nelimitată a forței de lucru israelite."}]
]},
{v:"5:15", newTags:[
  ["Iar Solomon avea", {heb:"וַיְהִי לִשְׁלֹמֹה", translit:"vaihi lișlomo", strong:"H1961", pos:"verb, qal imperfect consecutiv + nume propriu", def_ro:"și avea Solomon.", dict_ro:"Rashi socotește că toți cei o sută cincizeci de mii de lucrători, cărăuși și tăietori în carieră, erau prozeliți atrași, convertiți din pricina mărimii și a mesei lui Solomon — nu israeliți nativi puși la corvoadă."}]
]},
{v:"5:16", newTags:[
  ["pe lângă cei trei mii trei sute de", {heb:"לְבַד מִשָּׂרֵי הַנִּצָּבִים לִשְׁלֹמֹה אֲשֶׁר עַל הַמְּלָאכָה שְׁלֹשֶׁת אֲלָפִים וּשְׁלֹשׁ מֵאוֹת", translit:"levad misarē hanițavim lișlomo așer al hamlaha șeloșet alafim ușloș mēot", strong:"H905", pos:"substantiv + substantiv plural construct + verb, nifal participiu + nume propriu + particulă relativă + prepoziție + substantiv + numeral + numeral + numeral + numeral", def_ro:"pe lângă căpeteniile puse de Solomon peste lucrare, trei mii trei sute.", dict_ro:"Rashi rezolvă o contradicție numerică reală între mai multe versete biblice care par să se contrazică asupra numărului exact al supraveghetorilor — explică faptul că unele surse numără doar supraveghetorii direcți ai prozeliților, altele adaugă și o categorie superioară de supraveghere generală."}]
]},
{v:"5:17", newTags:[
  ["Și regele a dat poruncă și ei au", {heb:"וַיְצַו הַמֶּלֶךְ וַיַּסִּעוּ", translit:"vaițav hameleh vaiasiu", strong:"H6680", pos:"verb, piel imperfect consecutiv + substantiv + verb, hifil imperfect consecutiv", def_ro:"și a poruncit regele și au dislocat.", dict_ro:"Porunca regală directă declanșează extracția pietrelor masive necesare fundației — un act de autoritate regală aplicat primei etape, cea mai grea, a construcției."}],
  ["ca să așeze fundația Templului cu", {heb:"לְיַסֵּד הַבָּיִת", translit:"leiasēd habait", strong:"H3245", pos:"verb, piel infinitiv + substantiv", def_ro:"ca să întemeieze Templul.", dict_ro:"Rashi rezolvă tensiunea aparentă cu v.7 din capitolul următor, care spune că niciun fier n-a fost auzit la Templu: pietrele fundației erau cioplite și finisate afară, la carieră, apoi transportate deja gata."}]
]},
{v:"5:18", newTags:[
  ["Constructorii lui Solomon, constructorii lui Hiram și", {heb:"בֹּנֵי שְׁלֹמֹה וּבֹנֵי חִירוֹם", translit:"bonē șelomo uvonē hirom", strong:"H1129", pos:"verb, qal participiu + nume propriu + verb, qal participiu + nume propriu", def_ro:"constructorii lui Solomon și constructorii lui Hiram și.", dict_ro:"Colaborarea explicită între constructorii israeliți și cei tirieni, alături de ghibliții iscusiți (menționați și la Ezechiel 27:9 pentru lucrul la corăbii), arată caracterul internațional al expertizei tehnice mobilizate pentru Templu."}]
]},
{v:"6:1", newTags:[
  ["după ieșirea copiilor lui Israel din țara Egiptului", {heb:"לְצֵאת בְּנֵי יִשְׂרָאֵל מֵאֶרֶץ מִצְרַיִם", translit:"lețēt benē israēl mēereț mițraim", strong:"H3318", pos:"verb, qal infinitiv + substantiv construct + nume propriu + substantiv construct + nume propriu", def_ro:"de la ieșirea copiilor lui Israel din țara Egiptului.", dict_ro:"Datarea Templului prin numărarea anilor de la Exod, nu doar prin anul domniei lui Solomon, leagă construcția direct de evenimentul fondator al poporului — Templul e punctul culminant al unui proiect început la Sinai."}],
  ["în anul al patrulea de domnie a lui Solomon peste Israel", {heb:"בַּשָּׁנָה הָרְבִיעִית... לִמְלֹךְ שְׁלֹמֹה עַל יִשְׂרָאֵל", translit:"bașana harvit... limloh șelomo al israēl", strong:"H8141", pos:"substantiv + numeral ordinal + verb, qal infinitiv + nume propriu + prepoziție + nume propriu", def_ro:"în anul al patrulea al domniei lui Solomon peste Israel.", dict_ro:"Rashi leagă explicit «anul al patrulea» de domnia lui Solomon, confirmat identic și în 2 Cronici 3:2 — a doua datare precisă, complementară celei de la Exod, fixează momentul istoric al începerii construcției."}],
  ["a construit Templul pentru DOMNUL", {heb:"וַיִּבֶן הַבַּיִת לַיהוָה", translit:"vaiven habait la'Adonai", strong:"H1129", pos:"verb, qal imperfect consecutiv + substantiv + nume propriu", def_ro:"a construit Casa pentru DOMNUL.", dict_ro:"Formula finală a versetului rezumă scopul întregii narațiuni cronologice precedente — toate datările converg spre acest moment unic: începerea construcției Casei DOMNULUI."}]
]},
{v:"6:2", newTags:[
  ["Iar Templul pe care Solomon l-a construit pentru DOMNUL era de", {heb:"וְהַבַּיִת אֲשֶׁר בָּנָה הַמֶּלֶךְ שְׁלֹמֹה לַיהוָה", translit:"vehabait așer bana hameleh șelomo la'Adonai", strong:"H1004", pos:"substantiv + particulă relativă + verb, qal perfect + substantiv + nume propriu + nume propriu", def_ro:"și Templul pe care l-a construit regele Solomon pentru DOMNUL.", dict_ro:"Rashi explică faptul că cei șaizeci de coți ai lungimii totale includ împreună Locul Sfânt și Locul Preasfânt — dimensiunile exacte ale acestui verset devin reperul tehnic pentru toată descrierea arhitecturală care urmează."}]
]},
{v:"6:4", newTags:[
  ["Și a făcut pentru Templu", {heb:"וַיַּעַשׂ לַבָּיִת", translit:"vaiaas labait", strong:"H6213", pos:"verb, qal imperfect consecutiv + substantiv", def_ro:"și a făcut pentru Templu.", dict_ro:"Rashi explică faptul că aceste ferestre erau deschise pe dinafară și închise pe dinăuntru, înguste, nu după felul celorlalte ferestre făcute pentru lumină — ca să arate că Templul n-are nevoie de lumină naturală, Șechina Însăși fiind lumina lui."}]
]},
{v:"6:5", newTags:[
  ["Lângă peretele Templului a construit o", {heb:"וַיִּבֶן עַל קִיר הַבַּיִת", translit:"vaiven al kir habait", strong:"H1129", pos:"verb, qal imperfect consecutiv + prepoziție + substantiv construct + substantiv", def_ro:"și a construit lângă peretele Templului.", dict_ro:"Rashi explică faptul că acest rând de odăi are trei nume diferite în Scriptură — iația, ta și țela — toate desemnând aceeași structură anexă, lipită de zidurile exterioare ale Sălii Sfinte și ale Sfintei Sfintelor."}],
  ["de jur împrejur – pereții Templului de jur împrejurul Sălii și", {heb:"סָבִיב אֶת קִירוֹת הַבַּיִת סָבִיב לַהֵיכָל וְלַדְּבִיר", translit:"saviv et kirot habait saviv lahēhal veladvir", strong:"H5439", pos:"substantiv + marcă a complementului direct + substantiv plural construct + substantiv + substantiv + substantiv + substantiv", def_ro:"de jur împrejur, pereții Templului de jur împrejurul Sălii Sfinte și al Sfintei Sfintelor.", dict_ro:"Camerele anexă înconjoară deopotrivă Locul Sfânt și Locul Preasfânt, pe toate cele trei laturi libere ale clădirii — doar fațada dinspre pridvor rămânea fără aceste odăi laterale."}],
  ["și a făcut camere de jur împrejur", {heb:"וַיַּעַשׂ צְלָעוֹת סָבִיב", translit:"vaiaas țelaot saviv", strong:"H6213", pos:"verb, qal imperfect consecutiv + substantiv + substantiv", def_ro:"și a făcut odăi de jur împrejur.", dict_ro:"Formula de încheiere a versetului confirmă execuția completă a planului descris — odăile anexe acoperă integral perimetrul lateral al clădirii sacre."}]
]},
{v:"6:6", newTags:[
  ["Nivelul de jos era lat de cinci coți, cel mijlociu era lat de șase coți, iar al treilea era lat de șapte coți, căci făcuse", {heb:"הַיָּצִיעַ הַתַּחְתֹּנָה חָמֵשׁ בָּאַמָּה רָחְבָּהּ וְהַתִּיכֹנָה שֵׁשׁ בָּאַמָּה רָחְבָּהּ וְהַשְּׁלִישִׁית שֶׁבַע בָּאַמָּה רָחְבָּהּ כִּי מִגְרָעוֹת נָתַן", translit:"haiația hatahtona hamēș baama rahbah vehatihona șēș baama rahbah vehașlișit șeva baama rahbah ki migraot natan", strong:"H3326", pos:"substantiv + adjectiv + numeral + substantiv + substantiv construct + sufix (repetat pe trei niveluri) + conjuncție + substantiv + verb, qal perfect", def_ro:"anexa de jos, cinci coți lățimea ei; cea de mijloc, șase coți lățimea ei; și a treia, șapte coți lățimea ei, căci a făcut praguri.", dict_ro:"Rashi descrie tehnica arhitecturală precisă, confirmată în Tratatul Middot: zidul Sălii se subția cu un cot la fiecare cinci coți de înălțime, creând praguri pe care se sprijineau capetele grinzilor fiecărui nivel al anexei, fără ca acestea să fie înfipte direct în zidul sacru al Templului."}]
]},
{v:"6:8", newTags:[
  ["Intrarea camerei centrale de jos era în partea de miazăzi a Templului, iar pe o", {heb:"פֶּתַח הַצֵּלָע הַתִּיכֹנָה אֶל כֶּתֶף הַבַּיִת הַיְמָנִית וּבְלוּלִּים", translit:"petah hațēla hatihona el ketef habait haimanit uvlulim", strong:"H6607", pos:"substantiv construct + substantiv + adjectiv + prepoziție + substantiv construct + substantiv + adjectiv + substantiv", def_ro:"ușa odăii de mijloc era pe partea dreaptă a Templului, și o scară în spirală.", dict_ro:"Rashi descrie construcția scării în spirală: un stâlp de piatră în jurul căruia se înfășoară trepte, oferind acces la nivelurile superioare fără a necesita o pantă lină ca la o scară dreaptă obișnuită."}]
]},
{v:"6:9", newTags:[
  ["[Solomon] a construit Templul și l-a", {heb:"וַיִּבֶן אֶת הַבַּיִת וַיְכַלֵּהוּ", translit:"vaiven et habait vaihalēhu", strong:"H1129", pos:"verb, qal imperfect consecutiv + marcă a complementului direct + substantiv + verb, piel imperfect consecutiv + sufix", def_ro:"a construit Templul și l-a isprăvit.", dict_ro:"Verbul «a isprăvi» (kalah) marchează finalizarea întregii structuri de bază, înainte de etapa decorativă a tavanului descrisă imediat după."}]
]},
{v:"6:10", newTags:[
  ["A construit camera de jur împrejurul întregului Templu, de", {heb:"וַיִּבֶן אֶת הַיָּצִיעַ עַל כָּל הַבַּיִת חָמֵשׁ אַמּוֹת", translit:"vaiven et haiația al kal habait hamēș amot", strong:"H1129", pos:"verb, qal imperfect consecutiv + marcă a complementului direct + substantiv + prepoziție + substantiv construct + substantiv + numeral + substantiv", def_ro:"a construit anexa peste tot Templul, de cinci coți.", dict_ro:"Rashi precizează: înălțimea totală a anexei, cu cele trei niveluri de cinci coți fiecare, era de cincisprezece coți, fără a socoti grosimea tavanului fiecărui etaj."}]
]},
{v:"6:12", newTags:[
  ["Acest Templu pe care îl construiești – dacă vei urma", {heb:"הַבַּיִת הַזֶּה אֲשֶׁר אַתָּה בֹנֶה אִם תֵּלֵךְ", translit:"habait haze așer ata vone im tēlēh", strong:"H1004", pos:"substantiv + pronume demonstrativ + particulă relativă + pronume personal + verb, qal participiu + conjuncție + verb, qal imperfect", def_ro:"Templul acesta pe care tu îl construiești — dacă vei merge.", dict_ro:"Metzudat David explică faptul că, deși Solomon zidește frumos, cu toate clădirile, DOMNUL nu-Și va face să locuiască Prezența în el decât condiționat de ascultarea legilor Sale — frumusețea arhitecturală nu înlocuiește fidelitatea morală."}]
]}
];
