module.exports = [
{v:"43:10", newTags:[
  ["Tu, fiu al omului, spune casei lui Israel despre Templu și fă-i să se", {heb:"אַתָּה בֶן אָדָם הַגֵּד אֶת בֵּית יִשְׂרָאֵל אֶת הַבַּיִת וְיִכָּלְמוּ", translit:"ata ven adam hagēd et bēt israēl et habait veikalmu", strong:"H859", pos:"pronume personal + substantiv construct + substantiv + verb, hifil imperativ + marcă a complementului direct + substantiv construct + nume propriu (repetat) + verb, nifal jusiv", def_ro:"tu, fiu al omului, vestește casei lui Israel despre Templu, ca să se rușineze.", dict_ro:"Rashi citește porunca drept act de har divin, nu de pedeapsă: descrierea măreției Templului viitor produce rușine autentică pentru trecut tocmai pentru că vine ca dar nemeritat, nu ca amenințare."}]
]},
{v:"43:11", newTags:[
  ["Și dacă le va fi rușine de tot ce au făcut – de", {heb:"וְאִם נִכְלְמוּ מִכֹּל אֲשֶׁר עָשׂוּ", translit:"veim nihlemu mikol așer asu", strong:"H3637", pos:"conjuncție + verb, nifal perfect + substantiv + particulă relativă + verb, qal perfect", def_ro:"și dacă se vor rușina de tot ce au făcut.", dict_ro:"Metzudat David explică faptul că profetul trebuie să vadă pe fețele lor dacă, amintindu-și de Templul dintâi dărâmat din pricina nelegiuirii, se rușinează de faptele rele — iar dacă și-au făcut fața «mai tare decât stânca», să nu mai adauge nimic despre forma Templului."}],
  ["ieșirile și intrările sale cu toate formele sale, toate edictele cu toate formele sale și toate regulile sale –", {heb:"וּמוֹצָאָיו וּמוֹבָאָיו וְכָל צוּרֹתָו וְאֵת כָּל חֻקֹּתָיו וְכָל צוּרֹתָיו וְכָל תּוֹרֹתָיו", translit:"umoțaaiv umovaaiv vehal țurotav veēt kal hukotaiv vehal țurotaiv vehal torotaiv", strong:"H4161", pos:"substantiv plural construct + sufix + substantiv plural construct + sufix + substantiv construct + substantiv plural construct + sufix (repetat de trei ori pentru hotărâri, forme, legi)", def_ro:"ieșirile ei și intrările ei și toate formele ei și toate rânduielile ei și toate formele ei și toate legile ei.", dict_ro:"Metzudat David explică «ieșirile și intrările» ca măsura ușilor pe unde se iese și se intră, iar «toate regulile ei» ca locul unde stau preoții și poporul — Radak adaugă că cei care vor păzi aceste rânduieli în inimă vor fi vrednici de învierea morților, căci Scriptura măsoară om pentru om, măsură pentru măsură."}]
]},
{v:"43:12", newTags:[
  ["pe vârful muntelui, tot", {heb:"עַל רֹאשׁ הָהָר כָּל", translit:"al roș hahar kal", strong:"H7218", pos:"prepoziție + substantiv construct + substantiv + substantiv construct", def_ro:"pe vârful muntelui, tot.", dict_ro:"Metzudat David explică faptul că clădirea viitoare va sta chiar pe vârful muntelui Templului — toată moșia preoților și leviților se numește «sfântă», dar muntele Templului însuși e numit, față de ea, «Sfânta Sfintelor»."}],
  ["de jur împrejur este Sfânta Sfintelor; iată, aceasta este", {heb:"סָבִיב סָבִיב קֹדֶשׁ קָדָשִׁים הִנֵּה זֹאת", translit:"saviv saviv kodeș kadașim hinē zot", strong:"H5439", pos:"substantiv (repetat) + substantiv construct + substantiv + particulă demonstrativă + pronume demonstrativ", def_ro:"de jur împrejur, de jur împrejur, sfânta sfintelor; iată, aceasta este.", dict_ro:"Radak explică gradația sfințeniei: tot Ierusalimul e sfânt, muntele Templului e sfânt al sfintelor față de cetate, iar locul Templului însuși, al altarului și Locul Preasfânt sunt sfinte ale sfintelor în interiorul muntelui."}]
]},
{v:"43:14", newTags:[
  ["Iar de la baza care este pe pământ", {heb:"וּמֵחֵיק הָאָרֶץ", translit:"umēhēk haareț", strong:"H2436", pos:"substantiv construct + substantiv", def_ro:"și de la poala pământului.", dict_ro:"Rashi explică faptul că măsura începe exact de la fața pământului, de la temelia altarului — primul punct de referință al întregii descrieri arhitecturale care urmează."}]
]},
{v:"43:17", newTags:[
  ["Iar Azara are paisprezece coți lungime și paisprezece coți lățime, către cele patru sferturi ale sale", {heb:"וְהָעֲזָרָה אַרְבַּע עֶשְׂרֵה אֹרֶךְ בְּאַרְבַּע עֶשְׂרֵה רֹחַב אֶל אַרְבַּעַת רְבָעֶיהָ", translit:"vehaazara arba esrē oreh bearba esrē rohav el arbaat revaeha", strong:"H5835", pos:"substantiv + numeral + numeral + substantiv + numeral + numeral + substantiv + prepoziție + numeral + substantiv plural construct + sufix", def_ro:"și pervazul, paisprezece [coți] lungime, pe paisprezece lățime, către cele patru laturi ale sale.", dict_ro:"Rashi explică faptul că acoperișul altarului, cu locul coarnelor și cu locul picioarelor preoților, era de douăzeci și opt pe douăzeci și opt, iar cei paisprezece coți sunt măsurați de la mijlocul lui spre fiecare parte."}]
]},
{v:"43:18", newTags:[
  ["Apoi mi-a spus: „Fiul omului, așa spune Stăpânul meu, Domnul DUMNEZEU: «Acestea sunt", {heb:"וַיֹּאמֶר אֵלַי בֶּן אָדָם כֹּה אָמַר אֲדֹנָי יֱהוִה אֵלֶּה", translit:"vaiomer ēlai ben adam ko amar adonai Adonai ēle", strong:"H559", pos:"verb, qal imperfect consecutiv + prepoziție + sufix + substantiv construct + substantiv + adverb + verb, qal perfect + substantiv construct + sufix + nume propriu + pronume demonstrativ", def_ro:"și mi-a spus: fiu al omului, așa a spus Stăpânul meu, Domnul DUMNEZEU: acestea sunt.", dict_ro:"Formula de poruncă divină directă precedă rânduielile exacte ale sfințirii altarului — fiecare detaliu al ritualului de inaugurare vine direct din gura DOMNULUI, nu din tradiția omenească."}]
]},
{v:"43:19", newTags:[
  ["Dă-le preoților", {heb:"וְנָתַתָּה אֶל הַכֹּהֲנִים", translit:"venatata el hakohanim", strong:"H5414", pos:"verb, qal perfect consecutiv + prepoziție + substantiv", def_ro:"și vei da preoților.", dict_ro:"Porunca de a preda animalul jertfei direct preoților marchează începutul ritualului de inaugurare a altarului, condus exclusiv de clasa sacerdotală autorizată."}],
  ["care vin aproape de Mine ca să Îmi slujească – rostirea Stăpânului meu, Domnul DUMNEZEU – un tăuraș ca jertfă de păcat", {heb:"הַקְּרֹבִים אֵלַי נְאֻם אֲדֹנָי יֱהוִה לְשָׁרְתֵנִי פַּר בֶּן בָּקָר לְחַטָּאת", translit:"hakrovim ēlai neum adonai Adonai leșartēni par ben bakar lehatat", strong:"H7138", pos:"adjectiv + prepoziție + sufix + substantiv construct + sufix + nume propriu + verb, piel infinitiv + sufix + substantiv + substantiv construct + substantiv + substantiv", def_ro:"cei care se apropie de Mine, rostirea Stăpânului meu, Domnul DUMNEZEU, să-Mi slujească, un tăuraș ca jertfă de păcat.", dict_ro:"Rashi explică faptul că acești preoți «din sămânța lui Țadoc» sunt numiți așa pentru că Țadoc a fost marele preot care a slujit cel dintâi în Templu, în zilele lui Solomon — linia preoțească legitimă e definită explicit prin descendența lui."}]
]},
{v:"43:20", newTags:[
  ["Și ia din sângele lui și pune-l pe cele patru", {heb:"וְלָקַחְתָּ מִדָּמוֹ וְנָתַתָּה עַל אַרְבַּע", translit:"velakahta midamo venatata al arba", strong:"H3947", pos:"verb, qal perfect consecutiv + substantiv construct + sufix + verb, qal perfect consecutiv + prepoziție + numeral", def_ro:"și vei lua din sângele lui și vei pune pe cele patru.", dict_ro:"Rashi explică faptul că ungerea coarnelor altarului cu sânge are scopul de a-l curăți de starea lui obișnuită, aducându-l în sfințenie, ca să fie vrednic să se facă pe el ispășire de acum înainte."}]
]},
{v:"43:23", newTags:[
  ["Atunci când vei fi isprăvit [curățirea] de păcate, să aduci un tăuraș fără meteahnă, și un", {heb:"בְּכַלּוֹתְךָ מֵחַטֵּא תַּקְרִיב פַּר בֶּן בָּקָר תָּמִים וְאַיִל", translit:"behalotha mēhatē takriv par ben bakar tamim veail", strong:"H3615", pos:"verb, piel infinitiv + sufix + verb, piel infinitiv + verb, hifil imperfect + substantiv + substantiv construct + substantiv + adjectiv + substantiv", def_ro:"când vei fi isprăvit de curățit, vei aduce un tăuraș fără meteahnă și un berbec.", dict_ro:"Radak notează că această a doua etapă a curățirii, cu tăuraș și berbec împreună, nu are precedent în rânduiala de la Cortul Întâlnirii din zilele lui Moise — o înnoire rituală specifică Templului viitor."}]
]},
{v:"43:24", newTags:[
  ["Să îi apropii înaintea DOMNULUI și preoții să arunce", {heb:"וְהִקְרַבְתָּם לִפְנֵי יְהוָה וְהִשְׁלִיכוּ הַכֹּהֲנִים עֲלֵיהֶם", translit:"vehikravtam lifnē Adonai vehișlihu hakohanim alēhem", strong:"H7126", pos:"verb, hifil perfect consecutiv + sufix + substantiv construct + nume propriu + verb, hifil perfect consecutiv + substantiv + prepoziție + sufix", def_ro:"și le vei apropia înaintea DOMNULUI și preoții vor arunca peste ele.", dict_ro:"Radak leagă aruncarea sării peste jertfe direct de porunca Torei: «la toate darurile tale să aduci sare» (Levitic 2:13) — ritualul altarului viitor respectă exact rânduiala originară a jertfelor."}]
]},
{v:"43:26", newTags:[
  ["Șapte zile să facă ispășire pentru altar și să-l curețe și să-l", {heb:"שִׁבְעַת יָמִים יְכַפְּרוּ אֶת הַמִּזְבֵּחַ וְטִהֲרוּ אֹתוֹ וּמִלְאוּ", translit:"șivat iamim iehapru et hamizbēah vetiharu oto umilu", strong:"H7651", pos:"numeral + substantiv + verb, piel imperfect + marcă a complementului direct + substantiv + verb, piel perfect consecutiv + sufix + verb, piel perfect consecutiv", def_ro:"șapte zile vor face ispășire pentru altar și îl vor curăți și îi vor umple.", dict_ro:"Radak explică faptul că altarul trebuie curățit pentru că fusese pângărit de mâna neamurilor țării — cele șapte zile de ispășire repetată corespund ciclului complet al sfințirii, înainte de folosirea lui obișnuită."}]
]},
{v:"43:27", newTags:[
  ["Iar când se vor fi încheiat zilele, începând din", {heb:"וִיכַלּוּ אֶת הַיָּמִים וְהָיָה בַיּוֹם", translit:"vihalu et haiamim vehaia vaiom", strong:"H3615", pos:"verb, piel imperfect + marcă a complementului direct + substantiv + verb, qal perfect consecutiv + substantiv", def_ro:"și vor încheia zilele, și va fi în ziua.", dict_ro:"Radak compară acest termen de șapte zile de inaugurare cu rânduiala similară de la Cortul Întâlnirii, în ziua a opta a închinării (Levitic 9) — modelul mozaic se repetă, cu înnoiri proprii, pentru Templul viitor."}],
  ["preoții pot pregăti pe altar arderile-de-tot ale tale și jertfele tale de pace, iar Eu îți voi arăta", {heb:"יַעֲשׂוּ הַכֹּהֲנִים עַל הַמִּזְבֵּחַ אֶת עוֹלוֹתֵיכֶם וְאֶת שַׁלְמֵיכֶם", translit:"iaasu hakohanim al hamizbēah et olotēhem veet șalmēhem", strong:"H6213", pos:"verb, qal imperfect + substantiv + prepoziție + substantiv + marcă a complementului direct + substantiv plural construct + sufix (repetat)", def_ro:"vor pregăti preoții pe altar arderile voastre de tot și jertfele voastre de pace.", dict_ro:"Trecerea de la jertfele de inaugurare, obligatorii și unice, la arderile-de-tot și jertfele de pace obișnuite marchează momentul în care altarul devine pe deplin funcțional pentru cultul zilnic al poporului."}]
]}
];
