module.exports = [
{v:"7:13", newTags:[
  ["Regele Solomon a trimis și l-a adus pe", {heb:"וַיִּשְׁלַח הַמֶּלֶךְ שְׁלֹמֹה וַיִּקַּח אֶת", translit:"vaișlah hameleh șelomo vaikah et", strong:"H7971", pos:"verb, qal imperfect consecutiv + substantiv + nume propriu + verb, qal imperfect consecutiv + marcă a complementului direct", def_ro:"și a trimis regele Solomon și a luat pe.", dict_ro:"Metzudat David explică simplu: «pe Hiram» — așa era numele meșterului chemat special pentru lucrările de aramă ale Templului, distinct de regele omonim al Tirului."}]
]},
{v:"7:14", newTags:[
  ["El era fiul unei femei văduve din tribul Naftali, iar tatăl lui era un bărbat din Tir. El era făuritor în aramă", {heb:"בֶּן אִשָּׁה אַלְמָנָה הוּא מִמַּטֵּה נַפְתָּלִי וְאָבִיו אִישׁ צֹרִי חֹרֵשׁ נְחֹשֶׁת", translit:"ben ișa almana hu mimatē naftali veaviv iș țori horēș nehoșet", strong:"H1121", pos:"substantiv construct + substantiv + substantiv + pronume personal + substantiv construct + nume propriu + substantiv construct + sufix + substantiv + nume de neam + verb, qal participiu + substantiv", def_ro:"fiul unei femei văduve, el, din tribul Naftali, și tatăl lui, om din Tir, meșter în aramă.", dict_ro:"Radak explică faptul că tatăl lui Hiram era și el făuritor în aramă, iar Înțelepții noștri s-au sprijinit pe acest verset pentru a spune că omul trebuie să se îndeletnicească cu meșteșugul tatălui său — Hiram a învățat arta tocmai de la el."}],
  ["talent și cunoaștere în întocmirea oricărei lucrări din aramă, și a venit la regele Solomon și a făcut toată lucrarea lui", {heb:"וְאֶת הַתְּבוּנָה וְאֶת הַדַּעַת לַעֲשׂוֹת כָּל מְלָאכָה בַּנְּחֹשֶׁת וַיָּבוֹא אֶל הַמֶּלֶךְ שְׁלֹמֹה וַיַּעַשׂ אֶת כָּל מְלַאכְתּוֹ", translit:"veet hatvuna veet hadaat laasot kal melaha banhoșet vaiavo el hameleh șelomo vaiaas et kal melahto", strong:"H8394", pos:"marcă a complementului direct + substantiv + marcă a complementului direct + substantiv + verb, qal infinitiv + substantiv + substantiv + verb, qal imperfect consecutiv + prepoziție + substantiv + nume propriu + verb, qal imperfect consecutiv + marcă a complementului direct + substantiv construct + sufix", def_ro:"și priceperea și cunoștința de a face orice lucrare din aramă; și a venit la regele Solomon și a făcut toată lucrarea lui.", dict_ro:"Rashi leagă cele trei calități — înțelepciune, pricepere, cunoștință — de cele trei unelte cu care a fost zidită lumea însăși, potrivit Proverbelor 3:19-20: Templul a fost construit cu exact aceleași trei calități divine."}]
]},
{v:"7:15", newTags:[
  ["Și [Hiram] a făurit cei doi", {heb:"וַיָּצַר אֶת שְׁנֵי", translit:"vaiațar et șenē", strong:"H6696", pos:"verb, qal imperfect consecutiv + marcă a complementului direct + numeral", def_ro:"și a turnat cei doi.", dict_ro:"Verbul «a turna/a forma» (iațar) deschide descrierea tehnică a celor doi stâlpi de aramă — aceeași rădăcină folosită pentru plăsmuirea omului din țărână la Geneza 2:7, aplicată aici metalului topit."}],
  ["de aramă: optsprezece coți era înălțimea fiecărui stâlp și o sfoară [cu lungimea] de doisprezece coți îi putea măsura circumferința; și la fel era și al doilea stâlp", {heb:"נְחֹשֶׁת שְׁמֹנֶה עֶשְׂרֵה אַמָּה קוֹמַת הָעַמּוּד הָאֶחָד וְחוּט שְׁתֵּים עֶשְׂרֵה אַמָּה יָסֹב אֶת הָעַמּוּד הַשֵּׁנִי", translit:"nehoșet șemone esrē ama komat haamud haehad vehut șetēm esrē ama iasov et haamud hașēni", strong:"H5178", pos:"substantiv + numeral + numeral + substantiv + substantiv construct + substantiv + numeral + substantiv construct + numeral + numeral + substantiv + verb, qal imperfect + marcă a complementului direct + substantiv + numeral ordinal", def_ro:"aramă, optsprezece coți înălțimea unui stâlp, și un fir de doisprezece coți îl înconjoară; și așa era și al doilea stâlp.", dict_ro:"Rashi rezolvă discrepanța dintre cei optsprezece coți de aici și cei treizeci și cinci din Cronici, explicând că relatarea din Cronici numără lungimea totală a metalului turnat pentru amândoi stâlpii, incluzând porțiunile ascunse în interiorul zidului."}]
]},
{v:"7:16", newTags:[
  ["A făcut două", {heb:"וּשְׁתֵּי כֹתָרֹת עָשָׂה", translit:"uștē hotarot asa", strong:"H3805", pos:"numeral + substantiv + verb, qal perfect", def_ro:"și două capiteluri a făcut.", dict_ro:"Radak explică «hotarot» ca «cununi», comparabile cu o cunună de domnie — aceste piese ornamentale încoronau literal vârful fiecărui stâlp al Templului."}],
  ["care să fie puse la vârful celor doi stâlpi, turnate din aramă; înălțimea unui capitel era de cinci coți și înălțimea celuilalt capitel era de cinci coți", {heb:"לָתֵת עַל רָאשֵׁי הָעַמּוּדִים מֻצַק נְחֹשֶׁת חָמֵשׁ אַמּוֹת קוֹמַת הַכֹּתֶרֶת הָאֶחָת וְחָמֵשׁ אַמּוֹת קוֹמַת הַכֹּתֶרֶת הַשֵּׁנִית", translit:"latēt al rașē haamudim muțak nehoșet hamēș amot komat hakoteret haehat vehamēș amot komat hakoteret hașēnit", strong:"H5414", pos:"verb, qal infinitiv + prepoziție + substantiv plural construct + substantiv + verb, hofal participiu pasiv + substantiv + numeral + substantiv + substantiv construct + substantiv + numeral + numeral + substantiv + substantiv construct + substantiv + numeral ordinal", def_ro:"ca să le pună pe vârfurile stâlpilor, turnate din aramă; cinci coți înălțimea unui capitel și cinci coți înălțimea celui de-al doilea capitel.", dict_ro:"Radak explică discrepanța cu măsura de trei coți din finalul cărții (2 Împărați 25:17): cei doi coți de jos ai capitelurilor erau asemenea stâlpului, fără formă proprie, iar cei trei de sus, înconjurați de rețele, erau singurii socotiți separat ca «podoabă»."}]
]},
{v:"7:17", newTags:[
  ["A făcut niște", {heb:"שְׂבָכִים מַעֲשֵׂה שְׂבָכָה", translit:"sevahim maasē sevaha", strong:"H7638", pos:"substantiv + substantiv construct + substantiv", def_ro:"rețele, lucrare de plasă.", dict_ro:"Rashi explică faptul că aceste rețele erau ca un fel de acoperământ de cap, cu ramuri împletite, imagine care revine și în descrierea Sfintei Sfintelor din Ezechiel."}],
  ["de plasă împletită, din lanțuri împletite, pentru capitelurile care se aflau pe vârful stâlpilor – șapte pentru primul capitel și șapte pentru al doilea capitel", {heb:"גְּדִלִים מַעֲשֵׂה שַׁרְשְׁרוֹת לַכֹּתָרֹת אֲשֶׁר עַל רֹאשׁ הָעַמּוּדִים שִׁבְעָה לַכֹּתֶרֶת הָאֶחָת וְשִׁבְעָה לַכֹּתֶרֶת הַשֵּׁנִית", translit:"gedilim maasē șarșerot lakotarot așer al roș haamudim șiva lakoteret haehat veșiva lakoteret hașēnit", strong:"H1434", pos:"substantiv + substantiv construct + substantiv + substantiv + particulă relativă + prepoziție + substantiv construct + substantiv + numeral + substantiv + numeral + substantiv + numeral ordinal", def_ro:"ciucuri, lucrare de lănțișoare, pentru capiteluri, care erau pe vârful stâlpilor — șapte pentru capitelul unu și șapte pentru capitelul al doilea.", dict_ro:"Metzudat Țion explică «sevahim» prin asemănarea cu ramurile unui stejar, iar «gedilim» ca ciucuri împletiți și răsuciți, aceeași rădăcină folosită pentru ciucurii porunciți la Deuteronom 22:12 — o legătură lexicală neașteptată între ornamentul Templului și porunca îmbrăcămintei personale."}]
]},
];
