module.exports = [
{v:"7:51", newTags:[
  ["Când s-a isprăvit toată lucrarea pe care o făcuse regele Solomon în Casa DOMNULUI", {heb:"וַתִּשְׁלַם כָּל הַמְּלָאכָה אֲשֶׁר עָשָׂה הַמֶּלֶךְ שְׁלֹמֹה בֵּית יְהוָה", translit:"vatișlam kal hamlaha așer asa hameleh șelomo bēt Adonai", strong:"H7999", pos:"verb, qal imperfect consecutiv + substantiv construct + substantiv + particulă relativă + verb, qal perfect + substantiv + nume propriu + substantiv construct + nume propriu", def_ro:"și s-a desăvârșit toată lucrarea pe care a făcut-o regele Solomon [pentru] Casa DOMNULUI.", dict_ro:"Formula de încheiere marchează finalul complet al construcției Templului, pregătind tranziția spre ceremonia de dedicare și aducere a Chivotului care urmează."}],
  ["Solomon a adus", {heb:"וַיָּבֵא שְׁלֹמֹה", translit:"vaiavē șelomo", strong:"H935", pos:"verb, hifil imperfect consecutiv + nume propriu", def_ro:"și a adus Solomon.", dict_ro:"Radak explică faptul că Solomon a pus în zidirea Templului o parte din lucrurile închinate de tatăl său, spre cinstea lui, deși nu avea nevoie de ele, căci avea argint și aur din belșug propriu."}],
  ["tatăl său David", {heb:"דָּוִד אָבִיו", translit:"david aviv", strong:"H1732", pos:"nume propriu + substantiv construct + sufix", def_ro:"David, tatăl lui.", dict_ro:"Rashi redă un midraș alternativ: potrivit unora, Solomon n-a vrut să folosească nimic din lucrurile închinate de David pentru zidirea Templului, ca să nu dea neamurilor păgâne prilej să spună că idolii lor s-au răzbunat pe un Templu zidit din prada luată de la ei."}],
  ["aurul, argintul și vasele – pe care le pusese în visteriile Casei DOMNULUI", {heb:"אֶת הַכֶּסֶף וְאֶת הַזָּהָב וְאֶת הַכֵּלִים נָתַן בְּאֹצְרוֹת בֵּית יְהוָה", translit:"et hakesef veet hazahav veet hakēlim natan beoțrot bēt Adonai", strong:"H3701", pos:"marcă a complementului direct + substantiv + marcă a complementului direct + substantiv + marcă a complementului direct + substantiv + verb, qal perfect + substantiv plural construct + substantiv construct + nume propriu", def_ro:"argintul și aurul și vasele le-a pus în visteriile Casei DOMNULUI.", dict_ro:"O a treia explicație rabinică, redată tot de Rashi: Solomon ar fi vrut să cheltuiască aceste bunuri închinate pentru a-i hrăni pe săracii lui Israel în anii de foamete ai lui David, dar a ales în cele din urmă să le depună integral în vistieriile Templului."}]
]},
{v:"8:1", newTags:[
  ["Atunci, Solomon i-a adunat laolaltă pe bătrânii lui Israel", {heb:"אָז יַקְהֵל שְׁלֹמֹה אֶת זִקְנֵי יִשְׂרָאֵל", translit:"az iakhēl șelomo et ziknē israēl", strong:"H227", pos:"adverb + verb, hifil jusiv + nume propriu + marcă a complementului direct + adjectiv + nume propriu", def_ro:"atunci a adunat Solomon pe bătrânii lui Israel.", dict_ro:"Convocarea tuturor categoriilor de conducere — bătrâni, căpetenii de triburi, căpetenii de familii — pregătește un eveniment de amploare națională, nu o ceremonie restrânsă la curtea regală."}],
  ["și pe toți conducătorii triburilor, pe conducătorii familiilor patriarhale ale copiilor lui Israel", {heb:"אֶת כָּל רָאשֵׁי הַמַּטּוֹת נְשִׁיאֵי הָאָבוֹת לִבְנֵי יִשְׂרָאֵל", translit:"et kal rașē hamatot nesiē haavot livnē israēl", strong:"H7218", pos:"marcă a complementului direct + substantiv construct + substantiv construct + substantiv + substantiv plural construct + substantiv + substantiv plural construct + nume propriu", def_ro:"pe toate căpeteniile triburilor, conducătorii familiilor patriarhale ale fiilor lui Israel.", dict_ro:"Enumerarea triplă a reprezentanților poporului — bătrâni, căpetenii de trib, căpetenii de familie — asigură că fiecare nivel al structurii sociale israelite e martor direct la strămutarea Chivotului."}],
  ["la regele Solomon, în Ierusalim, pentru ca să ridice Chivotul Legământului DOMNULUI din Orașul lui David, care este Țion", {heb:"אֶל הַמֶּלֶךְ שְׁלֹמֹה יְרוּשָׁלִָם לְהַעֲלוֹת אֶת אֲרוֹן בְּרִית יְהוָה מֵעִיר דָּוִד הִיא צִיּוֹן", translit:"el hameleh șelomo ierușalam lehaalot et aron berit Adonai mēir david hi țion", strong:"H5927", pos:"prepoziție + substantiv + nume propriu + nume propriu + verb, hifil infinitiv + marcă a complementului direct + substantiv construct + substantiv construct + nume propriu + substantiv construct + nume propriu + pronume personal + nume propriu", def_ro:"la regele Solomon, la Ierusalim, ca să ridice Chivotul Legământului DOMNULUI din cetatea lui David, care este Țion.", dict_ro:"Identificarea explicită «Orașul lui David, care este Țion» confirmă că Chivotul se mută de la locuința sa provizorie, de pe vremea lui David, la locul său final și permanent în noul Templu."}]
]},
{v:"8:2", newTags:[
  ["Și toți bărbații lui Israel s-au adunat la regele Solomon", {heb:"וַיִּקָּהֲלוּ אֶל הַמֶּלֶךְ שְׁלֹמֹה כָּל אִישׁ יִשְׂרָאֵל", translit:"vaikahalu el hameleh șelomo kal iș israēl", strong:"H6950", pos:"verb, nifal imperfect consecutiv + prepoziție + substantiv + nume propriu + substantiv construct + substantiv + nume propriu", def_ro:"și s-au adunat la regele Solomon toți oamenii lui Israel.", dict_ro:"Această a doua adunare, de la poporul de rând, completează convocarea anterioară a conducătorilor — ceremonia strămutării Chivotului implică, în cele din urmă, întreaga națiune."}],
  ["la sărbătoarea [de Sucot], aceasta fiind luna a șaptea", {heb:"בֶּחָג הוּא הַחֹדֶשׁ הַשְּׁבִיעִי", translit:"behag hu hahodeș hașvi", strong:"H2282", pos:"substantiv + pronume personal + substantiv + numeral ordinal", def_ro:"la sărbătoare, ea [fiind] luna a șaptea.", dict_ro:"Rashi explică faptul că luna Tișrei e numită «luna a șaptea» pentru că Tora numără lunile anului începând cu Nisan, luna Exodului — nu pentru că Tișrei ar fi, în sine, mai puțin importantă."}]
]},
{v:"8:3", newTags:[
  ["Toți bătrânii lui Israel au venit, iar preoții purtau Chivotul", {heb:"וַיָּבֹאוּ כֹּל זִקְנֵי יִשְׂרָאֵל וַיִּשְׂאוּ הַכֹּהֲנִים אֶת הָאָרוֹן", translit:"vaiavou kol ziknē israēl vaisu hakohanim et haaron", strong:"H935", pos:"verb, qal imperfect consecutiv + substantiv construct + adjectiv + nume propriu + verb, qal imperfect consecutiv + substantiv + marcă a complementului direct + substantiv", def_ro:"și au venit toți bătrânii lui Israel și au purtat preoții Chivotul.", dict_ro:"Radak enumeră cele patru momente istorice în care preoții au purtat Chivotul: la trecerea Iordanului, la înconjurarea Ierihonului, la fuga lui David de Abșalom, și acum, la readucerea lui definitivă în Templu."}]
]},
{v:"8:4", newTags:[
  ["Și au ridicat Chivotul DOMNULUI și", {heb:"וַיַּעֲלוּ אֶת אֲרוֹן יְהוָה וְ", translit:"vaiaalu et aron Adonai ve", strong:"H5927", pos:"verb, hifil imperfect consecutiv + marcă a complementului direct + substantiv construct + nume propriu", def_ro:"și au ridicat Chivotul DOMNULUI și.", dict_ro:"Verbul «a ridica/a sui» (alah) marchează explicit mișcarea Chivotului spre locul lui cel mai înalt și central — Sfânta Sfintelor din noul Templu."}],
  ["împreună cu toate ustensilele sfinte care se aflau în cort; preoții și leviții le-au ridicat", {heb:"וְאֶת כָּל כְּלֵי הַקֹּדֶשׁ אֲשֶׁר בָּאֹהֶל וַיַּעֲלוּ אֹתָם הַכֹּהֲנִים וְהַלְוִיִּם", translit:"veet kal kelē hakodeș așer baohel vaiaalu otam hakohanim vehalvim", strong:"H3627", pos:"marcă a complementului direct + substantiv construct + substantiv construct + substantiv + particulă relativă + substantiv + verb, hifil imperfect consecutiv + marcă a complementului direct + sufix + substantiv + nume de neam", def_ro:"și toate uneltele sfinte care erau în Cort; și le-au suit preoții și leviții.", dict_ro:"Rashi explică, pe baza unei tradiții din Tosefta, că vechiul Cort al Întâlnirii construit de Moise a fost ascuns definitiv odată adus în Templu — momentul acesta marchează încheierea erei sanctuarului mobil, început în pustiu."}]
]},
{v:"8:5", newTags:[
  ["Iar regele Solomon și toată obștea lui Israel care se adunase cu el înaintea Chivotului", {heb:"וְהַמֶּלֶךְ שְׁלֹמֹה וְכָל עֲדַת יִשְׂרָאֵל הַנּוֹעָדִים עָלָיו אִתּוֹ לִפְנֵי הָאָרוֹן", translit:"vehameleh șelomo vehal adat israēl hanoadim alaiv ito lifnē haaron", strong:"H4428", pos:"substantiv + nume propriu + substantiv construct + substantiv construct + nume propriu + verb, nifal participiu + prepoziție + sufix + prepoziție + sufix + substantiv construct + substantiv", def_ro:"și regele Solomon și toată obștea lui Israel care se adunaseră cu el, înaintea Chivotului.", dict_ro:"Metzudat Țion explică «hanoadim» ca «cei adunați», aceeași rădăcină folosită pentru adunarea răsculată împotriva lui Moise la Numeri 16:11 — aici, însă, adunarea e una de devoțiune, nu de răzvrătire."}],
  ["jertfeau [atâtea] turme și cirezi, încât nu puteau fi socotite și nici numărate, de multe ce erau", {heb:"מְזַבְּחִים צֹאן וּבָקָר אֲשֶׁר לֹא יִסָּפְרוּ וְלֹא יִמָּנוּ מֵרֹב", translit:"mezabhim țon uvakar așer lo isafru velo imanu mērov", strong:"H2076", pos:"verb, piel participiu + substantiv + substantiv + particulă relativă + particulă negativă + verb, nifal imperfect + particulă negativă + verb, nifal imperfect + substantiv", def_ro:"jertfeau oi și vite care nu puteau fi socotite și nici numărate, din pricina mulțimii.", dict_ro:"Repetarea dublă a imposibilității de a le socoti — «nu puteau fi socotite» și «nici numărate» — intensifică retoric amploarea fără precedent a jertfelor aduse la dedicarea Templului."}]
]},
{v:"8:6", newTags:[
  ["Preoții au adus Chivotul Legământului DOMNULUI la locul său, în Sanctuarul Templului, în Sfânta Sfintelor, dedesubtul aripilor", {heb:"וַיָּבִאוּ הַכֹּהֲנִים אֶת אֲרוֹן בְּרִית יְהוָה אֶל מְקוֹמוֹ אֶל דְּבִיר הַבַּיִת אֶל קֹדֶשׁ הַקֳּדָשִׁים אֶל תַּחַת כַּנְפֵי", translit:"vaiaviu hakohanim et aron berit Adonai el mekomo el devir habait el kodeș hakodașim el tahat kanfē", strong:"H935", pos:"verb, hifil imperfect consecutiv + substantiv + marcă a complementului direct + substantiv construct + substantiv construct + nume propriu + prepoziție + substantiv construct + sufix + prepoziție + substantiv construct + substantiv + prepoziție + substantiv construct + substantiv + prepoziție + prepoziție + substantiv construct", def_ro:"și au adus preoții Chivotul Legământului DOMNULUI la locul lui, în Sanctuarul Casei, în Sfânta Sfintelor, sub aripile.", dict_ro:"Rashi precizează că acești heruvimi, ale căror aripi acoperă Chivotul, sunt cei făcuți de Solomon, așezați pe pământ — distincți de heruvimii mici de pe capacul ispășirii, de pe Chivotul însuși."}]
]},
{v:"8:7", newTags:[
  ["Căci heruvimii și-au întins aripile deasupra locului Chivotului și heruvimii au acoperit Chivotul și drugii săi, de deasupra", {heb:"כִּי הַכְּרוּבִים פֹּרְשִׂים כְּנָפַיִם אֶל מְקוֹם הָאָרוֹן וַיָּסֹכּוּ הַכְּרֻבִים עַל הָאָרוֹן וְעַל בַּדָּיו מִלְמָעְלָה", translit:"ki hakruvim porsim kenafaim el mekom haaron vaiasoku hakruvim al haaron veal badaiv milmala", strong:"H3742", pos:"conjuncție + substantiv + verb, qal participiu + substantiv + prepoziție + substantiv construct + substantiv + verb, qal imperfect consecutiv + substantiv + prepoziție + substantiv + prepoziție + substantiv plural construct + sufix + adverb", def_ro:"căci heruvimii își întind aripile peste locul Chivotului și acoperă heruvimii Chivotul și drugii lui, de deasupra.", dict_ro:"Metzudat David explică faptul că heruvimii fuseseră făcuți de la început astfel încât să-și întindă aripile exact peste locul unde avea să stea Chivotul — la aducerea lui, protecția era deja pregătită, nu improvizată."}]
]},
{v:"8:8", newTags:[
  ["se extindeau într-atât încât vârfurile lor puteau fi văzute din Sfânta, în fața Sanctuarului, dar nu puteau fi văzute din afară; și așa au rămas până în ziua de astăzi", {heb:"וַיֵּרָאוּ רָאשֵׁי הַבַּדִּים מִן הַקֹּדֶשׁ עַל פְּנֵי הַדְּבִיר וְלֹא יֵרָאוּ הַחוּצָה וַיִּהְיוּ שָׁם עַד הַיּוֹם הַזֶּה", translit:"vaiērau rașē habadim min hakodeș al penē hadvir velo iērau hahuța vaihiu șam ad haiom haze", strong:"H7200", pos:"verb, nifal imperfect consecutiv + substantiv plural construct + substantiv + prepoziție + substantiv + prepoziție + substantiv construct + substantiv + particulă negativă + verb, nifal imperfect + substantiv + verb, qal imperfect consecutiv + adverb + prepoziție + substantiv + pronume demonstrativ", def_ro:"și s-au văzut vârfurile drugilor din Sfânta, în fața Sanctuarului, dar nu se vedeau afară; și au rămas acolo până în ziua aceasta.", dict_ro:"Rashi rezolvă contradicția aparentă — drugii «se vedeau» dinăuntrul Sfintei, dar «nu se vedeau» din curtea exterioară — explicând că vârfurile lor împingeau perdeaua interioară ca două umflături vizibile, «asemenea a doi sâni», imagine a apropierii intime a prezenței divine de popor."}]
]},
{v:"8:9", newTags:[
  ["pe care Moise le pusese acolo la Horeb, acolo unde DOMNUL pecetluise [legământ] cu copiii lui Israel când ieșiseră din țara Egiptului", {heb:"אֲשֶׁר הִנִּחַ שָׁם מֹשֶׁה בְּחֹרֵב אֲשֶׁר כָּרַת יְהוָה עִם בְּנֵי יִשְׂרָאֵל בְּצֵאתָם מֵאֶרֶץ מִצְרָיִם", translit:"așer hiniah șam moșe behorēv așer karat Adonai im benē israēl bețētam mēereț mițraim", strong:"H5117", pos:"particulă relativă + verb, hifil perfect + adverb + nume propriu + nume propriu + particulă relativă + verb, qal perfect + nume propriu + prepoziție + substantiv construct + nume propriu + verb, qal infinitiv + sufix + substantiv construct + nume propriu", def_ro:"pe care le-a pus acolo Moise la Horeb, unde a încheiat DOMNUL [legământ] cu fiii lui Israel, la ieșirea lor din țara Egiptului.", dict_ro:"Talmudul (Bava Batra 14a) deduce din formula «nimic... în afară de» — o restrângere după o restrângere — că, de fapt, și un Sefer Tora stătea în Chivot, alături de cele două table de piatră, nu doar tablele singure."}]
]},
{v:"8:10", newTags:[
  ["Când preoții au plecat din Sfânta, norul a umplut Casa DOMNULUI", {heb:"וַיְהִי בְּצֵאת הַכֹּהֲנִים מִן הַקֹּדֶשׁ וְהֶעָנָן מָלֵא אֶת בֵּית יְהוָה", translit:"vaihi bețēt hakohanim min hakodeș veheanan malē et bēt Adonai", strong:"H1961", pos:"verb, qal imperfect consecutiv + verb, qal infinitiv + substantiv + prepoziție + substantiv + substantiv + verb, qal perfect + marcă a complementului direct + substantiv construct + nume propriu", def_ro:"și a fost, la ieșirea preoților din Sfânta, că norul a umplut Casa DOMNULUI.", dict_ro:"Rashi explică faptul că, în clipa în care preoții care duseseră Chivotul în Sfânta Sfintelor au ieșit, îndată Prezența lui Dumnezeu S-a odihnit în Templu — simultaneitatea exactă a celor două evenimente confirmă legătura directă dintre ele."}]
]},
{v:"8:11", newTags:[
  ["Și preoții nu au putut sta să slujească din pricina norului, căci slava DOMNULUI umplea Casa DOMNULUI", {heb:"וְלֹא יָכְלוּ הַכֹּהֲנִים לַעֲמֹד לְשָׁרֵת מִפְּנֵי הֶעָנָן כִּי מָלֵא כְבוֹד יְהוָה אֶת בֵּית יְהוָה", translit:"velo iahlu hakohanim laamod leșarēt mipnē heanan ki malē hevod Adonai et bēt Adonai", strong:"H3201", pos:"particulă negativă + verb, qal perfect + substantiv + verb, qal infinitiv + verb, piel infinitiv + substantiv construct + substantiv + conjuncție + verb, qal perfect + substantiv construct + nume propriu + marcă a complementului direct + substantiv construct + nume propriu", def_ro:"și n-au putut preoții să stea să slujească din pricina norului, căci slava DOMNULUI umpluse Casa DOMNULUI.", dict_ro:"Metzudat David identifică explicit «slava DOMNULUI» cu norul descris anterior — același fenomen vizibil, numit de două ori cu termeni diferiți, pentru a-i sublinia dubla natură: materială (nor) și teologică (slavă)."}]
]},
{v:"8:12", newTags:[
  ["Atunci Solomon a spus: „DOMNUL a spus că va sălășlui în", {heb:"אָז אָמַר שְׁלֹמֹה יְהוָה אָמַר לִשְׁכֹּן בָּ", translit:"az amar șelomo Adonai amar lișkon ba", strong:"H227", pos:"adverb + verb, qal perfect + nume propriu + nume propriu + verb, qal perfect + verb, qal infinitiv", def_ro:"atunci a spus Solomon: DOMNUL a spus [că] va locui în.", dict_ro:"Rashi explică faptul că, văzând norul, Solomon a înțeles imediat că Prezența lui Dumnezeu locuiește cu adevărat în casa pe care o zidise, întocmai cum DOMNUL făgăduise să vină și să locuiască în ea «din mijlocul norului și al negurii» (Levitic 16:2)."}]
]},
{v:"8:13", newTags:[
  ["Și am construit într-adevăr un adăpost pentru Tine, o temelie veșnică a sălașului Tău", {heb:"בָּנֹה בָנִיתִי בֵּית זְבֻל לָךְ מָכוֹן לְשִׁבְתְּךָ עוֹלָמִים", translit:"bano vaniti bēt zevul lah mahon leșivteha olamim", strong:"H1129", pos:"verb, qal infinitiv absolut + verb, qal perfect + substantiv construct + substantiv + prepoziție + sufix + substantiv + verb, qal infinitiv + sufix + substantiv", def_ro:"zidind, am zidit o casă de locuit pentru Tine, un loc statornic pentru șederea Ta în veci.", dict_ro:"Rashi explică faptul că, de când a fost ales acest loc, înălțimile [bamot] n-au mai fost îngăduite, iar Prezența lui Dumnezeu n-a mai locuit în alt loc — Templul devine sălaș unic și permanent, nu unul dintre mai multe locuri posibile."}]
]},
{v:"8:14", newTags:[
  ["Regele și-a întors fața și a binecuvântat întreaga obște a lui Israel și toată obștea lui Israel stătea în picioare", {heb:"וַיַּסֵּב הַמֶּלֶךְ אֶת פָּנָיו וַיְבָרֶךְ אֵת כָּל קְהַל יִשְׂרָאֵל וְכָל קְהַל יִשְׂרָאֵל עֹמֵד", translit:"vaiasēv hameleh et panaiv vaivareh ēt kal kehal israēl vehal kehal israēl omēd", strong:"H5437", pos:"verb, hifil imperfect consecutiv + substantiv + marcă a complementului direct + substantiv plural construct + sufix + verb, piel imperfect consecutiv + marcă a complementului direct + substantiv construct + substantiv construct + nume propriu + substantiv construct + substantiv construct + nume propriu + verb, qal participiu", def_ro:"și a întors regele fața lui și a binecuvântat toată adunarea lui Israel; și toată adunarea lui Israel stătea.", dict_ro:"Metzudat David explică poziția poporului — stătea în picioare — pentru că nu era permisă șederea în curtea Templului; Radak adaugă că binecuvântarea exactă dată de Solomon nu e redată aici, ci doar cea rostită mai târziu, după rugăciunea lui."}]
]},
{v:"8:15", newTags:[
  ["Și [Solomon] a spus: „Binecuvântat ești Tu, DOAMNE, Dumnezeul lui Israel, care a vorbit cu", {heb:"וַיֹּאמֶר בָּרוּךְ יְהוָה אֱלֹהֵי יִשְׂרָאֵל אֲשֶׁר דִּבֶּר בְּ", translit:"vaiomer baruh Adonai elohē israēl așer diber be", strong:"H559", pos:"verb, qal imperfect consecutiv + verb, qal participiu pasiv + nume propriu + substantiv construct + nume propriu + particulă relativă + verb, piel perfect", def_ro:"și a spus: binecuvântat [este] DOMNUL, Dumnezeul lui Israel, care a vorbit cu.", dict_ro:"Radak explică faptul că Solomon Îi mulțumește mai întâi lui Dumnezeu, înainte de a adresa vreun cuvânt poporului — recunoștința pentru împlinirea promisiunii precede orice altă rostire regală."}],
  ["tatălui meu David, și care cu mâna Lui a împlinit [cuvântul pe care i l-a vorbit], spunând:", {heb:"אֵת דָּוִד אָבִי וּבְיָדוֹ מִלֵּא לֵאמֹר", translit:"ēt david avi uviado milē lēmor", strong:"H1732", pos:"prepoziție + nume propriu + substantiv construct + sufix + substantiv construct + sufix + verb, piel perfect + verb, qal infinitiv", def_ro:"cu David, tatăl meu, și cu mâna Lui a împlinit, spunând.", dict_ro:"Rashi explică faptul că expresia «și cu mâna Lui a împlinit» înseamnă că DOMNUL Și-a împlinit cuvântul «cu mâna Lui cea bună» — puterea divină activă, nu doar promisiunea verbală, a dus la zidirea efectivă a Templului."}]
]},
{v:"8:16", newTags:[
  ["«Din ziua în care l-am scos pe poporul Meu Israel din Egipt, nu am ales niciun oraș dintre triburile lui Israel să-Mi construiască o Casă unde să fie numele Meu", {heb:"מִן הַיּוֹם אֲשֶׁר הוֹצֵאתִי אֶת עַמִּי אֶת יִשְׂרָאֵל מִמִּצְרַיִם לֹא בָחַרְתִּי בְעִיר מִכֹּל שִׁבְטֵי יִשְׂרָאֵל לִבְנוֹת בַּיִת לִהְיוֹת שְׁמִי שָׁם", translit:"min haiom așer hoțēti et ami et israēl mimițraim lo vaharti veir mikol șivtē israēl livnot bait lihiot șemi șam", strong:"H3117", pos:"prepoziție + substantiv + particulă relativă + verb, hifil perfect + marcă a complementului direct + substantiv construct + sufix + marcă a complementului direct + nume propriu + nume propriu + particulă negativă + verb, qal perfect + substantiv + substantiv construct + substantiv plural construct + nume propriu + verb, qal infinitiv + substantiv + verb, qal infinitiv + substantiv construct + sufix + adverb", def_ro:"din ziua în care am scos pe poporul Meu Israel din Egipt, n-am ales oraș din toate triburile lui Israel ca să zidesc o casă, ca să fie numele Meu acolo.", dict_ro:"Rashi notează că aceste cuvinte sunt exact cele spuse de DOMNUL tatălui lui Solomon, David — citarea directă confirmă continuitatea exactă dintre promisiunea veche și împlinirea ei prezentă."}],
  ["și l-am ales pe David să fie peste poporul Meu Israel.»", {heb:"וָאֶבְחַר בְּדָוִד לִהְיוֹת עַל עַמִּי יִשְׂרָאֵל", translit:"vaevhar bedavid lihiot al ami israēl", strong:"H977", pos:"verb, qal imperfect consecutiv + nume propriu + verb, qal infinitiv + prepoziție + substantiv construct + sufix + nume propriu", def_ro:"și am ales pe David să fie peste poporul Meu Israel.", dict_ro:"Radak explică faptul că alegerea Ierusalimului nu a fost descoperită decât odată cu alegerea lui David — DOMNUL i-a arătat ulterior locul ales, în Ierusalim, când i-a răspuns prin foc din cer la aria lui Arauna."}]
]},
{v:"8:17", newTags:[
  ["Și a fost dorința inimii tatălui meu David să construiască o Casă pentru numele DOMNULUI, Dumnezeul lui Israel", {heb:"וַיְהִי עִם לְבַב דָּוִד אָבִי לִבְנוֹת בַּיִת לְשֵׁם יְהוָה אֱלֹהֵי יִשְׂרָאֵל", translit:"vaihi im levav david avi livnot bait leșēm Adonai elohē israēl", strong:"H1961", pos:"verb, qal imperfect consecutiv + prepoziție + substantiv construct + nume propriu + substantiv construct + sufix + verb, qal infinitiv + substantiv + substantiv construct + nume propriu + substantiv construct + nume propriu", def_ro:"și a fost [aceasta] cu inima lui David, tatăl meu: să zidească o casă pentru numele DOMNULUI, Dumnezeul lui Israel.", dict_ro:"Dorința inimii lui David devine motivul inițial al întregii narațiuni a Templului, chiar dacă împlinirea ei efectivă e lăsată fiului său — intenția sinceră e recunoscută ca merit propriu, distinct de execuția faptei."}]
]},
{v:"8:18", newTags:[
  ["DOMNUL i-a spus tatălui meu, David: «Dorința pe care ai avut-o în inima ta să construiești o Casă pentru numele Meu – ai făcut bine să o ai în inima ta", {heb:"וַיֹּאמֶר יְהוָה אֶל דָּוִד אָבִי יַעַן אֲשֶׁר הָיָה עִם לְבָבְךָ לִבְנוֹת בַּיִת לִשְׁמִי הֱטִיבֹתָ כִּי הָיָה עִם לְבָבֶךָ", translit:"vaiomer Adonai el david avi iaan așer haia im levavha livnot bait lișmi hetivota ki haia im levaveha", strong:"H559", pos:"verb, qal imperfect consecutiv + nume propriu + prepoziție + nume propriu + substantiv construct + sufix + conjuncție + particulă relativă + verb, qal perfect + prepoziție + substantiv construct + sufix + verb, qal infinitiv + substantiv + prepoziție + sufix + verb, hifil perfect + conjuncție + verb, qal perfect + prepoziție + substantiv construct + sufix", def_ro:"și a spus DOMNUL lui David, tatăl meu: pentru că a fost în inima ta să zidești o casă pentru numele Meu, ai făcut bine că a fost în inima ta.", dict_ro:"Metzudat David explică promisiunea ca fiind recunoașterea onestă a unei intenții bune, chiar dacă neîmplinite direct de cel care a avut-o — DOMNUL apreciază gândul curat al lui David independent de faptul că fiul său va fi cel care zidește efectiv."}]
]},
{v:"8:19", newTags:[
  ["Însă nu tu vei construi Casa, ci fiul tău care va ieși dintre coapsele tale, el va construi Casa pentru numele Meu.»", {heb:"רַק אַתָּה לֹא תִבְנֶה הַבָּיִת כִּי אִם בִּנְךָ הַיֹּצֵא מֵחֲלָצֶיךָ הוּא יִבְנֶה הַבַּיִת לִשְׁמִי", translit:"rak ata lo tivne habait ki im binha haioțē mēhalațeha hu ivne habait lișmi", strong:"H7535", pos:"particulă afirmativă + pronume personal + particulă negativă + verb, qal imperfect + substantiv + conjuncție + conjuncție + substantiv construct + sufix + verb, qal participiu + substantiv construct + sufix + pronume personal + verb, qal imperfect + substantiv + substantiv construct + sufix", def_ro:"însă tu nu vei zidi Casa, ci fiul tău care va ieși din coapsele tale, el va zidi Casa pentru numele Meu.", dict_ro:"Metzudat Țion explică «dintre coapsele tale» (mēhalațeha) ca un eufemism pentru mădularul nașterii, desemnând descendența directă — limitarea exclude pe David de la împlinirea directă a propriei dorințe, transferând promisiunea exact fiului care avea să fie Solomon."}]
]},
{v:"8:20", newTags:[
  ["DOMNUL Și-a împlinit cuvântul pe care l-a rostit și eu m-am ridicat în locul tatălui meu David și am stat pe tronul lui Israel", {heb:"וַיָּקֶם יְהוָה אֶת דְּבָרוֹ אֲשֶׁר דִּבֵּר וָאָקֻם תַּחַת דָּוִד אָבִי וָאֵשֵׁב עַל כִּסֵּא יִשְׂרָאֵל", translit:"vaiakem Adonai et devaro așer dibēr vaakum tahat david avi vaēșēv al kisē israēl", strong:"H6965", pos:"verb, hifil imperfect consecutiv + nume propriu + marcă a complementului direct + substantiv construct + sufix + particulă relativă + verb, piel perfect + verb, qal imperfect consecutiv + prepoziție + nume propriu + substantiv construct + sufix + verb, qal imperfect consecutiv + prepoziție + substantiv construct + nume propriu", def_ro:"și a împlinit DOMNUL cuvântul Lui pe care l-a vorbit; și m-am ridicat în locul lui David, tatăl meu, și am șezut pe tronul lui Israel.", dict_ro:"Solomon confirmă public, în fața întregii adunări, împlinirea exactă a promisiunii divine făcute tatălui său — succesiunea sa la tron e explicit legată de fidelitatea cuvântului divin, nu doar de dreptul dinastic."}],
  ["precum a vorbit DOMNUL, și am construit [azi] Casa pentru numele DOMNULUI, Dumnezeul lui Israel", {heb:"כַּאֲשֶׁר דִּבֶּר יְהוָה וָאֶבְנֶה הַבַּיִת לְשֵׁם יְהוָה אֱלֹהֵי יִשְׂרָאֵל", translit:"kaașer diber Adonai vaevne habait leșēm Adonai elohē israēl", strong:"H834", pos:"particulă relativă + verb, piel perfect + nume propriu + verb, qal imperfect consecutiv + substantiv + substantiv construct + nume propriu + substantiv construct + nume propriu", def_ro:"precum a vorbit DOMNUL, și am zidit Casa pentru numele DOMNULUI, Dumnezeul lui Israel.", dict_ro:"Construirea efectivă a Casei încheie, în fapt, întregul șir de promisiuni rostite către David — scopul final rămâne, ca și la început, slava numelui DOMNULUI."}]
]},
{v:"8:21", newTags:[
  ["Și acolo am făcut un loc pentru Chivot, unde se află", {heb:"וָאָשִׂם שָׁם מָקוֹם לָאָרוֹן אֲשֶׁר שָׁם", translit:"vaasim șam makom laaron așer șam", strong:"H7760", pos:"verb, qal imperfect consecutiv + adverb + substantiv + substantiv + particulă relativă + adverb", def_ro:"și am pus acolo un loc pentru Chivot, unde acolo.", dict_ro:"Radak identifică acest «loc» cu Locul Preasfânt — destinația finală, pregătită special, a Chivotului adus din cetatea lui David."}],
  ["DOMNULUI, pe care l-a pecetluit cu strămoșii noștri, când i-a scos din țara Egiptului.”", {heb:"יְהוָה אֲשֶׁר כָּרַת עִם אֲבֹתֵינוּ בְּהוֹצִיאוֹ אֹתָם מֵאֶרֶץ מִצְרָיִם", translit:"Adonai așer karat im avotēnu behoțio otam mēereț mițraim", strong:"H3068", pos:"nume propriu + particulă relativă + verb, qal perfect + prepoziție + substantiv plural construct + sufix + verb, hifil infinitiv + sufix + marcă a complementului direct + sufix + substantiv construct + nume propriu", def_ro:"DOMNUL, pe care l-a încheiat cu strămoșii noștri, la scoaterea lor din țara Egiptului.", dict_ro:"Metzudat David identifică «legământul DOMNULUI» cu tablele legământului înseși, prin care DOMNUL a încheiat legământ cu Israel exact în vremea când li le-a dat la Horeb — discursul lui Solomon se încheie cu aceeași referință istorică fondatoare cu care a început."}]
]}
];
