module.exports = [
{v:"7:21", newTags:[
  ["Așa a spus DOMNUL Oștirilor, Dumnezeul lui Israel: „Îngrămădiți-vă", {heb:"כֹּה אָמַר יְהוָה צְבָאוֹת אֱלֹהֵי יִשְׂרָאֵל", translit:"ko amar Adonai țevaot elohē israēl", strong:"H3541", pos:"adverb + verb, qal perfect + nume propriu + substantiv + substantiv construct + nume propriu", def_ro:"așa a spus DOMNUL Oștirilor, Dumnezeul lui Israel.", dict_ro:"Rashi explică faptul că DOMNUL îi spune poporului, cu o ironie amară: de vreme ce arderile-de-tot nu-Mi sunt primite, e mai bine să le adăugați la jertfele voastre de pace și să mâncați carnea — nu refuzul ritualului în sine, ci inima nesupusă din spatele lui e problema reală."}],
  ["peste jertfele voastre de pace și mâncați[-le] carnea.", {heb:"סְפוּ עַל זִבְחֵיכֶם וְאִכְלוּ בָשָׂר", translit:"sefu al zivhēhem veihlu vasar", strong:"H5595", pos:"verb, qal imperativ + prepoziție + substantiv construct + sufix + verb, qal imperativ + substantiv", def_ro:"adăugați la jertfele voastre și mâncați carne.", dict_ro:"Metzudat David explică faptul că DOMNUL nu impune o pedeapsă rituală, ci arată indiferența Sa față de un cult golit de sens moral — carnea arderilor de tot, oricum nefolositoare spiritual, poate fi cel puțin mâncată, nu pierdută în van."}]
]},
{v:"7:22", newTags:[
  ["Căci nu am vorbit strămoșilor voștri și nici nu le-am", {heb:"כִּי לֹא דִבַּרְתִּי אֶת אֲבוֹתֵיכֶם וְלֹא", translit:"ki lo dibarti et avotēhem velo", strong:"H3588", pos:"conjuncție + particulă negativă + verb, piel perfect + marcă a complementului direct + substantiv construct + sufix + particulă negativă", def_ro:"căci n-am vorbit strămoșilor voștri și nici nu le-am.", dict_ro:"Rashi explică faptul că la Sinai condiția inițială n-a fost nicidecum jertfa, ci: «dacă veți asculta glasul Meu și dacă veți păzi legământul Meu, veți fi ai Mei dintre toate popoarele» (Exod 19:5) — jertfele au venit mult mai târziu, ca poruncă secundară."}],
  ["în ziua când i-am scos din țara Egiptului, despre arderi-de-tot sau jertfe de pace,", {heb:"בְּיוֹם הוֹצִיאִי אוֹתָם מֵאֶרֶץ מִצְרָיִם עַל דִּבְרֵי עוֹלָה וָזָבַח", translit:"beom hoți otam mēereț mițraim al divrē ola vazavah", strong:"H3117", pos:"substantiv construct + verb, hifil infinitiv + sufix + marcă a complementului direct + sufix + substantiv construct + nume propriu + prepoziție + substantiv construct + substantiv + substantiv", def_ro:"în ziua scoaterii lor din țara Egiptului, cu privire la arderea-de-tot și jertfă.", dict_ro:"Metzudat David explică faptul că, dacă scopul scoaterii din Egipt ar fi fost aducerea jertfelor, ar fi fost firesc ca porunca despre ele să fie dată chiar în acea zi — faptul că n-a fost arată că jertfa nu e temelia relației cu DOMNUL."}]
]},
{v:"7:23", newTags:[
  ["ci le-am poruncit doar legat de aceasta, spunând: „", {heb:"כִּי אִם אֶת הַדָּבָר הַזֶּה צִוִּיתִי אוֹתָם לֵאמֹר", translit:"ki im et hadavar haze țiviti otam lēmor", strong:"H3588", pos:"conjuncție + conjuncție + marcă a complementului direct + substantiv + pronume demonstrativ + verb, piel perfect + marcă a complementului direct + sufix + verb, qal infinitiv", def_ro:"ci doar acest lucru le-am poruncit, spunând.", dict_ro:"Metzudat David explică faptul că aceasta a fost porunca temelie, iar jertfa e doar una dintre poruncile particulare — fără ascultarea de glasul DOMNULUI, nicio jertfă nu are valoare."}],
  ["de glasul Meu, ca să vă fiu Dumnezeu și voi să-Mi fiți popor și să urmați toată calea pe care v-o poruncesc, ca să vă fie bine.", {heb:"בְקוֹלִי וְהָיִיתִי לָכֶם לֵאלֹהִים וְאַתֶּם תִּהְיוּ לִי לְעָם וַהֲלַכְתֶּם בְּכָל הַדֶּרֶךְ אֲשֶׁר אֲצַוֶּה אֶתְכֶם לְמַעַן יִיטַב לָכֶם", translit:"vekoli vehaiti lahem lēlohim veatem tihiu li leam vahalahtem behal hadereh așer ațave ethem lemaan itav lahem", strong:"H6963", pos:"substantiv construct + sufix + verb, qal perfect consecutiv + prepoziție + sufix + substantiv + pronume personal + verb, qal imperfect + prepoziție + sufix + substantiv + verb, qal perfect consecutiv + substantiv construct + substantiv + particulă relativă + verb, piel imperfect + marcă a complementului direct + sufix + prepoziție + verb, qal imperfect + prepoziție + sufix", def_ro:"glasul Meu, și voi fi vouă Dumnezeu, și voi Îmi veți fi popor, și veți merge pe toată calea pe care v-o poruncesc, ca să vă fie bine.", dict_ro:"Metzudat David explică faptul că binele promis nu e un folos pentru DOMNUL Însuși, ci exclusiv pentru popor — relația de legământ e structurată integral în beneficiul celui care ascultă, nu al Celui care poruncește."}]
]},
{v:"7:24", newTags:[
  ["Dar ei nu au ascultat și nu și-au plecat urechea, ci au urmat propriile lor sfaturi,", {heb:"וְלֹא שָׁמְעוּ וְלֹא הִטּוּ אֶת אָזְנָם וַיֵּלְכוּ בְּמֹעֵצוֹת", translit:"velo șamu velo hitu et aznam vaiēlhu bemoēțot", strong:"H3808", pos:"particulă negativă + verb, qal perfect + particulă negativă + verb, hifil perfect + marcă a complementului direct + substantiv construct + sufix + verb, qal imperfect consecutiv + substantiv", def_ro:"și n-au ascultat și nu și-au plecat urechea, ci au mers după sfaturi.", dict_ro:"Metzudat David explică faptul că aceasta se referă chiar la generația ieșită din Egipt — neascultarea nu e un fenomen recent, ci o trăsătură constantă, repetată, a istoriei poporului."}],
  ["au mers înapoi și nu înainte.", {heb:"וַיִּהְיוּ לְאָחוֹר וְלֹא לְפָנִים", translit:"vaihiu leahor velo lefanim", strong:"H1961", pos:"verb, qal imperfect consecutiv + substantiv + particulă negativă + substantiv", def_ro:"și au fost spre înapoi și nu spre înainte.", dict_ro:"Metzudat David explică faptul că, în fiecare zi, poporul se depărta tot mai mult de slujirea DOMNULUI, în loc să se apropie — regresul moral descris aici e progresiv, nu un eveniment singular."}]
]},
{v:"7:25", newTags:[
  ["Din ziua în care strămoșii tăi au ieșit din țara Egiptului și până astăzi, le-am trimis pe toți", {heb:"לְמִן הַיּוֹם אֲשֶׁר יָצְאוּ אֲבוֹתֵיכֶם מֵאֶרֶץ מִצְרַיִם עַד הַיּוֹם הַזֶּה וָאֶשְׁלַח אֲלֵיכֶם אֶת", translit:"lemin haiom așer iațu avotēhem mēereț mițraim ad haiom haze vaeșlah alēhem et", strong:"H4480", pos:"prepoziție + substantiv + particulă relativă + verb, qal perfect + substantiv construct + sufix + substantiv construct + nume propriu + prepoziție + substantiv + pronume demonstrativ + verb, qal imperfect consecutiv + prepoziție + sufix + marcă a complementului direct", def_ro:"din ziua în care au ieșit strămoșii voștri din țara Egiptului și până în ziua aceasta, am trimis la voi pe toți.", dict_ro:"Metzudat David explică faptul că, de atunci și până acum, DOMNUL n-a lipsit poporul de slujitorii Săi profeții nicio zi, ci în fiecare zi îi trimitea devreme, stăruind să-i întoarcă spre bine — continuitatea trimiterii contrastează dureros cu continuitatea refuzului."}],
  ["în fiecare zi îi trimit dimineața devreme.", {heb:"יוֹם הַשְׁכֵּם וְשָׁלֹחַ", translit:"iom hașkēm veșaloah", strong:"H3117", pos:"substantiv + verb, hifil infinitiv absolut + verb, qal infinitiv absolut", def_ro:"zi de zi, trimitere stăruitoare și devreme.", dict_ro:"Rashi explică «yom hașkem veșaloah» ca «zi de zi, dis-de-dimineață și stăruitor» — dubla formă infinitivă intensifică insistența neîntreruptă a chemării profetice."}]
]},
{v:"7:26", newTags:[
  ["Dar ei nu ascultă de Mine și nu își pleacă urechea; ei și-au", {heb:"וְלֹא שָׁמְעוּ אֵלַי וְלֹא הִטּוּ אֶת אָזְנָם", translit:"velo șamu ēlai velo hitu et aznam", strong:"H3808", pos:"particulă negativă + verb, qal perfect + prepoziție + sufix + particulă negativă + verb, hifil perfect + marcă a complementului direct + substantiv construct + sufix", def_ro:"și n-au ascultat de Mine și nu și-au plecat urechea; și-au.", dict_ro:"Metzudat David explică imaginea «grumazului înțepenit» ca pe un om care nu vrea să-și întoarcă fața spre semenul lui pentru a-i asculta cuvintele — refuzul fizic al atenției devine simbol al refuzului spiritual."}],
  ["și au devenit mai răi decât strămoșii lor.", {heb:"הֵרֵעוּ מֵאֲבוֹתָם", translit:"hērēu mēavotam", strong:"H7489", pos:"verb, hifil perfect + substantiv construct + sufix", def_ro:"au făcut mai rău decât strămoșii lor.", dict_ro:"Escaladarea morală — fiecare generație mai rea decât precedenta — confirmă structura deliberată a acuzației: nu doar repetarea păcatului, ci intensificarea lui progresivă de-a lungul istoriei."}]
]},
{v:"7:27", newTags:[
  ["Le vei spune toate aceste lucruri, dar ei nu te vor asculta; îi vei", {heb:"וְדִבַּרְתָּ אֲלֵיהֶם אֶת כָּל הַדְּבָרִים הָאֵלֶּה וְלֹא יִשְׁמְעוּ אֵלֶיךָ וְ", translit:"vedibarta alēhem et kal hadvarim haēle velo ișmeu ēleha ve", strong:"H1696", pos:"verb, piel perfect consecutiv + prepoziție + sufix + marcă a complementului direct + substantiv construct + substantiv + pronume demonstrativ + particulă negativă + verb, qal imperfect + prepoziție + sufix", def_ro:"și le vei vorbi toate aceste cuvinte, și nu te vor asculta, și.", dict_ro:"Metzudat David explică faptul că, chiar dacă profetul știe dinainte că nu va fi ascultat, trebuie totuși să vorbească — ca poporul să nu aibă ce răspunde la judecată, pretinzând că n-a fost înștiințat."}],
  ["dar ei nu îți vor răspunde.", {heb:"אֲלֵיהֶם וְלֹא יַעֲנוּכָה", translit:"alēhem velo iaanuha", strong:"H6030", pos:"prepoziție + sufix + particulă negativă + verb, qal imperfect + sufix", def_ro:"către ei, și nu-ți vor răspunde.", dict_ro:"Dublul refuz — de a asculta și de a răspunde — confirmă surditatea completă a poporului, nu doar o neatenție parțială sau temporară."}]
]},
{v:"7:28", newTags:[
  ["Le vei spune: „Acesta este neamul care nu va asculta de glasul DOMNULUI, Dumnezeului său, și nu va primi", {heb:"וְאָמַרְתָּ אֲלֵיהֶם זֶה הַגּוֹי אֲשֶׁר לוֹא שָׁמְעוּ בְּקוֹל יְהוָה אֱלֹהָיו וְלֹא לָקְחוּ", translit:"veamarta alēhem ze hagoi așer lo șamu bekol Adonai elohaiv velo lakhu", strong:"H559", pos:"verb, qal perfect consecutiv + prepoziție + sufix + pronume demonstrativ + substantiv + particulă relativă + particulă negativă + verb, qal perfect + substantiv construct + nume propriu + substantiv construct + sufix + particulă negativă + verb, qal perfect", def_ro:"și le vei spune: acesta e neamul care n-a ascultat de glasul DOMNULUI, Dumnezeul lui, și n-a primit.", dict_ro:"Metzudat David explică faptul că aceștia nu mai sunt socotiți ca fiii lui Israel care au auzit cuvântul DOMNULUI la Sinai, ci ca și cum n-ar fi ascultat niciodată glasul Lui și n-ar fi învățat vreodată disciplina — o pierdere completă a identității legământului."}],
  ["credința sa este pierdută și nimicită din gura lor.”", {heb:"אָבְדָה הָאֱמוּנָה וְנִכְרְתָה מִפִּיהֶם", translit:"avda haemuna venihreta mipihem", strong:"H6", pos:"verb, qal perfect + substantiv + verb, nifal perfect + substantiv construct + sufix", def_ro:"a pierit credința și s-a stins din gura lor.", dict_ro:"Metzudat David explică faptul că credința în Dumnezeu nu doar s-a stins din inimile lor, ci s-a stins chiar din gura lor — nu se mai pomenește nici măcar verbal, semn al unei pierderi totale, nu doar interioare."}]
]},
{v:"7:29", newTags:[
  ["și aruncă-l, înalță cântare de jale din înălțimi, căci DOMNUL a disprețuit și a părăsit generația mâniei Lui.", {heb:"וְהַשְׁלִיכִי וּשְׂאִי עַל שְׁפָיִם קִינָה כִּי מָאַס יְהוָה וַיִּטֹּשׁ אֶת דּוֹר עֶבְרָתוֹ", translit:"vehașlihi usi al șefaim kina ki maas Adonai vaitoș et dor evrato", strong:"H7993", pos:"verb, hifil imperativ + verb, qal imperativ + prepoziție + substantiv + substantiv + conjuncție + verb, qal perfect + nume propriu + verb, qal imperfect consecutiv + marcă a complementului direct + substantiv construct + sufix", def_ro:"și aruncă-l, și înalță pe înălțimi cântare de jale, căci a disprețuit DOMNUL și a părăsit generația mâniei Lui.", dict_ro:"Rashi explică «nizrech» printr-o posibilă dublă tâlcuire: fie «smulge-ți părul» (ca un gest de doliu), fie «cununa ta», termen de măreție, tradus de Targumul lui Ionatan drept «rabrevich», măreția ta — în ambele cazuri, un semn public al pierderii totale."}]
]},
{v:"7:30", newTags:[
  ["Căci copiii lui Iuda au făcut ce este rău în ochii Mei – rostirea DOMNULUI – și-au pus", {heb:"כִּי עָשׂוּ בְנֵי יְהוּדָה הָרַע בְּעֵינַי נְאֻום יְהוָה שָׂמוּ", translit:"ki asu venē iehuda hara beēnai neuvm Adonai samu", strong:"H3588", pos:"conjuncție + verb, qal perfect + substantiv construct + nume propriu + adjectiv + substantiv construct + sufix + substantiv construct + nume propriu + verb, qal perfect", def_ro:"căci au făcut copiii lui Iuda răul în ochii Mei, rostirea DOMNULUI, au pus.", dict_ro:"Metzudat David explică faptul că idolatria scârboasă pusă chiar în Casa DOMNULUI arată cât de puțin le-a păsat de sfințenia ei — n-au ezitat s-o spurce cu propriii lor idoli, în locul cel mai sfânt al națiunii."}]
]},
{v:"7:31", newTags:[
  ["care sunt în valea fiului lui Hinom, ca să-i ardă pe fiii și pe fiicele lor în foc – ce nici n-am poruncit și nici nu Mi-a trecut prin minte.", {heb:"אֲשֶׁר בְּגֵיא בֶן הִנֹּם לִשְׂרֹף אֶת בְּנֵיהֶם וְאֶת בְּנֹתֵיהֶם בָּאֵשׁ אֲשֶׁר לֹא צִוִּיתִי וְלֹא עָלְתָה עַל לִבִּי", translit:"așer begē ven hinom lisrof et benēhem veet benotēhem baēș așer lo țiviti velo alta al libi", strong:"H834", pos:"particulă relativă + substantiv construct + nume propriu + nume propriu + verb, qal infinitiv + marcă a complementului direct + substantiv plural construct + sufix + marcă a complementului direct + substantiv plural construct + sufix + substantiv + particulă relativă + particulă negativă + verb, piel perfect + particulă negativă + verb, qal perfect + prepoziție + substantiv construct + sufix", def_ro:"care sunt în valea fiului lui Hinom, ca să ardă pe fiii lor și pe fiicele lor în foc, ceea ce n-am poruncit și n-a venit în inima Mea.", dict_ro:"Rashi identifică «Tofet» cu idolul Moloh, de aramă, încălzit pe dedesubt, cu brațele întinse, unde copiii erau puși și arși în timp ce preoții băteau tobe ca strigătele să nu ajungă la tatăl îngrozit — explicând astfel și numele locului, derivat fie de la sunetul tobei, fie de la gemătul victimei."}]
]},
{v:"7:32", newTags:[
  ["De aceea, iată, vin zile – rostirea DOMNULUI – când nu se va mai spune Tofet și nici Valea Ben-Hinom, ci", {heb:"לָכֵן הִנֵּה יָמִים בָּאִים נְאֻם יְהוָה וְלֹא יֵאָמֵר עוֹד הַתֹּפֶת וְגֵיא בֶן הִנֹּם כִּי אִם", translit:"lahēn hinē iamim baim neum Adonai velo iēamēr od hatofet vegē ven hinom ki im", strong:"H3651", pos:"adverb + particulă demonstrativă + substantiv + verb, qal participiu + substantiv construct + nume propriu + particulă negativă + verb, nifal imperfect + adverb + nume propriu + substantiv construct + nume propriu + nume propriu + conjuncție + conjuncție", def_ro:"de aceea, iată, vin zile, rostirea DOMNULUI, și nu se va mai numi Tofet și valea fiului lui Hinom, ci.", dict_ro:"Schimbarea numelui locului — de la Tofet la Valea Măcelului — marchează transformarea sensului său: nu mai e locul idolatriei infantice, ci locul judecății pentru cei care au practicat-o."}],
  ["și îi vor îngropa [pe cei morți] în Tofet din lipsă de loc.", {heb:"וְקָבְרוּ בְתֹפֶת מֵאֵין מָקוֹם", translit:"vekavru vetofet mēēn makom", strong:"H6912", pos:"verb, qal perfect consecutiv + nume propriu + particulă negativă + substantiv", def_ro:"și vor îngropa în Tofet, din lipsă de loc.", dict_ro:"Metzudat David explică faptul că acolo vor cădea atât de mulți uciși, încât se vor îngropa chiar la Tofet, fiindcă nu se va mai găsi loc pentru alți morți — ironia judecății e că locul idolatriei devine locul de înmormântare al celor care au practicat-o."}]
]},
{v:"7:33", newTags:[
  ["Și hoitul acestui popor va fi hrană pentru păsările cerurilor și pentru fiarele pământului și nimeni nu le va", {heb:"וְהָיְתָה נִבְלַת הָעָם הַזֶּה לְמַאֲכָל לְעוֹף הַשָּׁמַיִם וּלְבֶהֱמַת הָאָרֶץ וְאֵין", translit:"vehaita nivlat haam haze lemaahal leof hașamaim ulvehemat haareț veēn", strong:"H1961", pos:"verb, qal perfect consecutiv + substantiv construct + substantiv + pronume demonstrativ + substantiv + substantiv construct + substantiv + substantiv construct + substantiv + particulă negativă", def_ro:"și va fi hoitul acestui popor hrană pentru pasărea cerurilor și pentru fiara pământului, și nu [va fi].", dict_ro:"Metzudat David explică faptul că nu va mai rămâne niciun om viu care să alunge păsările și fiarele de pe hoituri, căci toți vor fi uciși sau duși în exil — absența totală a unui îngrijitor confirmă amploarea dezastrului."}]
]},
{v:"7:34", newTags:[
  ["Voi face să înceteze în orașele din Iuda și pe străzile Ierusalimului sunetul bucuriei și sunetul veseliei,", {heb:"וְהִשְׁבַּתִּי מֵעָרֵי יְהוּדָה וּמֵחֻצוֹת יְרוּשָׁלִַם קוֹל שָׂשׂוֹן וְקוֹל שִׂמְחָה", translit:"vehișbati mēarē iehuda umēhuțot ierușalam kol sason vekol simha", strong:"H7673", pos:"verb, hifil perfect consecutiv + substantiv plural construct + nume propriu + substantiv plural construct + nume propriu + substantiv construct + substantiv + substantiv construct + substantiv", def_ro:"și voi face să tacă din cetățile lui Iuda și din străzile Ierusalimului glasul bucuriei și glasul veseliei.", dict_ro:"Metzudat David explică faptul că până și cea mai firească bucurie a vieții de zi cu zi — inclusiv glasul de nuntă — se va stinge complet, căci țara va rămâne pustie și fără locuitori."}],
  ["căci în ruină va fi țara.", {heb:"כִּי לְחָרְבָּה תִּהְיֶה הָאָרֶץ", translit:"ki leharba tihie haareț", strong:"H3588", pos:"conjuncție + substantiv + verb, qal imperfect + substantiv", def_ro:"căci în ruină va fi țara.", dict_ro:"Formula de încheiere a oracolului confirmă cauza directă a tăcerii generale: nu o pedeapsă arbitrară, ci consecința inevitabilă a pustiirii totale a țării."}]
]},
{v:"8:1", newTags:[
  ["În vremea aceea – rostirea DOMNULUI – vor scoate", {heb:"בָּעֵת הַהִיא נְאֻם יְהוָה יוֹצִיאוּ אֶת", translit:"baēt hahi neum Adonai ioțiu et", strong:"H6256", pos:"substantiv + pronume personal + substantiv construct + nume propriu + verb, hifil imperfect + marcă a complementului direct", def_ro:"în vremea aceea, rostirea DOMNULUI, vor scoate.", dict_ro:"Metzudat David explică faptul că vrăjmașii care vor veni vor scoate oasele din morminte special ca să le dezonoreze — o profanare post-mortem adăugată la pedeapsa deja suferită în viață."}],
  ["regilor din Iuda și oasele conducătorilor săi, și oasele preoților, și oasele profeților, și oasele locuitorilor Ierusalimului, din mormintele lor.", {heb:"מַלְכֵי יְהוּדָה וְאֶת עַצְמוֹת שָׂרָיו וְאֶת עַצְמוֹת הַכֹּהֲנִים וְאֵת עַצְמוֹת הַנְּבִיאִים וְאֵת עַצְמוֹת יוֹשְׁבֵי יְרוּשָׁלִָם מִקִּבְרֵיהֶם", translit:"malhē iehuda veet ațmot saraiv veet ațmot hakohanim veēt ațmot hanvim veēt ațmot ioșvē ierușalam mikivrēhem", strong:"H4428", pos:"substantiv plural construct + nume propriu + marcă a complementului direct + substantiv plural construct + substantiv plural construct + sufix (repetat de patru ori pentru oasele) + verb, qal participiu + nume propriu + substantiv plural construct + sufix", def_ro:"regilor lui Iuda, și oasele căpeteniilor lui, și oasele preoților, și oasele profeților, și oasele locuitorilor Ierusalimului, din mormintele lor.", dict_ro:"Metzudat David identifică «preoții» cu cei ai lui Baal și «profeții» cu profeții mincinoși — enumerarea exhaustivă a tuturor categoriilor sociale, de la regi la locuitori de rând, arată că nicio clasă n-a fost scutită de idolatrie, și deci de pedeapsă."}]
]},
{v:"8:2", newTags:[
  ["Și le vor împrăștia la [lumina] soarelui și a lunii și a întregii", {heb:"וּשְׁטָחוּם לַשֶּׁמֶשׁ וְלַיָּרֵחַ וּלְכֹל", translit:"uștahum lașemeș velaiarēah ulhol", strong:"H7849", pos:"verb, qal perfect consecutiv + sufix + substantiv + substantiv + substantiv construct", def_ro:"și le vor întinde la soare și la lună și la toată.", dict_ro:"Rashi explică faptul că asediatorii caldei vor profana cetatea chiar din mormintele conducătorilor, frumoase ca niște palate — oasele expuse «la soare» sunt o batjocură deliberată a fastului funerar de odinioară."}],
  ["pe care le-au iubit și pe care le-au venerat și pe care le-au urmat, pe care le-au căutat și înaintea cărora s-au prosternat. Nu vor mai fi adunate laolaltă și nici îngropate, ci vor fi ca gunoiul peste fața pământului.", {heb:"אֲשֶׁר אֲהֵבוּם וַאֲשֶׁר עֲבָדוּם וַאֲשֶׁר הָלְכוּ אַחֲרֵיהֶם וַאֲשֶׁר דְּרָשׁוּם וַאֲשֶׁר הִשְׁתַּחֲווּ לָהֶם לֹא יֵאָסְפוּ וְלֹא יִקָּבֵרוּ לְדֹמֶן עַל פְּנֵי הָאֲדָמָה יִהְיוּ", translit:"așer ahēvum vaașer avadum vaașer halhu aharēhem vaașer derașum vaașer hiștahavu lahem lo iēasfu velo ikavēru ledomen al penē haadama ihiu", strong:"H834", pos:"particulă relativă + verb, qal perfect + sufix (repetat de cinci ori) + particulă negativă + verb, nifal imperfect + particulă negativă + verb, nifal imperfect + substantiv + prepoziție + substantiv construct + substantiv + verb, qal imperfect", def_ro:"pe care le-au iubit, și pe care le-au slujit, și după care au mers, și pe care le-au căutat, și înaintea cărora s-au prosternat; nu vor fi adunate și nici îngropate, ci ca gunoi pe fața pământului vor fi.", dict_ro:"Rashi explică «ledomen» ca «gunoi de grajd» — soarta rămășițelor umane, lăsate neîngropate ca gunoiul, oglindește exact lipsa de respect pe care corpurile astrale venerate idolatru nu le-au putut oferi niciodată adoratorilor lor."}]
]},
{v:"8:3", newTags:[
  ["vieții pentru toți cei rămași din rămășița acestei familii rele, pentru cei rămași prin toate locurile în care i-am izgonit – rostirea DOMNULUI Oștirilor.", {heb:"מֵחַיִּים לְכֹל הַשְּׁאֵרִית הַנִּשְׁאָרִים מִן הַמִּשְׁפָּחָה הָרָעָה הַזֹּאת בְּכָל הַמְּקֹמוֹת הַנִּשְׁאָרִים אֲשֶׁר הִדַּחְתִּים שָׁם נְאֻם יְהוָה צְבָאוֹת", translit:"mēhaim lehol hașērit hanișarim min hamișpaha haraa hazot behal hamkomot hanișarim așer hidahtim șam neum Adonai țevaot", strong:"H2416", pos:"substantiv + substantiv construct + substantiv + verb, nifal participiu + prepoziție + substantiv + adjectiv + pronume demonstrativ + substantiv construct + substantiv + verb, nifal participiu + particulă relativă + verb, hifil perfect + sufix + adverb + substantiv construct + nume propriu + substantiv", def_ro:"decât viața, pentru toată rămășița celor rămași din această familie rea, în toate locurile celor rămași, pe care i-am alungat acolo, rostirea DOMNULUI Oștirilor.", dict_ro:"Rashi explică faptul că, chiar dacă văd morții zăcând în batjocură, necazul celor vii va fi și mai mare decât al lor — rămășița va alege moartea nu din deznădejde pasivă, ci din comparație directă cu suferința continuă a supraviețuirii în exil."}]
]},
{v:"9:23", newTags:[
  ["Așa a spus DOMNUL: „Cel înțelept să nu se", {heb:"כֹּה אָמַר יְהוָה אַל יִתְהַלֵּל חָכָם", translit:"ko amar Adonai al ithalēl haham", strong:"H3541", pos:"adverb + verb, qal perfect + nume propriu + particulă negativă + verb, hitpael imperfect + substantiv", def_ro:"așa a spus DOMNUL: să nu se laude cel înțelept.", dict_ro:"Rashi leagă acest verset direct de mustrarea anterioară: «nu vă lăudați spunând: suntem înțelepți (Ieremia 8:8); iată, ați lepădat cuvântul Meu, și ce înțelepciune aveți?» — lauda de sine e nefondată tocmai pentru cei care au respins deja cuvântul divin."}],
  ["cu înțelepciunea sa", {heb:"בְּחָכְמָתוֹ", translit:"behahmato", strong:"H2451", pos:"substantiv construct + sufix", def_ro:"cu înțelepciunea lui.", dict_ro:"Primirea respinsă a cuvântului divin anulează orice pretenție reală de înțelepciune — o înțelepciune separată de ascultare e, pentru profet, o contradicție în termeni."}],
  ["și nici cel puternic să nu se laude cu puterea sa", {heb:"וְאַל יִתְהַלֵּל הַגִּבּוֹר בִּגְבוּרָתוֹ", translit:"veal ithalēl hagibor bigvurato", strong:"H408", pos:"particulă negativă + verb, hitpael imperfect + substantiv + substantiv construct + sufix", def_ro:"și să nu se laude cel puternic cu puterea lui.", dict_ro:"Repetarea formulei de trei ori — înțelept, puternic, bogat — cuprinde toate formele de mândrie omenească convențională, niciuna fiind un temei real de laudă înaintea lui Dumnezeu."}],
  ["și nici cel bogat să nu se laude cu bogăția sa.", {heb:"אַל יִתְהַלֵּל עָשִׁיר בְּעָשְׁרוֹ", translit:"al ithalēl așir beașro", strong:"H408", pos:"particulă negativă + verb, hitpael imperfect + substantiv + substantiv construct + sufix", def_ro:"să nu se laude cel bogat cu bogăția lui.", dict_ro:"A treia și ultima categorie, bogăția, încheie triada mândriilor omenești deșarte, pregătind contrastul direct cu singurul temei legitim de laudă descris în versetul următor."}]
]},
{v:"9:24", newTags:[
  ["Doar cu aceasta poate lăudărosul să se laude: că Mă înțelege și că Mă cunoaște, căci Eu sunt DOMNUL, care înfăptuiesc", {heb:"כִּי אִם בְּזֹאת יִתְהַלֵּל הַמִּתְהַלֵּל הַשְׂכֵּל וְיָדֹעַ אוֹתִי כִּי אֲנִי יְהוָה עֹשֶׂה", translit:"ki im bezot ithalēl hamithalēl haskēl veiadoa oti ki ani Adonai ose", strong:"H3588", pos:"conjuncție + conjuncție + pronume demonstrativ + verb, hitpael imperfect + verb, hitpael participiu + verb, hifil infinitiv absolut + verb, qal infinitiv absolut + marcă a complementului direct + sufix + conjuncție + pronume personal + nume propriu + verb, qal participiu", def_ro:"ci doar cu aceasta se va lăuda cel ce se laudă: că a priceput și M-a cunoscut, că Eu sunt DOMNUL, care fac.", dict_ro:"Metzudat David explică faptul că singurul temei legitim de laudă este cunoașterea reală a lui Dumnezeu — nu doar unul care lucrează binele și altul răul, ci recunoașterea că DOMNUL dă fiecăruia după fapta lui, în bunăvoință, judecată și dreptate deopotrivă."}],
  ["pe pământ; căci acestea sunt cele pe care le doresc – rostirea DOMNULUI!", {heb:"בָּאָרֶץ כִּי בְאֵלֶּה חָפַצְתִּי נְאֻם יְהוָה", translit:"baareț ki veēle hafațti neum Adonai", strong:"H776", pos:"substantiv + conjuncție + prepoziție + pronume demonstrativ + verb, qal perfect + substantiv construct + nume propriu", def_ro:"pe pământ, căci în acestea Îmi aflu plăcerea, rostirea DOMNULUI.", dict_ro:"Formula finală de autoritate divină confirmă că bunăvoința, judecata și dreptatea — nu puterea, înțelepciunea sau bogăția — sunt valorile pe care DOMNUL Însuși le dorește și le prețuiește pe pământ."}]
]}
];
