module.exports = [
{v:"6:1", newTags:[
  ["David i-a adunat", {heb:"וַיֹּסֶף דָּוִד", translit:"vaiosef david", strong:"H622", pos:"verb, qal imperfect consecutiv + nume propriu", def_ro:"și a adunat din nou David.", dict_ro:"Rashi explică faptul că poporul se adunase deja la David când l-au făcut rege la Hebron — aceasta fiind a doua adunare, de aceea textul precizează explicit «din nou»."}],
  ["pe toți aleșii din Israel, treizeci de mii [la număr].", {heb:"אֶת כָּל בָּחוּר בְּיִשְׂרָאֵל שְׁלֹשִׁים אָלֶף", translit:"et kal bahur beisraēl șeloșim alef", strong:"H3605", pos:"marcă a complementului direct + substantiv construct + verb, qal participiu pasiv + nume propriu + numeral + numeral", def_ro:"pe tot cel ales în Israel, treizeci de mii.", dict_ro:"Metzudat David explică faptul că mulți se adunau deja la David de la începutul domniei sale, de aceea textul precizează că a mai adunat «din nou» un grup ales, special pentru ridicarea Chivotului."}]
]},
{v:"6:2", newTags:[
  ["Apoi David s-a ridicat și a mers, împreună cu tot poporul care era cu el, de la", {heb:"וַיָּקָם וַיֵּלֶךְ דָּוִד וְכָל הָעָם אֲשֶׁר אִתּוֹ", translit:"vaiakam vaiēleh david vehal haam așer ito", strong:"H6965", pos:"verb, qal imperfect consecutiv + verb, qal imperfect consecutiv + nume propriu + substantiv construct + substantiv + particulă relativă + prepoziție + sufix", def_ro:"și s-a ridicat și a mers David și tot poporul care era cu el, de la.", dict_ro:"Rashi identifică «Baalei Iuda» cu Chiriat-Iearim, confirmat atât la Iosua 15:9 cât și la 1 Cronici 13:6 — același loc numit în ambele texte prin denumirea sa dublă."}],
  ["ca să ridice de acolo Chivotul lui Dumnezeu asupra căruia este invocat numele – numele DOMNULUI, Stăpânul Oștirilor, întronat pe heruvimi, este asupra lui.", {heb:"לְהַעֲלוֹת מִשָּׁם אֵת אֲרוֹן הָאֱלֹהִים אֲשֶׁר נִקְרָא שֵׁם שֵׁם יְהוָה צְבָאוֹת יֹשֵׁב הַכְּרֻבִים עָלָיו", translit:"lehaalot mișam ēt aron haelohim așer nikra șēm șēm Adonai țevaot ioșēv hakruvim alaiv", strong:"H5927", pos:"verb, hifil infinitiv + adverb + marcă a complementului direct + substantiv construct + substantiv + particulă relativă + verb, nifal perfect + substantiv + substantiv construct + nume propriu + substantiv + verb, qal participiu + substantiv + prepoziție + sufix", def_ro:"ca să ridice de acolo Chivotul lui Dumnezeu, asupra căruia e chemat numele, numele DOMNULUI Oștirilor, care șade pe heruvimi, asupra lui.", dict_ro:"Titlul complet al Chivotului — «numele DOMNULUI, Stăpânul Oștirilor, întronat pe heruvimi» — îl identifică explicit ca tronul pământesc al prezenței divine, nu un simplu obiect sacru de transportat."}]
]},
{v:"6:3", newTags:[
  ["Și au pus Chivotul lui Dumnezeu într-un", {heb:"וַיַּרְכִּבוּ אֶת אֲרוֹן הָאֱלֹהִים אֶל", translit:"vaiarkivu et aron haelohim el", strong:"H7392", pos:"verb, hifil imperfect consecutiv + marcă a complementului direct + substantiv construct + substantiv + prepoziție", def_ro:"și au suit Chivotul lui Dumnezeu pe un.", dict_ro:"Rashi explică greșeala fundamentală comisă aici: Chivotul trebuia purtat pe umeri de leviți, «căci slujba sfântă e a lor» (Numeri 7:9), nu transportat într-un car — o eroare pe care, spune Rashi, chiar copiii de la școală o cunoșteau."}],
  ["și l-au purtat din casa lui Avinadav care era pe deal, iar Uza și Ahio, fiii lui Avinadav, conduceau carul cel nou.", {heb:"וַיִּשָּׂאֻהוּ מִבֵּית אֲבִינָדָב אֲשֶׁר בַּגִּבְעָה וְעֻזָּא וְאַחְיוֹ בְּנֵי אֲבִינָדָב נֹהֲגִים אֶת הָעֲגָלָה חֲדָשָׁה", translit:"vaisauhu mibēt avinadav așer bagiva veuza veahio benē avinadav nohagim et haagala hadașa", strong:"H5375", pos:"verb, qal imperfect consecutiv + sufix + substantiv construct + nume propriu + particulă relativă + substantiv + nume propriu + nume propriu + substantiv plural construct + nume propriu + verb, qal participiu + marcă a complementului direct + substantiv + adjectiv", def_ro:"și l-au purtat din casa lui Avinadav, care era pe deal, și Uza și Ahio, fiii lui Avinadav, conducând carul cel nou.", dict_ro:"Rashi leagă greșeala lui David de propriile sale cuvinte din Psalmul 119:54 — «cântări au fost pentru mine hotărârile Tale, în casa pribegiei mele» — pentru care a fost pedepsit să vadă moartea lui Uza chiar prin mâna lui."}]
]},
{v:"6:4", newTags:[
  ["Și l-au purtat din casa lui Avinadav, care era pe deal, împreună cu Chivotul lui Dumnezeu, iar Ahio mergea", {heb:"וַיִּשָּׂאֻהוּ מִבֵּית אֲבִינָדָב אֲשֶׁר בַּגִּבְעָה עִם אֲרוֹן הָאֱלֹהִים וְאַחְיוֹ הֹלֵךְ", translit:"vaisauhu mibēt avinadav așer bagiva im aron haelohim veahio holēh", strong:"H5375", pos:"verb, qal imperfect consecutiv + sufix + substantiv construct + nume propriu + particulă relativă + substantiv + prepoziție + substantiv construct + substantiv + nume propriu + verb, qal participiu", def_ro:"și l-au purtat din casa lui Avinadav, care era pe deal, cu Chivotul lui Dumnezeu, și Ahio mergea.", dict_ro:"Metzudat David explică faptul că Ahio mergea înaintea carului pentru a conduce boii din față, pe când Uza mergea alături de Chivot — de aceea doar Uza a simțit clătinarea boilor, iar Ahio, fiind înainte, nu și-a dat seama."}]
]},
{v:"6:5", newTags:[
  ["Și David și toată casa lui Israel jucau înaintea DOMNULUI cu tot [soiul de] instrumente din", {heb:"וְדָוִד וְכָל בֵּית יִשְׂרָאֵל מְשַׂחֲקִים לִפְנֵי יְהוָה בְּכֹל", translit:"vedavid vehal bēt israēl mesahakim lifnē Adonai behol", strong:"H1732", pos:"nume propriu + substantiv construct + substantiv construct + nume propriu + verb, piel participiu + substantiv construct + nume propriu + substantiv construct", def_ro:"și David și toată casa lui Israel jucau înaintea DOMNULUI cu toate.", dict_ro:"Rashi explică faptul că aceste instrumente erau lucrate din lemn de chiparos — detaliul material al construcției lor arată grija artizanală pusă în crearea lor special pentru acest moment solemn."}],
  ["și cu harpe, și cu lire, și cu tobe, și cu tamburine, și cu talgere.", {heb:"וּבְכִנֹּרוֹת וּבִנְבָלִים וּבְתֻפִּים וּבִמְנַעַנְעִים וּבְצֶלְצֶלִים", translit:"uvhinorot uvinvalim uvtupim uvimnaanim uvțelțelim", strong:"H3658", pos:"substantiv plural + substantiv plural + substantiv plural + substantiv plural + substantiv plural", def_ro:"și cu lire, și cu harpe, și cu tobe, și cu zurgălăi, și cu talgere.", dict_ro:"Enumerarea celor cinci instrumente diferite arată amploarea orchestrației muzicale care a acompaniat procesiunea Chivotului — o sărbătoare de proporții naționale, nu un ceremonial restrâns."}]
]},
{v:"6:6", newTags:[
  ["Au ajuns la aria lui Nahon, și Uza s-a întins către Chivotul lui Dumnezeu și l-a", {heb:"וַיָּבֹאוּ עַד גֹּרֶן נָכוֹן וַיִּשְׁלַח עֻזָּא אֶל אֲרוֹן הָאֱלֹהִים", translit:"vaiavou ad goren nahon vaișlah uza el aron haelohim", strong:"H935", pos:"verb, qal imperfect consecutiv + prepoziție + substantiv construct + nume propriu + verb, qal imperfect consecutiv + nume propriu + prepoziție + substantiv construct + substantiv", def_ro:"și au venit până la aria lui Nahon, și a întins Uza [mâna] către Chivotul lui Dumnezeu.", dict_ro:"Rashi explică «ki șametu habakar» — căci boii l-au clătinat și l-au mișcat — confirmând exact motivul gestului lui Uza: teama instinctivă, nu o intenție sacrilegă deliberată."}],
  ["căci boii îl mișcaseră.", {heb:"כִּי שָׁמְטוּ הַבָּקָר", translit:"ki șamtu habakar", strong:"H8058", pos:"conjuncție + verb, qal perfect + substantiv", def_ro:"căci l-au clătinat boii.", dict_ro:"Metzudat David explică faptul că Uza și-a întins mâna crezând că, dacă boii îl clatină, Chivotul va cădea la pământ — un gest de protecție instinctivă, nu de nesocotire a sfințeniei lui."}]
]},
{v:"6:7", newTags:[
  ["Mânia DOMNULUI s-a aprins împotriva lui Uza și Dumnezeu l-a lovit acolo pentru", {heb:"וַיִּחַר אַף יְהוָה בְּעֻזָּה וַיַּכֵּהוּ שָ�ם הָאֱלֹהִים עַל", translit:"vaihar af Adonai beuza vaiakēhu șam haelohim al", strong:"H2734", pos:"verb, qal imperfect consecutiv + substantiv construct + nume propriu + prepoziție + nume propriu + verb, hifil imperfect consecutiv + sufix + adverb + substantiv + prepoziție", def_ro:"și s-a aprins mânia DOMNULUI împotriva lui Uza, și l-a lovit acolo Dumnezeu pentru.", dict_ro:"Rashi explică faptul că greșeala lui Uza a fost una «neintenționată» (hașal), căci ar fi trebuit să raționeze a fortiori: dacă cei ce l-au purtat prin Iordan n-au trebuit să-l atingă cu mâna, cu atât mai mult el n-ar fi trebuit s-o facă."}],
  ["și Uza a murit acolo, alături de Chivotul lui Dumnezeu.", {heb:"וַיָּמָת שָׁם עִם אֲרוֹן הָאֱלֹהִים", translit:"vaiamat șam im aron haelohim", strong:"H4191", pos:"verb, qal imperfect consecutiv + adverb + prepoziție + substantiv construct + substantiv", def_ro:"și a murit acolo, cu Chivotul lui Dumnezeu.", dict_ro:"Metzudat David explică faptul că mânia DOMNULUI s-a aprins pentru puțina încredere a lui Uza, care a gândit că Chivotul ar putea cădea la pământ — ca și cum ar fi uitat sfințenia și puterea proprie a obiectului pe care îl proteja."}]
]},
{v:"6:8", newTags:[
  ["David s-a mâniat de", {heb:"וַיִּחַר לְדָוִד עַל אֲשֶׁר פָּרַץ יְהוָה", translit:"vaihar ledavid al așer paraț Adonai", strong:"H2734", pos:"verb, qal imperfect consecutiv + nume propriu + prepoziție + particulă relativă + verb, qal perfect + nume propriu", def_ro:"și s-a mâhnit David pentru că a făcut spărtură DOMNUL.", dict_ro:"Metzudat David explică faptul că David s-a mâhnit și s-a tulburat pentru sine, în felul celui strâmtorat și înspăimântat, la fel cum se spune despre Samuel la 1 Samuel 15:11 — reacția e de neliniște personală, nu de revoltă față de judecata divină."}],
  ["cu care DOMNUL răbufnise împotriva lui Uza și a numit locul acela Pereț-Uza (n.t. Răbufnirea [contra] lui Uza), până în ziua de astăzi.", {heb:"בְּעֻזָּה וַיִּקְרָא לַמָּקוֹם הַהוּא פֶּרֶץ עֻזָּה עַד הַיּוֹם הַזֶּה", translit:"beuza vaikra lamakom hahu pereț uza ad haiom haze", strong:"H5798", pos:"nume propriu + verb, qal imperfect consecutiv + substantiv + pronume demonstrativ + nume propriu + nume propriu + prepoziție + substantiv + pronume demonstrativ", def_ro:"împotriva lui Uza, și a chemat locul acela Pereț-Uza, până în ziua aceasta.", dict_ro:"Numele locului, păstrat «până în ziua de astăzi», fixează permanent în memoria colectivă acest eveniment, transformând neliniștea momentană a lui David într-un reper geografic durabil."}]
]},
{v:"6:9", newTags:[
  ["Și David s-a temut de DOMNUL în ziua aceea și a spus: „Cum să", {heb:"וַיִּרָא דָוִד אֶת יְהוָה בַּיּוֹם הַהוּא וַיֹּאמֶר אֵיךְ", translit:"vaira david et Adonai baiom hahu vaiomer ēh", strong:"H3372", pos:"verb, qal imperfect consecutiv + nume propriu + marcă a complementului direct + nume propriu + substantiv + pronume demonstrativ + verb, qal imperfect consecutiv + particulă interogativă", def_ro:"și s-a temut David de DOMNUL în ziua aceea și a spus: cum.", dict_ro:"Metzudat David explică faptul că David s-a gândit că nu se poate păzi cu adevărat sfințenia Chivotului — frica lui nu e de DOMNUL Însuși, ci de propria incapacitate de a-I găzdui prezența corect."}],
  ["Chivotul DOMNULUI la mine?”", {heb:"אֵלַי אֲרוֹן יְהוָה", translit:"ēlai aron Adonai", strong:"H413", pos:"prepoziție + sufix + substantiv construct + nume propriu", def_ro:"la mine Chivotul DOMNULUI?", dict_ro:"Întrebarea retorică a lui David marchează tranziția de la entuziasmul inițial al procesiunii la o teamă reflexivă profundă, declanșată direct de moartea lui Uza."}]
]},
{v:"6:10", newTags:[
  ["Și David n-a mai vrut să aducă Chivotul DOMNULUI la el, în Orașul lui David, ci David l-a deturnat către casa lui", {heb:"וְלֹא אָבָה דָוִד לְהָסִיר אֵלָיו אֶת אֲרוֹן יְהוָה עַל עִיר דָּוִד וַיַּטֵּהוּ דָוִד בֵּית", translit:"velo ava david lehasir ēlaiv et aron Adonai al ir david vaiatēhu david bēt", strong:"H3808", pos:"particulă negativă + verb, qal perfect + nume propriu + verb, hifil infinitiv + prepoziție + sufix + marcă a complementului direct + substantiv construct + nume propriu + prepoziție + substantiv construct + nume propriu + verb, hifil imperfect consecutiv + sufix + nume propriu + substantiv construct", def_ro:"și n-a vrut David să ducă la el Chivotul DOMNULUI, în Cetatea lui David, și l-a abătut David, [spre] casa.", dict_ro:"Metzudat David explică faptul că David a abătut Chivotul de la drumul direct spre Cetatea lui David, îndreptându-l spre casa lui Oved-Edom — o soluție intermediară, prudentă, înainte de a îndrăzni din nou aducerea lui finală."}]
]},
{v:"6:11", newTags:[
  ["Și Chivotul DOMNULUI a rămas în casa lui Oved-Edom, ghititul, timp de trei luni, iar DOMNUL l-a", {heb:"וַיֵּשֶׁב אֲרוֹן יְהוָה בֵּית עֹבֵד אֱדוֹם הַגִּתִּי שְׁלֹשָׁה חֳדָשִׁים יְהוָה", translit:"vaiēșev aron Adonai bēt ovēd edom hagiti șeloșa hodașim Adonai", strong:"H3427", pos:"verb, qal imperfect consecutiv + substantiv construct + nume propriu + substantiv construct + nume propriu + nume propriu + nume de neam + numeral + substantiv plural + nume propriu", def_ro:"și a rămas Chivotul DOMNULUI în casa lui Oved-Edom, ghititul, trei luni; și DOMNUL.", dict_ro:"Rashi notează, pe baza Cronicilor, că soția lui Oved-Edom și cele opt nurori ale sale au născut câte șase fii fiecare dintr-o singură sarcină — o binecuvântare a fertilității de proporții extraordinare, legată direct de prezența Chivotului în casa lor."}],
  ["pe Oved-Edom împreună cu toată casa lui.", {heb:"אֶת עֹבֵד אֱדֹם וְאֶת כָּל בֵּיתוֹ", translit:"et ovēd edom veet kal bēto", strong:"H5654", pos:"marcă a complementului direct + nume propriu + marcă a complementului direct + substantiv construct + substantiv construct + sufix", def_ro:"pe Oved-Edom și toată casa lui.", dict_ro:"Binecuvântarea extinsă la întreaga casă, nu doar la Oved-Edom personal, confirmă că apropierea de Chivot, când e tratată cu respectul cuvenit, aduce bunăstare colectivă, nu pericol."}]
]},
{v:"6:12", newTags:[
  ["Și i s-a vestit lui David că DOMNUL îl binecuvântase pe Oved-Edom și toată casa lui din pricina Chivotului DOMNULUI, și David a mers și a ridicat Chivotul lui Dumnezeu din casa lui Oved-Edom, către Orașul lui David, cu", {heb:"וַיֻּגַּד לַמֶּלֶךְ דָּוִד לֵאמֹר בֵּרַךְ יְהוָה אֶת בֵּית עֹבֵד אֱדֹם וְאֶת כָּל אֲשֶׁר לוֹ בַּעֲבוּר אֲרוֹן הָאֱלֹהִים וַיֵּלֶךְ דָּוִד וַיַּעַל אֶת אֲרוֹן הָאֱלֹהִים מִבֵּית עֹבֵד אֱדֹם עִיר דָּוִד", translit:"vaiugad lameleh david lēmor bērah Adonai et bēt ovēd edom veet kal așer lo baavur aron haelohim vaiēleh david vaiaal et aron haelohim mibēt ovēd edom ir david", strong:"H5046", pos:"verb, hofal imperfect consecutiv + substantiv + nume propriu + verb, qal infinitiv + verb, piel perfect + nume propriu + marcă a complementului direct + substantiv construct + nume propriu + marcă a complementului direct + substantiv construct + particulă relativă + prepoziție + sufix + substantiv construct + substantiv construct + substantiv + verb, qal imperfect consecutiv + nume propriu + verb, hifil imperfect consecutiv + marcă a complementului direct + substantiv construct + substantiv + substantiv construct + nume propriu + substantiv construct + nume propriu", def_ro:"și s-a vestit regelui David, spunând: a binecuvântat DOMNUL casa lui Oved-Edom și tot ce are, din pricina Chivotului lui Dumnezeu; și a mers David și a ridicat Chivotul lui Dumnezeu din casa lui Oved-Edom, la cetatea lui David, cu.", dict_ro:"Metzudat David explică faptul că, abia aflând de binecuvântarea revărsată asupra lui Oved-Edom, David a prins curaj să reia ridicarea Chivotului spre Cetatea lui, Țion — vestea bună devine semnalul care anulează teama precedentă."}]
]},
{v:"6:13", newTags:[
  ["La fiecare", {heb:"וַיְהִי כִּי צָעֲדוּ נֹשְׂאֵי אֲרוֹן יְהוָה", translit:"vaihi ki țaadu nosē aron Adonai", strong:"H1961", pos:"verb, qal imperfect consecutiv + conjuncție + verb, qal perfect + verb, qal participiu + substantiv construct + nume propriu", def_ro:"și a fost, când au pășit purtătorii Chivotului DOMNULUI.", dict_ro:"Metzudat David explică faptul că, de fiecare dată când purtătorii Chivotului făceau șase pași, David jertfea din nou — repetiția deasă a jertfei s-a continuat de-a lungul întregului drum, nu doar o singură dată la început."}],
  ["pe care îi făceau purtătorii Chivotului DOMNULUI, el jertfea un taur și un taur îngrășat.", {heb:"וַיִּזְבַּח שׁוֹר וּמְרִיא", translit:"vaizbah șor umri", strong:"H2076", pos:"verb, qal imperfect consecutiv + substantiv + substantiv", def_ro:"a jertfit bou și vită îngrășată.", dict_ro:"Dubla jertfă, repetată la fiecare șase pași, exprimă intensitatea recunoștinței lui David pentru succesul acestei a doua tentative, după dezastrul primei încercări."}]
]},
{v:"6:14", newTags:[
  ["Și David dansa cu toată puterea [lui] înaintea DOMNULUI, încins cu o", {heb:"וְדָוִד מְכַרְכֵּר בְּכָל עֹז לִפְנֵי יְהוָה וְדָוִד חָגוּר", translit:"vedavid meharkēr behal oz lifnē Adonai vedavid hagur", strong:"H1732", pos:"nume propriu + verb, pilpel participiu + substantiv construct + substantiv + substantiv construct + nume propriu + nume propriu + verb, qal participiu pasiv", def_ro:"și David dansa cu toată puterea înaintea DOMNULUI; și David [era] încins cu o.", dict_ro:"Metzudat David explică «efod bad» ca un veșmânt făcut după chipul efodului marelui preot, dedicat celor ce se consacră în chip aparte slujirii DOMNULUI, la fel cum e descris și Samuel la 1 Samuel 2:18 — David îmbracă simbolic o haină de devoțiune specială pentru acest moment."}]
]},
{v:"6:15", newTags:[
  ["Și David și toată casa lui Israel au ridicat Chivotul DOMNULUI cu", {heb:"וְדָוִד וְכָל בֵּית יִשְׂרָאֵל מַעֲלִים אֶת אֲרוֹן יְהוָה", translit:"vedavid vehal bēt israēl maalim et aron Adonai", strong:"H1732", pos:"nume propriu + substantiv construct + substantiv construct + nume propriu + verb, hifil participiu + marcă a complementului direct + substantiv construct + nume propriu", def_ro:"și David și toată casa lui Israel ridicau Chivotul DOMNULUI cu.", dict_ro:"Metzudat David explică «bitrua» ca «glas de bucurie», obiceiul folosit la aducerea unui lucru de mare cinste — expresia arată bucuria autentică simțită de popor la ridicarea finală a Chivotului."}],
  ["și cu sunet de corn.", {heb:"וּבְקוֹל שׁוֹפָר", translit:"uvkol șofar", strong:"H6963", pos:"substantiv construct + substantiv", def_ro:"și cu glas de corn.", dict_ro:"Sunetul cornului, alături de strigătul de bucurie, completează amploarea sonoră a ceremoniei de intrare a Chivotului în Cetatea lui David."}]
]},
{v:"6:16", newTags:[
  ["Când Chivotul a ajuns în Orașul lui David, Mihal, fiica lui Șaul, a privit pe fereastră și l-a văzut pe regele David sărind și dansând înaintea DOMNULUI, și l-a", {heb:"וְהָיָה אֲרוֹן יְהוָה בָּא עִיר דָּוִד וּמִיכַל בַּת שָׁאוּל נִשְׁקְפָה בְּעַד הַחַלּוֹן וַתֵּרֶא אֶת הַמֶּלֶךְ דָּוִד מְפַזֵּז וּמְכַרְכֵּר לִפְנֵי יְהוָה וַתִּבֶז", translit:"vehaia aron Adonai ba ir david umihal bat șaul nișkefa bead hahalon vatēre et hameleh david mefazēz umharkēr lifnē Adonai vativez", strong:"H727", pos:"verb, qal perfect + substantiv construct + nume propriu + verb, qal perfect + substantiv construct + nume propriu + nume propriu + substantiv construct + nume propriu + verb, nifal perfect + prepoziție + substantiv + verb, qal imperfect consecutiv + marcă a complementului direct + substantiv + nume propriu + verb, piel participiu + verb, pilpel participiu + substantiv construct + nume propriu + verb, qal imperfect consecutiv", def_ro:"și a fost, când a venit Chivotul DOMNULUI în Cetatea lui David, și Mihal, fiica lui Șaul, a privit prin fereastră și a văzut pe regele David sărind și dansând înaintea DOMNULUI, și l-a disprețuit.", dict_ro:"Metzudat David explică faptul că Mihal a socotit, în inima ei, o faptă necuvenită pentru un rege să sară și să danseze în public, chiar înaintea Chivotului — disprețul ei vine din concepția despre demnitatea regală, nu din necredință."}]
]},
{v:"6:17", newTags:[
  ["Au adus Chivotul DOMNULUI și l-au așezat la", {heb:"וַיָּבִאוּ אֶת אֲרוֹן יְהוָה וַיַּצִּגוּ אֹתוֹ", translit:"vaiaviu et aron Adonai vaiațigu oto", strong:"H935", pos:"verb, hifil imperfect consecutiv + marcă a complementului direct + substantiv construct + nume propriu + verb, hifil imperfect consecutiv + marcă a complementului direct + sufix", def_ro:"și au adus Chivotul DOMNULUI și l-au așezat.", dict_ro:"Metzudat David explică «bimkomo» ca locul special pregătit pentru Chivot în mijlocul cortului pe care David îl întinsese anume pentru el — un spațiu dedicat, nu improvizat în ultima clipă."}],
  ["în cortul pe care David îl ridicase pentru el; și David a adus arderi-de-tot înaintea DOMNULUI și jertfe de pace.", {heb:"בְּתוֹךְ הָאֹהֶל אֲשֶׁר נָטָה לוֹ דָּוִד וַיַּעַל דָּוִד עֹלוֹת לִפְנֵי יְהוָה וּשְׁלָמִים", translit:"betoh haohel așer nata lo david vaiaal david olot lifnē Adonai ușlamim", strong:"H8432", pos:"substantiv construct + substantiv + particulă relativă + verb, qal perfect + prepoziție + sufix + nume propriu + verb, hifil imperfect consecutiv + nume propriu + substantiv + substantiv construct + nume propriu + substantiv", def_ro:"în mijlocul cortului pe care David îl întinsese pentru el; și a adus David arderi-de-tot înaintea DOMNULUI și jertfe de pace.", dict_ro:"Secvența finală — așezarea Chivotului, apoi jertfele — confirmă finalizarea completă a misiunii începute cu atâta dificultate, încheiată aici cu succes deplin și recunoștință rituală."}]
]},
{v:"6:18", newTags:[
  ["Când David a încheiat de adus arderea-de-tot și jertfa de pace, a", {heb:"וַיְכַל דָּוִד מֵהַעֲלוֹת הָעוֹלָה וְהַשְּׁלָמִים וַיְבָרֶךְ", translit:"vaihal david mēhaalot haola vehașlamim vaivareh", strong:"H3615", pos:"verb, piel imperfect consecutiv + nume propriu + verb, hifil infinitiv + substantiv + substantiv + verb, piel imperfect consecutiv", def_ro:"și a încheiat David aducerea arderii-de-tot și a jertfelor de pace, și a binecuvântat.", dict_ro:"Metzudat David compară acest gest cu cel al lui Solomon la sfințirea Templului (1 Împărați 8:55) — David, ca rege, binecuvântează poporul în Numele DOMNULUI, precedent pentru ceremonia regală ulterioară a fiului său."}],
  ["poporul cu numele DOMNULUI Oștirilor.", {heb:"אֶת הָעָם בְּשֵׁם יְהוָה צְבָאוֹת", translit:"et haam beșēm Adonai țevaot", strong:"H5971", pos:"marcă a complementului direct + substantiv + substantiv construct + nume propriu + substantiv", def_ro:"pe popor în numele DOMNULUI Oștirilor.", dict_ro:"Binecuvântarea rostită «în numele DOMNULUI Oștirilor» încheie ritualul cu aceeași formulă regală de autoritate care avea să fie reluată mai târziu de Solomon."}]
]},
{v:"6:19", newTags:[
  ["Și a dat întregului popor, întregii multitudini a lui Israel, bărbaților și femeilor deopotrivă, câte o franzelă de pâine, o bucată de carne și o", {heb:"וַיְחַלֵּק לְכָל הָעָם לְכָל הֲמוֹן יִשְׂרָאֵל לְמֵאִישׁ וְעַד אִשָּׁה לְאִישׁ חַלַּת לֶחֶם אַחַת וְאֶשְׁפָּר אֶחָד וַ", translit:"vaihalēk lehal haam lehal hamon israēl lemēiș vead ișa leiș halat lehem ahat veeșpar ehad va", strong:"H2505", pos:"verb, piel imperfect consecutiv + substantiv construct + substantiv + substantiv construct + substantiv construct + nume propriu + substantiv + prepoziție + substantiv + substantiv construct + substantiv construct + substantiv + numeral + substantiv + numeral", def_ro:"și a împărțit la tot poporul, la toată mulțimea lui Israel, de la om la femeie, fiecăruia o turtă de pâine și o bucată și.", dict_ro:"Rashi identifică «eșpar» ca a șasea parte dintr-un taur, potrivit Talmudului (Pesahim 36b) — o porție precisă, nu simbolică, confirmând amploarea reală a distribuției de hrană către întreaga mulțime adunată."}],
  ["(n.t. turtă cu stafide sau ulcior de vin); și apoi tot poporul, fiecare om, a mers la casa lui.", {heb:"וַיֵּלֶךְ כָּל הָעָם אִישׁ לְבֵיתוֹ", translit:"vaiēleh kal haam iș levēto", strong:"H3212", pos:"verb, qal imperfect consecutiv + substantiv construct + substantiv + substantiv + substantiv construct + sufix", def_ro:"și a mers tot poporul, fiecare om, la casa lui.", dict_ro:"Rashi explică «așișa» ca urcior de vin, potrivit aceluiași tratat talmudic — darul complet de pâine, carne și vin încheie sărbătoarea cu o masă festivă oferită întregii națiuni, înainte ca fiecare să se retragă acasă."}]
]}
];
