module.exports = [
{v:"4:42", newTags:[
  ["Și a venit un om din Baal-Șalișa și a adus la omul lui Dumnezeu mâncare din", {heb:"וְאִישׁ בָּא מִבַּעַל שָׁלִשָׁה וַיָּבֵא לְאִישׁ הָאֱלֹהִים לֶחֶם", translit:"veiș ba mibaal șalișa vaiavē leiș haelohim lehem", strong:"H376", pos:"substantiv + verb, qal perfect + nume propriu + nume propriu + verb, hifil imperfect consecutiv + substantiv construct + substantiv + substantiv construct", def_ro:"și un om a venit din Baal-Șalișa și a adus omului lui Dumnezeu pâine din.", dict_ro:"Rashi explică faptul că Targum Ionatan traduce «Baal-Șalișa» ca «țara de spre miazăzi», căci «baal» are sensul de câmpie în acest context geografic."}],
  [": douăzeci de franzele de pâine de orz și spice proaspete de grâu cu pleava lor. [Elișa] i-a spus: „Dă-le poporului să le mănânce.”", {heb:"עֶשְׂרִים לֶחֶם שְׂעֹרִים וְכַרְמֶל בְּצִקְלֹנוֹ וַיֹּאמֶר תֵּן לָעָם וְיֹאכֵלוּ", translit:"esrim lehem seorim veharmel bețiklono vaiomer tēn laam veiohēlu", strong:"H6242", pos:"numeral + substantiv construct + substantiv + substantiv + substantiv construct + sufix + verb, qal imperfect consecutiv + verb, qal imperativ + substantiv + verb, qal imperfect", def_ro:"douăzeci de pâini de orz și spice pline în învelișul lor, și a spus: dă poporului să mănânce.", dict_ro:"Talmudul Bavli (Sanhedrin 12a) explică faptul că aceste roade din Baal-Șalișa, locul unde roadele se coceau cel mai repede din toată Țara Israelului, erau din orz, nu din grâu — detaliu confirmat prin precizarea exactă a textului — iar momentul era chiar în vremea lui Pesah."}]
]},
{v:"4:43", newTags:[
  ["Slujitorul lui a spus: „Cum pot să pun aceasta înaintea a o sută de oameni?” Așa că el a spus: „Dă poporului să le mănânce, căci așa a spus DOMNUL: «Vor mânca și", {heb:"וַיֹּאמֶר מְשָׁרְתוֹ מָה אֶתֵּן זֶה לִפְנֵי מֵאָה אִישׁ וַיֹּאמֶר תֵּן לָעָם וְיֹאכֵלוּ כִּי כֹה אָמַר יְהוָה אָכֹל", translit:"vaiomer meșarto ma etēn ze lifnē mēa iș vaiomer tēn laam veiohēlu ki ho amar Adonai ahol", strong:"H559", pos:"verb, qal imperfect consecutiv + verb, piel participiu + sufix + particulă interogativă + verb, qal imperfect + pronume demonstrativ + substantiv construct + numeral + substantiv + verb, qal imperfect consecutiv + verb, qal imperativ + substantiv + verb, qal jusiv + conjuncție + adverb + verb, qal perfect + nume propriu + verb, qal infinitiv absolut", def_ro:"și a spus slujitorul lui: ce să dau aceasta înaintea a o sută de oameni? Și a spus: dă poporului să mănânce, căci așa a spus DOMNUL: mâncând.", dict_ro:"Metzudat David explică faptul că slujitorul socotește cantitatea prea mică pentru atâția oameni, dar Elișa îi răspunde cu certitudinea poruncii divine, nu cu o justificare omenească a cantității."}]
]},
{v:"4:44", newTags:[
  ["El le-a pus înaintea lor și ei au mâncat și a mai și rămas,", {heb:"וַיִּתֵּן לִפְנֵיהֶם וַיֹּאכְלוּ וַיּוֹתִרוּ", translit:"vaitēn lifnēhem vaiohlu vaiotiru", strong:"H5414", pos:"verb, qal imperfect consecutiv + substantiv construct + sufix + verb, qal imperfect consecutiv + verb, hifil imperfect consecutiv", def_ro:"și le-a pus înaintea lor, și au mâncat, și a mai rămas.", dict_ro:"Împlinirea exactă a cuvântului lui Elișa, confirmată «precum spusese DOMNUL», arată că minunea nu venea din puterea profetului însuși, ci era strict garantată de cuvântul divin transmis prin el."}]
]},
{v:"5:1", newTags:[
  ["Naaman, un general în oștirea regelui Aramului, era om de seamă înaintea stăpânului său,", {heb:"וְנַעֲמָן שַׂר צְבָא מֶלֶךְ אֲרָם הָיָה אִישׁ גָּדוֹל לִפְנֵי אֲדֹנָיו", translit:"venaaman sar țeva meleh aram haia iș gadol lifnē adonaiv", strong:"H5283", pos:"nume propriu + substantiv construct + substantiv construct + substantiv construct + nume propriu + verb, qal perfect + substantiv + adjectiv + substantiv construct + substantiv construct + sufix", def_ro:"și Naaman, generalul oștirii regelui Aramului, era om mare înaintea stăpânului său.", dict_ro:"Rashi explică faptul că textul continuă să înșire minunile făcute prin Elișa — Naaman fiind cel care, trăgând cu arcul fără țintă, l-a ucis pe regele Ahab al Israelului, potrivit tradiției din Yalkut Șimoni."}],
  ["și foarte respectat, căci prin el dăduse DOMNUL biruință Aramului. El era mare luptător, [dar] era", {heb:"וּנְשֻׂא פָנִים כִּי בוֹ נָתַן יְהוָה תְּשׁוּעָה לַאֲרָם וְהָאִישׁ הָיָה גִּבּוֹר חַיִל", translit:"unsu fanim ki vo natan Adonai teșua laaram vehaiș haia gibor hail", strong:"H5375", pos:"verb, qal participiu pasiv + substantiv + conjuncție + prepoziție + sufix + verb, qal perfect + nume propriu + substantiv + nume propriu + substantiv + verb, qal perfect + adjectiv + substantiv", def_ro:"și ridicat la față, căci prin el a dat DOMNUL biruință Aramului; și omul era viteaz în luptă.", dict_ro:"Metzudat David explică faptul că Naaman era cinstit de toți pentru biruința adusă Aramului, dar fiind lepros era împiedicat să coboare mereu la luptă, cum ar fi dorit ca mare luptător — contrastul dintre măreția lui și boala care-l limita."}]
]},
{v:"5:2", newTags:[
  ["Aram ieșise la luptă în cete și luaseră prizonieră", {heb:"וַאֲרָם יָצְאוּ גְדוּדִים וַיִּשְׁבּוּ מֵאֶרֶץ יִשְׂרָאֵל", translit:"vaaram iațu gedudim vaișbu mēereț israēl", strong:"H758", pos:"nume propriu + verb, qal perfect + substantiv + verb, qal imperfect consecutiv + substantiv construct + nume propriu", def_ro:"și Aramul a ieșit în cete și au luat prizonieri din țara Israelului.", dict_ro:"Rashi explică faptul că «gedud» denumește cetele de oameni care merg de capul lor, câte o sută sau două sute, ca să jefuiască tot ce găsesc pe unde trec."}],
  ["din țara Israelului și ea îi slujea soției lui Naaman.", {heb:"וַתְּהִי לִפְנֵי אֵשֶׁת נַעֲמָן", translit:"vathi lifnē ēșet naaman", strong:"H1961", pos:"verb, qal imperfect consecutiv + substantiv construct + substantiv construct + nume propriu", def_ro:"și a fost înaintea soției lui Naaman.", dict_ro:"Rashi identifică fata captivă ca fiind din orașul Naaran, iar expresia «îi slujea» e tradusă de Targum Ionatan ca «slujea înaintea soției lui Naaman»."}]
]},
{v:"5:3", newTags:[
  ["Ea i-a spus stăpânei ei: „Rugămințile stăpânului meu să fie aduse în fața profetului care este în Samaria, și atunci el", {heb:"וַתֹּאמֶר אֶל גְּבִרְתָּהּ אַחֲלֵי אֲדֹנִי לִפְנֵי הַנָּבִיא אֲשֶׁר בְּשֹׁמְרוֹן אָז", translit:"vatomer el gevirtah ahalē adoni lifnē hanavi așer beșomron az", strong:"H559", pos:"verb, qal imperfect consecutiv + prepoziție + substantiv construct + sufix + interjecție + substantiv construct + sufix + substantiv construct + substantiv + particulă relativă + nume propriu + adverb", def_ro:"și a spus către stăpâna ei: o, de-ar fi stăpânul meu înaintea profetului care este în Samaria, atunci.", dict_ro:"Rashi explică «ahalei» ca o expresie de rugăminte, întocmai ca «și Moise L-a rugat» (Exod 32:11) — fata captivă exprimă o dorință fierbinte, nu o certitudine, pentru vindecarea stăpânului ei."}],
  [" de lepră.”", {heb:"אֹתוֹ מִצָּרַעְתּוֹ", translit:"oto mițarato", strong:"H853", pos:"marcă a complementului direct + sufix + substantiv construct + sufix", def_ro:"pe el, de lepra lui.", dict_ro:"Rashi și Metzudat David explică faptul că «adunarea» (ieesof) spusă despre lepros înseamnă chiar vindecarea lui: cât e bolnav, leprosul stă departe de tabără, iar vindecarea îl «adună» din nou printre oameni, ca la Numeri 12:15 despre Miriam."}]
]},
{v:"5:4", newTags:[
  ["[Naaman] a mers și i-a povestit stăpânului său, spunând: „", {heb:"וַיָּבֹא וַיַּגֵּד לַאדֹנָיו לֵאמֹר", translit:"vaiavo vaiagēd ladonaiv lēmor", strong:"H935", pos:"verb, qal imperfect consecutiv + verb, hifil imperfect consecutiv + substantiv plural + sufix + verb, qal infinitiv", def_ro:"și a venit și a vestit stăpânului său, spunând.", dict_ro:"Rashi precizează că subiectul acțiunii e Naaman, care îi povestește regelui Aramului cuvintele fetei captive, fără să le pună el însuși la îndoială."}],
  [" [cuvinte] a vorbit fata din țara Israelului.”", {heb:"דִּבְּרָה הַנַּעֲרָה אֲשֶׁר מֵאֶרֶץ יִשְׂרָאֵל", translit:"dibra hanaara așer mēereț israēl", strong:"H1696", pos:"verb, piel perfect + substantiv + particulă relativă + substantiv construct + nume propriu", def_ro:"a vorbit fata care este din țara Israelului.", dict_ro:"Metzudat David notează simplu că Naaman a povestit stăpânului său exact ce spusese fata, fără adaosuri — relatare fidelă care pune în mișcare întregul șir al evenimentelor următoare."}]
]},
{v:"5:5", newTags:[
  ["Regele Aramului i-a spus: „Mergi la el și eu voi trimite o scrisoare regelui Israelului.”", {heb:"וַיֹּאמֶר מֶלֶךְ אֲרָם לֶךְ בֹּא וְאֶשְׁלְחָה סֵפֶר אֶל מֶלֶךְ יִשְׂרָאֵל", translit:"vaiomer meleh aram leh bo veeșleha sēfer el meleh israēl", strong:"H559", pos:"verb, qal imperfect consecutiv + substantiv construct + nume propriu + verb, qal imperativ + verb, qal imperativ + verb, qal cohortativ + substantiv + prepoziție + substantiv construct + nume propriu", def_ro:"și a spus regele Aramului: mergi, du-te, și voi trimite o scrisoare la regele Israelului.", dict_ro:"Metzudat David explică faptul că regele Aramului trimite scrisoarea «regelui Israelului» pentru ca acesta să-i poruncească profetului să-l vindece pe Naaman, nu crezând că regele însuși ar putea vindeca lepra."}],
  [" El a mers și a luat cu sine zece talanți de argint, șase mii de monede de aur și", {heb:"וַיֵּלֶךְ וַיִּקַּח בְּיָדוֹ עֶשֶׂר כִּכְּרֵי כֶסֶף וְשֵׁשֶׁת אֲלָפִים זָהָב וְעֶשֶׂר", translit:"vaiēleh vaikah beiado eser kikrē hesef veșēșet alafim zahav veeser", strong:"H3212", pos:"verb, qal imperfect consecutiv + verb, qal imperfect consecutiv + substantiv construct + sufix + numeral + substantiv construct + substantiv + numeral + numeral + substantiv + numeral", def_ro:"și a mers și a luat în mâna lui zece talanți de argint și șase mii de arginți de aur, și zece.", dict_ro:"Rashi explică faptul că toate acestea erau un dar pentru profet, pe care Naaman îl aduce cu sine încă înainte de a-i fi cerut nimic — pregătit să plătească generos pentru vindecare."}]
]},
{v:"5:6", newTags:[
  ["Și i-a adus regelui Israelului o", {heb:"וַיָּבֵא אֶל מֶלֶךְ יִשְׂרָאֵל", translit:"vaiavē el meleh israēl", strong:"H935", pos:"verb, hifil imperfect consecutiv + prepoziție + substantiv construct + nume propriu", def_ro:"și a adus la regele Israelului.", dict_ro:"Metzudat David subliniază că Naaman a adus scrisoarea direct regelui Israelului, urmând exact sfatul regelui Aramului de la versetul precedent."}],
  [" care spunea: „Și acum, când această scrisoare va ajunge la tine, iată, l-am trimis la tine pe slujitorul meu Naaman, ca să-l vindeci de lepra lui.”", {heb:"לֵאמֹר וְעַתָּה כְּבוֹא הַסֵּפֶר הַזֶּה אֵלֶיךָ הִנֵּה שָׁלַחְתִּי אֵלֶיךָ אֶת נַעֲמָן עַבְדִּי וַאֲסַפְתּוֹ מִצָּרַעְתּוֹ", translit:"lēmor veata kevo hasēfer haze ēleha hinē șalahti ēleha et naaman avdi vaasafto mițarato", strong:"H559", pos:"verb, qal infinitiv + adverb + verb, qal infinitiv + substantiv + pronume demonstrativ + prepoziție + sufix + particulă demonstrativă + verb, qal perfect + prepoziție + sufix + marcă a complementului direct + nume propriu + substantiv construct + sufix + verb, qal perfect consecutiv + sufix + substantiv construct + sufix", def_ro:"spunând: și acum, când va veni scrisoarea aceasta la tine, iată, am trimis la tine pe Naaman, slujitorul meu, și să-l aduni de lepra lui.", dict_ro:"Metzudat David explică faptul că scrisoarea omite formulele obișnuite de salut și începe direct cu partea esențială — regele Aramului presupune că regele Israelului îi va porunci profetului să-l vindece, nu că el însuși ar face-o."}]
]},
{v:"5:7", newTags:[
  ["Când regele Israelului a citit scrisoarea, și-a sfâșiat veșmintele și a spus: „Sunt eu oare Dumnezeu ca să pot ucide și să pot da viață,", {heb:"וַיְהִי כִּקְרֹא מֶלֶךְ יִשְׂרָאֵל אֶת הַסֵּפֶר וַיִּקְרַע בְּגָדָיו וַיֹּאמֶר הַאֱלֹהִים אָנִי לְהָמִית וּלְהַחֲיוֹת", translit:"vaihi kikro meleh israēl et hasēfer vaikra begadaiv vaiomer haelohim ani lehamit ulhahaiot", strong:"H1961", pos:"verb, qal imperfect consecutiv + verb, qal infinitiv + substantiv construct + nume propriu + marcă a complementului direct + substantiv + verb, qal imperfect consecutiv + substantiv construct + sufix + verb, qal imperfect consecutiv + substantiv + pronume personal + verb, hifil infinitiv + verb, hifil infinitiv", def_ro:"și a fost, când a citit regele Israelului scrisoarea, și-a sfâșiat veșmintele și a spus: sunt eu Dumnezeu, să ucid și să dau viață?", dict_ro:"Rashi explică faptul că litera «he» de la începutul întrebării «haelohim» e vocalizată cu patah, pentru a arăta clar că e o formă interogativă — regele exprimă consternare, nu afirmație."}],
  [" că omul acesta trimite la mine pe cineva să-l vindec de lepră? Să știi și să vezi că el", {heb:"כִּי זֶה שֹׁלֵחַ אֵלַי לֶאֱסֹף אִישׁ מִצָּרַעְתּוֹ כִּי אַךְ דְּעוּ נָא וּרְאוּ כִּי", translit:"ki ze șolēah ēlai leesof iș mițarato ki ah deu na uru ki", strong:"H3588", pos:"conjuncție + pronume demonstrativ + verb, qal participiu + prepoziție + sufix + verb, qal infinitiv + substantiv + substantiv construct + sufix + conjuncție + particulă afirmativă + verb, qal imperativ + interjecție + verb, qal imperativ + conjuncție", def_ro:"căci acesta trimite la mine ca să adun un om de lepra lui? Căci, într-adevăr, știți și vedeți că.", dict_ro:"Metzudat David explică faptul că regele, din marea lui răutate, n-a crezut în puterea profetului și a presupus în schimb că regele Aramului îl trimitea pe el însuși să-l vindece — o neînțelegere ce-l duce la disperare."}],
  [" împotriva mea!”", {heb:"הוּא לִי", translit:"hu li", strong:"H1931", pos:"pronume personal + prepoziție + sufix", def_ro:"el [este] pentru mine.", dict_ro:"Rashi explică «mitane» ca o expresie de «învinuiri mincinoase», aceeași rădăcină folosită la Deuteronom 22:14 — regele crede că cererea ascunde intenția de a găsi un pretext de război."}]
]},
{v:"5:8", newTags:[
  ["Când Elișa, omul lui Dumnezeu, a auzit că regele Israelului și-a sfâșiat veșmintele, a trimis [veste] la rege, spunând: „De ce ți-ai sfâșiat veșmintele?", {heb:"וַיְהִי כִּשְׁמֹעַ אֱלִישָׁע אִישׁ הָאֱלֹהִים כִּי קָרַע מֶלֶךְ יִשְׂרָאֵל אֶת בְּגָדָיו וַיִּשְׁלַח אֶל הַמֶּלֶךְ לֵאמֹר לָמָּה קָרַעְתָּ בְּגָדֶיךָ", translit:"vaihi kișmoa elișa iș haelohim ki kara meleh israēl et begadaiv vaișlah el hameleh lēmor lama karata begadeha", strong:"H1961", pos:"verb, qal imperfect consecutiv + verb, qal infinitiv + nume propriu + substantiv construct + substantiv + conjuncție + verb, qal perfect + substantiv construct + nume propriu + marcă a complementului direct + substantiv construct + sufix + verb, qal imperfect consecutiv + prepoziție + substantiv + verb, qal infinitiv + particulă interogativă + verb, qal perfect + substantiv construct + sufix", def_ro:"și a fost, când a auzit Elișa, omul lui Dumnezeu, că și-a sfâșiat regele Israelului veșmintele, a trimis la rege, spunând: pentru ce ți-ai sfâșiat veșmintele?", dict_ro:"Metzudat David explică faptul că Elișa trimite acest mesaj nu de dragul cinstei lui, ci pentru sfințirea Numelui lui Dumnezeu — ca regele și toți ceilalți să știe că există cu adevărat un profet în Israel."}],
  [" Dă-i voie să vină la mine și va ști că există", {heb:"יָבֹא נָא אֵלַי וְיֵדַע כִּי יֵשׁ", translit:"iavo na ēlai veiēda ki iēș", strong:"H935", pos:"verb, qal jusiv + interjecție + prepoziție + sufix + verb, qal jusiv + conjuncție + particulă demonstrativă", def_ro:"să vină, te rog, la mine, și va ști că există.", dict_ro:"Elișa invită direct, calm, fără a cere nimic de la rege — contrastul dintre teama regelui și siguranța profetului e deliberat, pregătind următoarea scenă cu Naaman."}],
  [" în Israel.”", {heb:"בְּיִשְׂרָאֵל", translit:"beisraēl", strong:"H3478", pos:"nume propriu", def_ro:"în Israel.", dict_ro:"Afirmarea existenței unui profet autentic «în Israel» e rostită special pentru a contracara teama regelui că nimeni, nici chiar un om, n-ar putea vindeca o boală ca lepra."}]
]},
{v:"5:9", newTags:[
  ["Naaman a venit cu caii lui și carul lui și a stat", {heb:"וַיָּבֹא נַעֲמָן בְּסוּסָיו וּבְרִכְבּוֹ וַיַּעֲמֹד", translit:"vaiavo naaman besusaiv uvrihbo vaiaamod", strong:"H935", pos:"verb, qal imperfect consecutiv + nume propriu + substantiv construct + sufix + substantiv construct + sufix + verb, qal imperfect consecutiv", def_ro:"și a venit Naaman cu caii lui și carul lui și a stat.", dict_ro:"Radak notează o diferență între scrisul textului («besuso», «cu calul lui», singular) și citirea tradițională («besusav», plural) — scrisul arată că el însuși călărea pe calul lui, iar citirea include alaiul care venea cu el."}],
  [" lui Elișa.", {heb:"הַבַּיִת לֶאֱלִישָׁע", translit:"habait leelișa", strong:"H1004", pos:"substantiv + nume propriu", def_ro:"[la] casa lui Elișa.", dict_ro:"Naaman se oprește exact la ușa casei profetului — gestul stabilește scena așteptării, pe care Elișa o va surprinde trimițând doar un sol, fără a ieși el însuși."}]
]},
{v:"5:10", newTags:[
  ["Elișa a trimis la el un sol, spunând: „Mergi și cufundă-te", {heb:"וַיִּשְׁלַח אֵלָיו אֱלִישָׁע מַלְאָךְ לֵאמֹר הָלוֹךְ וְרָחַצְתָּ", translit:"vaișlah ēlaiv elișa malah lēmor haloh verahațta", strong:"H7971", pos:"verb, qal imperfect consecutiv + prepoziție + sufix + nume propriu + substantiv + verb, qal infinitiv + verb, qal infinitiv absolut + verb, qal perfect consecutiv", def_ro:"și a trimis la el Elișa un sol, spunând: du-te și te scaldă.", dict_ro:"Faptul că Elișa trimite doar un sol, fără să iasă personal să-l întâmpine pe marele general, pregătește exact jignirea pe care Naaman o va simți la versetul următor."}],
  [" în Iordan și carnea ta își va reveni și vei fi curățit.”", {heb:"פְּעָמִים בַּיַּרְדֵּן וְיָשֹׁב בְּשָׂרְךָ לְךָ וּטְהָר", translit:"peamim baiardēn veiașov besarha leha uthar", strong:"H6471", pos:"substantiv + nume propriu + verb, qal imperfect + substantiv construct + sufix + prepoziție + sufix + verb, qal imperativ", def_ro:"de [șapte] ori în Iordan, și îți va reveni carnea ta, și fii curat.", dict_ro:"Metzudat David explică faptul că din cauza leprei carnea lui Naaman slăbise, iar promisiunea e dublă: refacerea trupului și curățirea de boală, ambele printr-un gest simplu — scufundarea de șapte ori."}]
]},
{v:"5:11", newTags:[
  ["Naaman s-a mâniat și a plecat; și a spus: „Iată, mi-am spus că va ieși negreșit în întâmpinarea mea și că va sta în picioare și va chema în numele DOMNULUI, Dumnezeului lui, și își va ridica mâinile către", {heb:"וַיִּקְצֹף נַעֲמָן וַיֵּלַךְ וַיֹּאמֶר הִנֵּה אָמַרְתִּי אֵלַי יֵצֵא יָצוֹא וְעָמַד וְקָרָא בְּשֵׁם יְהוָה אֱלֹהָיו וְהֵנִיף יָדוֹ אֶל", translit:"vaikțof naaman vaiēlah vaiomer hinē amarti ēlai iēțē iațo veamad vekara beșēm Adonai elohaiv vehēnif iado el", strong:"H7107", pos:"verb, qal imperfect consecutiv + nume propriu + verb, qal imperfect consecutiv + verb, qal imperfect consecutiv + particulă demonstrativă + verb, qal perfect + prepoziție + sufix + verb, qal imperfect + verb, qal infinitiv absolut + verb, qal perfect consecutiv + verb, qal perfect consecutiv + substantiv construct + nume propriu + substantiv construct + sufix + verb, hifil perfect consecutiv + substantiv construct + sufix + prepoziție", def_ro:"și s-a mâniat Naaman și a plecat, și a spus: iată, îmi spuneam că negreșit va ieși și va sta și va chema în numele DOMNULUI, Dumnezeului lui, și își va flutura mâna către.", dict_ro:"Metzudat David explică faptul că Naaman se aștepta la onoruri potrivite rangului său — profetul să iasă în întâmpinarea lui, să stea în picioare în semn de respect — și la o vindecare prin gest vizibil, nu printr-o poruncă transmisă de la distanță."}],
  [" și leprosul se va vindeca.", {heb:"וְאָסַף הַמְּצֹרָע", translit:"veasaf hamțora", strong:"H622", pos:"verb, qal perfect consecutiv + verb, pual participiu pasiv", def_ro:"și va fi adunat leprosul.", dict_ro:"Verbul «adunare» (asaf) revine aici exact ca în v.3 și v.6 — vindecarea leprei e descrisă sistematic prin ideea de „re-adunare” în comunitate, nu doar ca o simplă curățire fizică."}]
]},
{v:"5:12", newTags:[
  ["Nu sunt oare", {heb:"הֲלֹא טוֹב", translit:"halo tov", strong:"H3808", pos:"particulă negativă + adjectiv", def_ro:"nu [sunt] bune oare.", dict_ro:"Întrebarea retorică a lui Naaman pune râurile cunoscute ale patriei sale în competiție directă cu Iordanul, pe care-l disprețuiește ca simplu leac natural."}],
  [" și Farpar, râurile Damascului, mai bune decât toate apele din Israel? Mă voi scălda în ele și voi fi curățit.” Și s-a întors și a plecat mânios.", {heb:"וּפַרְפַּר נַהֲרוֹת דַּמֶּשֶׂק מִכֹּל מֵימֵי יִשְׂרָאֵל הֲלֹא אֶרְחַץ בָּהֶם וְטָהָרְתִּי וַיִּפֶן וַיֵּלֶךְ בְּחֵמָה", translit:"ufarpar naharot damesek mikol mēmē israēl halo erhaț bahem vetaharti vaifen vaiēleh behēma", strong:"H6554", pos:"nume propriu + substantiv plural construct + nume propriu + substantiv construct + substantiv plural construct + nume propriu + particulă negativă + verb, qal imperfect + prepoziție + sufix + verb, qal perfect + verb, qal imperfect consecutiv + verb, qal imperfect consecutiv + substantiv", def_ro:"și Farpar, râurile Damascului, decât toate apele Israelului? Nu mă voi scălda în ele și voi fi curat? Și s-a întors și a plecat cu mânie.", dict_ro:"Metzudat David explică faptul că raționamentul lui Naaman e greșit: dacă râurile Damascului, în care se scaldă mereu, nu l-au curățit vreodată de lepră, nici apele Iordanului n-ar avea de ce să-l curețe — nefiind vorba de un leac natural, ci de o minune legată de ascultare."}]
]},
{v:"5:13", newTags:[
  ["Dar slujitorii lui s-au apropiat și i-au vorbit, spunând: „", {heb:"וַיִּגְּשׁוּ עֲבָדָיו וַיְדַבְּרוּ אֵלָיו וַיֹּאמְרוּ", translit:"vaigșu avadaiv vaidabru ēlaiv vaiomru", strong:"H5066", pos:"verb, qal imperfect consecutiv + substantiv construct + sufix + verb, piel imperfect consecutiv + prepoziție + sufix + verb, qal imperfect consecutiv", def_ro:"și s-au apropiat slujitorii lui și i-au vorbit, și au spus.", dict_ro:"Slujitorii intervin cu înțelepciune practică, descâlcind orgoliul rănit al stăpânului lor printr-un argument simplu de logică, nu prin contestarea mâniei lui."}],
  [", dacă profetul îți spunea un lucru greu, oare nu l-ai fi făcut? [Cu atât mai mult acum,] când ți-a spus doar «cufundă-te și vei fi curățit.»”", {heb:"דָּבָר גָּדוֹל הַנָּבִיא דִּבֶּר אֵלֶיךָ הֲלוֹא תַעֲשֶׂה וְאַף כִּי אָמַר אֵלֶיךָ רְחַץ וּטְהָר", translit:"davar gadol hanavi diber ēleha halo taase veaf ki amar ēleha rehaț uthar", strong:"H1697", pos:"substantiv + adjectiv + substantiv + verb, piel perfect + prepoziție + sufix + particulă negativă + verb, qal imperfect + adverb + conjuncție + verb, qal perfect + prepoziție + sufix + verb, qal imperativ + verb, qal imperativ", def_ro:"un lucru mare dacă ți-ar fi spus profetul, n-ai face? Și cu atât mai mult când ți-a spus: scaldă-te și fii curat.", dict_ro:"Rashi explică acest argument ca o deducție de la mai greu la mai ușor (kal vahomer): dacă David ar fi ascultat o poruncă grea, cu atât mai mult trebuie ascultată una ușoară ca aceasta."}]
]},
{v:"5:14", newTags:[
  ["Așa că el a coborât și", {heb:"וַיֵּרֶד", translit:"vaiēred", strong:"H3381", pos:"verb, qal imperfect consecutiv", def_ro:"și a coborât.", dict_ro:"Supunerea lui Naaman, în urma argumentului slujitorilor, marchează momentul de cotitură al întregii povestiri — mândria cedează în fața ascultării simple."}],
  [" de șapte ori în Iordan, după vorba omului lui Dumnezeu, și carnea sa a întinerit și a fost curățit.", {heb:"בַּיַּרְדֵּן שֶׁבַע פְּעָמִים כִּדְבַר אִישׁ הָאֱלֹהִים וַיָּשָׁב בְּשָׂרוֹ כִּבְשַׂר נַעַר קָטֹן וַיִּטְהָר", translit:"baiardēn șeva peamim kidvar iș haelohim vaiașav besaro kivsar naar katon vaithar", strong:"H3383", pos:"nume propriu + numeral + substantiv + substantiv construct + substantiv construct + substantiv + verb, qal imperfect consecutiv + substantiv construct + sufix + substantiv construct + substantiv + adjectiv + verb, qal imperfect consecutiv", def_ro:"în Iordan, de șapte ori, după vorba omului lui Dumnezeu, și i-a revenit carnea ca și carnea unui copil mic, și a fost curățit.", dict_ro:"Metzudat David explică faptul că expresia «ca trupul unui copil mic» descrie pielea lui Naaman devenind curată și strălucitoare — vindecarea e vizibilă, completă, nu simbolică."}]
]},
{v:"5:15", newTags:[
  ["El s-a întors la omul lui Dumnezeu, el și întregul său alai. A venit la el și a stat înaintea lui și a spus: „Iată, acum știu că nu este Dumnezeu în toată lumea, în afară de în Israel; primește așadar", {heb:"וַיָּשָׁב אֶל אִישׁ הָאֱלֹהִים הוּא וְכָל מַחֲנֵהוּ וַיָּבֹא וַיַּעֲמֹד לְפָנָיו וַיֹּאמֶר הִנֵּה נָא יָדַעְתִּי כִּי אֵין אֱלֹהִים בְּכָל הָאָרֶץ כִּי אִם בְּיִשְׂרָאֵל וְעַתָּה קַח נָא", translit:"vaiașav el iș haelohim hu vehal mahanēhu vaiavo vaiaamod lefanaiv vaiomer hinē na iadati ki ēn elohim behal haareț ki im beisraēl veata kah na", strong:"H7725", pos:"verb, qal imperfect consecutiv + prepoziție + substantiv construct + substantiv + pronume personal + substantiv construct + sufix + verb, qal imperfect consecutiv + verb, qal imperfect consecutiv + substantiv construct + sufix + verb, qal imperfect consecutiv + particulă demonstrativă + interjecție + verb, qal perfect + conjuncție + particulă negativă + substantiv + substantiv construct + substantiv + conjuncție + conjuncție + nume propriu + adverb + verb, qal imperativ + interjecție", def_ro:"și s-a întors la omul lui Dumnezeu, el și toată tabăra lui, și a venit și a stat înaintea lui și a spus: iată, acum știu că nu este Dumnezeu în tot pământul, decât în Israel; și acum, primește, te rog.", dict_ro:"Talmudul Bavli (Ghitin 57b) îl identifică pe Naaman ca «ger toșav» — un neevreu care păzește cele șapte porunci ale urmașilor lui Noe — spre deosebire de Nebuzaradan, care avea să devină un convertit deplin."}],
  [" de la slujitorul tău.”", {heb:"מֵאֵת עַבְדֶּךָ", translit:"mēēt avdeha", strong:"H854", pos:"prepoziție + substantiv construct + sufix", def_ro:"de la slujitorul tău.", dict_ro:"Rashi explică «prinosul» (beraha) ca un dar de pace, oferit la salut, precum un ucenic sau un slujitor ar da stăpânului său — gestul lui Naaman e unul de recunoștință, nu de plată."}]
]},
{v:"5:16", newTags:[
  ["Dar [Elișa] a răspuns: „Pe viața DOMNULUI înaintea Căruia am stat, nu voi primi.” El", {heb:"וַיֹּאמֶר חַי יְהוָה אֲשֶׁר עָמַדְתִּי לְפָנָיו אִם אֶקָּח", translit:"vaiomer hai Adonai așer amadti lefanaiv im ekah", strong:"H559", pos:"verb, qal imperfect consecutiv + adjectiv + nume propriu + particulă relativă + verb, qal perfect + substantiv construct + sufix + conjuncție + verb, qal imperfect", def_ro:"și a spus: pe viața DOMNULUI, înaintea Căruia am stat, nu voi lua.", dict_ro:"Rashi explică refuzul lui Elișa prin faptul că printre darurile oferite erau, probabil, bani legați cumva de idolatrie — profetul nu putea accepta un dar din averea unui general al unei țări idolatre, oricât de recunoscător ar fi fost acesta."}],
  [" față de el să primească, dar [profetul] a refuzat.", {heb:"לָקַחַת וַיְמָאֵן", translit:"lakahat vaimaēn", strong:"H3947", pos:"verb, qal infinitiv + verb, piel imperfect consecutiv", def_ro:"să ia; și a refuzat.", dict_ro:"Metzudat David explică faptul că «înaintea Căruia am stat» se referă la obiceiul lui Elișa de a sta în rugăciune înaintea DOMNULUI — refuzul darului e un jurământ legat direct de această relație personală cu Dumnezeu."}]
]},
{v:"5:17", newTags:[
  ["Naaman a spus: „Măcar dă-i voie slujitorului tău să ia doi măgari încărcați cu", {heb:"וַיֹּאמֶר נַעֲמָן וָלֹא יֻתַּן נָא לְעַבְדְּךָ מַשָּׂא צֶמֶד פְּרָדִים", translit:"vaiomer naaman valo iutan na leavdeha masa țemed peradim", strong:"H559", pos:"verb, qal imperfect consecutiv + nume propriu + particulă negativă + verb, hofal jusiv + interjecție + substantiv construct + sufix + substantiv construct + substantiv construct + substantiv", def_ro:"și a spus Naaman: o, de s-ar da, te rog, slujitorului tău o încărcătură cât duc doi catâri de.", dict_ro:"Rashi explică «valo» ca o expresie de rugăminte — «o, de-ar fi așa!» — Naaman cere permisiunea explicită a profetului, nu voind să ia nimic fără încuviințarea lui."}],
  [", căci slujitorul tău nu va mai aduce niciodată vreo ardere-de-tot sau vreo jertfă de pace altor dumnezei, ci numai DOMNULUI.", {heb:"כִּי לוֹא יַעֲשֶׂה עוֹד עַבְדְּךָ עֹלָה וָזֶבַח לֵאלֹהִים אֲחֵרִים כִּי אִם לַיהוָה", translit:"ki loa iaase od avdeha ola vazevah lēlohim ahērim ki im la'Adonai", strong:"H3588", pos:"conjuncție + particulă negativă + verb, qal imperfect + adverb + substantiv construct + sufix + substantiv + substantiv + prepoziție + substantiv + adjectiv + conjuncție + conjuncție + nume propriu", def_ro:"căci nu va mai face slujitorul tău ardere-de-tot sau jertfă altor dumnezei, decât numai DOMNULUI.", dict_ro:"Rashi explică faptul că pământul cerut e din Țara Israelului, socotit sfânt, pe care Naaman intenționează să-l ducă în patria lui și să construiască din el un altar pentru DOMNUL — o formă de a continua, pe pământ străin, închinarea descoperită aici."}]
]},
{v:"5:18", newTags:[
  ["Și fie ca DOMNUL să-l ierte pe slujitorul tău în legătură cu aceasta: când stăpânul meu vine la", {heb:"לַדָּבָר הַזֶּה יִסְלַח יְהוָה לְעַבְדֶּךָ בְּבוֹא אֲדֹנִי בֵית", translit:"ladavar haze islah Adonai leavdeha bevo adoni vēt", strong:"H1697", pos:"substantiv construct + pronume demonstrativ + verb, qal imperfect + nume propriu + substantiv construct + sufix + verb, qal infinitiv + substantiv construct + sufix + substantiv construct", def_ro:"pentru lucrul acesta, să ierte DOMNUL pe slujitorul tău: când vine stăpânul meu la casa.", dict_ro:"Metzudat David explică faptul că Naaman cere mijlocirea profetului înaintea DOMNULUI pentru acest compromis viitor, nu pentru idolatria cultivată activ, ci pentru gestul involuntar la care va fi forțat de funcția sa."}],
  [" să se prosterneze acolo, el se sprijină de mâna mea, așa că trebuie [și eu] să mă înclin în templul din Rimon", {heb:"לְהִשְׁתַּחֲוֺת שָׁמָּה וְהוּא נִשְׁעָן עַל יָדִי וְהִשְׁתַּחֲוֵיתִי בֵּית רִמֹּן", translit:"lehiștahavot șama vehu nișan al iadi vehiștahavēti bēt rimon", strong:"H7812", pos:"verb, hitpael infinitiv + adverb + pronume personal + verb, nifal participiu + prepoziție + substantiv construct + sufix + verb, hiștafel perfect consecutiv + substantiv construct + nume propriu", def_ro:"să se prosterneze acolo, și el se sprijină pe mâna mea, și mă voi prosterna [și eu] în templul lui Rimon.", dict_ro:"Rashi explică «Rimon» ca numele unei zeități idolatre, și precizează că Naaman se închină «împotriva voii lui», doar pentru că stăpânul lui se sprijină de mâna lui când intră să se prosterneze."}],
  [" – DOMNUL să-i ierte slujitorului tău acest lucru.”", {heb:"בְּהִשְׁתַּחֲוָיָתִי בֵּית רִמֹּן יִסְלַח יְהוָה לְעַבְדְּךָ בַּדָּבָר הַזֶּה", translit:"behiștahavaiati bēt rimon islah Adonai leavdeha badavar haze", strong:"H7812", pos:"verb, hiștafel infinitiv + sufix + substantiv construct + nume propriu + verb, qal jusiv + nume propriu + substantiv construct + sufix + substantiv + pronume demonstrativ", def_ro:"la prosternarea mea în templul lui Rimon, să ierte DOMNUL pe slujitorul tău pentru lucrul acesta.", dict_ro:"Metzudat David explică faptul că Naaman cere o iertare specifică pentru acel moment anume de închinare forțată — un compromis onest recunoscut deschis, nu ascuns, înaintea profetului."}]
]},
{v:"5:19", newTags:[
  ["[Elișa] i-a spus: „Mergi în pace” și el s-a dus de la el", {heb:"וַיֹּאמֶר לוֹ לֵךְ לְשָׁלוֹם וַיֵּלֶךְ מֵאִתּוֹ", translit:"vaiomer lo lēh leșalom vaiēleh mēito", strong:"H559", pos:"verb, qal imperfect consecutiv + prepoziție + sufix + verb, qal imperativ + substantiv + verb, qal imperfect consecutiv + prepoziție + sufix", def_ro:"și i-a spus: mergi în pace; și a plecat de la el.", dict_ro:"Rashi explică «kivrat eretz» ca numele unei măsuri de pământ, folosită identic la Isaia 5:10 — Elișa îl lasă pe Naaman să plece fără altă discuție, închiderea senină a episodului."}]
]}
];
