module.exports = [
{v:"32:6", newTags:[
  ["Ieremia a spus: „", {heb:"וַיֹּאמֶר יִרְמְיָהוּ הָיָה", translit:"vaiomer irmeiahu haia", strong:"H559", pos:"verb, qal imperfect consecutiv + nume propriu + verb, qal perfect", def_ro:"și a spus Ieremia: a fost.", dict_ro:"Rashi explică faptul că Ieremia nu i-a spus aceasta lui Țedekia — Scriptura a explicat mai întâi de ce l-a închis regele, apoi s-a întors la cuvintele de la început, ca să arate care a fost cuvântul ce a venit la profet."}],
  [" a venit la mine, spunând:", {heb:"יְהוָה אֵלַי לֵאמֹר", translit:"Adonai ēlai lēmor", strong:"H3068", pos:"nume propriu + prepoziție + sufix + verb, qal infinitiv", def_ro:"DOMNUL, la mine, spunând.", dict_ro:"Metzudat David explică faptul că versetul se întoarce la cele spuse mai sus, ca să arate că acesta este cuvântul care a venit la Ieremia în anul al zecelea — după ce s-au lungit cuvintele despre asediu și despre pricina închiderii lui."}]
]},
{v:"32:7", newTags:[
  ["«Iată, Hanamel, fiul unchiului tău Șalum, vine la tine să spună: ‘Cumpără pentru tine ogorul meu din Anatot, căci al tău este", {heb:"הִנֵּה חֲנַמְאֵל בֶּן שַׁלֻּם דֹּדְךָ בָּא אֵלֶיךָ לֵאמֹר קְנֵה לְךָ אֶת שָׂדִי אֲשֶׁר בַּעֲנָתוֹת כִּי לְךָ מִשְׁפַּט", translit:"hinē hanamēl ben șalum dodha ba ēleha lēmor kenē leha et sadi așer baanatot ki leha mișpat", strong:"H2009", pos:"particulă demonstrativă + nume propriu + substantiv construct + nume propriu + substantiv construct + sufix + verb, qal participiu + prepoziție + sufix + verb, qal infinitiv + verb, qal imperativ + prepoziție + sufix + marcă a complementului direct + substantiv construct + sufix + particulă relativă + nume propriu + conjuncție + prepoziție + sufix + substantiv construct", def_ro:"iată, Hanamel, fiul lui Șalum, unchiul tău, vine la tine, spunând: cumpără-ți ogorul meu care este în Anatot, căci al tău este dreptul.", dict_ro:"Metzudat David explică faptul că, fiind rudă apropiată, dreptul de răscumpărare îi revenea direct lui Ieremia, ca ogorul să nu ajungă în mâinile altora — aceeași rânduială aplicată și lui Boaz la Rut 4:3-4."}],
  [" ca să cumperi.’»", {heb:"לִקְנוֹת", translit:"liknot", strong:"H7069", pos:"verb, qal infinitiv", def_ro:"să cumperi.", dict_ro:"Radak explică faptul că, dacă Hanamel ar fi vândut ogorul altcuiva, Ieremia ar fi avut doar dreptul de a-l răscumpăra din mâna cumpărătorului — fiind rudă directă, e cu atât mai vrednic să-l cumpere chiar de la el."}]
]},
{v:"32:8", newTags:[
  ["Hanamel, vărul meu, a venit la mine, după rostirea DOMNULUI, în curtea temniței, și mi-a spus: «Te rog, cumpără-ți ogorul meu din Anatot, care este în ținutul lui Beniamin, căci al tău este", {heb:"וַיָּבֹא אֵלַי חֲנַמְאֵל בֶּן דֹּדִי כִּדְבַר יְהוָה אֶל חֲצַר הַמַּטָּרָה וַיֹּאמֶר אֵלַי קְנֵה נָא אֶת שָׂדִי אֲשֶׁר בַּעֲנָתוֹת אֲשֶׁר בְּאֶרֶץ בִּנְיָמִין כִּי לְךָ מִשְׁפַּט", translit:"vaiavo ēlai hanamēl ben dodi kidvar Adonai el hațar hamatara vaiomer ēlai kenē na et sadi așer baanatot așer beereț biniamin ki leha mișpat", strong:"H935", pos:"verb, qal imperfect consecutiv + prepoziție + sufix + nume propriu + substantiv construct + substantiv construct + sufix + substantiv construct + nume propriu + prepoziție + substantiv construct + substantiv + verb, qal imperfect consecutiv + prepoziție + sufix + verb, qal imperativ + interjecție + marcă a complementului direct + substantiv construct + sufix + particulă relativă + nume propriu + particulă relativă + substantiv construct + nume propriu + conjuncție + prepoziție + sufix + substantiv construct", def_ro:"și a venit la mine Hanamel, fiul unchiului meu, după cuvântul DOMNULUI, la curtea temniței, și mi-a spus: cumpără-ți, te rog, ogorul meu care este în Anatot, care este în ținutul lui Beniamin, căci al tău este dreptul.", dict_ro:"Radak explică faptul că Ieremia a cunoscut autenticitatea profeției exact pentru că ea s-a împlinit cu precizie — dacă n-ar fi fost de la DOMNUL, de ce i-ar fi fost vestit dinainte că Hanamel va veni să-i vândă ogorul?"}],
  [" și al tău este [dreptul de] răscumpărare. Cumpără-l pentru tine!» Și am cunoscut că fusese cuvântul DOMNULUI.", {heb:"וּלְךָ הַגְּאֻלָּה קְנֵה לָךְ וָאֵדַע כִּי דְבַר יְהוָה הוּא", translit:"ulha hagula kenē lah vaēda ki devar Adonai hu", strong:"H3605", pos:"prepoziție + sufix + substantiv + verb, qal imperativ + prepoziție + sufix + verb, qal imperfect consecutiv + conjuncție + substantiv construct + nume propriu + pronume personal", def_ro:"și al tău e dreptul de răscumpărare; cumpără-l pentru tine. Și am cunoscut că este cuvântul DOMNULUI.", dict_ro:"Metzudat David explică faptul că Ieremia a cunoscut în mintea lui că aceasta este cu adevărat porunca DOMNULUI de a cumpăra ogorul — nu doar o coincidență, ci confirmarea exactă a profeției primite dinainte."}]
]},
{v:"32:9", newTags:[
  ["Așa că am cumpărat ogorul care era în Anatot, de la Hanamel, vărul meu, și am cântărit pentru el argintul,", {heb:"וָאֶקְנֶה אֶת הַשָּׂדֶה מֵאֵת חֲנַמְאֵל בֶּן דֹּדִי אֲשֶׁר בַּעֲנָתוֹת וָאֶשְׁקֲלָה לּוֹ אֶת הַכֶּסֶף", translit:"vaekne et hasade mēēt hanamēl ben dodi așer baanatot vaeșkala lo et hakesef", strong:"H7069", pos:"verb, qal imperfect consecutiv + marcă a complementului direct + substantiv + prepoziție + nume propriu + substantiv construct + sufix + particulă relativă + nume propriu + verb, qal imperfect consecutiv + sufix + prepoziție + sufix + marcă a complementului direct + substantiv", def_ro:"și am cumpărat ogorul de la Hanamel, fiul unchiului meu, care este în Anatot, și i-am cântărit argintul.", dict_ro:"Metzudat David explică faptul că siclii sunt numiți de înțelepți mine, iar «zece de argint» sunt zece sela, potrivit traducerii lui Ionatan — o unitate monetară distinctă de siclu, confirmată și de Radak."}],
  [" și zece selaim de argint.", {heb:"וַעֲשָׂרָה הַכָּסֶף", translit:"vaasara hakasef", strong:"H6235", pos:"numeral + substantiv", def_ro:"și zece, argintul.", dict_ro:"Radak confirmă aceeași interpretare: șapte sicli și zece de argint reprezintă șapte mine și zece sela de argint, potrivit traducerii lui Ionatan Ben Uziel."}]
]},
{v:"32:10", newTags:[
  ["Am scris actul și", {heb:"וָאֶכְתֹּב בַּסֵּפֶר", translit:"vaehtov basēfer", strong:"H3789", pos:"verb, qal imperfect consecutiv + substantiv", def_ro:"și am scris în act.", dict_ro:"Metzudat David explică faptul că Ieremia a poruncit să se scrie în act detaliile cumpărării, apoi a poruncit stăpânului ogorului să-și semneze numele pe actul de cumpărare — pecetluirea fiind semnătura proprietarului anterior."}],
  [", și am numit martori și am cântărit argintul în balanță.", {heb:"וָאָעֵד עֵדִים וָאֶשְׁקֹל הַכֶּסֶף בְּמֹאזְנָיִם", translit:"vaaēd ēdim vaeșkol hakesef bemoznaim", strong:"H5749", pos:"verb, hifil imperfect consecutiv + substantiv plural + verb, qal imperfect consecutiv + substantiv + substantiv dual", def_ro:"și am chemat martori, și am cântărit argintul în balanță.", dict_ro:"Radak explică faptul că, deși mai sus se spusese deja «i-am cântărit», acum se precizează că cântărirea s-a făcut înaintea martorilor, cu greutate dreaptă, ca să nu existe vreo contestație ulterioară asupra exactității prețului."}]
]},
{v:"32:11", newTags:[
  ["Și am luat actul de vânzare, cel pecetluit, [scris] conform poruncii și decretelor, și", {heb:"וָאֶקַּח אֶת סֵפֶר הַמִּקְנָה אֶת הֶחָתוּם הַמִּצְוָה וְהַחֻקִּים וְאֶת", translit:"vaekah et sēfer hamikna et hehatum hamițva vehahukim veet", strong:"H3947", pos:"verb, qal imperfect consecutiv + marcă a complementului direct + substantiv construct + substantiv + marcă a complementului direct + verb, qal participiu pasiv + substantiv + substantiv plural + marcă a complementului direct", def_ro:"și am luat actul cumpărării, cel pecetluit, [după] porunca și decretele, și.", dict_ro:"Talmudul Bavli (Bava Batra 160b) explică, prin cuvintele lui Rafram, că acest verset e temeiul pentru cele două feluri de acte legale: cel «obișnuit» cu doi martori și cel «legat» cu trei martori — «porunca și decretele» fiind lucrurile care le deosebesc."}]
]},
{v:"32:12", newTags:[
  ["Și am dat actul de vânzare lui", {heb:"וָאֶתֵּן אֶת הַסֵּפֶר הַמִּקְנָה אֶל", translit:"vaetēn et hasēfer hamikna el", strong:"H5414", pos:"verb, qal imperfect consecutiv + marcă a complementului direct + substantiv + substantiv + prepoziție", def_ro:"și am dat actul cumpărării lui.", dict_ro:"Metzudat David precizează că acest Baruh e identificat după dubla sa genealogie, fiul lui Neria, fiul lui Mahseia — detaliu care confirmă identitatea precisă a scribului de încredere al lui Ieremia."}],
  [", fiul lui Neria, fiul lui Mahseia, sub ochii lui Hanamel, [fiul] unchiului meu, și sub ochii martorilor care semnaseră actul de vânzare, sub ochii tuturor iudeilor care stăteau în curtea temniței.", {heb:"בֶּן נֵרִיָּה בֶּן מַחְסֵיָה לְעֵינֵי חֲנַמְאֵל דֹּדִי וּלְעֵינֵי הָעֵדִים הַכֹּתְבִים בְּסֵפֶר הַמִּקְנָה לְעֵינֵי כָּל הַיְּהוּדִים הַיֹּשְׁבִים בַּחֲצַר הַמַּטָּרָה", translit:"ben nēria ben mahsēia leēnē hanamēl dodi ulēnē haēdim hakotvim besēfer hamikna leēnē kal haihudim haioșvim bahațar hamatara", strong:"H1121", pos:"substantiv construct + nume propriu + substantiv construct + nume propriu + substantiv dual construct + nume propriu + substantiv construct + sufix + substantiv dual construct + substantiv plural + verb, qal participiu + substantiv construct + substantiv + substantiv dual construct + substantiv construct + nume de neam + verb, qal participiu + substantiv construct + substantiv", def_ro:"fiul lui Neria, fiul lui Mahseia, sub ochii lui Hanamel, unchiul meu, și sub ochii martorilor care scriau în actul cumpărării, sub ochii tuturor iudeilor care locuiau în curtea temniței.", dict_ro:"Rashi observă o dificultate: până aici Hanamel fusese numit «fiul unchiului meu», iar aici e numit «unchiul meu» — o inconsecvență pe care Radak o rezolvă socotind că e vorba de două persoane diferite cu același nume, sau de o expresie convențională echivalentă."}]
]},
{v:"32:13", newTags:[
  [" pe Baruh sub ochii lor, spunând:", {heb:"אֶת בָּרוּךְ לְעֵינֵיהֶם לֵאמֹר", translit:"et baruh leēnēhem lēmor", strong:"H853", pos:"marcă a complementului direct + nume propriu + substantiv dual construct + sufix + verb, qal infinitiv", def_ro:"pe Baruh, sub ochii lor, spunând.", dict_ro:"Instruirea publică a lui Baruh, sub ochii tuturor martorilor, confirmă din nou grija lui Ieremia pentru transparența deplină a întregii tranzacții, exact ca la scrierea și pecetluirea actului."}]
]},
{v:"32:14", newTags:[
  ["«Așa a spus DOMNUL Oștirilor, Dumnezeul lui Israel: ‘Ia aceste acte, actul acesta de vânzare și pe cel pecetluit și actul acesta nepecetluit, și pune-le într-un", {heb:"כֹּה אָמַר יְהוָה צְבָאוֹת אֱלֹהֵי יִשְׂרָאֵל לָקוֹחַ אֶת הַסְּפָרִים הָאֵלֶּה אֵת סֵפֶר הַמִּקְנָה הַזֶּה וְאֵת הֶחָתוּם וְאֵת סֵפֶר הַגָּלוּי הַזֶּה וּנְתַתָּם בִּכְלִי", translit:"ko amar Adonai țevaot elohē israēl lakoah et hasfarim haēle ēt sēfer hamikna haze veēt hehatum veēt sēfer hagalui haze untatam bihli", strong:"H3541", pos:"adverb + verb, qal perfect + nume propriu + substantiv + substantiv construct + nume propriu + verb, qal infinitiv absolut + marcă a complementului direct + substantiv plural + pronume demonstrativ + marcă a complementului direct + substantiv construct + substantiv + pronume demonstrativ + marcă a complementului direct + verb, qal participiu pasiv + marcă a complementului direct + substantiv construct + verb, qal participiu pasiv + pronume demonstrativ + verb, qal perfect consecutiv + sufix + substantiv construct", def_ro:"așa a spus DOMNUL Oștirilor, Dumnezeul lui Israel: ia actele acestea, actul acesta de cumpărare și cel pecetluit și actul acesta deschis, și pune-le într-un vas.", dict_ro:"Rashi explică faptul că întregul gest de a pune actele într-un vas, destinat să dureze, e menit să arate că DOMNUL nu le ascunde în van, de vreme ce toți merg în exil — ci exact pentru întoarcerea viitoare, precizată în versetul următor."}],
  [" ca să se păstreze vreme lungă.’", {heb:"לְמַעַן יַעַמְדוּ יָמִים רַבִּים", translit:"lemaan iaamdu iamim rabim", strong:"H4616", pos:"prepoziție + verb, qal imperfect + substantiv plural + adjectiv", def_ro:"pentru ca să rămână multe zile.", dict_ro:"Radak explică faptul că scopul exact al acestei păstrări e «până la întoarcerea exilului», când se va împlini profeția «se vor mai cumpăra case» — un semn concret al speranței date direct celor din Israel."}]
]},
{v:"32:15", newTags:[
  ["Căci așa a spus DOMNUL Oștirilor, Dumnezeul lui Israel: ‘", {heb:"כִּי כֹה אָמַר יְהוָה צְבָאוֹת אֱלֹהֵי יִשְׂרָאֵל עוֹד", translit:"ki ho amar Adonai țevaot elohē israēl od", strong:"H3588", pos:"conjuncție + adverb + verb, qal perfect + nume propriu + substantiv + substantiv construct + nume propriu + adverb", def_ro:"căci așa a spus DOMNUL Oștirilor, Dumnezeul lui Israel: din nou.", dict_ro:"Metzudat David explică faptul că întreaga cumpărare și păstrare a actelor nu e o deșertăciune, chiar dacă caldeenii vor moșteni temporar țara — intenția e un semn clar că fiii lui Israel se vor întoarce și vor cumpăra din nou case acolo."}],
  [" case, ogoare și vii pe pământul acesta.’»", {heb:"בָתִּים וְשָׂדוֹת וּכְרָמִים בָּאָרֶץ הַזֹּאת", translit:"vatim vesadot uhramim baareț hazot", strong:"H1004", pos:"substantiv plural + substantiv plural + substantiv plural + substantiv + pronume demonstrativ", def_ro:"case și ogoare și vii, pe pământul acesta.", dict_ro:"Rashi notează simplu, în puține cuvinte, esența promisiunii: «în cele din urmă se vor cumpăra case» — certitudinea restaurării, oricât de îndepărtată ar fi părut în momentul asediului."}]
]},
{v:"32:16", newTags:[
  [" DOMNULUI după ce i-am dat actul de vânzare lui Baruh, fiul lui Neria, spunând:", {heb:"אֶל יְהוָה אַחֲרֵי תִתִּי אֶת סֵפֶר הַמִּקְנָה אֶל בָּרוּךְ בֶּן נֵרִיָּה לֵאמֹר", translit:"el Adonai aharē titi et sēfer hamikna el baruh ben nēria lēmor", strong:"H413", pos:"prepoziție + nume propriu + prepoziție + verb, qal infinitiv + sufix + marcă a complementului direct + substantiv + substantiv + prepoziție + nume propriu + substantiv construct + nume propriu + verb, qal infinitiv", def_ro:"către DOMNUL, după ce am dat actul cumpărării lui Baruh, fiul lui Neria, spunând.", dict_ro:"Metzudat David explică faptul că aici se pomenește doar actul de vânzare pecetluit, pentru scurtare, deși înțelesul include și actul deschis dat anterior — detaliul important e momentul rugăciunii, imediat după finalizarea tranzacției."}]
]},
{v:"32:17", newTags:[
  ["«Vai, Stăpâne, Doamne DUMNEZEULE, iată – Tu ai făcut cerurile și pământul cu puterea Ta cea mare și cu brațul Tău cel întins,", {heb:"אֲהָהּ אֲדֹנָי יְהוִה הִנֵּה אַתָּה עָשִׂיתָ אֶת הַשָּׁמַיִם וְאֶת הָאָרֶץ בְּכֹחֲךָ הַגָּדוֹל וּבִזְרֹעֲךָ הַנְּטוּיָה לֹא", translit:"ahah adonai Adonai hinē ata asita et hașamaim veet haareț behohaha hagadol uvizroaha hantuia lo", strong:"H162", pos:"interjecție + substantiv construct + sufix + nume propriu + particulă demonstrativă + pronume personal + verb, qal perfect + marcă a complementului direct + substantiv + marcă a complementului direct + substantiv + substantiv construct + sufix + adjectiv + substantiv construct + sufix + verb, qal participiu pasiv + particulă negativă", def_ro:"vai, Stăpânul meu, DOMNUL! Iată, Tu ai făcut cerurile și pământul cu puterea Ta cea mare și cu brațul Tău cel întins; nu.", dict_ro:"Metzudat David explică faptul că strigătul «Vai» e o tânguire autentică — Ieremia era întristat și nedumerit, căutând adevărata tâlcuire a poruncii de a cumpăra un ogor exact când cetatea era aproape să cadă."}],
  [" de Tine,", {heb:"מִמְּךָ כָּל דָּבָר", translit:"mimha kal davar", strong:"H4480", pos:"prepoziție + sufix + substantiv construct + substantiv", def_ro:"de la Tine niciun lucru.", dict_ro:"Radak explică faptul că, de vreme ce DOMNUL a făcut cerurile și pământul, nimic din ce se petrece în ele nu-I poate fi ascuns — de aceea Ieremia se întreabă, în rugăciunea lui, de ce i s-a poruncit totuși să cumpere ogorul."}]
]},
{v:"32:18", newTags:[
  ["Cel care arăți milă la mii [de generații] și răsplătești păcatul părinților în sânul copiilor lor, după ei,", {heb:"עֹשֶׂה חֶסֶד לַאֲלָפִים וּמְשַׁלֵּם עֲוֺן אָבוֹת אֶל חֵיק בְּנֵיהֶם אַחֲרֵיהֶם", translit:"ose hesed laalafim umșalēm avon avot el hēk benēhem aharēhem", strong:"H6213", pos:"verb, qal participiu + substantiv + numeral + verb, piel participiu + substantiv construct + substantiv + prepoziție + substantiv construct + sufix + prepoziție + sufix", def_ro:"cel care face milă la mii, și care răsplătește vina părinților în sânul fiilor lor, după ei.", dict_ro:"Talmudul Bavli (Yoma 69b) relatează cum Ieremia a omis titlul «înfricoșător», folosit de Moise la Deuteronom 10:17, exact pentru că neamurile dansau în Templu — unde erau atunci lucrările înfricoșătoare? Bărbații Marii Adunări au explicat mai târziu că răbdarea față de cei răi e, de fapt, cea mai mare putere a DOMNULUI."}],
  [", numele Său este DOMNUL Oștirilor,", {heb:"הַגָּדוֹל הַגִּבּוֹר יְהוָה צְבָאוֹת שְׁמוֹ", translit:"hagadol hagibor Adonai țevaot șemo", strong:"H1419", pos:"adjectiv + adjectiv + nume propriu + substantiv + substantiv construct + sufix", def_ro:"cel mare, cel puternic, DOMNUL Oștirilor [este] numele Lui.", dict_ro:"Rashi explică faptul că, deși a păstrat «mare și puternic», Ieremia a omis «înfricoșător», pentru că vedea neamurile dansând chiar în Sanctuarul DOMNULUI — o observație care a declanșat o întreagă dezbatere talmudică despre atributele divine potrivite fiecărei generații."}]
]},
{v:"32:19", newTags:[
  [" și măreț în întreprindere, ai cărui ochi sunt deschiși față de toate căile oamenilor, pentru a da oricărui om după calea sa și după rodul întreprinderilor sale,", {heb:"וְרַב הָעֲלִילִיָּה אֲשֶׁר עֵינֶיךָ פְקֻחוֹת עַל כָּל דַּרְכֵי בְּנֵי אָדָם לָתֵת לְאִישׁ כִּדְרָכָיו וְכִפְרִי מַעֲלָלָיו", translit:"verav haalilia așer ēneha fekuhot al kal darhē benē adam latēt leiș kidrahaiv vehifri maalalaiv", strong:"H7227", pos:"adjectiv + substantiv + particulă relativă + substantiv dual construct + sufix + verb, qal participiu pasiv + prepoziție + substantiv construct + substantiv plural construct + substantiv plural construct + substantiv + verb, qal infinitiv + substantiv + substantiv plural construct + sufix + substantiv construct + substantiv plural construct + sufix", def_ro:"și mare în faptă, ai cărui ochi [sunt] deschiși asupra tuturor căilor fiilor omului, ca să dea fiecărui om după căile lui și după rodul faptelor lui.", dict_ro:"Metzudat David explică faptul că «rodul întreprinderilor sale» se referă la ceea ce urmează din faptele omului, chiar fără să fi fost intenția lui directă — și pentru aceasta va fi adus la judecată, nu doar pentru intenție."}]
]},
{v:"32:20", newTags:[
  ["cel care ai pus", {heb:"אֲשֶׁר שַׂמְתָּ", translit:"așer samta", strong:"H834", pos:"particulă relativă + verb, qal perfect", def_ro:"care ai pus.", dict_ro:"Rashi explică faptul că semnele și minunile n-au fost doar pentru Israel, ci deodată și pentru egipteni — același înger a slujit ca întuneric pentru egipteni și ca lumină pentru israeliți, potrivit Exod 14:20."}],
  [" în țara Egiptului, [care sunt cunoscute] până în ziua de astăzi, și în Israel și în [ochii] omului, și care Ți-ai făcut un renume până în ziua aceasta", {heb:"בְּאֶרֶץ מִצְרַיִם עַד הַיּוֹם הַזֶּה וּבְיִשְׂרָאֵל וּבָאָדָם וַתַּעֲשֶׂה לְּךָ שֵׁם כַּיּוֹם הַזֶּה", translit:"beereț mițraim ad haiom haze uvisraēl uvaadam vataase leha șēm kaiom haze", strong:"H776", pos:"substantiv construct + nume propriu + prepoziție + substantiv + pronume demonstrativ + nume propriu + substantiv + verb, qal imperfect consecutiv + prepoziție + sufix + substantiv + substantiv + pronume demonstrativ", def_ro:"în țara Egiptului, până în ziua aceasta, și în Israel și în om; și Ți-ai făcut un nume ca ziua aceasta.", dict_ro:"Radak explică faptul că aceste semne sunt cunoscute «printre oameni» chiar fără voia lor — renumele DOMNULUI nu depinde de recunoașterea voluntară, ci se impune prin însăși amploarea minunilor înfăptuite."}]
]},
{v:"32:21", newTags:[
  ["și ai scos pe poporul Tău, pe Israel, din țara Egiptului, cu semne și cu minuni, și cu mână puternică, și cu braț întins, și", {heb:"וַתֹּצֵא אֶת עַמְּךָ אֶת יִשְׂרָאֵל מֵאֶרֶץ מִצְרָיִם בְּאֹתוֹת וּבְמוֹפְתִים וּבְיָד חֲזָקָה וּבְאֶזְרוֹעַ נְטוּיָה", translit:"vatoțē et amha et israēl mēereț mițraim beotot uvmoftim uviad hazaka uvezroa netuia", strong:"H3318", pos:"verb, hifil imperfect consecutiv + marcă a complementului direct + substantiv construct + sufix + marcă a complementului direct + nume propriu + substantiv construct + nume propriu + substantiv plural + substantiv plural + substantiv construct + adjectiv + substantiv + verb, qal participiu pasiv", def_ro:"și ai scos pe poporul Tău, pe Israel, din țara Egiptului, cu semne și cu minuni, și cu mână puternică, și cu braț întins.", dict_ro:"Metzudat David compară brațul întins cu imaginea unui viteaz care își întinde mâna asupra celui cu care se luptă — un gest de putere directă, nu doar de simbolism retoric."}],
  [",", {heb:"גָּדוֹל", translit:"gadol", strong:"H1419", pos:"adjectiv", def_ro:"mare.", dict_ro:"Metzudat David explică «mare înfricoșare» prin spaima pe care DOMNUL a adus-o asupra egiptenilor — o teroare reală provocată de puterea vizibilă a minunilor."}]
]},
{v:"32:22", newTags:[
  ["și le-ai dat această țară pe care ai jurat-o strămoșilor lor să le-o dai, o țară", {heb:"וַתִּתֵּן לָהֶם אֶת הָאָרֶץ הַזֹּאת אֲשֶׁר נִשְׁבַּעְתָּ לַאֲבוֹתָם לָתֵת לָהֶם אֶרֶץ", translit:"vatitēn lahem et haareț hazot așer nișbata laavotam latēt lahem ereț", strong:"H5414", pos:"verb, qal imperfect consecutiv + prepoziție + sufix + marcă a complementului direct + substantiv + pronume demonstrativ + particulă relativă + verb, nifal perfect + substantiv plural construct + sufix + verb, qal infinitiv + prepoziție + sufix + substantiv", def_ro:"și le-ai dat lor țara aceasta, pe care ai jurat-o strămoșilor lor să le-o dai, o țară.", dict_ro:"Repetarea exactă a formulei jurământului confirmă fidelitatea DOMNULUI față de promisiunea veche făcută patriarhilor — darul țării nu e o noutate, ci împlinirea unui legământ străvechi."}],
  [".", {heb:"חָלָב וּדְבָשׁ", translit:"halav udvaș", strong:"H2461", pos:"substantiv + substantiv", def_ro:"lapte și miere.", dict_ro:"Metzudat David explică faptul că laptele picură din ugerele vitelor hrănite pe pășune grasă, iar mierea picură din curmale — o imagine a belșugului natural al țării promise."}]
]},
{v:"32:23", newTags:[
  ["Ei au venit și au luat în stăpânire [țara Canaanului], dar nu au ascultat de glasul Tău, după învățătura Ta nu au mers, tot ce le-ai poruncit să facă nu au făcut și [de aceea]", {heb:"וַיָּבֹאוּ וַיִּרְשׁוּ אֹתָהּ וְלֹא שָׁמְעוּ בְקוֹלֶךָ וּבְתוֹרָתְךָ לֹא הָלָכוּ אֵת כָּל אֲשֶׁר צִוִּיתָה לָהֶם לַעֲשׂוֹת לֹא עָשׂוּ", translit:"vaiavou vairșu otah velo șamu vekoleha uvtoratha lo halahu ēt kal așer țivita lahem laasot lo asu", strong:"H935", pos:"verb, qal imperfect consecutiv + verb, qal imperfect consecutiv + marcă a complementului direct + sufix + particulă negativă + verb, qal perfect + substantiv construct + sufix + substantiv construct + sufix + particulă negativă + verb, qal perfect + marcă a complementului direct + substantiv construct + particulă relativă + verb, piel perfect + prepoziție + sufix + verb, qal infinitiv + particulă negativă + verb, qal perfect", def_ro:"și au venit și au luat-o în stăpânire, și n-au ascultat de glasul Tău, și în învățătura Ta n-au umblat; tot ce le-ai poruncit să facă nu au făcut, și.", dict_ro:"Radak explică faptul că cuvântul «vatakre» e scris cu alef în loc de he, ca să arate că răul venit asupra lor nu este o întâmplare oarbă, ci ceva ce DOMNUL Însuși a făcut să se întâmple — nu «mikre» (soartă), ci voie dreaptă."}],
  [" tot acest rău.", {heb:"אֹתָם אֵת כָּל הָרָעָה הַזֹּאת", translit:"otam ēt kal haraa hazot", strong:"H853", pos:"marcă a complementului direct + sufix + marcă a complementului direct + substantiv construct + substantiv + pronume demonstrativ", def_ro:"pe ei, tot răul acesta.", dict_ro:"Rashi explică «ai făcut să vină asupra lor» ca pe o expresie a «întâmplării» (mikre), dar Radak nuanțează: nu e o întâmplare deplină venită de la sine, ci DOMNUL Însuși a adus-o, în dreapta Sa judecată."}]
]},
{v:"32:24", newTags:[
  ["Iată,", {heb:"הִנֵּה", translit:"hinē", strong:"H2009", pos:"particulă demonstrativă", def_ro:"iată.", dict_ro:"Radak traduce «hasolelot» ca pe un tell de țărână strâns în jurul zidului cetății, pentru ca atacatorii să se poată ridica pe el și să cucerească zidul — o tehnică de asediu confirmată prin traducerea lui Ionatan: «valurile au urcat asupra cetății»."}],
  [" au venit la oraș să-l cucerească și orașul a fost predat în mâna caldeenilor care îl atacau, din pricina sabiei, a foametei și a molimei, iar ceea ce ai spus Tu [așa] a fost și Tu vezi asta!", {heb:"בָּאוּ הָעִיר לְלָכְדָהּ וְהָעִיר נִתְּנָה בְּיַד הַכַּשְׂדִּים הַנִּלְחָמִים עָלֶיהָ מִפְּנֵי הַחֶרֶב וְהָרָעָב וְהַדָּבֶר וַאֲשֶׁר דִּבַּרְתָּ הָיָה וְהִנְּךָ רֹאֶה", translit:"bau hair lelahdah vehair nitna beiad hakasdim hanilhamim aleha mipnē haherev veharaav vehadaver vaașer dibarta haia vehinha roe", strong:"H935", pos:"verb, qal perfect + substantiv + verb, qal infinitiv + sufix + substantiv + verb, nifal perfect + substantiv construct + nume propriu + verb, nifal participiu + prepoziție + sufix + substantiv construct + substantiv + substantiv + substantiv + particulă relativă + verb, piel perfect + verb, qal perfect + interjecție + sufix + verb, qal participiu", def_ro:"au venit la cetate ca s-o cucerească, și cetatea a fost dată în mâna caldeenilor care luptă împotriva ei, din pricina sabiei și a foametei și a molimei; și ceea ce ai vorbit s-a împlinit, și iată, Tu vezi.", dict_ro:"Metzudat David explică faptul că locuitorii cetății n-au putere să-i mai împiedice pe atacatori, fiind sfârșiți de sabie, foamete și molimă — Ieremia mărturisește direct înaintea DOMNULUI că profeția rostită de mult s-a împlinit exact cum fusese vestită."}]
]},
{v:"32:25", newTags:[
  ["Și totuși, Tu mi-ai spus, Stăpâne, Doamne DUMNEZEULE: «Cumpără pentru tine cu argint un ogor și", {heb:"וְאַתָּה אָמַרְתָּ אֵלַי אֲדֹנָי יְהוִה קְנֵה לְךָ הַשָּׂדֶה בַּכֶּסֶף", translit:"veata amarta ēlai adonai Adonai kenē leha hasade bakesef", strong:"H859", pos:"pronume personal + verb, qal perfect + prepoziție + sufix + substantiv construct + sufix + nume propriu + verb, qal imperativ + prepoziție + sufix + substantiv + substantiv", def_ro:"și Tu mi-ai spus, Stăpânul meu, DOMNUL: cumpără-ți ogorul cu argint.", dict_ro:"Metzudat David explică faptul că Ieremia se întreabă nedumerit ce rost mai are cumpărarea ogorului și chemarea martorilor, după obiceiul cumpărătorilor obișnuiți, de vreme ce cetatea e deja dată în mâna caldeenilor."}],
  [" – dar orașul a fost predat caldeenilor!»”", {heb:"וְהָעִיר נִתְּנָה בְּיַד הַכַּשְׂדִּים", translit:"vehair nitna beiad hakasdim", strong:"H5892", pos:"substantiv + verb, nifal perfect + substantiv construct + nume propriu", def_ro:"și cetatea a fost dată în mâna caldeenilor.", dict_ro:"Rashi observă, scurt și direct, întrebarea implicită a lui Ieremia: «ce folos îmi mai este ogorul?» — contrastul dintre porunca divină și realitatea militară pare, pentru profet, o contradicție de neînțeles."}]
]},
{v:"32:26", newTags:[
  ["Și apoi a venit", {heb:"וַיְהִי", translit:"vaihi", strong:"H1961", pos:"verb, qal imperfect consecutiv", def_ro:"și a fost.", dict_ro:"Răspunsul DOMNULUI vine imediat după rugăciunea tulburată a lui Ieremia — profeția nu întârzie în fața nedumeririi sincere a profetului."}],
  [" la Ieremia, spunând:", {heb:"יְהוָה אֶל יִרְמְיָהוּ לֵאמֹר", translit:"Adonai el irmeiahu lēmor", strong:"H3068", pos:"nume propriu + prepoziție + nume propriu + verb, qal infinitiv", def_ro:"DOMNUL, la Ieremia, spunând.", dict_ro:"Formula standard de introducere profetică pregătește răspunsul direct al DOMNULUI, care va dezlega chiar nedumerirea exprimată în rugăciunea precedentă."}]
]},
{v:"32:27", newTags:[
  ["„Iată, Eu sunt DOMNUL,", {heb:"הִנֵּה אֲנִי יְהוָה אֱלֹהֵי", translit:"hinē ani Adonai elohē", strong:"H2009", pos:"particulă demonstrativă + pronume personal + nume propriu + substantiv plural construct", def_ro:"iată, Eu [sunt] DOMNUL, Dumnezeul.", dict_ro:"Metzudat David explică faptul că DOMNUL Se identifică aici ca Dumnezeul întregii creații, temei direct pentru întrebarea retorică ce urmează: dacă e Dumnezeul lumii, cum ar putea exista ceva care să-I fie imposibil?"}],
  [". Există oare vreun lucru ascuns de Mine?”", {heb:"הֲמִמֶּנִּי יִפָּלֵא כָּל דָּבָר", translit:"hamimeni ipalē kal davar", strong:"H4480", pos:"prepoziție + sufix + verb, nifal imperfect + substantiv construct + substantiv", def_ro:"de la Mine va fi oare ascuns vreun lucru?", dict_ro:"Radak explică faptul că răspunsul DOMNULUI confirmă explicit: nimic nu-I e ascuns, știa deja că cetatea va fi dată în mâna caldeenilor — și totuși i-a poruncit lui Ieremia să cumpere ogorul, ca mângâiere a întoarcerii viitoare din exil."}]
]}
];
