module.exports = [
{v:"16:19", newTags:[
  ["DOAMNE – Tăria mea, Cetățuia mea și", {heb:"יְהוָה עֻזִּי וּמָעֻזִּי", translit:"Adonai uzi umauzi", strong:"H3068", pos:"nume propriu + substantiv construct + sufix + substantiv construct + sufix", def_ro:"DOMNUL, tăria mea și cetățuia mea.", dict_ro:"Metzudat David explică faptul că dublarea termenilor pentru «tărie» și «cetățuie» întărește ideea: Ieremia afirmă cu putere că DOMNUL e singura lui apărare împotriva celor ce se luptă cu el."}],
  [" în ziua nenorocirii – la Tine vor veni neamuri de la marginile pământului și vor spune: „Strămoșii noștri au moștenit doar minciună, deșertăciune care nu are niciun rost.", {heb:"בְּיוֹם צָרָה אֵלֶיךָ גּוֹיִם יָבֹאוּ מֵאַפְסֵי אָרֶץ וְיֹאמְרוּ אַךְ שֶׁקֶר נָחֲלוּ אֲבוֹתֵינוּ הֶבֶל וְאֵין בָּם מוֹעִיל", translit:"beom țara ēleha goim iavou mēafsē areț veiomru ah șeker nahalu avotēnu hevel veēn bam moil", strong:"H3117", pos:"substantiv construct + substantiv + prepoziție + sufix + substantiv plural + verb, qal imperfect + adverb + substantiv + verb, qal imperfect + particulă afirmativă + substantiv + verb, qal perfect + substantiv plural construct + sufix + substantiv + particulă negativă + prepoziție + sufix + verb, hifil participiu", def_ro:"în ziua necazului, la Tine vor veni neamuri de la marginile pământului și vor spune: numai minciună au moștenit părinții noștri, deșertăciune, și nu e în ea niciun folos.", dict_ro:"Radak explică faptul că această întoarcere a neamurilor îndepărtate, care își vor mărturisi nelegiuirea idolatră, se va petrece în zilele lui Mesia — iar «au moștenit» arată că slujirea idolilor s-a transmis din generație în generație, ca o moștenire de familie."}]
]},
{v:"16:20", newTags:[
  ["Poate oare omul să-și facă", {heb:"הֲיַעֲשֶׂה לּוֹ אָדָם", translit:"haiaase lo adam", strong:"H6213", pos:"verb, qal imperfect + prepoziție + sufix + substantiv", def_ro:"oare își va face omul.", dict_ro:"Radak explică faptul că aceasta e exact mărturisirea pe care neamurile o vor face atunci când vor veni la DOMNUL: se vor uimi cum le-a putut trece prin minte o asemenea credință falsă, că lucrarea propriilor mâini ar putea fi un dumnezeu adevărat."}],
  ["? [Ce face omul] nu sunt dumnezei!”", {heb:"וְהֵמָּה לֹא אֱלֹהִים", translit:"vehēma lo elohim", strong:"H1992", pos:"pronume personal + particulă negativă + substantiv plural", def_ro:"și ei nu [sunt] dumnezei.", dict_ro:"Metzudat David explică faptul că întrebarea retorică subliniază absurditatea idolatriei: oamenii înșiși nu sunt dumnezei, deci cum ar putea lucrarea mâinilor lor să fie mai presus de ei?"}]
]},
{v:"16:21", newTags:[
  ["De aceea, iată, le vestesc de această dată, îi voi face să știe despre mâna Mea și puterea Mea; și vor cunoaște că", {heb:"לָכֵן הִנְנִי מוֹדִיעָם בַּפַּעַם הַזֹּאת אוֹדִיעֵם אֶת יָדִי וְאֶת גְּבוּרָתִי וְיָדְעוּ כִּי", translit:"lahēn hinni modiam bapaam hazot odiēm et iadi veet gevurati veiadu ki", strong:"H3651", pos:"adverb + particulă demonstrativă + sufix + verb, hifil participiu + sufix + substantiv + pronume demonstrativ + verb, hifil imperfect + sufix + marcă a complementului direct + substantiv construct + sufix + marcă a complementului direct + substantiv construct + sufix + verb, qal perfect consecutiv + conjuncție", def_ro:"de aceea, iată, le fac cunoscut de data aceasta, îi voi face să cunoască mâna Mea și puterea Mea; și vor cunoaște că.", dict_ro:"Radak explică faptul că DOMNUL se adresează exact celor care nu vor să se întoarcă de la idolatrie — de data aceasta le va face cunoscută puterea Lui prin fapte, nu doar prin cuvinte, ca să nu mai fie nedumeriți."}],
  [".", {heb:"יְהוָה", translit:"Adonai", strong:"H3068", pos:"nume propriu", def_ro:"DOMNUL.", dict_ro:"Rashi explică faptul că «numele Meu este DOMNUL» se referă, în sensul simplu al textului, la stăpânitorul și suveranul care Își împlinește întotdeauna hotărârea — identitatea divină confirmată prin acțiune, nu doar prin titlu."}]
]},
{v:"17:1", newTags:[
  ["Păcatul lui Iuda este scris cu", {heb:"חַטַּאת יְהוּדָה כְּתוּבָה בְּעֵט בַּרְזֶל", translit:"hatat iehuda ketuva beēt barzel", strong:"H2403", pos:"substantiv construct + nume propriu + verb, qal participiu pasiv + substantiv construct + substantiv", def_ro:"păcatul lui Iuda [este] scris cu condei de fier.", dict_ro:"Metzudat David leagă acest verset de cel precedent: iată, la sfârșit chiar neamurile își vor părăsi idolii, dar Iuda își păstrează încă păcatul în inimă, săpat adânc, ca scris cu condei de fier și vârf de diamant."}],
  [", cu o unghie [ca] de diamant, gravat pe tăblița inimii lor și pe coarnele altarelor lor.", {heb:"בְּצִפֹּרֶן שָׁמִיר חֲרוּשָׁה עַל לוּחַ לִבָּם וּלְקַרְנוֹת מִזְבְּחוֹתֵיכֶם", translit:"bețiporen șamir harușa al luah libam ulkarnot mizbehotēhem", strong:"H6856", pos:"substantiv construct + substantiv + verb, qal participiu pasiv + prepoziție + substantiv construct + substantiv construct + sufix + substantiv plural construct + substantiv plural construct + sufix", def_ro:"cu unghie de diamant, gravat pe tăblița inimii lor și pe coarnele altarelor voastre.", dict_ro:"Rashi notează că Midrașul Agada leagă «unghia de diamant» de Ezechiel 3:9, unde profetul e numit «mai tare decât cremenea» — același material simbolic al încăpățânării, folosit aici pentru a descrie încăpățânarea păcatului lui Iuda, nu a profetului."}]
]},
{v:"17:2", newTags:[
  ["Cum își amintesc de copiii lor, așa [își amintesc și] de altarele lor și de", {heb:"כִּזְכֹּר בְּנֵיהֶם מִזְבְּחוֹתָם", translit:"kizkor benēhem mizbehotam", strong:"H2142", pos:"verb, qal infinitiv + substantiv plural construct + sufix + substantiv plural construct + sufix", def_ro:"cum își amintesc de fiii lor, [așa] de altarele lor.", dict_ro:"Rashi explică faptul că amintirea altarelor era pentru popor la fel de vie și dragă ca amintirea propriilor copii — o comparație care arată profunzimea atașamentului idolatru, nu doar o practică superficială."}],
  [" de lângă pomii înfrunziți de pe dealurile înalte.", {heb:"עַל עֵץ רַעֲנָן עַל גְּבָעוֹת הַגְּבֹהוֹת", translit:"al ēț raanan al gevaot hagvohot", strong:"H5921", pos:"prepoziție + substantiv + adjectiv + prepoziție + substantiv plural + adjectiv plural", def_ro:"lângă pomul înfrunzit, pe dealurile cele înalte.", dict_ro:"Radak explică faptul că amintirea altarelor și a arborilor sacri le era poporului dragă precum amintirea copiilor, din aceeași iubire statornică — comentatorul respinge explicația alternativă potrivit căreia versetul s-ar referi la trecerea copiilor prin foc."}]
]},
{v:"17:3", newTags:[
  ["Cei care slujiți [idoli] pe munți, pe câmpuri: bogăția ta, toate comorile tale, le voi da", {heb:"הֲרָרִי בַּשָּׂדֶה חֵילְךָ כָל אוֹצְרוֹתֶיךָ", translit:"harari basade hēlha hal oțroteha", strong:"H2042", pos:"substantiv construct + sufix + substantiv + substantiv construct + sufix + substantiv construct + substantiv plural construct + sufix", def_ro:"munții [tăi] din câmpie, bogăția ta, toate comorile tale.", dict_ro:"Rashi identifică «cei de pe munte, în câmpie» cu Ierusalimul, așezat pe un munte situat într-o câmpie cu ogoare de jur împrejur — descrierea geografică precisă a cetății supuse judecății."}],
  [", din pricina înălțimilor tale [făcute] în păcat pretutindeni între hotarele tale.", {heb:"אֶתֵּן בָּמֹתֶיךָ בְּחַטָּאת בְּכָל גְּבוּלֶיךָ", translit:"etēn bamoteha behatat behal gevuleha", strong:"H5414", pos:"verb, qal imperfect + substantiv plural construct + sufix + substantiv + substantiv construct + substantiv plural construct + sufix", def_ro:"voi da, [din pricina] înălțimilor tale în păcat, în toate hotarele tale.", dict_ro:"Radak explică faptul că înălțimile de cult, răspândite în toate hotarele țării, fără să lipsească vreun loc, sunt motivul exact pentru care toată averea și comorile vor fi date pradă dușmanilor."}]
]},
{v:"17:4", newTags:[
  [" de moștenirea pe care ți-am dat-o și te voi pune să muncești pentru dușmanii tăi într-o țară pe care nu o cunoști, căci ai aprins foc în nările Mele, care va arde veșnic.”", {heb:"וּבְךָ מִנַּחֲלָתְךָ אֲשֶׁר נָתַתִּי לָךְ וְהַעֲבַדְתִּיךָ אֶת אֹיְבֶיךָ בָּאָרֶץ אֲשֶׁר לֹא יָדָעְתָּ כִּי אֵש קְדַחְתֶּם בְּאַפִּי עַד עוֹלָם תּוּקָד", translit:"uvha minahalatha așer natati lah vehaavadtiha et oiveha baareț așer lo iadata ki ēș kedahtem beapi ad olam tukad", strong:"H5159", pos:"prepoziție + sufix + substantiv construct + sufix + particulă relativă + verb, qal perfect + prepoziție + sufix + verb, hifil perfect consecutiv + sufix + marcă a complementului direct + verb, qal participiu + sufix + substantiv + particulă relativă + particulă negativă + verb, qal perfect + conjuncție + substantiv + verb, qal perfect + substantiv construct + sufix + prepoziție + substantiv + verb, hofal imperfect", def_ro:"și prin tine, de la moștenirea ta pe care ți-am dat-o; și te voi pune să slujești pe dușmanii tăi, într-o țară pe care n-ai cunoscut-o, căci foc ați aprins în nările Mele, care va arde pe veci.", dict_ro:"Rashi explică faptul că eliberarea forțată a țării e răsplata exactă pentru faptul că poporul n-a lăsat pământul să se odihnească în anul sabatic, așa cum poruncea Levitic 25:2 — pedeapsa corespunde precis neglijenței comise."}]
]},
{v:"17:5", newTags:[
  ["Așa a spus DOMNUL: „", {heb:"כֹּה אָמַר יְהוָה", translit:"ko amar Adonai", strong:"H3541", pos:"adverb + verb, qal perfect + nume propriu", def_ro:"așa a spus DOMNUL.", dict_ro:"Formula introductivă marchează trecerea de la blestemul descris anterior la contrastul fundamental dintre cel care se încrede în om și cel care se încrede în DOMNUL, dezvoltat în versetele următoare."}],
  [" este bărbatul care se încrede în om și care face din muritor tăria sa și care își abate inima de la DOMNUL.", {heb:"הַגֶּבֶר אֲשֶׁר יִבְטַח בָּאָדָם וְשָׂם בָּשָׂר זְרֹעוֹ וּמִן יְהוָה יָסוּר לִבּוֹ", translit:"hagever așer ivtah baadam vesam basar zeroo umin Adonai iasur libo", strong:"H1397", pos:"substantiv + particulă relativă + verb, qal imperfect + substantiv + verb, qal perfect consecutiv + substantiv + substantiv construct + sufix + prepoziție + nume propriu + verb, qal imperfect + substantiv construct + sufix", def_ro:"bărbatul care se încrede în om și face din carne brațul lui, și de la DOMNUL se abate inima lui.", dict_ro:"Radak explică faptul că nu e rău în sine să te încrezi în ajutorul omului, ci doar atunci când inima se abate complet de la DOMNUL — ajutorul omenesc poate fi primit ca mijlocire a lui Dumnezeu, nu ca substitut al Lui."}]
]},
{v:"17:6", newTags:[
  ["El este ca un", {heb:"וְהָיָה", translit:"vehaia", strong:"H1961", pos:"verb, qal perfect consecutiv", def_ro:"și va fi.", dict_ro:"Rashi explică «kearar» ca pe numele unui copac din pădure, numit arar — aceeași identificare apărând și la Ieremia 48:6, «ca un aroer în pustie»."}],
  [" în pustietate și nu va vedea când vine binele; el va locui într-un deșert arid, într-un ținut de pucioasă, nelocuit.", {heb:"בָּעֲרָבָה וְלֹא יִרְאֶה כִּי יָבוֹא טוֹב וְשָׁכַן חֲרֵרִים בַּמִּדְבָּר אֶרֶץ מְלֵחָה וְלֹא תֵשֵׁב", translit:"baarava velo ire ki iavo tov veșahan harērim bamidbar ereț melēha velo tēșēv", strong:"H6160", pos:"substantiv + particulă negativă + verb, qal imperfect + conjuncție + verb, qal imperfect + adjectiv + verb, qal perfect consecutiv + substantiv plural + substantiv + substantiv construct + substantiv + particulă negativă + verb, qal imperfect", def_ro:"în pustietate, și nu va vedea când va veni binele, și va locui în locuri uscate, în pustie, țară sărată, și nu va fi locuită.", dict_ro:"Radak explică, pe baza lui Rav Hai, că ararul e spinos pe dinafară, dar are înăuntru un fruct comestibil — comparația arată că omul rău, chiar dacă nu moare, va trăi toate zilele lui în uscăciune și nelocuire spirituală."}]
]},
{v:"17:7", newTags:[
  [" este bărbatul care se încrede în DOMNUL – atunci DOMNUL îi va fi încrederea.", {heb:"הַגֶּבֶר אֲשֶׁר יִבְטַח בַּיהוָה וְהָיָה יְהוָה מִבְטַחוֹ", translit:"hagever așer ivtah ba'Adonai vehaia Adonai mivtaho", strong:"H1397", pos:"substantiv + particulă relativă + verb, qal imperfect + nume propriu + verb, qal perfect consecutiv + nume propriu + substantiv construct + sufix", def_ro:"bărbatul care se încrede în DOMNUL, și DOMNUL va fi încrederea lui.", dict_ro:"Radak explică simplu: dacă omul se încrede în DOMNUL, DOMNUL îi va fi încrederea, și nu se va teme de niciun rău — o reciprocitate directă între încredere și ocrotire."}]
]},
{v:"17:8", newTags:[
  ["El este ca", {heb:"וְהָיָה", translit:"vehaia", strong:"H1961", pos:"verb, qal perfect consecutiv", def_ro:"și va fi.", dict_ro:"Contrastul cu versetul 6 e deliberat: același verb de introducere, dar de această dată urmat de imaginea opusă — pomul sădit lângă apă, mereu rodnic, spre diferență de ararul uscat al celui necredincios."}],
  [" lângă apă, care își întinde rădăcinile lângă pâraie și nu va vedea când vine arșița, al cărui frunziș este de-a pururea verde și nu se teme în ani de secetă și nu va înceta niciodată să aibă rod.", {heb:"עַל מַיִם וְעַל יוּבַל יְשַׁלַּח שָׁרָשָׁיו וְלֹא יִרְאֶה כִּי יָבֹא חֹם וְהָיָה עָלֵהוּ רַעֲנָן וּבִשְׁנַת בַּצֹּרֶת לֹא יִדְאָג וְלֹא יָמִישׁ מֵעֲשׂוֹת פֶּרִי", translit:"al maim veal iuval ieșalah șarașaiv velo ire ki iavo hom vehaia alēhu raanan uvișnat bațoret lo idag velo iamiș mēasot peri", strong:"H4325", pos:"prepoziție + substantiv plural + prepoziție + substantiv + verb, piel imperfect + substantiv plural construct + sufix + particulă negativă + verb, qal imperfect + conjuncție + verb, qal imperfect + substantiv + verb, qal perfect consecutiv + substantiv construct + sufix + adjectiv + substantiv construct + substantiv + particulă negativă + verb, qal imperfect + particulă negativă + verb, qal imperfect + verb, qal infinitiv + substantiv", def_ro:"lângă ape, și lângă pârâu își întinde rădăcinile, și nu va vedea când va veni arșița, și va fi frunzișul lui verde, și în anul secetei nu se va îngrijora și nu va înceta din a face rod.", dict_ro:"Radak explică faptul că acest pom, sădit lângă ape, nu însetoșează niciodată, iar frunzele lui nu cad ca ale celorlalți pomi — chiar în anul secetei își dă rodul la vremea lui, exact ca omul care se încrede în DOMNUL, al cărui bine nu se îndepărtează niciodată."}]
]},
{v:"17:9", newTags:[
  ["Inima este", {heb:"הַלֵּב", translit:"halēv", strong:"H3820", pos:"substantiv", def_ro:"inima.", dict_ro:"Radak explică de ce versetul trece de la încrederea greșită în om la natura inimii: omul poate arăta binele prin gură și prin fapte, dar inima lui să fie rea pe dinăuntru — numai DOMNUL poate cunoaște adevărul ascuns al inimii."}],
  [" din toate și perversă, cine o cunoaște?", {heb:"מִכֹּל וְאָנֻשׁ הוּא מִי יֵדָעֶנּוּ", translit:"mikol veanuș hu mi iēdaenu", strong:"H3605", pos:"substantiv + adjectiv + pronume personal + particulă interogativă + verb, qal imperfect + sufix", def_ro:"decât toate, și bolnavă [este] ea; cine o va cunoaște?", dict_ro:"Rashi explică «veanuș» ca o expresie de boală — inima gândește în sinea ei «cine mă cunoaște?», dar răspunsul vine imediat în versetul următor: Eu, DOMNUL, o cercetez."}]
]},
{v:"17:10", newTags:[
  ["Eu, DOMNUL, cercetez inima și", {heb:"אֲנִי יְהוָה חֹקֵר לֵב", translit:"ani Adonai hokēr lēv", strong:"H589", pos:"pronume personal + nume propriu + verb, qal participiu + substantiv", def_ro:"Eu, DOMNUL, cercetez inima.", dict_ro:"Radak explică faptul că rărunchii sunt pomeniți special pentru că ei «sfătuiesc», pe când inima «hotărăște» — amândouă organele interioare sunt supuse cercetării depline a DOMNULUI, nu doar faptele exterioare."}],
  [", ca să îi dau omului după căile lui, după roadele faptelor lui.", {heb:"וְלָתֵת לְאִישׁ כִּדְרָכָיו כִּפְרִי מַעֲלָלָיו", translit:"velatēt leiș kidrahaiv kifri maalalaiv", strong:"H5414", pos:"verb, qal infinitiv + substantiv + substantiv plural construct + sufix + substantiv construct + substantiv plural construct + sufix", def_ro:"și ca să dau omului după căile lui, după rodul faptelor lui.", dict_ro:"Metzudat David explică faptul că «roadele faptelor» sunt gândurile, lucrarea și căile inimii — o dublare a aceleiași idei în cuvinte diferite, pentru a sublinia judecata completă, interioară și exterioară deopotrivă."}]
]},
{v:"17:11", newTags:[
  [", clocind ouă pe care nu le-a ouat, este cel ce strânge bogăție pe nedrept; la jumătatea zilelor lui, [bogăția] îl va părăsi, și când îi va veni sfârșitul va fi un biet nebun.", {heb:"דָגַר וְלֹא יָלָד עֹשֶׂה עֹשֶׁר וְלֹא בְמִשְׁפָּט בַּחֲצִי יָמָיו יַעַזְבֶנּוּ וּבְאַחֲרִיתוֹ יִהְיֶה נָבָל", translit:"dagar velo ialad ose oșer velo vemișpat bahați iamaiv iaazvenu uvaharito ihie naval", strong:"H1716", pos:"verb, qal perfect + particulă negativă + verb, qal perfect + verb, qal participiu + substantiv + particulă negativă + substantiv + substantiv construct + substantiv plural construct + sufix + verb, qal imperfect + sufix + substantiv construct + sufix + verb, qal imperfect + adjectiv", def_ro:"a clocit, dar n-a ouat; cel care strânge avere fără dreptate, la jumătatea zilelor lui îl va părăsi, și la sfârșitul lui va fi nebun.", dict_ro:"Radak explică asemănarea cu pasărea «kore», care clocește ouăle altei păsări — puii ieșiți nu o vor urma, ci o vor părăsi când cresc și înțeleg că nu ea i-a născut, exact cum bogăția nedreaptă îl părăsește pe cel ce a strâns-o."}]
]},
{v:"17:12", newTags:[
  [", înălțat de la început, este locul Sanctuarului nostru.", {heb:"כָבוֹד מָרוֹם מֵרִאשׁוֹן מְקוֹם מִקְדָּשֵׁנוּ", translit:"havod marom mērișon mekom mikdașēnu", strong:"H3519", pos:"substantiv + substantiv + adjectiv + substantiv construct + substantiv construct + sufix", def_ro:"al gloriei, înălțat, de la început, locul Sanctuarului nostru.", dict_ro:"Talmudul Bavli (Pesahim 54a) citează o baraită potrivit căreia șapte lucruri au fost create înainte de lume — Tora, pocăința, Grădina Edenului, Gheena, Tronul slavei, Templul și numele lui Mesia — iar acest verset e dovada textuală pentru precedența Tronului slavei și a Templului."}]
]},
{v:"17:13", newTags:[
  ["Nădejdea lui Israel este DOMNUL, toți cei care Te părăsesc vor fi făcuți de rușine, vor fi înscriși către temeliile pământului, căci ei L-au părăsit pe DOMNUL,", {heb:"מִקְוֵה יִשְׂרָאֵל יְהוָה כָּל עֹזְבֶיךָ יֵבֹשׁוּ וְסוּרַי בָּאָרֶץ יִכָּתֵבוּ כִּי עָזְבוּ", translit:"mikvē israēl Adonai kal ozveha iēvoșu vesurai baareț ikatēvu ki azvu", strong:"H4723", pos:"substantiv construct + nume propriu + nume propriu + substantiv construct + verb, qal participiu + sufix + verb, qal imperfect + verb, qal participiu + sufix + substantiv + verb, nifal imperfect + conjuncție + verb, qal perfect", def_ro:"nădejdea lui Israel [este] DOMNUL; toți cei ce Te părăsesc vor fi făcuți de rușine, și cei ce se abat de la Mine vor fi înscriși pe pământ, căci au părăsit.", dict_ro:"Mișna (Yoma, cap. 8, mișna 9) citează pe Rabi Akiva: «mikve-ul lui Israel este DOMNUL», folosind același cuvânt pentru «nădejde» și «bazin de curățire» — precum mikve-ul îi curăță pe cei necurați, așa DOMNUL Îl curăță pe Israel."}],
  [".", {heb:"מְקוֹר מַיִם חַיִּים אֶת יְהוָה", translit:"mekor maim haim et Adonai", strong:"H4726", pos:"substantiv construct + substantiv plural + adjectiv plural + marcă a complementului direct + nume propriu", def_ro:"izvorul apelor vii, pe DOMNUL.", dict_ro:"Rashi explică faptul că cei ce se abat de la cuvintele profetului vor fi «înscriși în mormintele de jos ale pământului» — pedeapsa măsură pentru măsură pentru cei care au părăsit izvorul apelor vii, alegând în schimb fântâni crăpate."}]
]},
{v:"17:14", newTags:[
  [", DOAMNE, și voi fi vindecat, salvează-mă și voi fi salvat, căci Tu ești lauda mea.", {heb:"יְהוָה וְאֵרָפֵא הוֹשִׁיעֵנִי וְאִוָּשֵׁעָה כִּי תְהִלָּתִי אָתָּה", translit:"Adonai veērafē hoșiēni veivașēa ki tehilati ata", strong:"H3068", pos:"nume propriu + verb, nifal cohortativ + verb, hifil imperativ + sufix + verb, nifal cohortativ + conjuncție + substantiv construct + sufix + pronume personal", def_ro:"DOAMNE, și voi fi vindecat; mântuiește-mă și voi fi mântuit, căci lauda mea Tu [ești].", dict_ro:"Rashi explică faptul că «Tu ești lauda mea» înseamnă că profetul se laudă și se fălește anume cu DOMNUL, spunând că El este singurul lui Mântuitor — nimeni altcineva nu-l poate izbăvi din mâna celor ce-l asupresc."}]
]}
];
