module.exports = [
{v:"13:2", newTags:[
  ["Era un bărbat anume din Țora, din familia daniților, al cărui nume era Manoah, iar soția lui era", {heb:"וַיְהִי אִישׁ אֶחָד מִצָּרְעָה מִמִּשְׁפַּחַת הַדָּנִי וּשְׁמוֹ מָנוֹחַ וְאִשְׁתּוֹ", translit:"vaihi iș ehad mițara mimișpahat hadani ușmo manoah veișto", strong:"H1961", pos:"verb, qal imperfect consecutiv + substantiv + numeral + nume propriu + substantiv construct + nume propriu + substantiv construct + sufix + nume propriu + substantiv construct + sufix", def_ro:"și a fost un om din Țora, din familia daniților, și numele lui [era] Manoah, și soția lui.", dict_ro:"Talmudul Bavli (Bava Batra 91a) transmite o tradiție primită despre numele mamei și al surorii lui Samson, Țelelponit și Nașian, nepomenite explicit în text — un răspuns pregătit pentru cei care ar întreba de ce Scriptura nu le numește."}]
]},
{v:"13:3", newTags:[
  ["Și", {heb:"וַיֵּרָא", translit:"vaiēra", strong:"H7200", pos:"verb, nifal imperfect consecutiv", def_ro:"și s-a arătat.", dict_ro:"Radak explică faptul că adăugirea «și nu născuse» de la versetul precedent are rolul unei lămuriri suplimentare, ca la Geneza 11:30 despre Sarai — stearpă, fără copil."}],
  [" i s-a arătat femeii și i-a spus: „Iată, acum ești stearpă și nu ai născut, dar vei zămisli și vei naște un fiu.", {heb:"מַלְאַךְ יְהוָה אֶל הָאִשָּׁה וַיֹּאמֶר אֵלֶיהָ הִנֵּה נָא אַתְּ עֲקָרָה וְלֹא יָלַדְתְּ וְהָרִית וְיָלַדְתְּ בֵּן", translit:"malah Adonai el haișa vaiomer ēleha hinē na at akara velo ialadte veharit veialadte bēn", strong:"H4397", pos:"substantiv construct + nume propriu + prepoziție + substantiv + verb, qal imperfect consecutiv + prepoziție + sufix + particulă demonstrativă + interjecție + pronume personal + adjectiv + particulă negativă + verb, qal perfect + verb, qal perfect + verb, qal perfect + substantiv", def_ro:"un înger al DOMNULUI femeii, și i-a spus: iată, tu [ești] stearpă și n-ai născut, și vei rămâne însărcinată și vei naște un fiu.", dict_ro:"Metzudat David explică faptul că «vei zămisli» înseamnă literal că femeia va rămâne însărcinată — vestea depășește cu mult realitatea ei prezentă de sterilitate, întărind caracterul miraculos al promisiunii."}]
]},
{v:"13:4", newTags:[
  ["Și acum, păzește-te așadar: să nu bei nici vin și nici", {heb:"וְעַתָּה הִשָּׁמְרִי נָא וְאַל תִּשְׁתִּי יַיִן", translit:"veata hișamri na veal tiști iain", strong:"H6258", pos:"adverb + verb, nifal imperativ + interjecție + particulă negativă + verb, qal jusiv + substantiv", def_ro:"și acum, păzește-te, te rog, și să nu bei vin.", dict_ro:"Radak explică faptul că aceste restricții trebuiau respectate de mamă chiar din timpul sarcinii, ca sfințenia copilului nazireu să înceapă din pântece, nu abia după naștere."}],
  [", și să nu mănânci nimic necurat.", {heb:"וְאַל תֹּאכְלִי כָּל טָמֵא", translit:"veal tohli kal tamē", strong:"H408", pos:"particulă negativă + verb, qal jusiv + substantiv construct + adjectiv", def_ro:"și să nu mănânci nimic necurat.", dict_ro:"Talmudul Bavli (Sota 9b) explică, prin Rabi Ițhak din școala lui Rabi Ami, că «nimic necurat» nu se referă la mâncăruri propriu-zis necurate, ci la lucrurile interzise specific nazireului — altfel întrebarea ar fi de ce i s-ar fi permis anterior să mănânce necurat."}]
]},
{v:"13:5", newTags:[
  ["Căci iată, vei zămisli și vei naște un fiu. Briciul să nu treacă peste capul lui, căci tânărul va fi", {heb:"כִּי הִנָּךְ הָרָה וְיֹלַדְתְּ בֵּן וּמוֹרָה לֹא יַעֲלֶה עַל רֹאשׁוֹ כִּי", translit:"ki hinah hara veioladte bēn umora lo iaale al roșo ki", strong:"H3588", pos:"conjuncție + particulă demonstrativă + sufix + adjectiv + verb, qal perfect consecutiv + substantiv + substantiv + particulă negativă + verb, qal imperfect + prepoziție + substantiv construct + sufix + conjuncție", def_ro:"căci iată, tu [ești] însărcinată și vei naște un fiu, și briciul nu va trece peste capul lui, căci.", dict_ro:"Rashi explică «mora» (briciul) prin rădăcina ce înseamnă «a arunca și a îndepărta» — unealta folosită special pentru a îndepărta părul, aici interzisă categoric asupra capului copilului nenăscut încă."}],
  [" pentru Dumnezeu încă din pântec și va începe să-l mântuiască pe Israel din mâna filistenilor.”", {heb:"אֱלֹהִים יִהְיֶה הַנַּעַר מִן הַבָּטֶן וְהוּא יָחֵל לְהוֹשִׁיעַ אֶת יִשְׂרָאֵל מִיַּד פְּלִשְׁתִּים", translit:"elohim ihie hanaar min habaten vehu iahēl lehoșia et israēl miad peliștim", strong:"H430", pos:"substantiv plural + verb, qal imperfect + substantiv + prepoziție + substantiv + pronume personal + verb, hifil imperfect + verb, hifil infinitiv + marcă a complementului direct + nume propriu + substantiv construct + nume de neam", def_ro:"pentru Dumnezeu va fi tânărul din pântece, și el va începe să mântuiască pe Israel din mâna filistenilor.", dict_ro:"Talmudul Bavli (Sota 9b-10a) explică faptul că mântuirea e numită doar «un început» fără încheiere, pentru că jurământul lui Avimeleh, regele filistenilor, se desfăcuse (huhal) — ei înșiși încălcaseră pacea asuprindu-i pe israeliți, declanșând astfel dreptul la luptă."}]
]},
{v:"13:6", newTags:[
  ["Femeia a venit și i-a spus soțului ei astfel: „Un om al lui Dumnezeu a venit la mine. Iar înfățișarea lui era ca înfățișarea unui înger al lui Dumnezeu,", {heb:"וַתָּבֹא הָאִשָּׁה וַתֹּאמֶר לְאִישָׁהּ לֵאמֹר אִישׁ הָאֱלֹהִים בָּא אֵלַי וּמַרְאֵהוּ כְּמַרְאֵה מַלְאַךְ הָאֱלֹהִים", translit:"vatavo haișa vatomer leișah lēmor iș haelohim ba ēlai umarēhu kemarē malah haelohim", strong:"H935", pos:"verb, qal imperfect consecutiv + substantiv + verb, qal imperfect consecutiv + substantiv construct + sufix + verb, qal infinitiv + substantiv construct + substantiv + verb, qal perfect + prepoziție + sufix + substantiv construct + sufix + substantiv construct + substantiv construct + substantiv", def_ro:"și a venit femeia și a spus soțului ei, spunând: un om al lui Dumnezeu a venit la mine, și înfățișarea lui [era] ca înfățișarea unui înger al lui Dumnezeu.", dict_ro:"Metzudat David explică faptul că femeia a crezut că era un profet, nu un înger — ea nu a recunoscut natura adevărată a vizitatorului, deși i-a descris corect înfățișarea înfricoșătoare."}],
  [". Nici eu nu l-am întrebat de unde era și nici el nu mi-a dezvăluit care era numele lui.", {heb:"וְלֹא שְׁאִלְתִּיהוּ אֵי מִזֶּה הוּא וְאֶת שְׁמוֹ לֹא הִגִּיד לִי", translit:"velo șeiltihu ē mize hu veet șemo lo higid li", strong:"H3808", pos:"particulă negativă + verb, qal perfect + sufix + particulă interogativă + pronume demonstrativ + pronume personal + marcă a complementului direct + substantiv construct + sufix + particulă negativă + verb, hifil perfect + prepoziție + sufix", def_ro:"și nu l-am întrebat de unde este el, și numele lui nu mi-a spus.", dict_ro:"Metzudat David explică faptul că femeia n-a mai întrebat de locul de origine al vizitatorului exact pentru că acesta nu-i spusese numele când l-a întrebat — tăcerea lui a descurajat-o de la a continua întrebările."}]
]},
{v:"13:7", newTags:[
  ["Și mi-a spus: „Iată, vei zămisli și vei naște un fiu. Și acum, să nu bei nici vin și nici băutură tare, și să nu mănânci nimic necurat, căci tânărul va fi nazireu pentru Dumnezeu,", {heb:"וַיֹּאמֶר לִי הִנָּךְ הָרָה וְיֹלַדְתְּ בֵּן וְעַתָּה אַל תִּשְׁתִּי יַיִן וְשֵׁכָר וְאַל תֹּאכְלִי כָּל טֻמְאָה כִּי נְזִיר אֱלֹהִים יִהְיֶה הַנַּעַר מִן", translit:"vaiomer li hinah hara veioladte bēn veata al tiști iain veșēhar veal tohli kal tuma ki nezir elohim ihie hanaar min", strong:"H559", pos:"verb, qal imperfect consecutiv + prepoziție + sufix + particulă demonstrativă + sufix + adjectiv + verb, qal perfect consecutiv + substantiv + adverb + particulă negativă + verb, qal jusiv + substantiv + substantiv + particulă negativă + verb, qal jusiv + substantiv construct + substantiv + conjuncție + substantiv construct + substantiv + verb, qal imperfect + substantiv + prepoziție", def_ro:"și mi-a spus: iată, tu [ești] însărcinată și vei naște un fiu, și acum nu bea vin și băutură tare, și nu mânca nimic necurat, căci nazireu al lui Dumnezeu va fi tânărul, din.", dict_ro:"Rashi precizează că «nimic necurat» include, pe lângă vin, și sucul de struguri — orice lucru interzis nazireului, potrivit Numeri 6:4, de la sâmburi până la pieliță."}],
  [" până în ziua morții lui.”", {heb:"עַד יוֹם מוֹתוֹ", translit:"ad iom moto", strong:"H5704", pos:"prepoziție + substantiv construct + substantiv construct + sufix", def_ro:"până în ziua morții lui.", dict_ro:"Talmudul Bavli (Nazir 4b) ridică întrebarea dacă Samson a fost nazireu printr-un jurământ propriu-zis — răspunsul e negativ, căci aici îngerul a fost cel care a vorbit, nazireatul lui venind dintr-o poruncă divină, nu dintr-un vot personal."}]
]},
{v:"13:8", newTags:[
  ["Manoah", {heb:"מָנוֹחַ", translit:"manoah", strong:"H4495", pos:"nume propriu", def_ro:"Manoah.", dict_ro:"Metzudat David explică faptul că Manoah se roagă pentru o a doua vizită a îngerului, deși nu era nevoie, căci îngerul nu avea nimic nou de adăugat — rugăciunea arată dorința lui de confirmare, nu o lacună reală în mesaj."}],
  [" pe DOMNUL și a spus: „Rogu-Te, stăpâne, se poate ca omul lui Dumnezeu pe care l-ai trimis să revină la noi să ne învețe ce să facem cu tânărul care se va naște?”", {heb:"אֶל יְהוָה וַיֹּאמַר בִּי אֲדוֹנָי אִישׁ הָאֱלֹהִים אֲשֶׁר שָׁלַחְתָּ יָבוֹא נָא עוֹד אֵלֵינוּ וְיוֹרֵנוּ מַה נַּעֲשֶׂה לַנַּעַר הַיּוּלָּד", translit:"el Adonai vaiomar bi adoni iș haelohim așer șalahta iavo na od ēlēnu veorēnu ma naase lanaar haiulad", strong:"H413", pos:"prepoziție + nume propriu + verb, qal imperfect consecutiv + interjecție + substantiv construct + sufix + substantiv construct + substantiv + particulă relativă + verb, qal perfect + verb, qal jusiv + interjecție + adverb + prepoziție + sufix + verb, hifil imperfect + sufix + particulă interogativă + verb, qal imperfect + substantiv + verb, qal pasiv participiu pasiv", def_ro:"către DOMNUL, și a spus: te rog, stăpânul meu, omul lui Dumnezeu pe care l-ai trimis să vină iarăși la noi și să ne învețe ce să facem cu tânărul care se va naște.", dict_ro:"Rashi, citând Targumul lui Ionatan, explică faptul că întrebarea lui Manoah nu se referea la ce trebuie să facă băiatul, ci la ce trebuie să facă ei, părinții, cu el — grija practică a educației nazireatului, nu a comportamentului copilului."}]
]},
{v:"13:9", newTags:[
  ["Dumnezeu a ascultat glasul lui Manoah și îngerul lui Dumnezeu a venit iarăși la femeie când ea stătea", {heb:"וַיִּשְׁמַע הָאֱלֹהִים בְּקוֹל מָנוֹחַ וַיָּבֹא מַלְאַךְ הָאֱלֹהִים עוֹד אֶל הָאִשָּׁה וְהִיא יוֹשֶׁבֶת", translit:"vaișma haelohim bekol manoah vaiavo malah haelohim od el haișa vehi ioșevet", strong:"H8085", pos:"verb, qal imperfect consecutiv + substantiv + substantiv construct + nume propriu + verb, qal imperfect consecutiv + substantiv construct + substantiv + adverb + prepoziție + substantiv + pronume personal + verb, qal participiu", def_ro:"și a ascultat Dumnezeu glasul lui Manoah, și a venit îngerul lui Dumnezeu iarăși la femeie, și ea ședea.", dict_ro:"Metzudat David explică faptul că DOMNUL a răspuns rugăciunii lui Manoah pentru a-i împlini cererea, deși, strict vorbind, nu era nevoie — îngerul n-avea nimic nou de adăugat la mesajul deja transmis."}],
  [", dar soțul ei Manoah nu era cu ea.", {heb:"וּמָנוֹחַ אִישָׁהּ אֵין עִמָּהּ", translit:"umanoah ișah ēn imah", strong:"H4495", pos:"nume propriu + substantiv construct + sufix + particulă negativă + prepoziție + sufix", def_ro:"și Manoah, soțul ei, nu [era] cu ea.", dict_ro:"Absența deliberată a lui Manoah la a doua apariție a îngerului pregătește exact episodul care urmează — femeia trebuie să alerge să-l cheme, confirmând că doar ea cunoștea locul exact al arătării."}]
]},
{v:"13:10", newTags:[
  ["Femeia", {heb:"הָאִשָּׁה", translit:"haișa", strong:"H802", pos:"substantiv", def_ro:"femeia.", dict_ro:"Radak confirmă, pe baza Targumului lui Ionatan, că «în ziua aceea» se referă la ziua anume, cea despre care femeia îi spusese deja soțului ei mai înainte — un detaliu temporal precis, nu vag."}],
  [" și a alergat și i-a povestit soțului ei și i-a spus: „Iată, omul care a venit la mine în ziua aceea mi-a apărut.”", {heb:"וַתָּרָץ וַתַּגֵּד לְאִישָׁהּ וַתֹּאמֶר אֵלָיו הִנֵּה נִרְאָה אֵלַי הָאִישׁ אֲשֶׁר בָּא בַיּוֹם אֵלָי", translit:"vataraț vatagēd leișah vatomer ēlaiv hinē nira ēlai haiș așer ba vaiom ēlai", strong:"H7323", pos:"verb, qal imperfect consecutiv + verb, hifil imperfect consecutiv + substantiv construct + sufix + verb, qal imperfect consecutiv + prepoziție + sufix + particulă demonstrativă + verb, nifal perfect + prepoziție + sufix + substantiv + particulă relativă + verb, qal perfect + substantiv + prepoziție + sufix", def_ro:"și a alergat și a vestit soțului ei, și i-a spus: iată, mi s-a arătat omul care a venit la mine în ziua aceea.", dict_ro:"Metzudat David explică faptul că «mi-a apărut» confirmă identitatea exactă a vizitatorului cu cel din prima arătare — nu era o ființă nouă, ci aceeași prezență revenită."}]
]},
{v:"13:11", newTags:[
  [" s-a ridicat și a mers după soția sa; și a ajuns la om și i-a spus: „Tu ești omul care i-a vorbit soției [mele]?” Și el a spus: „Eu sunt.”", {heb:"וַיָּקָם וַיֵּלֶךְ מָנוֹחַ אַחֲרֵי אִשְׁתּוֹ וַיָּבֹא אֶל הָאִישׁ וַיֹּאמֶר לוֹ הַאַתָּה הָאִישׁ אֲשֶׁר דִּבַּרְתָּ אֶל הָאִשָּׁה וַיֹּאמֶר אָנִי", translit:"vaiakam vaiēleh manoah aharē ișto vaiavo el haiș vaiomer lo haata haiș așer dibarta el haișa vaiomer ani", strong:"H6965", pos:"verb, qal imperfect consecutiv + verb, qal imperfect consecutiv + nume propriu + prepoziție + substantiv construct + sufix + verb, qal imperfect consecutiv + prepoziție + substantiv + verb, qal imperfect consecutiv + prepoziție + sufix + pronume personal + substantiv + particulă relativă + verb, piel perfect + prepoziție + substantiv + verb, qal imperfect consecutiv + pronume personal", def_ro:"și s-a ridicat și a mers Manoah după soția lui, și a venit la om, și i-a spus: tu [ești] omul care i-a vorbit femeii? Și a spus: eu [sunt].", dict_ro:"Talmudul Bavli (Berahot 61a) explică, prin Rav Nahman, expresia «a mers după soția sa» ca «a mers după sfatul și cuvintele ei», nu literalmente în urma ei — paralelă cu Elcana și Elisei, despre care se folosește aceeași expresie fără sens literal."}]
]},
{v:"13:12", newTags:[
  ["Și Manoah a spus: „Acum, se vor adeveri vorbele tale;", {heb:"וַיֹּאמֶר מָנוֹחַ עַתָּה יָבֹא דְבָרֶיךָ מַה יִּהְיֶה", translit:"vaiomer manoah ata iavo devareha ma ihie", strong:"H559", pos:"verb, qal imperfect consecutiv + nume propriu + adverb + verb, qal imperfect + substantiv plural construct + sufix + particulă interogativă + verb, qal imperfect", def_ro:"și a spus Manoah: acum vor veni cuvintele tale; ce va fi.", dict_ro:"Metzudat David explică faptul că venirea a doua a îngerului, prin rugăciunea lui Manoah, confirmă acum fără îndoială că mesajul e cu adevărat cuvântul DOMNULUI — de aceea întreabă detaliile practice ale creșterii copilului."}],
  [" tânărul și ce trebuie să facă?”", {heb:"מִשְׁפַּט הַנַּעַר וּמַעֲשֵׂהוּ", translit:"mișpat hanaar umaasēhu", strong:"H4941", pos:"substantiv construct + substantiv + substantiv construct + sufix", def_ro:"rânduiala tânărului și fapta lui.", dict_ro:"Metzudat Țion explică «mișpat» cu sensul de purtare și rânduială, folosit identic la 1 Samuel 27:11 — «obiceiul lui» — nu o lege formală, ci modul de viață potrivit copilului."}]
]},
{v:"13:13", newTags:[
  ["Îngerul lui Dumnezeu i-a spus lui Manoah: „De orice i-am spus femeii,", {heb:"וַיֹּאמֶר מַלְאַךְ יְהוָה אֶל מָנוֹחַ מִכֹּל אֲשֶׁר אָמַרְתִּי אֶל הָאִשָּׁה", translit:"vaiomer malah Adonai el manoah mikol așer amarti el haișa", strong:"H559", pos:"verb, qal imperfect consecutiv + substantiv construct + nume propriu + prepoziție + nume propriu + substantiv + particulă relativă + verb, qal perfect + prepoziție + substantiv", def_ro:"și a spus îngerul DOMNULUI către Manoah: din tot ce am spus femeii.", dict_ro:"Metzudat David explică faptul că rânduiala tânărului nu adaugă nimic nou peste nazireatul obișnuit — singurul adaos e că și mama trebuie să se păzească de toate restricțiile deja spuse, nu copilul singur."}]
]},
{v:"13:14", newTags:[
  ["Orice care iese din", {heb:"מִכֹּל אֲשֶׁר יֵצֵא", translit:"mikol așer iēțē", strong:"H3605", pos:"substantiv + particulă relativă + verb, qal imperfect", def_ro:"din tot ce iese.", dict_ro:"Metzudat Țion explică faptul că expresia precizează «vița vinului», pentru că există și o viță de câmp, pomenită la 2 Împărați 4:39 — precizarea evită confuzia cu alte plante numite tot «viță»."}],
  [" să nu mănânce, vin sau băutură tare să nu bea, și nimic necurat să nu mănânce, tot ce i-am poruncit să păzească.”", {heb:"מִגֶּפֶן הַיַּיִן לֹא תֹאכַל וְיַיִן וְשֵׁכָר אַל תֵּשְׁתְּ וְכָל טֻמְאָה אַל תֹּאכַל כֹּל אֲשֶׁר צִוִּיתִיהָ תִּשְׁמֹר", translit:"migefen haiain lo tohal veiain veșēhar al tēște vehal tuma al tohal kol așer țivitiha tișmor", strong:"H1612", pos:"substantiv construct + substantiv + particulă negativă + verb, qal imperfect + substantiv + substantiv + particulă negativă + verb, qal jusiv + substantiv construct + substantiv + particulă negativă + verb, qal jusiv + substantiv + particulă relativă + verb, piel perfect + verb, qal imperfect", def_ro:"vița vinului, să nu mănânce; și vin și băutură tare să nu bea; și nimic necurat să nu mănânce; tot ce i-am poruncit să păzească.", dict_ro:"Metzudat David precizează clar: nu mai e nimic de adăugat, doar să păzească tot ce fusese deja poruncit — simplitatea finală a rânduielii, fără complicații suplimentare cerute de statutul special al copilului."}]
]},
{v:"13:15", newTags:[
  ["Și Manoah i-a spus îngerului DOMNULUI: „Lasă-ne să te reținem și-ți vom pregăti", {heb:"וַיֹּאמֶר מָנוֹחַ אֶל מַלְאַךְ יְהוָה נַעְצְרָה נָּא אוֹתָךְ וְנַעֲשֶׂה לְפָנֶיךָ", translit:"vaiomer manoah el malah Adonai națera na otah venaase lefaneha", strong:"H559", pos:"verb, qal imperfect consecutiv + nume propriu + prepoziție + substantiv construct + nume propriu + verb, qal cohortativ + interjecție + marcă a complementului direct + sufix + verb, qal imperfect + substantiv plural construct + sufix", def_ro:"și a spus Manoah către îngerul DOMNULUI: să te reținem, te rog, și să pregătim înaintea ta.", dict_ro:"Rashi explică faptul că Manoah vrea să-l rețină pe înger ca pe un oaspete obișnuit în casa lor — fără să suspecteze încă natura lui supranaturală, oferindu-i ospitalitate convențională."}],
  [" din turmă.”", {heb:"עִזִּים", translit:"izim", strong:"H5795", pos:"substantiv", def_ro:"de capre.", dict_ro:"Metzudat Țion explică «națera» cu sensul de a opri sau reține, ca la 1 Împărați 18:44 — «să nu te oprească ploaia» — aceeași rădăcină pentru oprirea unui oaspete înainte de plecare."}]
]},
{v:"13:16", newTags:[
  ["Dar îngerul DOMNULUI i-a spus lui Manoah: „Dacă mă reții, nu voi mânca din mâncarea ta, dar dacă vei face", {heb:"וַיֹּאמֶר מַלְאַךְ יְהוָה אֶל מָנוֹחַ אִם תַּעְצְרֵנִי לֹא אֹכַל בְּלַחְמֶךָ וְאִם תַּעֲשֶׂה", translit:"vaiomer malah Adonai el manoah im tațerēni lo ohal belahmeha veim taase", strong:"H559", pos:"verb, qal imperfect consecutiv + substantiv construct + nume propriu + prepoziție + nume propriu + conjuncție + verb, qal imperfect + sufix + particulă negativă + verb, qal imperfect + substantiv construct + sufix + conjuncție + verb, qal imperfect", def_ro:"și a spus îngerul DOMNULUI către Manoah: dacă mă vei reține, nu voi mânca din pâinea ta; și dacă vei face.", dict_ro:"Radak explică faptul că «din mâncarea ta» (lahmeha) cuprinde orice fel de mâncare, nu doar pâinea propriu-zisă — refuzul îngerului de a mânca e absolut, indiferent de natura ofrandei pregătite."}],
  [", atunci înalț-o către DOMNUL” – căci Manoah nu știa că era un înger al DOMNULUI.", {heb:"עֹלָה לַיהוָה תַּעֲלֶנָּה כִּי לֹא יָדַע מָנוֹחַ כִּי מַלְאַךְ יְהוָה הוּא", translit:"la'Adonai taalena ki lo iada manoah ki malah Adonai hu", strong:"H3068", pos:"nume propriu + verb, hifil imperfect + sufix + conjuncție + particulă negativă + verb, qal perfect + nume propriu + conjuncție + substantiv construct + nume propriu + pronume personal", def_ro:"către DOMNUL s-o înalți, căci n-a cunoscut Manoah că înger al DOMNULUI [era] el.", dict_ro:"Radak explică faptul că îngerul a spus special «către DOMNUL», pentru că generația aceea făcea rău în ochii DOMNULUI și aducea arderi-de-tot altor dumnezei — precizarea exclude orice ambiguitate despre destinatarul jertfei."}]
]},
{v:"13:17", newTags:[
  ["Și Manoah i-a spus îngerului DOMNULUI: „Care îți este numele, ca atunci când se vor adeveri vorbele tale", {heb:"וַיֹּאמֶר מָנוֹחַ אֶל מַלְאַךְ יְהוָה מִי שְׁמֶךָ כִּי יָבֹא דְבָרְךָ", translit:"vaiomer manoah el malah Adonai mi șemeha ki iavo devarha", strong:"H559", pos:"verb, qal imperfect consecutiv + nume propriu + prepoziție + substantiv construct + nume propriu + particulă interogativă + substantiv construct + sufix + conjuncție + verb, qal imperfect + substantiv construct + sufix", def_ro:"și a spus Manoah către îngerul DOMNULUI: care [este] numele tău, ca atunci când va veni cuvântul tău.", dict_ro:"Radak explică faptul că Manoah folosește «mi» (cine), nu «ma» (ce), deși gramatical ar fi cerut «ce e numele tău» — folosirea lui «mi» arată că, în ochii lui Manoah, numele unui om mare și cinstit e aproape identic cu ființa lui însăși."}]
]},
{v:"13:18", newTags:[
  ["Iar îngerul DOMNULUI i-a spus: „De ce îmi ceri numele? Este", {heb:"וַיֹּאמֶר לּוֹ מַלְאַךְ יְהוָה לָמָּה זֶּה תִּשְׁאַל לִשְׁמִי וְהוּא", translit:"vaiomer lo malah Adonai lama ze tișal lișmi vehu", strong:"H559", pos:"verb, qal imperfect consecutiv + prepoziție + sufix + substantiv construct + nume propriu + particulă interogativă + pronume demonstrativ + verb, qal imperfect + substantiv construct + sufix + pronume personal", def_ro:"și i-a spus îngerul DOMNULUI: de ce întrebi de numele meu? Și el [este].", dict_ro:"Rashi explică faptul că numele îngerului e «miraculos» pentru că se schimbă mereu, după misiunea îndeplinită la momentul respectiv — nu există un nume fix pe care Manoah l-ar putea afla și folosi."}]
]},
{v:"13:19", newTags:[
  ["Manoah a luat un ied din turmă și prinosul și le-a adus ofrandă DOMNULUI,", {heb:"וַיִּקַּח מָנוֹחַ אֶת גְּדִי הָעִזִּים וְאֶת הַמִּנְחָה וַיַּעַל עַל", translit:"vaikah manoah et gedi haizim veet haminha vaiaal al", strong:"H3947", pos:"verb, qal imperfect consecutiv + nume propriu + marcă a complementului direct + substantiv construct + substantiv + marcă a complementului direct + substantiv + verb, hifil imperfect consecutiv + prepoziție", def_ro:"și a luat Manoah iedul de capre și prinosul, și le-a înălțat pe.", dict_ro:"Radak explică faptul că aducerea unei arderi-de-tot pe o stâncă, într-o vreme când altarele de pe înălțimi erau interzise, a fost o hotărâre excepțională pentru acel moment anume — îngerul însuși indicase exact acest loc."}],
  [". Iar [îngerul] a făcut o minune, în timp ce soția lui Manoah privea.", {heb:"הַצּוּר לַיהוָה וּמַפְלִא לַעֲשׂוֹת וּמָנוֹחַ וְאִשְׁתּוֹ רֹאִים", translit:"hațur la'Adonai umafli laasot umanoah veișto roim", strong:"H6697", pos:"substantiv + nume propriu + verb, hifil participiu + verb, qal infinitiv + nume propriu + substantiv construct + sufix + verb, qal participiu", def_ro:"stâncă pentru DOMNUL, și a făcut minuni, și Manoah și soția lui priveau.", dict_ro:"Radak explică faptul că îngerul a făcut minunea scoțând chiar focul din stâncă, mistuind iedul și prinosul fără o sursă de foc obișnuită — minunea precede exact momentul înălțării lui în flacără."}]
]},
{v:"13:20", newTags:[
  ["Și a fost că atunci când", {heb:"וַיְהִי בַעֲלוֹת", translit:"vaihi vaalot", strong:"H1961", pos:"verb, qal imperfect consecutiv + verb, qal infinitiv", def_ro:"și a fost, când s-a ridicat.", dict_ro:"Radak explică precizia temporală a textului, cu prefixul «bet», care marchează exact clipa înălțării flăcării — simultaneitatea dintre urcarea focului și urcarea îngerului."}],
  [" s-a ridicat de pe altar către ceruri, îngerul DOMNULUI a urcat și el în flacăra de pe altar. Iar Manoah și soția lui priveau și au căzut cu fața la pământ.", {heb:"מֵעַל הַמִּזְבֵּחַ הַשָּׁמַיְמָה וַיַּעַל מַלְאַךְ יְהוָה בְּלַהַב הַמִּזְבֵּחַ וּמָנוֹחַ וְאִשְׁתּוֹ רֹאִים וַיִּפְּלוּ עַל פְּנֵיהֶם אָרְצָה", translit:"mēal hamizbēah hașamaima vaiaal malah Adonai belahav hamizbēah umanoah veișto roim vaiplu al penēhem arța", strong:"H5921", pos:"prepoziție + substantiv + substantiv + verb, qal imperfect consecutiv + substantiv construct + nume propriu + prepoziție + substantiv construct + substantiv + nume propriu + substantiv construct + sufix + verb, qal participiu + verb, qal imperfect consecutiv + prepoziție + substantiv plural construct + sufix + substantiv", def_ro:"de pe altar către ceruri, și a urcat îngerul DOMNULUI în flacăra altarului, și Manoah și soția lui priveau, și au cădut cu fața la pământ.", dict_ro:"Metzudat David explică faptul că Manoah și soția lui priveau exact în clipa în care îngerul s-a înălțat în flacără — gestul de a cădea cu fața la pământ e reacția firească la descoperirea bruscă a naturii lui supranaturale."}]
]},
{v:"13:21", newTags:[
  ["Îngerul DOMNULUI nu le-a mai apărut lui Manoah și soției lui și [așa] Manoah", {heb:"וְלֹא יָסַף עוֹד מַלְאַךְ יְהוָה לְהֵרָאֹה אֶל מָנוֹחַ וְאֶל אִשְׁתּוֹ אָז", translit:"velo iasaf od malah Adonai lehērao el manoah veel ișto az", strong:"H3808", pos:"particulă negativă + verb, qal perfect + adverb + substantiv construct + nume propriu + verb, nifal infinitiv + prepoziție + nume propriu + prepoziție + substantiv construct + sufix + adverb", def_ro:"și n-a mai continuat îngerul DOMNULUI să se arate lui Manoah și soției lui; atunci.", dict_ro:"Radak explică faptul că expresia «atunci Manoah a știut» se poate lega atât de urcarea îngerului în flacără, cât și de faptul că nu li s-a mai arătat din nou — ambele detalii confirmă împreună natura lui angelică."}],
  [" că este un înger al DOMNULUI.", {heb:"כִּי מַלְאַךְ יְהוָה הוּא", translit:"ki malah Adonai hu", strong:"H3588", pos:"conjuncție + substantiv construct + nume propriu + pronume personal", def_ro:"că înger al DOMNULUI [era] el.", dict_ro:"Confirmarea finală a identității îngerului vine abia după ce toate semnele — minunea focului, urcarea în flacără, neapariția ulterioară — s-au adunat laolaltă, nu dintr-o singură dovadă izolată."}]
]},
{v:"13:22", newTags:[
  ["Și Manoah i-a spus soției lui: „Vom muri negreșit, căci", {heb:"וַיֹּאמֶר מָנוֹחַ אֶל אִשְׁתּוֹ מוֹת נָמוּת כִּי", translit:"vaiomer manoah el ișto mot namut ki", strong:"H559", pos:"verb, qal imperfect consecutiv + nume propriu + prepoziție + substantiv construct + sufix + verb, qal infinitiv absolut + verb, qal imperfect + conjuncție", def_ro:"și a spus Manoah către soția lui: negreșit vom muri, căci.", dict_ro:"Fraza «mot namut», cu infinitivul absolut dublat, exprimă o certitudine disperată — Manoah e convins că văzând fața divină a încălcat o limită de netrecut."}],
  [".”", {heb:"רָאִינוּ", translit:"rainu", strong:"H7200", pos:"verb, qal perfect", def_ro:"am văzut.", dict_ro:"Metzudat David explică faptul că «Dumnezeu» din această frază se referă în realitate la un înger al lui Dumnezeu, nu la vederea directă a divinității Înseși — distincția teologică importantă pe care Manoah, în panica lui, o pierde din vedere."}]
]},
{v:"13:23", newTags:[
  ["Dar soția lui i-a spus: „Dacă DOMNUL voia să ne omoare, nu ar fi primit din mâna noastră arderea-de-tot și", {heb:"וַתֹּאמֶר לוֹ אִשְׁתּוֹ לוּ חָפֵץ יְהוָה לַהֲמִיתֵנוּ לֹא לָקַח מִיָּדֵנוּ עֹלָה וּ", translit:"vatomer lo ișto lu hafēț Adonai lahamitēnu lo lakah miadēnu ola u", strong:"H559", pos:"verb, qal imperfect consecutiv + prepoziție + sufix + substantiv construct + sufix + conjuncție + verb, qal perfect + nume propriu + verb, hifil infinitiv + sufix + particulă negativă + verb, qal perfect + substantiv construct + sufix + substantiv + conjuncție", def_ro:"și i-a spus soția lui: dacă ar fi voit DOMNUL să ne ucidă, n-ar fi primit din mâna noastră arderea-de-tot și.", dict_ro:"Metzudat Țion explică «lu» cu sensul de «dacă», ca la Judecători 8:19 — «dacă i-ați fi lăsat în viață» — construcția condițională subliniază argumentul logic al femeii: acceptarea jertfei exclude intenția de a-i ucide."}],
  [", și nici nu ne-ar fi arătat toate acestea, și nici nu ne-ar fi făcut să auzim aceste vești la vremea aceasta.”", {heb:"מִנְחָה וְלֹא הֶרְאָנוּ אֶת כָּל אֵלֶּה וְכָעֵת לֹא הִשְׁמִיעָנוּ כָּזֹאת", translit:"minha velo heranu et kal ēle vehaēt lo hișmianu kazot", strong:"H4503", pos:"substantiv + particulă negativă + verb, hifil perfect + sufix + marcă a complementului direct + substantiv construct + pronume demonstrativ + substantiv + particulă negativă + verb, hifil perfect + sufix + pronume demonstrativ", def_ro:"prinosul; și nu ne-ar fi arătat toate acestea, și la vremea aceasta nu ne-ar fi făcut să auzim ca aceasta.", dict_ro:"Rashi explică faptul că, dacă ar fi meritat să moară, DOMNUL nu le-ar fi vestit aceste vești despre nașterea unui fiu — logica femeii e simplă: o veste despre viitor exclude o pedeapsă imediată cu moartea."}]
]},
{v:"13:24", newTags:[
  ["Femeia a născut un fiu și i-a pus numele", {heb:"וַתֵּלֶד הָאִשָּׁה בֵּן וַתִּקְרָא אֶת שְׁמוֹ", translit:"vatēled haișa bēn vatikra et șemo", strong:"H3205", pos:"verb, qal imperfect consecutiv + substantiv + substantiv + verb, qal imperfect consecutiv + marcă a complementului direct + substantiv construct + sufix", def_ro:"și a născut femeia un fiu, și a chemat numele lui.", dict_ro:"Talmudul Bavli (Sota 10a) explică, prin Rabi Iohanan, faptul că numele «Șimșon» e legat de numele DOMNULUI, numit «soare» (șemeș) la Psalmii 84:11 — precum DOMNUL ocrotește lumea întreagă, așa Samson, în generația lui, a ocrotit tot Israelul."}],
  [". Și tânărul a crescut și Dumnezeu l-a binecuvântat.", {heb:"וַיִּגְדַּל הַנַּעַר וַיְבָרְכֵהוּ יְהוָה", translit:"vaigdal hanaar vaivarhēhu Adonai", strong:"H1431", pos:"verb, qal imperfect consecutiv + substantiv + verb, piel imperfect consecutiv + sufix + nume propriu", def_ro:"și a crescut tânărul, și l-a binecuvântat DOMNUL.", dict_ro:"Binecuvântarea explicită a DOMNULUI, menționată încă din copilărie, pregătește direct versetul următor, în care duhul DOMNULUI începe să-l miște pe Samson spre fapte de vitejie."}]
]},
{v:"13:25", newTags:[
  ["Și duhul DOMNULUI a început", {heb:"וַתָּחֶל רוּחַ יְהוָה", translit:"vatahel ruah Adonai", strong:"H2490", pos:"verb, hifil imperfect consecutiv + substantiv construct + nume propriu", def_ro:"și a început duhul DOMNULUI.", dict_ro:"Talmudul Bavli (Sota 9b) explică, prin Rabi Hama, fiul lui Rabi Hanina, că profeția lui Iacov despre Dan — «Dan va fi un șarpe pe drum» (Geneza 49:17) — s-a împlinit exact prin Samson, confirmând legătura dintre binecuvântarea patriarhală și fapta eroului."}],
  [" în tabăra lui Dan, între Țora și Eștaol.", {heb:"לְפַעֲמוֹ בְּמַחֲנֵה דָן בֵּין צָרְעָה וּבֵין אֶשְׁתָּאֹל", translit:"lefaamo bemahanē dan bēn țara uvēn eștaol", strong:"H6470", pos:"verb, qal infinitiv + sufix + nume propriu + nume propriu + prepoziție + nume propriu + prepoziție + nume propriu", def_ro:"să-l miște, în tabăra lui Dan, între Țora și Eștaol.", dict_ro:"Rabi Ițhak din școala lui Rabi Ami explică, în același loc talmudic, că «lefaamo» ne învață că Șehina suna înaintea lui ca un clopoțel — aceeași rădăcină fiind folosită la Exod 39:26 pentru clopoțelul de pe haina marelui preot."}]
]}
];
