module.exports = [
{v:"2:10", newTags:[
  [" și bucură-te, fiică a Ționului, căci iată-Mă, vin și voi sălășlui în mijlocul tău – rostirea DOMNULUI.", {heb:"וְשִׂמְחִי בַּת צִיּוֹן כִּי הִנְנִי בָא וְשָׁכַנְתִּי בְתוֹכֵךְ נְאֻם יְהוָה", translit:"vesimhi bat țion ki hinni va veșahanti vetohēh neum Adonai", strong:"H8055", pos:"verb, qal imperativ + substantiv construct + nume propriu + conjuncție + particulă demonstrativă + sufix + verb, qal participiu + verb, qal perfect consecutiv + substantiv construct + sufix + substantiv construct + nume propriu", def_ro:"și bucură-te, fiică a Ționului, căci iată, Eu vin și voi locui în mijlocul tău — rostirea DOMNULUI.", dict_ro:"Radak explică faptul că această profeție, până la «sălașul Său cel sfânt», privește zilele lui Mesia, pentru că «multe neamuri se vor alipi» nu s-a văzut în vremea celui de-al Doilea Templu — restul capitolului, despre Ioșua și Zerubavel, privește însă direct acea epocă istorică."}]
]},
{v:"2:11", newTags:[
  ["Multe neamuri", {heb:"גוֹיִם רַבִּים", translit:"goim rabim", strong:"H1471", pos:"substantiv plural + adjectiv plural", def_ro:"multe neamuri.", dict_ro:"Metzudat Țion explică «venilvu» cu sensul de alăturare, ca la Isaia 14:1 — «străinul se va alipi» — aceeași rădăcină pentru unirea neamurilor cu Israel în vremea mântuirii."}],
  [" de DOMNUL în ziua aceea și vor deveni popor al Meu, dar Eu voi sălășlui în mijlocul tău – și atunci vei ști că DOMNUL Oștirilor m-a trimis la tine.", {heb:"אֶל יְהוָה בַּיּוֹם הַהוּא וְהָיוּ לִי לְעָם וְשָׁכַנְתִּי בְתוֹכֵךְ וְיָדַעַתְּ כִּי יְהוָה צְבָאוֹת שְׁלָחַנִי אֵלָיִךְ", translit:"el Adonai baiom hahu vehaiu li leam veșahanti vetohēh veiadaat ki Adonai țevaot șelahani ēlaih", strong:"H413", pos:"prepoziție + nume propriu + substantiv + pronume personal + verb, qal perfect consecutiv + prepoziție + sufix + substantiv + verb, qal perfect consecutiv + substantiv construct + sufix + verb, qal perfect consecutiv + conjuncție + nume propriu + substantiv + verb, qal perfect + sufix + prepoziție + sufix", def_ro:"la DOMNUL, în ziua aceea, și vor fi pentru Mine popor, și voi locui în mijlocul tău, și vei cunoaște că DOMNUL Oștirilor m-a trimis la tine.", dict_ro:"Metzudat David explică faptul că, deși multe neamuri vor crede în DOMNUL, Șehina va locui doar în mijlocul Ționului — miezul făgăduinței de bine rămâne rezervat special pentru fiica Ționului, nu împărțit deopotrivă cu neamurile convertite."}]
]},
{v:"2:12", newTags:[
  ["DOMNUL îl va lua pe Iuda ca moștenire pentru Sine, ca parte a Sa în", {heb:"וְנָחַל יְהוָה אֶת יְהוּדָה חֶלְקוֹ עַל", translit:"venahal Adonai et iehuda helko al", strong:"H5157", pos:"verb, qal perfect consecutiv + nume propriu + marcă a complementului direct + nume propriu + substantiv construct + sufix + prepoziție", def_ro:"și va lua ca moștenire DOMNUL pe Iuda, partea Lui, pe.", dict_ro:"Radak leagă acest verset de Deuteronom 32:9 — «partea DOMNULUI este poporul Său, Iacov este partea moștenirii Lui» — și explică de ce e pomenit anume Iuda: el e capul regatelor lui Israel, și în vremea celui de-al Doilea Templu Iuda a fost cel care s-a întors din exil."}],
  [", și va alege din nou Ierusalimul.", {heb:"אַדְמַת הַקֹּדֶשׁ וּבָחַר עוֹד בִּירוּשָׁלִָם", translit:"admat hakodeș uvahar od birușalam", strong:"H127", pos:"substantiv construct + substantiv + verb, qal perfect consecutiv + adverb + nume propriu", def_ro:"țara sfântă, și va alege din nou Ierusalimul.", dict_ro:"Metzudat David explică faptul că alegerea reînnoită a Ierusalimului are scopul precis ca Șehina să-și facă din nou sălaș acolo, exact ca odinioară, înainte de exil."}]
]},
{v:"2:13", newTags:[
  [" orice vietate înaintea DOMNULUI, căci El s-a ridicat din sălașul Său cel sfânt!", {heb:"כָּל בָּשָׂר מִפְּנֵי יְהוָה כִּי נֵעוֹר מִמְּעוֹן קָדְשׁוֹ", translit:"kal basar mipnē Adonai ki nēor mimon kadșo", strong:"H3605", pos:"substantiv construct + substantiv + substantiv plural construct + nume propriu + conjuncție + verb, nifal perfect + substantiv construct + substantiv construct + sufix", def_ro:"tot trupul, dinaintea DOMNULUI, căci S-a trezit din locuința sfințeniei Lui.", dict_ro:"Radak explică expresia «S-a trezit» ca pe o pildă, asemenea unui om care se trezește din somn, exact ca la Psalmii 78:65 — «Domnul S-a trezit ca unul care a dormit» — o imagine a trecerii de la pasivitatea îngăduinței la intervenția activă."}]
]},
{v:"3:1", newTags:[
  ["Și [El] mi l-a arătat pe Marele Preot Ioșua stând înaintea unui înger al DOMNULUI, și pe", {heb:"וַיַּרְאֵנִי אֶת יְהוֹשֻׁעַ הַכֹּהֵן הַגָּדוֹל עֹמֵד לִפְנֵי מַלְאַךְ יְהוָה", translit:"vaiarēni et iehoșua hakohēn hagadol omēd lifnē malah Adonai", strong:"H7200", pos:"verb, hifil imperfect consecutiv + sufix + marcă a complementului direct + nume propriu + substantiv + adjectiv + verb, qal participiu + substantiv construct + substantiv construct + nume propriu", def_ro:"și mi-a arătat pe Ioșua, marele preot, stând înaintea îngerului DOMNULUI, și.", dict_ro:"Rashi explică faptul că Satan îl acuza pe Ioșua pentru că fiii lui se căsătoriseră cu femei dintre neamuri, potrivit Ezra 10:18 — «s-au găsit dintre fiii preoților care luaseră femei străine: dintre fiii lui Ieșua, fiul lui Ioțadak»."}],
  [" stând în dreapta lui, ca să-l acuze.", {heb:"עֹמֵד עַל יְמִינוֹ לְשִׂטְנוֹ", translit:"omēd al iemino lesitno", strong:"H5975", pos:"verb, qal participiu + prepoziție + substantiv construct + sufix + verb, qal infinitiv + sufix", def_ro:"stând la dreapta lui, ca să-l acuze.", dict_ro:"Radak explică faptul că Satan e o pildă pentru Sanbalat și tovarășii lui, care îi acuzau pe iudei și le opreau lucrarea de zidire — Targumul lui Ionatan traduce «și păcatul stătea la dreapta lui ca să-l acuze»."}]
]},
{v:"3:2", newTags:[
  ["Și DOMNUL i-a spus lui Satan: „DOMNUL te va denunța, Satan, DOMNUL care alege Ierusalimul să te denunțe din nou. Oare nu este acesta", {heb:"וַיֹּאמֶר יְהוָה אֶל הַשָּׂטָן יִגְעַר יְהוָה בְּךָ הַשָּׂטָן וְיִגְעַר יְהוָה בְּךָ הַבֹּחֵר בִּירוּשָׁלִָם הֲלוֹא זֶה", translit:"vaiomer Adonai el hasatan igar Adonai beha hasatan veigar Adonai beha habohēr birușalam halo ze", strong:"H559", pos:"verb, qal imperfect consecutiv + nume propriu + prepoziție + substantiv + verb, qal jusiv + nume propriu + prepoziție + sufix + substantiv + verb, qal jusiv + nume propriu + prepoziție + sufix + verb, qal participiu + nume propriu + particulă negativă + pronume demonstrativ", def_ro:"și a spus DOMNUL către Satan: te va mustra DOMNUL, Satan, și te va mustra DOMNUL, Cel care alege Ierusalimul. Nu [este] acesta.", dict_ro:"Talmudul Bavli (Sanhedrin 93a) relatează cum Ahab și Țedechia, profeții mincinoși, l-au ales pe Ioșua, marele preot, ca al treilea tovarăș aruncat în cuptorul lui Nebucadnețar — ei au ars, iar lui Ioșua i s-au pârlit doar hainele, exact «tăciunele salvat din foc»."}],
  [" salvat din foc?”", {heb:"מֻצָּל מֵאֵש", translit:"muțal mēēș", strong:"H5337", pos:"verb, hofal participiu pasiv + substantiv", def_ro:"scos din foc.", dict_ro:"Rashi relatează aceeași tradiție din Agada (Sanhedrin 93a): Ioșua a fost aruncat în foc împreună cu Ahab, fiul lui Colaia, și cu tovarășul lui — meritul salvării lui e temeiul direct pentru care Satan nu ar trebui să-l mai poată acuza."}]
]},
{v:"3:3", newTags:[
  ["Iar Ioșua era îmbrăcat cu", {heb:"וִיהוֹשֻׁעַ הָיָה לָבֻשׁ", translit:"vihoșua haia lavuș", strong:"H3091", pos:"nume propriu + verb, qal perfect + verb, qal participiu pasiv", def_ro:"și Ioșua era îmbrăcat.", dict_ro:"Talmudul Bavli (Sanhedrin 93a), prin Rav Papa, explică faptul că obiceiul lui Ioșua nu era să poarte haine murdare — versetul arată, de fapt, că fiii lui se căsătoreau cu femei nepotrivite pentru preoție, iar el, tatăl, nu i-a mustrat pentru aceasta."}],
  [" și stătea înaintea îngerului.", {heb:"וְעֹמֵד לִפְנֵי הַמַּלְאָךְ", translit:"veomēd lifnē hamalah", strong:"H5975", pos:"verb, qal participiu + substantiv construct + substantiv", def_ro:"și stătea înaintea îngerului.", dict_ro:"Radak explică faptul că hainele murdare sunt o pildă pentru păcatul concret al fiilor lui Ioșua, nu o descriere literală a vestimentației marelui preot — exact ca la Ezra: «dintre fiii lui Ieșua, fiul lui Ioțadak, și frații lui»."}]
]},
{v:"3:4", newTags:[
  ["Și [îngerul] a răspuns și a spus celor care stăteau înaintea lui, spunând: „Îndepărtați hainele murdare de pe el!” Și i-a spus: „Uite, am îndepărtat păcatul tău de asupra ta și te-am îmbrăcat cu", {heb:"וַיַּעַן וַיֹּאמֶר אֶל הָעֹמְדִים לְפָנָיו לֵאמֹר הָסִירוּ הַבְּגָדִים הַצֹּאִים מֵעָלָיו וַיֹּאמֶר אֵלָיו רְאֵה הֶעֱבַרְתִּי מֵעָלֶיךָ עֲוֺנֶךָ וְהַלְבֵּשׁ אֹתְךָ", translit:"vaiaan vaiomer el haomdim lefanaiv lēmor hasiru habgadim hațoim mēalaiv vaiomer ēlaiv reē heevarti mēaleha avoneha vehalbēș otha", strong:"H6030", pos:"verb, qal imperfect consecutiv + verb, qal imperfect consecutiv + prepoziție + verb, qal participiu + substantiv plural construct + sufix + verb, qal infinitiv + verb, hifil imperativ + substantiv plural + adjectiv plural + prepoziție + sufix + verb, qal imperfect consecutiv + prepoziție + sufix + verb, qal imperativ + verb, hifil perfect + prepoziție + sufix + substantiv construct + sufix + verb, hifil infinitiv absolut + marcă a complementului direct + sufix", def_ro:"și a răspuns și a spus celor ce stăteau înaintea lui, spunând: îndepărtați hainele murdare de pe el; și i-a spus: iată, am îndepărtat de la tine vina ta, și te voi îmbrăca.", dict_ro:"Rashi explică faptul că «îndepărtați hainele murdare» aluzionează la despărțirea fiilor lui Ioșua de soțiile lor străine, iar «hainele curate» reprezintă meritul care se descoperă odată vina îndepărtată — pildă construită în oglindă, haină murdară pentru păcat, haină curată pentru virtute."}]
]},
{v:"3:5", newTags:[
  ["Apoi am spus: „Să i se pună", {heb:"וָאֹמַר יָשִׂימוּ", translit:"vaomar iasimu", strong:"H559", pos:"verb, qal imperfect consecutiv + verb, qal jusiv", def_ro:"și am spus: să pună.", dict_ro:"Rashi explică faptul că profetul Zaharia însuși a cerut milă pentru Ioșua, rugându-se ca pe cap să-i fie pus un turban curat — un gest de mijlocire personală, nu doar o descriere pasivă a vedeniei."}],
  [" pe cap” și ei i-au pus un turban curat pe cap și l-au îmbrăcat cu [alte] haine; iar îngerul DOMNULUI stătea [acolo].", {heb:"עַל רֹאשׁוֹ וַיָּשִׂימוּ הַצָּנִיף הַטָּהוֹר עַל רֹאשׁוֹ וַיַּלְבִּשֻׁהוּ בְּגָדִים וּמַלְאַךְ יְהוָה עֹמֵד", translit:"al roșo vaiasimu hațanif hatahor al roșo vaialbișuhu begadim umalah Adonai omēd", strong:"H5921", pos:"prepoziție + substantiv construct + sufix + verb, qal imperfect consecutiv + substantiv + adjectiv + prepoziție + substantiv construct + sufix + verb, hifil imperfect consecutiv + sufix + substantiv plural + substantiv construct + nume propriu + verb, qal participiu", def_ro:"pe capul lui; și au pus turbanul curat pe capul lui, și l-au îmbrăcat cu haine, și îngerul DOMNULUI stătea.", dict_ro:"Radak explică faptul că, în vedenia profetică, îngerul DOMNULUI a stat de față neîntrerupt până ce turbanul curat a fost pus pe capul lui Ioșua — prezența lui continuă confirmă autoritatea asupra întregului ritual de inaugurare."}]
]},
{v:"3:6", newTags:[
  ["Și îngerul DOMNULUI", {heb:"מַלְאַךְ יְהוָה", translit:"malah Adonai", strong:"H4397", pos:"substantiv construct + nume propriu", def_ro:"îngerul DOMNULUI.", dict_ro:"Rashi explică «l-a avertizat» ca o expresie de mărturie solemnă, întocmai ca «voi lua martori împotriva lor cerul și pământul» (Deuteronom 31:28) — avertismentul care urmează are forța unui jurământ public."}],
  [" pe Ioșua, spunând:", {heb:"בִּיהוֹשֻׁעַ לֵאמֹר", translit:"bihoșua lēmor", strong:"H3091", pos:"nume propriu + verb, qal infinitiv", def_ro:"pe Ioșua, spunând.", dict_ro:"Radak explică «l-a avertizat» ca «i-a mărturisit acest lucru», comparabil cu expresia lui Iosif către frații lui: «omul acela ne-a avertizat stăruitor» (Geneza 43:3)."}]
]},
{v:"3:7", newTags:[
  ["„Așa a spus DOMNUL Oștirilor: «Dacă vei merge pe căile Mele și dacă sarcina Mea o vei păzi, atunci și tu vei judeca Templul Meu și vei păzi curțile Mele și îți voi da voie", {heb:"כֹּה אָמַר יְהוָה צְבָאוֹת אִם בִּדְרָכַי תֵּלֵךְ וְאִם אֶת מִשְׁמַרְתִּי תִשְׁמֹר וְגַם אַתָּה תָּדִין אֶת בֵּיתִי וְגַם תִּשְׁמֹר אֶת חֲצֵרָי וְנָתַתִּי לְךָ", translit:"ko amar Adonai țevaot im bidrahai tēlēh veim et mișmarti tișmor vegam ata tadin et bēti vegam tișmor et hațērai venatati leha", strong:"H3541", pos:"adverb + verb, qal perfect + nume propriu + substantiv + conjuncție + substantiv plural construct + sufix + verb, qal imperfect + conjuncție + marcă a complementului direct + substantiv construct + sufix + verb, qal imperfect + particulă afirmativă + pronume personal + verb, qal imperfect + marcă a complementului direct + substantiv construct + sufix + particulă afirmativă + verb, qal imperfect + marcă a complementului direct + substantiv plural construct + sufix + verb, qal perfect consecutiv + prepoziție + sufix", def_ro:"așa a spus DOMNUL Oștirilor: dacă pe căile Mele vei merge, și dacă sarcina Mea o vei păzi, și tu vei judeca Casa Mea, și vei păzi curțile Mele, și-ți voi da.", dict_ro:"Rashi explică faptul că «să te miști printre acești [îngeri] neclintiți» se referă, potrivit Targumului, la învierea morților — îngerul îi vestește lui Ioșua că, la învierea viitoare, va fi înviat și el, printre serafimii care nu stau niciodată jos."}],
  [" printre acești [îngeri] neclintiți.", {heb:"בֵּין הָעֹמְדִים הָאֵלֶּה", translit:"bēn haomdim haēle", strong:"H996", pos:"prepoziție + verb, qal participiu + pronume demonstrativ", def_ro:"printre cei ce stau, aceștia.", dict_ro:"Radak explică faptul că «mahlehim» înseamnă umblare și plimbare printre îngerii care «stau și dăinuie pe veci» — o aluzie la sufletul lui Ioșua, la despărțirea de trup."}]
]},
{v:"3:8", newTags:[
  ["Ascultă așadar, Ioșua, Mare Preot – tu și semenii tăi care sunt așezați înaintea ta, căci ei sunt oameni ai semnului – căci iată-Mă, aduc pe slujitorul Meu,", {heb:"שְׁמַע נָא יְהוֹשֻׁעַ הַכֹּהֵן הַגָּדוֹל אַתָּה וְרֵעֶיךָ הַיֹּשְׁבִים לְפָנֶיךָ כִּי אַנְשֵׁי מוֹפֵת הֵמָּה כִּי הִנְנִי מֵבִיא אֶת עַבְדִּי", translit:"șema na iehoșua hakohēn hagadol ata verēeha haioșvim lefaneha ki anșē mofēt hēma ki hinni mēvi et avdi", strong:"H8085", pos:"verb, qal imperativ + interjecție + nume propriu + substantiv + adjectiv + pronume personal + substantiv plural construct + sufix + verb, qal participiu + substantiv plural construct + sufix + conjuncție + substantiv plural construct + substantiv + pronume personal + conjuncție + particulă demonstrativă + sufix + verb, hifil participiu + marcă a complementului direct + substantiv construct + sufix", def_ro:"ascultă, te rog, Ioșua, marele preot, tu și tovarășii tăi care șed înaintea ta, căci oameni ai semnului [sunt] ei; căci iată, Eu aduc pe slujitorul Meu.", dict_ro:"Talmudul Bavli (Sanhedrin 93a) identifică «semenii» lui Ioșua, «oamenii semnului», cu Hanania, Mișael și Azaria — cei pentru care s-a făcut o minune asemănătoare, salvarea din cuptorul de foc."}]
]},
{v:"3:9", newTags:[
  ["Căci iată piatra pe care am pus-o în fața lui Ioșua: pe o singură piatră sunt", {heb:"כִּי הִנֵּה הָאֶבֶן אֲשֶׁר נָתַתִּי לִפְנֵי יְהוֹשֻׁעַ עַל אֶבֶן אַחַת", translit:"ki hinē haeven așer natati lifnē iehoșua al even ahat", strong:"H3588", pos:"conjuncție + particulă demonstrativă + substantiv + particulă relativă + verb, qal perfect + substantiv construct + nume propriu + prepoziție + substantiv + numeral", def_ro:"căci iată piatra pe care am pus-o înaintea lui Ioșua: pe o piatră.", dict_ro:"Rashi explică faptul că piatra se referă la temelia Casei puse în zilele lui Cirus, pe care dușmanii au oprit-o, socotind-o prea mică — potrivit Ezra 3:12 și Hagai 2:3 — iar «șapte ochi» ar fi ochii Sfântului Însuși, care va mări-o de șapte ori."}],
  ["; iată-Mă, îi voi ciopli pe ea podoaba – rostirea DOMNULUI Oștirilor – și am dat la o parte păcatul țării aceleia într-o singură zi.", {heb:"הִנְנִי מְפַתֵּחַ פִּתֻּחָהּ נְאֻם יְהוָה צְבָאוֹת וּמַשְׁתִּי אֶת עֲוֺן הָאָרֶץ הַהִיא בְּיוֹם אֶחָד", translit:"hinni mefatēah pituhah neum Adonai țevaot umaști et avon haareț hahi beom ehad", strong:"H2005", pos:"particulă demonstrativă + sufix + verb, piel participiu + substantiv construct + sufix + substantiv construct + nume propriu + substantiv + verb, qal perfect consecutiv + marcă a complementului direct + substantiv construct + substantiv + pronume personal + substantiv construct + numeral", def_ro:"iată, Eu cioplesc cioplitura ei — rostirea DOMNULUI Oștirilor — și voi îndepărta vina țării aceleia într-o singură zi.", dict_ro:"Radak citează explicația tatălui său, care a identificat exact cei șapte «ochi» ai pietrei: Ioșua, Ezra, Zerubavel, Neemia și trei profeți — Hagai, Zaharia și Maleahi — vegheind împreună asupra zidirii."}]
]},
{v:"3:10", newTags:[
  ["În ziua aceea – rostirea DOMNULUI Oștirilor – fiecare va chema pe semenul său sub vița-de-vie și sub", {heb:"בַּיּוֹם הַהוּא נְאֻם יְהוָה צְבָאוֹת תִּקְרְאוּ אִישׁ לְרֵעֵהוּ אֶל תַּחַת גֶּפֶן וְאֶל תַּחַת", translit:"baiom hahu neum Adonai țevaot tikreu iș lerēēhu el tahat gefen veel tahat", strong:"H3117", pos:"substantiv + pronume personal + substantiv construct + nume propriu + substantiv + verb, qal imperfect + substantiv + substantiv construct + sufix + prepoziție + prepoziție + substantiv + prepoziție + prepoziție", def_ro:"în ziua aceea — rostirea DOMNULUI Oștirilor — veți chema fiecare pe semenul lui sub viță, și sub.", dict_ro:"Metzudat David explică faptul că chemarea sub viță și sub smochin descrie odihna deplină în tihnă, cu fiecare șezând la umbra propriilor roade, din pricina marii păci care va domni atunci."}]
]},
{v:"4:1", newTags:[
  ["Apoi îngerul care îmi vorbise s-a întors și", {heb:"וַיָּשָׁב הַמַּלְאָךְ הַדֹּבֵר בִּי וַיְעִירֵנִי", translit:"vaiașav hamalah hadovēr bi vairēni", strong:"H7725", pos:"verb, qal imperfect consecutiv + substantiv + verb, qal participiu + prepoziție + sufix + verb, hifil imperfect consecutiv + sufix", def_ro:"și s-a întors îngerul care vorbea în mine, și m-a trezit.", dict_ro:"Radak explică faptul că, la celelalte vedenii, profetul spunea «mi-am ridicat ochii», căci vedea de la sine; la această vedenie însă, îngerul l-a trezit anume ca s-o vadă — un detaliu care arată natura ei deosebit de importantă."}],
  [", precum se deșteaptă un om din somnul lui.", {heb:"כְּאִישׁ אֲשֶׁר יֵעוֹר מִשְּׁנָתוֹ", translit:"keiș așer iēor mișnato", strong:"H376", pos:"substantiv + particulă relativă + verb, nifal imperfect + substantiv construct + sufix", def_ro:"ca un om care se trezește din somnul lui.", dict_ro:"Metzudat David explică faptul că îngerul l-a mișcat anume ca să-l trezească, iar profetul s-a trezit exact ca un om obișnuit care se deșteaptă din somn — detaliul confirmă trecerea de la o stare pasivă la una activă de observare."}]
]},
{v:"4:2", newTags:[
  ["Apoi mi-a spus: „Ce vezi?” Iar eu i-am spus: „M-am uitat și iată:", {heb:"וַיֹּאמֶר אֵלַי מָה אַתָּה רֹאֶה וָאֹמַר רָאִיתִי וְהִנֵּה", translit:"vaiomer ēlai ma ata roe vaomar raiti vehinē", strong:"H559", pos:"verb, qal imperfect consecutiv + prepoziție + sufix + particulă interogativă + pronume personal + verb, qal participiu + verb, qal imperfect consecutiv + verb, qal perfect + particulă demonstrativă", def_ro:"și mi-a spus: ce vezi? Și am spus: am văzut, și iată.", dict_ro:"Metzudat David explică faptul că întreaga descriere a sfeșnicului e primită în vedenie profetică — răspunsul profetului redă exact ce a văzut, fără adăugiri interpretative proprii."}],
  [" în întregime din aur, având bolul lui [cu untdelemn] în vârful lui și șapte candele deasupra lui; și șapte tuburi la candelele care erau la vârful lui.", {heb:"זָהָב כֻּלָּהּ וְגֻלָּהּ עַל רֹאשָׁהּ וְשִׁבְעָה נֵרֹתֶיהָ עָלֶיהָ שִׁבְעָה וְשִׁבְעָה מוּצָקוֹת לַנֵּרוֹת אֲשֶׁר עַל רֹאשָׁהּ", translit:"zahav kulah vegulah al roșah veșiva nēroteha aleha șiva veșiva muțakot lanērot așer al roșah", strong:"H2091", pos:"substantiv + substantiv construct + sufix + substantiv + prepoziție + substantiv construct + sufix + numeral + substantiv plural construct + sufix + prepoziție + sufix + numeral + numeral + substantiv plural + substantiv plural + particulă relativă + prepoziție + substantiv construct + sufix", def_ro:"de aur, toată ea, și bolul pe vârful ei, și șapte candele ale ei deasupra ei, șapte și șapte țevi pentru candele, care sunt pe vârful ei.", dict_ro:"Rashi explică faptul că, la fiecare candelă, veneau câte șapte țevi mici, prin care untdelemnul curgea din bol direct în fiecare candelă — un sistem complet automat, fără intervenție omenească, pildă pentru zidirea Templului prin duhul DOMNULUI, nu prin putere umană."}]
]},
{v:"4:3", newTags:[
  [" erau lângă el, unul în dreapta bolului și unul în stânga lui.”", {heb:"עָלֶיהָ אֶחָד מִימִין הַגֻּלָּה וְאֶחָד עַל שְׂמֹאלָהּ", translit:"aleha ehad mimin hagula veehad al semolah", strong:"H5921", pos:"prepoziție + sufix + numeral + substantiv construct + substantiv + numeral + prepoziție + substantiv construct + sufix", def_ro:"lângă ea, unul la dreapta bolului și unul la stânga ei.", dict_ro:"Rashi explică faptul că măslinele se scutură singure în teascurile de aur pomenite mai jos, untdelemnul curgând apoi din teasc în bol și din bol prin cele patruzeci și nouă de țevi în candele — o aluzie la lumina viitoare, de șapte ori mai mare decât lumina celor șapte zile ale Creației."}]
]},
{v:"4:4", newTags:[
  ["Și am răspuns și i-am spus îngerului care îmi vorbea, spunând: „Ce sunt acestea,", {heb:"וָאַעַן וָאֹמַר אֶל הַמַּלְאָךְ הַדֹּבֵר בִּי לֵאמֹר מָה אֵלֶּה", translit:"vaaan vaomar el hamalah hadovēr bi lēmor ma ēle", strong:"H6030", pos:"verb, qal imperfect consecutiv + verb, qal imperfect consecutiv + prepoziție + substantiv + verb, qal participiu + prepoziție + sufix + verb, qal infinitiv + particulă interogativă + pronume demonstrativ", def_ro:"și am răspuns și am spus către îngerul care vorbea în mine, spunând: ce [sunt] acestea.", dict_ro:"Rashi explică întrebarea profetului ca purtând nedumerire concretă: ce înseamnă faptul că măslinele se culeg singure și untdelemnul vine singur în candele, fără nicio intervenție omenească?"}]
]},
{v:"4:5", newTags:[
  ["Îngerul care îmi vorbea a răspuns și mi-a spus: „", {heb:"וַיַּעַן הַמַּלְאָךְ הַדֹּבֵר בִּי וַיֹּאמֶר אֵלַי הֲלוֹא", translit:"vaiaan hamalah hadovēr bi vaiomer ēlai halo", strong:"H6030", pos:"verb, qal imperfect consecutiv + substantiv + verb, qal participiu + prepoziție + sufix + verb, qal imperfect consecutiv + prepoziție + sufix + particulă negativă", def_ro:"și a răspuns îngerul care vorbea în mine, și mi-a spus: nu.", dict_ro:"Întrebarea retorică a îngerului — «nu știi ce sunt acestea?» — presupune că profetul ar fi trebuit să priceapă de la sine semnificația vedeniei, pregătind astfel explicația ce urmează."}],
  [" ce sunt acestea?” Iar eu i-am spus: „Nu, stăpâne.”", {heb:"יָדַעְתָּ מָה הֵמָּה אֵלֶּה וָאֹמַר לֹא אֲדֹנִי", translit:"ma hēma ēle vaomar lo adoni", strong:"H4100", pos:"particulă interogativă + pronume personal + pronume demonstrativ + verb, qal imperfect consecutiv + particulă negativă + substantiv construct + sufix", def_ro:"ce [sunt] ele, acestea? Și am spus: nu, stăpânul meu.", dict_ro:"Metzudat David explică faptul că profetul recunoaște sincer: nu a priceput de la sine la ce fac aluzie măslinii și sfeșnicul — nedumerirea lui deschide calea pentru explicația esențială a versetului următor."}]
]},
{v:"4:6", newTags:[
  ["El a răspuns și mi-a spus astfel: „Acesta este cuvântul DOMNULUI către Zerubavel, spunând: «Nu prin oștire și nu prin putere, ci numai", {heb:"וַיַּעַן וַיֹּאמֶר אֵלַי לֵאמֹר זֶה דְּבַר יְהוָה אֶל זְרֻבָּבֶל לֵאמֹר לֹא בְחַיִל וְלֹא בְכֹחַ כִּי אִם", translit:"vaiaan vaiomer ēlai lēmor ze devar Adonai el zerubavel lēmor lo vehail velo vehoah ki im", strong:"H6030", pos:"verb, qal imperfect consecutiv + verb, qal imperfect consecutiv + prepoziție + sufix + verb, qal infinitiv + pronume demonstrativ + substantiv construct + nume propriu + prepoziție + nume propriu + verb, qal infinitiv + particulă negativă + substantiv + particulă negativă + substantiv + conjuncție + conjuncție", def_ro:"și a răspuns și mi-a spus, spunând: acesta [este] cuvântul DOMNULUI către Zerubavel, spunând: nu prin oștire și nu prin putere, ci numai.", dict_ro:"Rashi explică faptul că, precum măslinele și untdelemnul se desăvârșesc singure, tot așa zidirea Casei nu se va face prin puterea omenească — DOMNUL va pune duhul Lui asupra regelui Darius, care va porunci zidirea și va plăti toate cheltuielile din vistieria lui, potrivit Ezra 6-7."}],
  ["», spune DOMNUL Oștirilor.", {heb:"אָמַר יְהוָה צְבָאוֹת", translit:"amar Adonai țevaot", strong:"H559", pos:"verb, qal perfect + nume propriu + substantiv", def_ro:"a spus DOMNUL Oștirilor.", dict_ro:"Talmudul Bavli (Sanhedrin 38a) explică faptul că numele lui Zerubavel înseamnă «semănat (nizra) în Babilon (Bavel)», adică zămislit acolo — numele lui adevărat fiind, de fapt, Neemia, fiul lui Hacalia."}]
]},
{v:"4:7", newTags:[
  ["Cine ești tu,", {heb:"מִי אַתָּה", translit:"mi ata", strong:"H4310", pos:"particulă interogativă + pronume personal", def_ro:"cine [ești] tu?", dict_ro:"Rashi identifică «muntele măreț» cu căpeteniile de dincolo de Râu — Tatenai, guvernatorul, Șetar-Boznai și tovarășii lor (Ezra 6:6) — care opriseră lucrarea de zidire până atunci."}],
  ["? Înaintea lui Zerubavel [vei deveni] loc neted! Și el va scoate piatra cea dintâi, în strigăte de „Har, har pentru ea!”", {heb:"הַגָּדוֹל לִפְנֵי זְרֻבָּבֶל לְמִישֹׁר וְהוֹצִיא אֶת הָאֶבֶן הָרֹאשָׁה תְּשֻׁאוֹת חֵן חֵן לָהּ", translit:"har hagadol lifnē zerubavel lemișor vehoți et haeven haroșa teșuot hēn hēn lah", strong:"H2022", pos:"substantiv construct + adjectiv + substantiv construct + nume propriu + substantiv + verb, hifil perfect consecutiv + marcă a complementului direct + substantiv + adjectiv + substantiv plural + substantiv + substantiv + prepoziție + sufix", def_ro:"munte mare, înaintea lui Zerubavel [vei fi] loc drept; și va scoate piatra cea de căpetenie, în strigăte: har, har pentru ea!", dict_ro:"Radak explică faptul că, precum Zerubavel a scos piatra cea dintâi la începutul zidirii, în ziua a douăzeci și patra a lunii a noua, tot așa va încheia lucrarea — dublarea «har, har» întărește strigătul de bucurie, exact ca «pace, pace celui de departe» (Isaia 57:19)."}]
]}
];
