module.exports = [
{v:"11:1", newTags:[
  ["și era fiul unei femei prostituate; și lui Ghilad i s-a născut Iefta.", {heb:"וְהוּא בֶּן אִשָּׁה זוֹנָה וַיּוֹלֶד גִּלְעָד אֶת יִפְתָּח", translit:"vehu ben ișa zona vaioled gilad et iftah", strong:"H1931", pos:"pronume personal + substantiv construct + substantiv + verb, qal participiu + verb, hifil imperfect consecutiv + nume propriu + marcă a complementului direct + nume propriu", def_ro:"și el [era] fiul unei femei desfrânate; și i-a dat naștere Ghilad lui Iefta.", dict_ro:"Radak explică faptul că mama lui Iefta era de fapt concubina lui Ghilad, numită «desfrânată» pentru că nu era căsătorită cu el prin ketuba și logodnă — potrivit unei rânduieli din Israel, femeia care se lega de un bărbat din alt trib, fără moștenire, era numită astfel."}]
]},
{v:"11:2", newTags:[
  ["Soția lui Iefta îi născuse fii, iar când fiii soției au crescut, l-au alungat pe Iefta și i-au spus: „Tu nu vei avea", {heb:"וַתֵּלֶד אֵשֶׁת גִּלְעָד לוֹ בָּנִים וַיִּגְדְּלוּ בְנֵי הָאִשָּׁה וַיְגָרְשׁוּ אֶת יִפְתָּח וַיֹּאמְרוּ לוֹ לֹא", translit:"vatēled ēșet gilad lo banim vaigdelu venē haișa vaigarșu et iftah vaiomru lo lo", strong:"H3205", pos:"verb, qal imperfect consecutiv + substantiv construct + nume propriu + prepoziție + sufix + substantiv plural + verb, qal imperfect consecutiv + substantiv plural construct + substantiv + verb, piel imperfect consecutiv + marcă a complementului direct + nume propriu + verb, qal imperfect consecutiv + prepoziție + sufix + particulă negativă", def_ro:"și i-a născut soția lui Ghilad fii lui, și au crescut fiii femeii, și l-au alungat pe Iefta, și i-au spus: nu.", dict_ro:"Metzudat David explică faptul că frații vitregi, chiar alungându-l cu forța, au cruțat onoarea tatălui lor și n-au pomenit cuvântul «desfrânată», spunând în schimb doar «fiul unei alte femei»."}]
]},
{v:"11:3", newTags:[
  ["Iefta a plecat din pricina fraților săi și s-a așezat în ținutul Tov, și niște", {heb:"וַיִּבְרַח יִפְתָּח מִפְּנֵי אֶחָיו וַיֵּשֶׁב בְּאֶרֶץ טוֹב וַיִּתְלַקְּטוּ אֶל יִפְתָּח אֲנָשִׁים", translit:"vaivrah iftah mipnē ehaiv vaiēșev beereț tov vaitlaktu el iftah anașim", strong:"H1272", pos:"verb, qal imperfect consecutiv + nume propriu + substantiv plural construct + substantiv plural construct + sufix + verb, qal imperfect consecutiv + substantiv construct + nume propriu + verb, hitpael imperfect consecutiv + prepoziție + nume propriu + substantiv plural", def_ro:"și a fugit Iefta dinaintea fraților lui și a locuit în țara Tov, și s-au adunat la Iefta bărbați.", dict_ro:"Radak explică faptul că «Tov» era numele stăpânului acelui ținut, nu doar un cuvânt comun — Targumul traduce identic la Rut 3:13, «dacă te va răscumpăra Tov», confirmând că e un nume propriu."}]
]},
{v:"11:4", newTags:[
  ["Iar după un timp,", {heb:"וַיְהִי מִיָּמִים", translit:"vaihi miamim", strong:"H1961", pos:"verb, qal imperfect consecutiv + substantiv plural", def_ro:"și a fost, după zile.", dict_ro:"Metzudat David explică faptul că războiul copiilor lui Amon cu Israel a avut loc la sfârșitul multor zile după alungarea lui Iefta — un interval lung, nu imediat după exilul lui din casa tatălui."}],
  [" au făcut război cu Israel.", {heb:"וַיִּלָּחֲמוּ עִם יִשְׂרָאֵל", translit:"vailahamu im israēl", strong:"H3898", pos:"verb, nifal imperfect consecutiv + prepoziție + nume propriu", def_ro:"și s-au luptat cu Israel.", dict_ro:"Acest conflict reface legătura cu episodul anterior din carte, pregătind nevoia neașteptată a Ghiladului de a-l chema înapoi exact pe cel pe care-l respinseseră."}]
]},
{v:"11:5", newTags:[
  ["Și când copiii lui Amon au făcut război cu Israel,", {heb:"וַיְהִי כַּאֲשֶׁר נִלְחֲמוּ בְנֵי עַמּוֹן עִם יִשְׂרָאֵל", translit:"vaihi kaașer nilhamu venē amon im israēl", strong:"H1961", pos:"verb, qal imperfect consecutiv + particulă relativă + verb, nifal perfect + substantiv plural construct + nume propriu + prepoziție + nume propriu", def_ro:"și a fost, când s-au luptat copiii lui Amon cu Israel.", dict_ro:"Repetarea exactă a motivului conflictului, de la versetul precedent, marchează trecerea narativă către decizia bătrânilor de a-l chema pe Iefta — necesitatea militară devine motorul reconcilierii."}],
  [" au mers să îl aducă pe Iefta din ținutul Tov.", {heb:"וַיֵּלְכוּ לָקַחַת אֶת יִפְתָּח מֵאֶרֶץ טוֹב", translit:"vaiēlhu lakahat et iftah mēereț tov", strong:"H3212", pos:"verb, qal imperfect consecutiv + verb, qal infinitiv + marcă a complementului direct + nume propriu + substantiv construct + nume propriu", def_ro:"și au mers să-l ia pe Iefta din țara Tov.", dict_ro:"Metzudat David explică faptul că scopul lor era să-l «întoarcă în Ghilad» — nu doar să-l consulte, ci să-l readucă definitiv în ținutul din care fusese alungat."}]
]},
{v:"11:6", newTags:[
  ["Și i-au spus lui Iefta: „Mergi și fii", {heb:"וַיֹּאמְרוּ לְיִפְתָּח לְכָה וְהָיִיתָה לָּנוּ", translit:"vaiomru leiftah leha vehaita lanu", strong:"H559", pos:"verb, qal imperfect consecutiv + prepoziție + nume propriu + verb, qal imperativ + sufix + verb, qal perfect consecutiv + prepoziție + sufix", def_ro:"și au spus lui Iefta: vino și fii pentru noi.", dict_ro:"Metzudat Țion explică «lekațin» cu sensul de stăpânire, întocmai ca la Isaia 3:6 — «fii căpetenia noastră» — un titlu de conducere militară imediată, nu doar o funcție onorifică."}],
  [" noastră, ca să ne luptăm cu copiii lui Amon.”", {heb:"לְקָצִין וְנִלָּחֲמָה בִּבְנֵי עַמּוֹן", translit:"lekațin venilahama bivnē amon", strong:"H7101", pos:"substantiv + verb, nifal cohortativ + prepoziție + substantiv plural construct + nume propriu", def_ro:"căpetenie, și să ne luptăm cu copiii lui Amon.", dict_ro:"Cererea directă, fără nicio recunoaștere a nedreptății trecute, pregătește reacția amară a lui Iefta din versetul următor — bătrânii caută ajutor practic, nu împăcare sinceră."}]
]},
{v:"11:7", newTags:[
  ["Dar Iefta le-a spus bătrânilor Ghiladului: „Oare nu voi sunteți cei care m-ați urât și care m-ați alungat din casa tatălui meu? De ce ați venit la mine acum, când sunteți", {heb:"וַיֹּאמֶר יִפְתָּח לְזִקְנֵי גִלְעָד הֲלֹא אַתֶּם שְׂנֵאתֶם אוֹתִי וַתְּגָרְשׁוּנִי מִבֵּית אָבִי וּמַדּוּעַ בָּאתֶם אֵלַי עַתָּה כַּאֲשֶׁר", translit:"vaiomer iftah leziknē gilad halo atem senētem oti vatgarșuni mibēt avi umadua vatem ēlai ata kaașer", strong:"H559", pos:"verb, qal imperfect consecutiv + nume propriu + prepoziție + adjectiv plural + nume propriu + particulă negativă + pronume personal + verb, qal perfect + marcă a complementului direct + sufix + verb, piel imperfect consecutiv + sufix + substantiv construct + substantiv construct + sufix + adverb + verb, qal perfect + prepoziție + sufix + adverb + particulă relativă", def_ro:"și a spus Iefta către bătrânii Ghiladului: nu sunteți voi cei ce m-ați urât și m-ați alungat din casa tatălui meu? Și de ce ați venit la mine acum, când.", dict_ro:"Metzudat David explică faptul că întrebarea lui Iefta demască exact motivația bătrânilor: dacă s-ar fi căit sincer, n-ar fi întârziat atâta vreme — venirea lor abia «la ananghie», nu înainte, arată că necesitatea militară, nu remușcarea, i-a adus."}]
]},
{v:"11:8", newTags:[
  ["Atunci bătrânii Ghiladului i-au spus lui Iefta: „De aceasta ne-am întors la tine acum, pentru ca să mergi cu noi și să lupți împotriva copiilor lui Amon și să ne fii", {heb:"וַיֹּאמְרוּ זִקְנֵי גִלְעָד אֶל יִפְתָּח לָכֵן עַתָּה שַׁבְנוּ אֵלֶיךָ וְהָלַכְתָּ עִמָּנוּ וְנִלְחַמְתָּ בִּבְנֵי עַמּוֹן וְהָיִיתָ לָּנוּ", translit:"vaiomru ziknē gilad el iftah lahēn ata șavnu ēleha vehalahta imanu venilhamta bivnē amon vehaita lanu", strong:"H559", pos:"verb, qal imperfect consecutiv + adjectiv plural + nume propriu + prepoziție + nume propriu + adverb + adverb + verb, qal perfect + prepoziție + sufix + verb, qal perfect consecutiv + prepoziție + sufix + verb, nifal perfect consecutiv + prepoziție + substantiv plural construct + nume propriu + verb, qal perfect consecutiv + prepoziție + sufix", def_ro:"și au spus bătrânii Ghiladului către Iefta: de aceea ne-am întors la tine acum, și vei merge cu noi și te vei lupta cu copiii lui Amon, și vei fi pentru noi.", dict_ro:"Metzudat David explică faptul că bătrânii vin personal, nu trimit doar un mesaj — gestul arată o supunere și o dragoste deosebite, nu doar o cerere de nevoie, iar oferta se extinde «peste toți locuitorii Ghiladului», nu doar peste cei prezenți."}]
]},
{v:"11:9", newTags:[
  ["Iar Iefta le-a spus bătrânilor Ghiladului: „Dacă", {heb:"וַיֹּאמֶר יִפְתָּח אֶל זִקְנֵי גִלְעָד אִם", translit:"vaiomer iftah el ziknē gilad im", strong:"H559", pos:"verb, qal imperfect consecutiv + nume propriu + prepoziție + adjectiv plural + nume propriu + conjuncție", def_ro:"și a spus Iefta către bătrânii Ghiladului: dacă.", dict_ro:"Metzudat David explică faptul că Iefta cere ca stăpânirea să-i fie dată imediat, nu abia după victorie — altfel, dacă ar fi învins, bătrânii nu l-ar fi mai dorit, iar dacă ar fi învins, dreptul i s-ar cuveni fără discuție; de aceea cere condiția rostită clar de la început."}],
  [" pentru ca să lupt cu copiii lui Amon și îi dă DOMNUL înaintea mea, atunci voi fi căpetenia voastră.”", {heb:"אַתֶּם מְשִׁיבִים אוֹתִי לְהִלָּחֵם בִּבְנֵי עַמּוֹן וְנָתַן יְהוָה אוֹתָם לְפָנָי אָנֹכִי אֶהְיֶה לָכֶם לְרֹאשׁ", translit:"atem meșivim oti lehilahēm bivnē amon venatan Adonai otam lefanai anohi ehie lahem leroș", strong:"H859", pos:"pronume personal + verb, hifil participiu + marcă a complementului direct + sufix + verb, nifal infinitiv + prepoziție + substantiv plural construct + nume propriu + verb, qal perfect consecutiv + nume propriu + marcă a complementului direct + sufix + substantiv construct + sufix + pronume personal + verb, qal imperfect + prepoziție + sufix + substantiv", def_ro:"voi mă aduceți înapoi ca să lupt cu copiii lui Amon, și-i va da DOMNUL înaintea mea, eu voi fi pentru voi căpetenie.", dict_ro:"Condiția pusă explicit de Iefta — stăpânirea înainte de luptă, nu după — arată un om prudent, care nu se încrede în recunoștința viitoare a celor care l-au respins deja o dată."}]
]},
{v:"11:10", newTags:[
  ["Bătrânii Ghiladului i-au spus lui Iefta: „DOMNUL să fie", {heb:"וַיֹּאמְרוּ זִקְנֵי גִלְעָד אֶל יִפְתָּח יְהוָה יִהְיֶה", translit:"vaiomru ziknē gilad el iftah Adonai ihie", strong:"H559", pos:"verb, qal imperfect consecutiv + adjectiv plural + nume propriu + prepoziție + nume propriu + nume propriu + verb, qal imperfect", def_ro:"și au spus bătrânii Ghiladului către Iefta: DOMNUL va fi.", dict_ro:"Metzudat David explică faptul că bătrânii acceptă condiția lui Iefta fără obiecție — jurământul luat pe DOMNUL confirmă seriozitatea promisiunii lor de a-l face conducător imediat, nu abia după victorie."}],
  [" între noi dacă nu vom face precum vorba voastră.”", {heb:"שֹׁמֵעַ בֵּינוֹתֵינוּ אִם לֹא כִדְבָרְךָ כֵּן נַעֲשֶׂה", translit:"șomēa bēnotēnu im lo hidvarha kēn naase", strong:"H8085", pos:"verb, qal participiu + prepoziție + sufix + conjuncție + particulă negativă + substantiv construct + sufix + particulă demonstrativă + verb, qal imperfect", def_ro:"martor între noi, dacă nu vom face după cuvântul tău, așa.", dict_ro:"Jurământul reciproc pune ambele părți sub aceeași obligație — bătrânii se leagă public, înaintea DOMNULUI, să respecte întocmai condiția pe care Iefta a cerut-o."}]
]},
{v:"11:11", newTags:[
  ["Așa că Iefta a mers cu bătrânii Ghiladului și poporul l-a pus căpetenie și conducător peste ei; apoi Iefta a vorbit toate aceste vorbe înaintea DOMNULUI,", {heb:"וַיֵּלֶךְ יִפְתָּח עִם זִקְנֵי גִלְעָד וַיָּשִׂימוּ הָעָם אוֹתוֹ עֲלֵיהֶם לְרֹאשׁ וּלְקָצִין וַיְדַבֵּר יִפְתָּח אֶת כָּל דְּבָרָיו לִפְנֵי יְהוָה", translit:"vaiēleh iftah im ziknē gilad vaiasimu haam oto alēhem leroș ulkațin vaidabēr iftah et kal devaraiv lifnē Adonai", strong:"H3212", pos:"verb, qal imperfect consecutiv + nume propriu + prepoziție + adjectiv plural + nume propriu + verb, qal imperfect consecutiv + substantiv + marcă a complementului direct + sufix + prepoziție + sufix + substantiv + substantiv + verb, piel imperfect consecutiv + nume propriu + marcă a complementului direct + substantiv construct + substantiv plural construct + sufix + substantiv construct + nume propriu", def_ro:"și a mers Iefta cu bătrânii Ghiladului, și l-a pus poporul peste ei căpetenie și conducător; și a vorbit Iefta toate cuvintele lui înaintea DOMNULUI.", dict_ro:"Metzudat David explică faptul că poporul l-a făcut conducător «de îndată», înainte de a ieși la război, exact cum Iefta cerea — iar «înaintea DOMNULUI» confirmă prezența Șehinei peste majoritatea obștii adunate la Mițpa, potrivit tratatului Sanhedrin (39a)."}]
]},
{v:"11:12", newTags:[
  ["Iefta a trimis", {heb:"וַיִּשְׁלַח יִפְתָּח", translit:"vaișlah iftah", strong:"H7971", pos:"verb, qal imperfect consecutiv + nume propriu", def_ro:"și a trimis Iefta.", dict_ro:"Trecerea de la confirmarea internă a conducerii la trimiterea solilor externi marchează începutul diplomatic al conflictului — Iefta încearcă mai întâi calea pașnică, nu atacul direct."}],
  [" la regele copiilor lui Amon, spunând: „Ce este între mine și tine, de ai venit să lupți împotriva țării mele?”", {heb:"אֶל מֶלֶךְ בְּנֵי עַמּוֹן לֵאמֹר מַה לִּי וָלָךְ כִּי בָאתָ אֵלַי לְהִלָּחֵם בְּאַרְצִי", translit:"el meleh benē amon lēmor ma li valah ki vata ēlai lehilahēm bearți", strong:"H413", pos:"prepoziție + substantiv construct + substantiv plural construct + nume propriu + verb, qal infinitiv + particulă interogativă + prepoziție + sufix + prepoziție + sufix + conjuncție + verb, qal perfect + prepoziție + sufix + verb, nifal infinitiv + prepoziție + sufix", def_ro:"la regele copiilor lui Amon, spunând: ce [este] între mine și tine, că ai venit la mine ca să te lupți cu țara mea?", dict_ro:"Metzudat David explică faptul că, pentru că fusese numit căpetenie, Iefta pune problema «pe seama lui însuși», ca și cum conflictul ar fi personal între el și regele amonit, nu între popoare — un gest care îi arată acum rolul de reprezentant deplin al Ghiladului."}]
]},
{v:"11:13", newTags:[
  ["Regele copiilor lui Amon i-a spus solilor lui Iefta: „Pentru că Israel mi-a luat pământul când a urcat din Egipt, de la Arnon până la", {heb:"וַיֹּאמֶר מֶלֶךְ בְּנֵי עַמּוֹן אֶל מַלְאֲכֵי יִפְתָּח כִּי לָקַח יִשְׂרָאֵל אֶת אַרְצִי בַּעֲלוֹתוֹ מִמִּצְרַיִם מֵאַרְנוֹן וְעַד", translit:"vaiomer meleh benē amon el malahē iftah ki lakah israēl et arți baaloto mimițraim mēarnon vead", strong:"H559", pos:"verb, qal imperfect consecutiv + substantiv construct + substantiv plural construct + nume propriu + prepoziție + substantiv plural construct + nume propriu + conjuncție + verb, qal perfect + nume propriu + marcă a complementului direct + substantiv construct + sufix + verb, qal infinitiv + sufix + nume propriu + nume propriu + prepoziție", def_ro:"și a spus regele copiilor lui Amon către solii lui Iefta: căci a luat Israel țara mea la suirea lui din Egipt, de la Arnon până la.", dict_ro:"Radak explică faptul că regele amonit cere, de fapt, un ținut care se numea după Moab, nu direct al lui Amon — Iefta va răspunde arătând că acel teritoriu fusese luat de regele amoriților de la Moab, iar Israel l-a luat apoi de la amoriți, deci revendicarea lui e fără temei dublu."}],
  [", până la Iordan, așa că acum dă-l înapoi pașnic.”", {heb:"הַיַּבֹּק וְעַד הַיַּרְדֵּן וְעַתָּה הָשִׁיבָה אֶתְהֶן בְּשָׁלוֹם", translit:"haiabok vead haiardēn veata hașiva ethen beșalom", strong:"H2999", pos:"nume propriu + prepoziție + nume propriu + adverb + verb, hifil imperativ + sufix + marcă a complementului direct + sufix + substantiv", def_ro:"Iabok și până la Iordan, și acum dă-le înapoi în pace.", dict_ro:"Metzudat David explică «pașnic» ca «fără ceartă și război» — regele amonit propune o rezolvare diplomatică, cerând retragerea voluntară a lui Israel, nu o confrontare militară imediată."}]
]},
{v:"11:14", newTags:[
  ["Apoi Iefta a trimis", {heb:"יִפְתָּח", translit:"iftah", strong:"H3316", pos:"nume propriu", def_ro:"Iefta.", dict_ro:"Repetarea trimiterii solilor arată că Iefta insistă pe calea diplomatică, oferind un răspuns complet și argumentat, nu o ruptură imediată a negocierilor."}],
  [" soli la regele copiilor lui Amon.", {heb:"וַיִּשְׁלַח מַלְאָכִים אֶל מֶלֶךְ בְּנֵי עַמּוֹן", translit:"vaișlah malahim el meleh benē amon", strong:"H7971", pos:"verb, qal imperfect consecutiv + substantiv plural + prepoziție + substantiv construct + substantiv plural construct + nume propriu", def_ro:"și a trimis soli la regele copiilor lui Amon.", dict_ro:"Al doilea mesaj al lui Iefta aduce acum argumentul istoric detaliat, nu doar întrebarea retorică inițială din primul schimb de soli."}]
]},
{v:"11:15", newTags:[
  ["Și i-a spus: „Așa a spus Iefta: «Israel nu a luat", {heb:"וַיֹּאמֶר לוֹ כֹּה אָמַר יִפְתָּח לֹא לָקַח יִשְׂרָאֵל אֶת אֶרֶץ", translit:"vaiomer lo ko amar iftah lo lakah israēl et ereț", strong:"H559", pos:"verb, qal imperfect consecutiv + prepoziție + sufix + adverb + verb, qal perfect + nume propriu + particulă negativă + verb, qal perfect + nume propriu + marcă a complementului direct + substantiv construct", def_ro:"și i-a spus: așa a spus Iefta: n-a luat Israel țara.", dict_ro:"Metzudat David explică faptul că, dacă acel ținut fusese odinioară al Moabului și al lui Amon, el nu mai era al lor în momentul când Israel l-a luat — detaliul istoric precis urmează imediat în versetele următoare."}],
  [" și nici țara copiilor lui Amon.", {heb:"וְאֶת אֶרֶץ בְּנֵי עַמּוֹן", translit:"veet ereț benē amon", strong:"H853", pos:"marcă a complementului direct + substantiv construct + substantiv plural construct + nume propriu", def_ro:"și nici țara copiilor lui Amon.", dict_ro:"Radak explică faptul că regele amonit cerea, de fapt, un teritoriu numit după Moab — Iefta va arăta imediat că acel ținut fusese luat de amoriți de la Moab, nu de Israel de la Amon direct."}]
]},
{v:"11:16", newTags:[
  ["Căci atunci când Israel a urcat din Egipt, Israel a mers în deșert până la Marea Trestiilor și au ajuns la", {heb:"כִּי בַּעֲלוֹתָם מִמִּצְרָיִם וַיֵּלֶךְ יִשְׂרָאֵל בַּמִּדְבָּר עַד יַם סוּף וַיָּבֹא", translit:"ki baalotam mimițraim vaiēleh israēl bamidbar ad iam suf vaiavo", strong:"H3588", pos:"conjuncție + verb, qal infinitiv + sufix + nume propriu + verb, qal imperfect consecutiv + nume propriu + substantiv + prepoziție + substantiv construct + substantiv + verb, qal imperfect consecutiv", def_ro:"căci la suirea lor din Egipt, și a mers Israel în pustie până la Marea Trestiilor, și a venit.", dict_ro:"Radak explică faptul că, deși Marea Trestiilor fusese deja trecută, textul spune «până la» pentru că Israel n-a trecut-o de-a latul, ci a ieșit pe aceeași latură pe care intrase — un detaliu geografic precis care corectează o neînțelegere posibilă."}]
]},
{v:"11:17", newTags:[
  ["Israel a trimis soli la regele", {heb:"וַיִּשְׁלַח יִשְׂרָאֵל מַלְאָכִים אֶל מֶלֶךְ", translit:"vaișlah israēl malahim el meleh", strong:"H7971", pos:"verb, qal imperfect consecutiv + nume propriu + substantiv plural + prepoziție + substantiv construct", def_ro:"și a trimis Israel soli la regele.", dict_ro:"Repetarea tiparului diplomatic — cerere pașnică, refuz — pregătește argumentul principal al lui Iefta: Israel n-a cucerit nimic cu forța, ci doar a cerut trecere, refuzată de fiecare dată."}],
  [", spunând: ‘Lasă-mă, te rog, să trec prin țara ta’, însă regele Edomului nu a ascultat. Și regelui Moabului i-a trimis soli, dar nici el nu i-a îngăduit, așa că Israel a pribegit în Kadeș.", {heb:"לֵאמֹר אֶעְבְּרָה נָּא בְאַרְצֶךָ וְלֹא שָׁמַע מֶלֶךְ אֱדוֹם וְגַם אֶל מֶלֶךְ מוֹאָב שָׁלַח וְלֹא אָבָה וַיֵּשֶׁב יִשְׂרָאֵל בְּקָדֵשׁ", translit:"lēmor ebera na vearțeha velo șama meleh edom vegam el meleh moav șalah velo ava vaiēșev israēl bekadēș", strong:"H559", pos:"verb, qal infinitiv + verb, qal cohortativ + interjecție + substantiv construct + sufix + particulă negativă + verb, qal perfect + substantiv construct + nume propriu + particulă afirmativă + prepoziție + substantiv construct + nume propriu + verb, qal perfect + particulă negativă + verb, qal perfect + verb, qal imperfect consecutiv + nume propriu + nume propriu", def_ro:"spunând: voi trece, te rog, prin țara ta; și n-a ascultat regele Edomului; și a trimis și la regele Moabului, și n-a voit; și a locuit Israel la Kadeș.", dict_ro:"Rashi leagă acest refuz dublu de cuvintele lui Moise din Deuteronom 2:29 — «cum mi-au făcut fiii lui Esau care locuiesc în Seir și moabiții care locuiesc în Ar» — același refuz de trecere, documentat deja în Tora, confirmă istoric argumentul lui Iefta."}]
]},
{v:"11:18", newTags:[
  ["A mers prin deșert și a mers în jurul țării Edomului și țării Moabului, și a ajuns la latura de răsărit a țării Moabului, unde și-a așezat tabăra dincolo de", {heb:"וַיֵּלֶךְ בַּמִּדְבָּר וַיָּסָב אֶת אֶרֶץ אֱדוֹם וְאֶת אֶרֶץ מוֹאָב וַיָּבֹא מִמִּזְרַח שֶׁמֶשׁ לְאֶרֶץ מוֹאָב וַיַּחֲנוּן בְּעֵבֶר", translit:"vaiēleh bamidbar vaiasav et ereț edom veet ereț moav vaiavo mimizrah șemeș leereț moav vaiahanun beēver", strong:"H3212", pos:"verb, qal imperfect consecutiv + substantiv + verb, qal imperfect consecutiv + marcă a complementului direct + substantiv construct + nume propriu + marcă a complementului direct + substantiv construct + nume propriu + verb, qal imperfect consecutiv + substantiv construct + substantiv + substantiv construct + nume propriu + verb, qal imperfect consecutiv + substantiv construct", def_ro:"și a mers în pustie, și a înconjurat țara Edomului și țara Moabului, și a venit de la răsăritul soarelui spre țara Moabului, și au tăbărât dincolo de.", dict_ro:"Rashi detaliază traseul exact: Israel a mers de-a lungul hotarelor de sud ale Edomului și Moabului, apoi, la colțul de sud-est, a cotit spre nord pe marginea hotarului de răsărit, până la capătul teritoriului moabit — acolo unde începeau țările lui Sihon și Og."}],
  ["; dar nu au intrat în hotarul Moabului, căci Arnon este hotarul Moabului.", {heb:"וְלֹא בָאוּ בִּגְבוּל מוֹאָב כִּי אַרְנוֹן גְּבוּל מוֹאָב", translit:"velo vau bigvul moav ki arnon gevul moav", strong:"H3808", pos:"particulă negativă + verb, qal perfect + prepoziție + substantiv construct + nume propriu + conjuncție + nume propriu + substantiv construct + nume propriu", def_ro:"și n-au venit în hotarul Moabului, căci Arnon [este] hotarul Moabului.", dict_ro:"Metzudat David precizează clar: Arnonul marchează începutul hotarului moabit, iar Israel a tăbărât exact de partea cealaltă — confirmare geografică exactă că n-au călcat niciodată teritoriul Moabului propriu-zis."}]
]},
{v:"11:19", newTags:[
  ["Și Israel a trimis soli la", {heb:"וַיִּשְׁלַח יִשְׂרָאֵל מַלְאָכִים אֶל", translit:"vaișlah israēl malahim el", strong:"H7971", pos:"verb, qal imperfect consecutiv + nume propriu + substantiv plural + prepoziție", def_ro:"și a trimis Israel soli la.", dict_ro:"Al treilea episod de trimitere a solilor în același capitol confirmă tiparul constant al lui Israel: cerere pașnică de trecere, înainte de orice confruntare militară — comportamentul care contrazice direct acuzația regelui amonit."}],
  [", regele amoriților, regele Heșbonului, și Israel i-a spus: ‘Dă-mi voie, te rog, să trec prin țara ta, până [voi ajunge] la locul meu’.", {heb:"סִיחוֹן מֶלֶךְ הָאֱמֹרִי מֶלֶךְ חֶשְׁבּוֹן וַיֹּאמֶר לוֹ יִשְׂרָאֵל נַעְבְּרָה נָּא בְאַרְצְךָ עַד מְקוֹמִי", translit:"sihon meleh haemori meleh heșbon vaiomer lo israēl nabera na vearțeha ad mekomi", strong:"H5511", pos:"nume propriu + substantiv construct + nume de neam + substantiv construct + nume propriu + verb, qal imperfect consecutiv + prepoziție + sufix + nume propriu + verb, qal cohortativ + interjecție + substantiv construct + sufix + prepoziție + substantiv construct + sufix", def_ro:"Sihon, regele amoriților, regele Heșbonului, și i-a spus Israel: vom trece, te rog, prin țara ta, până la locul meu.", dict_ro:"Metzudat David explică «locul meu» ca referindu-se la țara Canaanului, locul pe care DOMNUL îl promisese deja lui Israel — cererea nu era pentru cucerire, ci pentru trecere simplă spre destinația rânduită."}]
]},
{v:"11:20", newTags:[
  ["Dar Sihon nu l-a crezut pe Israel că [doar] va trece prin hotarul său, ci Sihon și-a adunat poporul și și-au așezat tabăra la", {heb:"וְלֹא הֶאֱמִין סִיחוֹן אֶת יִשְׂרָאֵל עֲבֹר בִּגְבֻלוֹ וַיֶּאֱסֹף סִיחוֹן אֶת כָּל עַמּוֹ וַיַּחֲנוּ בְּיָהְצָה", translit:"velo heemin sihon et israēl avor bigvulo vaieesof sihon et kal amo vaiahanu beiahța", strong:"H3808", pos:"particulă negativă + verb, hifil perfect + nume propriu + marcă a complementului direct + nume propriu + verb, qal infinitiv + substantiv construct + sufix + verb, qal imperfect consecutiv + nume propriu + marcă a complementului direct + substantiv construct + sufix + verb, qal imperfect consecutiv", def_ro:"și n-a crezut Sihon pe Israel să treacă prin hotarul lui, și a adunat Sihon tot poporul lui, și au tăbărât la Iahaț.", dict_ro:"Metzudat David explică faptul că Sihon a socotit cererea de trecere drept o înșelătorie, crezând că israeliții veneau de fapt să-i cucerească țara — neîncrederea lui, nu agresivitatea lui Israel, a provocat războiul care a urmat."}],
  [" și s-a luptat cu Israel.", {heb:"וַיִּלָּחֶם עִם יִשְׂרָאֵל", translit:"vailahem im israēl", strong:"H3898", pos:"verb, nifal imperfect consecutiv + prepoziție + nume propriu", def_ro:"și s-a luptat cu Israel.", dict_ro:"Confrontarea militară a fost declanșată exclusiv de Sihon, nu de Israel — detaliu esențial al argumentului lui Iefta, care arată că teritoriul a fost câștigat în apărare, nu prin agresiune."}]
]},
{v:"11:21", newTags:[
  ["Atunci DOMNUL, Dumnezeul lui Israel, l-a dat pe Sihon și tot poporul său în mâna lui Israel și ei i-au lovit, și Israel a luat în stăpânire toată țara", {heb:"וַיִּתֵּן יְהוָה אֱלֹהֵי יִשְׂרָאֵל אֶת סִיחוֹן וְאֶת כָּל עַמּוֹ בְּיַד יִשְׂרָאֵל וַיַּכּוּם וַיִּירַשׁ יִשְׂרָאֵל אֵת כָּל אֶרֶץ", translit:"vaitēn Adonai elohē israēl et sihon veet kal amo beiad israēl vaiakum vairaș israēl ēt kal ereț", strong:"H5414", pos:"verb, qal imperfect consecutiv + nume propriu + substantiv plural construct + nume propriu + marcă a complementului direct + nume propriu + marcă a complementului direct + substantiv construct + sufix + substantiv construct + nume propriu + verb, hifil imperfect consecutiv + sufix + verb, qal imperfect consecutiv + nume propriu + marcă a complementului direct + substantiv construct + substantiv construct", def_ro:"și a dat DOMNUL, Dumnezeul lui Israel, pe Sihon și tot poporul lui în mâna lui Israel, și i-au lovit, și a moștenit Israel toată țara.", dict_ro:"Argumentul central al lui Iefta se consolidează aici: țara n-a fost luată direct de la Moab sau Amon, ci de la Sihon, regele amoriților, după ce acesta a atacat primul — teritoriul a trecut legitim în mâna lui Israel prin victorie dreaptă."}]
]},
{v:"11:22", newTags:[
  ["Și au luat în stăpânire tot hotarul amoriților, de la Arnon până la Iabok, și de la", {heb:"וַיִּירְשׁוּ אֵת כָּל גְּבוּל הָאֱמֹרִי מֵאַרְנוֹן וְעַד הַיַּבֹּק וּמִן", translit:"vairșu ēt kal gevul haemori mēarnon vead haiabok umin", strong:"H3423", pos:"verb, qal imperfect consecutiv + marcă a complementului direct + substantiv construct + substantiv construct + nume de neam + nume propriu + prepoziție + nume propriu + prepoziție", def_ro:"și au moștenit tot hotarul amoriților, de la Arnon până la Iabok, și de la.", dict_ro:"Rashi explică faptul că teritoriul pe care regele amonit îl pretinde ca fiind al lui a fost luat, de fapt, de la Sihon, nu direct de la Amon — argumentul lui Iefta precizează exact limitele geografice ale moștenirii legitime."}]
]},
{v:"11:23", newTags:[
  ["Și acum, când DOMNUL, Dumnezeul lui Israel,", {heb:"וְעַתָּה יְהוָה אֱלֹהֵי יִשְׂרָאֵל", translit:"veata Adonai elohē israēl", strong:"H6258", pos:"adverb + nume propriu + substantiv plural construct + nume propriu", def_ro:"și acum, DOMNUL, Dumnezeul lui Israel.", dict_ro:"Metzudat David explică faptul că întrebarea finală — «să-l stăpânești tu?» — e o întrebare de uimire: dacă DOMNUL Însuși a alungat amoriții pentru poporul Său, cum ar putea regele amonit pretinde acum acel teritoriu pentru sine?"}],
  [" pe amoriți dinaintea poporului Său Israel, să-i stăpânești tu [pământul]?", {heb:"הוֹרִישׁ אֶת הָאֱמֹרִי מִפְּנֵי עַמּוֹ יִשְׂרָאֵל וְאַתָּה תִּירָשֶׁנּוּ", translit:"horiș et haemori mipnē amo israēl veata tirașenu", strong:"H3423", pos:"verb, hifil perfect + marcă a complementului direct + nume de neam + substantiv plural construct + substantiv construct + sufix + nume propriu + pronume personal + verb, qal imperfect + sufix", def_ro:"a alungat pe amoriți dinaintea poporului Lui Israel, și tu îl vei stăpâni?", dict_ro:"Metzudat David precizează clar: alungarea a fost făcută «ca să moștenească ei», israeliții, nu ca teritoriul să fie restituit cuiva anume — regele amonit n-are niciun drept moral sau istoric asupra acelui pământ."}]
]},
{v:"11:24", newTags:[
  ["Oare nu trebuie să iei în stăpânire ceea ce dumnezeul tău", {heb:"הֲלֹא אֵת אֲשֶׁר יוֹרִישְׁךָ", translit:"halo ēt așer iorișha", strong:"H3808", pos:"particulă negativă + marcă a complementului direct + particulă relativă + verb, hifil imperfect + sufix", def_ro:"nu [este] oare ceea ce te face să moștenești.", dict_ro:"Metzudat David explică faptul că Iefta spune aceasta în batjocură — folosirea numelui lui Kemoș, dumnezeul Moabului, pentru un argument împotriva lui Amon, arată ironia cu care Iefta demontează pretenția teritorială."}],
  [" îți dă moștenire? Aceea vei lua în stăpânire! Dar [țara] tuturor celor pe care DOMNUL, Dumnezeul nostru, îi alungă dinaintea noastră, noi o vom lua în stăpânire.", {heb:"כְּמוֹשׁ אֱלֹהֶיךָ אוֹתוֹ תִירָשׁ וְאֵת כָּל אֲשֶׁר הוֹרִישׁ יְהוָה אֱלֹהֵינוּ מִפָּנֵינוּ אוֹתוֹ נִירָשׁ", translit:"kemoș eloheha oto tiraș veēt kal așer horiș Adonai elohēnu mipanēnu oto niraș", strong:"H3645", pos:"nume propriu + substantiv plural construct + sufix + marcă a complementului direct + verb, qal imperfect + marcă a complementului direct + substantiv construct + particulă relativă + verb, hifil perfect + nume propriu + substantiv plural construct + sufix + substantiv plural construct + sufix + marcă a complementului direct + verb, qal imperfect", def_ro:"Kemoș, dumnezeul tău, îl vei moșteni; și tot ce a alungat DOMNUL, Dumnezeul nostru, dinaintea noastră, îl vom moșteni.", dict_ro:"Radak citează o zicere populară — «vai de tine, Moabe, ai pierit, popor al lui Kemoș!» — pentru a arăta că Kemoș n-a putut salva țara Moabului de amoriți; dacă regele amonit respectă această logică, trebuie să accepte și că DOMNUL, care a biruit pentru Israel, îi dă dreptul la aceeași țară."}]
]},
{v:"11:25", newTags:[
  ["Și acum, oare ești tu mai vrednic decât", {heb:"וְעַתָּה הֲטוֹב טוֹב אַתָּה מִבָּלָק", translit:"veata hatov tov ata", strong:"H6258", pos:"adverb + particulă interogativă + adjectiv + adjectiv + pronume personal", def_ro:"și acum, ești tu oare mai bun.", dict_ro:"Metzudat David explică faptul că întrebarea îl compară pe regele amonit cu Balak, care, deși avea pretenții asemănătoare asupra ținutului odinioară moabit, nu s-a luptat niciodată direct cu Israel pentru el."}],
  [", fiul lui Țipor, regele Moabului? Oare a avut el izbândă împotriva lui Israel? S-a luptat el oare cu ei?", {heb:"בֶּן צִפּוֹר מֶלֶךְ מוֹאָב הֲרוֹב רָב עִם יִשְׂרָאֵל אִם נִלְחֹם נִלְחַם בָּם", translit:"ben țipor meleh moav harov rav im israēl im nilhom nilham bam", strong:"H1121", pos:"substantiv construct + nume propriu + substantiv construct + nume propriu + verb, qal infinitiv absolut + verb, qal perfect + prepoziție + nume propriu + conjuncție + verb, nifal infinitiv absolut + verb, nifal perfect + prepoziție + sufix", def_ro:"fiul lui Țipor, regele Moabului? S-a certat el oare cu Israel? S-a luptat el oare cu ei?", dict_ro:"Radak explică faptul că, în cartea lui Iosua, se spune că Balak «s-a ridicat și a luptat împotriva lui Israel», dar lupta lui a fost trimiterea lui Bilaam să-i blesteme, nu un război direct pentru teritoriu — timp de trei sute de ani, niciun rege moabit n-a contestat stăpânirea lui Israel asupra acelui ținut."}]
]},
{v:"11:26", newTags:[
  ["Când Israel a locuit în Heșbon și toate suburbiile sale și în Aroer și toate suburbiile sale și în toate orașele care au fost de-a lungul Arnonului, timp de", {heb:"בְּשֶׁבֶת יִשְׂרָאֵל בְּחֶשְׁבּוֹן וּבִבְנוֹתֶיהָ וּבְעַרְעוֹר וּבִבְנוֹתֶיהָ וּבְכָל הֶעָרִים אֲשֶׁר עַל יְדֵי אַרְנוֹן", translit:"beșevet israēl beheșbon uvivnoteha uvaror uvivnoteha uvhal hearim așer al iedē arnon", strong:"H3427", pos:"verb, qal infinitiv + nume propriu + nume propriu + substantiv plural construct + sufix + nume propriu + substantiv plural construct + sufix + substantiv construct + substantiv plural + particulă relativă + prepoziție + substantiv dual construct + nume propriu", def_ro:"la locuirea lui Israel în Heșbon și satele ei, și în Aroer și satele ei, și în toate cetățile care sunt lângă Arnon.", dict_ro:"Rashi explică faptul că din acest verset se calculează anii judecătorilor, în Seder Olam: Iosua douăzeci și opt de ani, Otniel patruzeci, Ehud optzeci, ș.a.m.d. — suma celor trei sute de ani fiind o dovadă istorică fermă a stăpânirii continue a lui Israel."}],
  [" – de ce nu le-ai recuperat în acest timp?", {heb:"שְׁלֹשׁ מֵאוֹת שָׁנָה וּמַדּוּעַ לֹא הִצַּלְתֶּם בָּעֵת הַהִיא", translit:"șeloș mēot șana umadua lo hițaltem baēt hahi", strong:"H7969", pos:"numeral + numeral + substantiv + particulă interogativă + particulă negativă + verb, hifil perfect + substantiv + pronume personal", def_ro:"trei sute de ani, și pentru ce nu le-ați recuperat în vremea aceea?", dict_ro:"Radak oferă socoteala exactă: Iosua, Otniel, Ehud, Debora și Barac, Ghedeon, Abimeleh, Tola, Iair — 276 de ani, plus optsprezece ani de asuprire amonită, plus cei șase ani ai lui Iefta — totalul confirmă exact cifra de trei sute, probă incontestabilă a stăpânirii legitime."}]
]},
{v:"11:27", newTags:[
  ["Eu nu am păcătuit față de tine, dar tu greșești față de mine, făcând război cu mine. Fie ca DOMNUL,", {heb:"וְאָנֹכִי לֹא חָטָאתִי לָךְ וְאַתָּה עֹשֶׂה אִתִּי רָעָה לְהִלָּחֶם בִּי יִשְׁפֹּט יְהוָה", translit:"veanohi lo hatati lah veata ose iti raa lehilahem bi ișpot Adonai", strong:"H595", pos:"pronume personal + particulă negativă + verb, qal perfect + prepoziție + sufix + pronume personal + verb, qal participiu + prepoziție + sufix + substantiv + verb, nifal infinitiv + prepoziție + sufix + verb, qal imperfect + nume propriu", def_ro:"și eu n-am păcătuit față de tine, și tu faci cu mine rău, luptându-te cu mine; va judeca DOMNUL.", dict_ro:"Metzudat David explică faptul că versetul e inversat în ordinea firească a frazei: sensul final este că DOMNUL, Judecătorul întregului pământ, va judeca astăzi între cele două popoare — încheierea argumentului retoric al lui Iefta, înainte de luptă."}]
]},
{v:"11:28", newTags:[
  ["Dar regele copiilor lui Amon", {heb:"וְלֹא ... מֶלֶךְ בְּנֵי עַמּוֹן", translit:"velo meleh benē amon", strong:"H3808", pos:"particulă negativă + substantiv construct + substantiv plural construct + nume propriu", def_ro:"și nu... regele copiilor lui Amon.", dict_ro:"Refuzul regelui amonit de a răspunde argumentelor istorice și teologice ale lui Iefta confirmă că dialogul diplomatic s-a epuizat — confruntarea militară devine inevitabilă."}],
  [" vorbele lui Iefta, pe care i le trimisese.", {heb:"אֶל דִּבְרֵי יִפְתָּח אֲשֶׁר שָׁלַח אֵלָיו", translit:"el divrē iftah așer șalah ēlaiv", strong:"H413", pos:"prepoziție + substantiv plural construct + nume propriu + particulă relativă + verb, qal perfect + prepoziție + sufix", def_ro:"la cuvintele lui Iefta, pe care i le-a trimis.", dict_ro:"Tăcerea regelui amonit, fără niciun răspuns la argumentele detaliate ale lui Iefta, marchează trecerea bruscă de la negociere la război."}]
]},
{v:"11:29", newTags:[
  ["Și", {heb:"וַתְּהִי עַל יִפְתָּח", translit:"vathi al iftah", strong:"H1961", pos:"verb, qal imperfect consecutiv + prepoziție + nume propriu", def_ro:"și a fost asupra lui Iefta.", dict_ro:"Radak explică faptul că, potrivit Targumului, «s-a odihnit asupra lui Iefta un duh de vitejie de dinaintea DOMNULUI» — momentul exact în care eșecul negocierilor cedează locul puterii divine primite pentru luptă."}],
  [" a fost asupra lui Iefta. El a trecut prin Ghilad și prin Menașe, și a trecut prin Mițpe din Ghilad, și de la Mițpe din Ghilad a trecut la copiii lui Amon.", {heb:"רוּחַ יְהוָה וַיַּעֲבֹר אֶת הַגִּלְעָד וְאֶת מְנַשֶּׁה וַיַּעֲבֹר אֶת מִצְפֵּה גִלְעָד וּמִמִּצְפֵּה גִלְעָד עָבַר בְּנֵי עַמּוֹן", translit:"ruah Adonai vaiaavor et hagilad veet menașe vaiaavor et mițpē gilad umimițpē gilad avar venē amon", strong:"H7307", pos:"substantiv construct + nume propriu + verb, qal imperfect consecutiv + marcă a complementului direct + nume propriu + marcă a complementului direct + nume propriu + verb, qal imperfect consecutiv + marcă a complementului direct + nume propriu + nume propriu + nume propriu + nume propriu + verb, qal perfect + substantiv plural construct + nume propriu", def_ro:"duhul DOMNULUI, și a trecut prin Ghilad și prin Menașe, și a trecut prin Mițpe din Ghilad, și de la Mițpe din Ghilad a trecut la copiii lui Amon.", dict_ro:"Metzudat David explică «duh al DOMNULUI» ca pe un duh de vitejie și curaj al inimii — traseul descris, prin Ghilad, Menașe și Mițpe, arată mobilizarea treptată a forțelor israelite spre teritoriul amonit."}]
]},
{v:"11:30", newTags:[
  ["Apoi Iefta a făcut", {heb:"וַיִּדַּר יִפְתָּח", translit:"vaidar iftah", strong:"H5087", pos:"verb, qal imperfect consecutiv + nume propriu", def_ro:"și a jurat Iefta.", dict_ro:"Talmudul Bavli (Taanit 4a) numără jurământul lui Iefta printre cele «trei cereri nepotrivite» din Scriptură, alături de cele ale lui Eliezer și Saul — formularea lui, deschisă oricărui lucru care ar ieși primul, era riscantă fără necesitate."}],
  [" DOMNULUI și a spus: „Dacă într-adevăr vei da pe copiii lui Amon în mâna mea,", {heb:"נֶדֶר לַיהוָה וַיֹּאמַר אִם נָתוֹן תִּתֵּן אֶת בְּנֵי עַמּוֹן בְּיָדִי", translit:"neder la'Adonai vaiomar im naton titēn et benē amon beiadi", strong:"H5088", pos:"substantiv + nume propriu + verb, qal imperfect consecutiv + conjuncție + verb, qal infinitiv absolut + verb, qal imperfect + marcă a complementului direct + substantiv plural construct + nume propriu + substantiv construct + sufix", def_ro:"jurământ DOMNULUI, și a spus: dacă, cu adevărat, vei da pe copiii lui Amon în mâna mea.", dict_ro:"Talmudul Bavli (Taanit 4a) explică faptul că Iefta ar fi putut, teoretic, primi ca ofrandă un lucru necurat — i s-a răspuns «nepotrivit», pentru că exact fiica lui a fost cea care i-a ieșit în cale, semn că jurământul ar fi putut fi dezlegat printr-un învățat priceput."}]
]},
{v:"11:31", newTags:[
  ["atunci orice va ieși, ceea ce va ieși pe ușile casei mele ca să mă întâmpine când mă voi întoarce în pace de la copiii lui Amon, va fi al DOMNULUI și îl voi aduce ca", {heb:"וְהָיָה הַיּוֹצֵא אֲשֶׁר יֵצֵא מִדַּלְתֵי בֵיתִי לִקְרָאתִי בְּשׁוּבִי בְשָׁלוֹם מִבְּנֵי עַמּוֹן וְהָיָה לַיהוָה וְהַעֲלִיתִהוּ", translit:"vehaia haioțē așer iēțē midaltē vēti likrati beșuvi veșalom mibnē amon vehaia la'Adonai vehaalitihu", strong:"H1961", pos:"verb, qal perfect consecutiv + verb, qal participiu + particulă relativă + verb, qal imperfect + substantiv dual construct + substantiv construct + sufix + verb, qal infinitiv + sufix + verb, qal infinitiv + sufix + substantiv + substantiv construct + nume propriu + verb, qal perfect consecutiv + nume propriu + verb, hifil perfect consecutiv + sufix", def_ro:"și va fi: cel ce iese, care va ieși pe ușile casei mele, să mă întâmpine la întoarcerea mea în pace de la copiii lui Amon, va fi al DOMNULUI, și îl voi aduce.", dict_ro:"Radak explică, citând pe tatăl său, că litera «vav» din «și-l voi aduce» ar putea sta în locul lui «sau»: fie va fi consacrat DOMNULUI, dacă nu e potrivit pentru ardere-de-tot, fie va fi adus ca ardere-de-tot, dacă e potrivit — interpretare care sugerează că Iefta n-a ucis-o pe fiica lui, ci doar a consacrat-o, despărțind-o de viața lumească."}]
]},
{v:"11:32", newTags:[
  ["Apoi Iefta a trecut prin copiii lui Amon, purtând război împotriva lor, și DOMNUL", {heb:"וַיַּעֲבֹר יִפְתָּח אֶל בְּנֵי עַמּוֹן לְהִלָּחֶם בָּם", translit:"vaiaavor iftah el benē amon lehilahem bam", strong:"H5674", pos:"verb, qal imperfect consecutiv + nume propriu + prepoziție + substantiv plural construct + nume propriu + verb, nifal infinitiv + prepoziție + sufix", def_ro:"și a trecut Iefta la copiii lui Amon, ca să se lupte cu ei.", dict_ro:"Mișcarea lui Iefta spre teritoriul amonit, imediat după jurământ, arată determinarea lui de a câștiga victoria promisă — jurământul nu întârzie acțiunea militară, ci o precedă direct."}]
]},
{v:"11:33", newTags:[
  ["El i-a lovit de la Aroer până când vii către Minit, douăzeci de orașe, până în", {heb:"וַיַּכֵּם מֵעֲרוֹעֵר וְעַד בּוֹאֲךָ מִנִּית עֶשְׂרִים עִיר וְעַד", translit:"vaiakēm mēaroēr vead boaha minit esrim ir vead", strong:"H5221", pos:"verb, hifil imperfect consecutiv + sufix + nume propriu + prepoziție + verb, qal infinitiv + sufix + nume propriu + numeral + substantiv + prepoziție", def_ro:"și i-a lovit de la Aroer, până la venirea ta la Minit, douăzeci de cetăți, și până la.", dict_ro:"Metzudat David explică faptul că expresia «până când vii către Minit» vorbește ca și cum s-ar adresa cuiva care cunoaște deja locul — pe toată acea distanță erau douăzeci de cetăți, și Iefta le-a lovit pe toate, fără excepție."}],
  [", o lovitură foarte mare; și copiii lui Amon au fost înfrânți în fața copiilor lui Israel.", {heb:"מַכָּה גְּדוֹלָה מְאֹד וַיִּכָּנְעוּ בְּנֵי עַמּוֹן מִפְּנֵי בְּנֵי יִשְׂרָאֵל", translit:"maka gedola meod vaikanu venē amon mipnē venē israēl", strong:"H4347", pos:"substantiv + adjectiv + adverb + verb, nifal imperfect consecutiv + substantiv plural construct + nume propriu + substantiv plural construct + substantiv plural construct + nume propriu", def_ro:"lovitură mare, foarte, și s-au supus copiii lui Amon dinaintea copiilor lui Israel.", dict_ro:"Metzudat Țion explică «vayikaneu» cu sensul de supunere și umilire — victoria lui Iefta încheie definitiv conflictul, confirmând dreptatea întregului argument istoric expus solilor amoniți."}]
]}
];
