module.exports = {
"36:16": ["Și a fost cuvântul Domnului către mine, spunând:", "Corespondență strânsă cu Textul Masoretic."],
"36:17": ["«Fiu al omului, casa lui Israel a locuit pe pământul lor și l-au spurcat pe calea lor și cu idolii lor și cu necurățiile lor; după necurăția celei îndepărtate a fost calea lor înaintea feței Mele.»", "Corespondență strânsă cu Textul Masoretic."],
"36:18": ["Și am revărsat mânia Mea asupra lor.", "Vezi nota de la cuvântul tagat „sângelui pe care l-au vărsat” — Septuaginta prescurtează radical, omițând sângele și idolii."],
"36:19": ["Și i-am împrăștiat printre neamuri și i-am vânturat prin țări; după calea lor și după păcatul lor i-am judecat.", "Corespondență apropiată cu Textul Masoretic."],
"36:20": ["Și au intrat la neamuri, unde au intrat, și au pângărit numele Meu cel sfânt, zicându-se despre ei: «Poporul Domnului [sunt] aceștia, și din țara Lui au venit.»", "Corespondență strânsă cu Textul Masoretic."],
"36:21": ["Și i-am cruțat pentru numele Meu cel sfânt, pe care l-a pângărit casa lui Israel printre neamurile unde au venit.", "Corespondență strânsă cu Textul Masoretic."],
"36:22": ["Pentru aceasta spune casei lui Israel: «Așa spune Domnul: nu pentru voi fac Eu [aceasta], casă a lui Israel, ci pentru numele Meu cel sfânt, pe care l-ați pângărit printre neamurile unde ați venit.»", "Corespondență strânsă cu Textul Masoretic."],
"36:23": ["Și voi sfinți numele Meu cel mare, pângărit printre neamuri, pe care l-ați pângărit în mijlocul lor, și vor cunoaște neamurile că Eu sunt Domnul, când Mă voi sfinți în voi, înaintea ochilor lor.", "Corespondență strânsă cu Textul Masoretic."],
"36:24": ["Și vă voi lua dintre neamuri și vă voi strânge din toate țările și vă voi aduce în țara voastră.", "Corespondență strânsă cu Textul Masoretic."],
"36:25": ["Și voi stropi asupra voastră apă curată, și vă veți curăți de toate necurățiile voastre și de toți idolii voștri, și vă voi curăți.", "Corespondență strânsă cu Textul Masoretic."],
"36:26": ["Și vă voi da o inimă nouă și un duh nou vă voi da în voi, și voi îndepărta inima de piatră din carnea voastră și vă voi da o inimă de carne.", "Corespondență strânsă cu Textul Masoretic."],
"36:27": ["Și duhul Meu îl voi da în voi și voi face să mergeți în hotărârile Mele, și judecățile Mele să le păziți și să le faceți.", "Corespondență strânsă cu Textul Masoretic."],
"36:28": ["Și veți locui pe pământul pe care l-am dat părinților voștri, și-Mi veți fi popor, și Eu vă voi fi Dumnezeu.", "Corespondență strânsă cu Textul Masoretic."],
"36:29": ["Și vă voi mântui de toate necurățiile voastre și voi chema grânele", "Septuaginta prescurtează fraza, întreruptă brusc, probabil dintr-o eroare de copiere veche; sensul complet se găsește continuat în ebraică."],
"36:30": ["și-l voi înmulți și nu voi da foamete asupra voastră; și voi înmulți rodul pomului și roadele câmpului, ca să nu mai luați ocara foametei printre neamuri.", "Corespondență apropiată cu Textul Masoretic."],
"36:31": ["Și vă veți aduce aminte de căile voastre cele rele și de faptele voastre care nu erau bune, și vă veți scârbi de voi înșivă din pricina nelegiuirilor voastre și a urâciunilor voastre.", "Corespondență strânsă cu Textul Masoretic."],
"36:32": ["Nu pentru voi fac Eu [aceasta], spune Domnul Domn, cunoscut să vă fie; rușinați-vă și umiliți-vă de căile voastre, casă a lui Israel.", "Corespondență strânsă cu Textul Masoretic."],
"36:33": ["Așa spune Domnul Stăpân: «În ziua când vă voi curăți de toate nelegiuirile voastre, și voi locui orașele, și se vor zidi [cele] pustii,", "Corespondență apropiată cu Textul Masoretic."],
"36:34": ["și pământul cel pustiit se va lucra, pentru că a fost pustiit înaintea ochilor oricărui trecător.»", "Corespondență strânsă cu Textul Masoretic."],
"36:35": ["Și vor spune: «Țara aceea pustiită a ajuns ca o grădină de desfătare, și orașele cele pustii și nimicite și dărâmate [acum] stau întărite.»", "Corespondență strânsă cu Textul Masoretic."],
"36:36": ["Și vor cunoaște neamurile, câte vor rămâne în jurul vostru, că Eu, Domnul, am zidit cele dărâmate și am plantat cele pustiite. Eu, Domnul, am grăit și voi face.", "Corespondență strânsă cu Textul Masoretic."],
"36:37": ["Așa spune Domnul Stăpân: «Încă aceasta Mă voi lăsa căutat de casa lui Israel, ca să le fac: îi voi înmulți ca pe oameni-oi,", "Corespondență apropiată cu Textul Masoretic."],
"36:38": ["ca oile cele sfinte, ca oile Ierusalimului la sărbătorile lui, așa vor fi orașele cele pustii, pline de oameni-oi, și vor cunoaște că Eu sunt Domnul.»", "Corespondență strânsă cu Textul Masoretic."]
};
