module.exports = {
"23:1": ["Și a trimis regele și a adunat la sine pe toți bătrânii lui Iuda și ai Ierusalimului.", "Corespondență strânsă cu Textul Masoretic."],
"23:2": ["Și s-a suit regele la Casa Domnului, și tot bărbatul lui Iuda, și toți cei care locuiau în Ierusalim cu el, și preoții și profeții și tot poporul, de la mic până la mare, și a citit în auzul lor toate cuvintele cărții legământului găsite în Casa Domnului.", "Corespondență strânsă cu Textul Masoretic."],
"23:3": ["Și a stat regele lângă stâlp și a încheiat legământ înaintea Domnului, ca să meargă după Domnul și să păzească poruncile Lui și mărturiile Lui și hotărârile Lui cu toată inima și cu tot sufletul, ca să împlinească cuvintele legământului acestuia, scrise în cartea aceasta; și a stat tot poporul în legământ.", "Corespondență strânsă cu Textul Masoretic."],
"23:4": ["Și a poruncit regele lui Helchia, preotul cel mare, și preoților de rangul al doilea, și celor care păzeau cântarul, să scoată din templul Domnului toate vasele făcute pentru Baal și pentru dumbravă și pentru toată puterea cerului, și le-a ars afară din Ierusalim, în câmpiile Kedronului, și a dus țărâna lor la Betel.", "Septuaginta transliterează netradus „șadmot” (câmpii) ca „sadēmoth”, un termen tehnic local lăsat ca atare, la fel ca alte cazuri similare întâlnite în această arhivă."],
"23:5": ["Și a ars pe preoții idolilor, pe care-i puseseră regii lui Iuda și tămâiau pe înălțimi și în cetățile lui Iuda și în împrejurimile Ierusalimului, și pe cei care tămâiau lui Baal și soarelui și lunii și semnelor zodiacului și toată puterea cerului.", "Diferență reală: Septuaginta are „a ars pe preoți” (κατέκαυσε), nu „a îndepărtat” (vehișbit) ca în Textul Masoretic — o intensificare semnificativă a pedepsei descrise."],
"23:6": ["Și a scos dumbrava din Casa Domnului, afară din Ierusalim, la pârâul Kedron, și a ars-o la pârâul Kedron, și a măcinat-o în țărână, și a aruncat țărâna ei pe mormântul fiilor poporului.", "Corespondență strânsă cu Textul Masoretic."],
"23:7": ["Și a dărâmat casa kadeșim-ilor care era în Casa Domnului, unde femeile țeseau acolo veșminte Hetim pentru dumbravă.", "Diferență reală: Septuaginta adaugă un termen netradus, „Hetim” (Χεττιΐμ), absent din Textul Masoretic, care are simplu „case/draperii” pentru Așera."],
"23:8": ["Și a adus pe toți preoții din cetățile lui Iuda și a pângărit înălțimile unde tămâiau acolo preoții, de la Gheva până la Beer-Șeba; și a dărâmat casa porților de lângă poarta lui Iisus, căpetenia cetății, cele din stânga unui om la poarta cetății.", "Corespondență strânsă cu Textul Masoretic."],
"23:9": ["Totuși n-au suit preoții înălțimilor la altarul Domnului în Ierusalim, decât [doar] au mâncat azime în mijlocul fraților lor.", "Corespondență strânsă cu Textul Masoretic."],
"23:21": ["Și a poruncit regele întregului popor, spunând: «Faceți Paștele Domnului Dumnezeului nostru, cum este scris în cartea legământului acestuia.»", "Corespondență strânsă cu Textul Masoretic."],
"23:22": ["Căci nu se făcuse acest Paște din zilele judecătorilor care judecau pe Israel, și în toate zilele regilor lui Israel și regilor lui Iuda,", "Corespondență strânsă cu Textul Masoretic."],
"23:23": ["ci numai în anul al optsprezecelea al regelui Iosia s-a făcut Paștele Domnului în Ierusalim.", "Corespondență strânsă cu Textul Masoretic."],
"23:24": ["Și chiar pe cei care au familiari și pe cei care cunosc [prin vrăjitorie] și terafimii și idolii și toate urâciunile care s-au aflat în țara lui Iuda și în Ierusalim le-a îndepărtat Iosia, ca să întemeieze cuvintele legii scrise în cartea pe care a găsit-o Helchia preotul în Casa Domnului.", "Corespondență strânsă cu Textul Masoretic."],
"23:25": ["Asemenea lui n-a fost înaintea lui rege care să se fi întors la Domnul cu toată inima lui și cu tot sufletul lui și cu toată puterea lui, după toată legea lui Moise; și după el n-a mai venit [niciunul] asemenea lui.", "Corespondență strânsă cu Textul Masoretic."]
};
