const C = {};
C["10:32"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Chiar astăzi va sta în Nob” — tot acest drum [al oastei asiriene] a fost parcurs cu zor ca să poată ajunge la Nob încă în timpul zilei, pentru că astrologii lui [Sanherib] îi spuseseră: «Dacă vei lupta împotriva ei [Ierusalimul] astăzi, o vei cuceri.» Când a stat la Nob și a văzut Ierusalimul mic, n-a mai ținut seama de cuvintele astrologilor și a început să-și flutureze mâna cu îngâmfare: «Pentru o cetate ca aceasta am tulburat toate aceste oștiri? Rămâneți aici în noaptea asta, iar mâine fiecare om va arunca o piatră asupra ei!»"},
 {author:"Radak (1160–1235)", text:"Potrivit sensului de midraș, [Sanherib] a mers într-o singură zi toate etapele pomenite [în versetele precedente] și s-a grăbit să ajungă chiar în ziua aceea la Nob, de unde se vedea Ierusalimul. Tatăl meu, de bună amintire, a explicat versetul altfel: «încă astăzi» se vor întoarce la Nob cei ce fugiseră de acolo dinaintea lui Sanherib. Iar «își va flutura mâna muntele fiicei Ționului» e spus prin asemănare — muntele fiicei Ționului își va flutura mâna asupra taberei Asiriei, la căderea ei, la fel și dealul Ierusalimului — repetând același lucru în cuvinte diferite, ca în «râzi de tine, fiică a Ționului, fecioară, dă din cap în urma ta, fiică a Ierusalimului»."},
]};
C["10:33"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Iată, Stăpânul” — în noaptea aceea. „Taie ramurile cu toporul” — îi despică crengile, trunchiul de bază al ramurilor pomilor săi. „Cu toporul” — cu secera care tunde crengile; nu e cuvântul «pura» aici în sensul de «teasc de vin» [cum e în Isaia 63:3 sau Hagai 2:16, scrise cu vav], ci cu alef, ca «ramurile lui s-au lungit» [Ezechiel 31:5]. «Mesaēf» înseamnă «cel care taie ramurile». «Cu toporul» — cu unealta nimicitoare care doboară și sfărâmă. «Cei semeți» — regii și dregătorii."},
 {author:"Metzudat David (sec. XVIII)", text:"„Iată, Stăpânul” — ca spunând: dar n-a fost cum a crezut el, căci Stăpânul, DOMNUL, i-a tăiat ramurile cu unealta nimicitoare, adică a trimis îngerul și i-a lovit. „Cei semeți” — copacii înalți la stat au fost doborâți, adică cei viteji au murit."},
 {author:"Radak (1160–1235)", text:"Sanherib credea că n-are niciun stăpân peste el, așa cum a zis: «Prin puterea mâinii mele am făcut aceasta, și prin înțelepciunea mea, căci sunt priceput.» Profetul spune: iată, există un Stăpân — DOMNUL Oștirilor, stăpân peste oștirile de sus și de jos — și El va doborî oastea regelui Asiriei. A asemuit tabăra lui cu o pădure plină de copaci înalți."},
]};
C["10:34"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Va fi tăiat” — tot acest cuvânt e tot din sensul de «a tăia», ca «precum culegerea măslinului» [Isaia 17:6]; forma e nifal. „Desișurile pădurii” — ramurile de seamă și cele viteze. „Și Libanul” — grosul pădurii sale și via lui, adică cea mai mare parte a oștirilor lui. „Prin cel măreț va cădea” — prin mâna unui înger va cădea. O altă explicație: «prin cel măreț» — prin meritul lui Ezechia, care este cel mai măreț și stăpânitor al lui Israel, așa cum se spune: «și va fi mai mare decât el stăpânul lui» [Ieremia 30:21]."},
 {author:"Metzudat David (sec. XVIII)", text:"„Va fi tăiat” — ramurile încâlcite una într-alta vor fi tăiate cu fierul, adică oastea lui cea mare va fi ucisă prin mâna îngerului. „Și Libanul” — copacii Libanului vor cădea prin [unul] măreț și puternic, el fiind îngerul; și a repetat lucrul în cuvinte diferite, pentru întărirea ideii și frumusețea exprimării."},
]};
C["11:1"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Și va răsări o mlădiță din buturuga lui Ișai” — și dacă veți spune: «iată mângâiere pentru Ezechia și poporul lui, ca să nu cadă în mâna [Asiriei], dar ce va fi cu exilații duși în Halah și Habor — oare le-a pierit nădejdea?» Nu le-a pierit! La sfârșit va veni Împăratul nostru, Mesia, și îi va izbăvi. „Hoter” — sceptru de domnie. „Nēțer” — termen pentru mlădița unui pom. „Și un vlăstar din rădăcinile lui va rodi” — și în toată trecerea acestei profeții, până la sfârșitul ei, «și va fi în ziua aceea, Domnul Își va adăuga a doua oară mâna» [Isaia 11:11] — iată că această profeție a fost spusă drept mângâiere pentru exilații din Asiria."},
 {author:"Metzudat David (sec. XVIII)", text:"„Și va răsări o mlădiță” — ca spunând: nu vă mirați de minunea aceasta mare, căci va veni vremea când [Dumnezeu] va face o minune și mai mare decât ea, căci va răsări un toiag de domnie din rădăcina lui Ișai, din sămânța lui David — el fiind Regele Mesia. „Și un vlăstar...” — repetarea aceluiași lucru în cuvinte diferite."},
 {author:"Radak (1160–1235)", text:"A legat această parte de făgăduința de pe vremea lui Ezechia: să nu vă mirați de o minune atât de mare precum cea din zilele lui Ezechia, la căderea taberei Asiriei într-o singură clipă, căci va face lui Israel o minune și mai mare decât aceasta în zilele lui Mesia, în strângerea exilaților, și aceasta va fi din familia regelui Ezechia. A pomenit pe Ișai pentru că din el a răsărit întâiul rege [David], și «hoter» e tălmăcit ca toiag, iar «gezaa» e ce rămâne din copac pe pământ [după tăiere], din laturile căruia și din rădăcini răsar mlădițe noi — căci, măcar că Israel a fost în exil de atâția ani și domnia le-a fost întreruptă, ca și cum copacul ar fi fost tăiat, totuși buturuga și rădăcinile au rămas: mai există nădejde că buturuga va înmuguri din nou."},
]};
C["11:2"] = {comm:[
 {author:"Metzudat David (sec. XVIII)", text:"„Duhul DOMNULUI” — duh de profeție. „Duh de înțelepciune și de înțelegere” — toate aceste duhuri se vor odihni asupra lui și se vor găsi în el."},
 {author:"Radak (1160–1235)", text:"Fiindcă totul va fi de la Domnul, spune mai întâi «duhul Domnului», apoi tâlcuiește: «duh de înțelepciune și de înțelegere», «duh de sfat și de putere», «duh de cunoaștere și de teamă de Domnul». Înțelepciunea este ceea ce omul învață de la altul și o știe, mereu la îndemână; înțelegerea e priceperea proprie a omului în ce n-a învățat, din ce a învățat."},
]};
C["11:3"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Și mireasma lui va fi în teama de DOMNUL” — se va umple de duhul fricii de Domnul. „Și nu va judeca după înfățișarea ochilor” — pentru că prin înțelepciunea Celui Sfânt binecuvântat în el, va ști și va pricepe cine e nevinovat și cine e vinovat."},
 {author:"Radak (1160–1235)", text:"Pentru că mirosul e simțul cel mai ușor [cel mai subtil], textul numește «miros» pentru ceva perceput ușor — ca cel care miroase de departe un război, sau ca fitilul care se aprinde la mirosul focului. Tot așa, spune aici: cu puțină pricepere va simți [Mesia] oamenii buni și pe cei răi, fără să aibă nevoie de vederea ochilor și de mărturia auzului urechilor atunci când va judeca și va mustra oamenii, căci din propria lui înțelegere și pricepere va pătrunde faptele lor cu minimă chibzuință."},
]};
C["11:4"] = {comm:[
 {author:"Metzudat David (sec. XVIII)", text:"„Și va judeca pe cel nevoiaș cu dreptate” — va lua dreptatea celor nevoiași de la cei avuți, cu dreptate, fără a ține partea celor mari; iar pe cei puternici îi va mustra cu nepărtinire, cum se cuvine, pentru cei modești ai pământului, ca să nu-i mai jefuiască de acum încolo. „Și va lovi pământul” — pe nelegiuiții pământului îi va lovi cu blestemul gurii lui, și acesta va fi ca un toiag care lovește."},
 {author:"Radak (1160–1235)", text:"Spune «cei nevoiași» și «cei modești ai pământului», chiar dacă el va judeca pe toți oamenii cu dreptate, deopotrivă săraci și avuți — pentru că lumea e deprinsă să țină partea celor mari și bogați, [textul] spune că el nu va face așa, ci cu dreptate va lua judecata celor nevoiași din [mâna] celor avuți, și va mustra pe cei puternici cu nepărtinire, din pricina celor modești ai pământului, ca să nu-i mai jefuiască și să nu-i mai asuprească fiind ei slabi și fără putere. «Și va lovi pământul cu toiagul gurii lui» — pentru că va vorbi și va blestema, și vor muri, cum s-a scris despre cei drepți: «vei hotărî un lucru și se va întâmpla»; și s-a spus despre Samuel profetul: «tot ce va grăi se va împlini», și despre Elisei profetul: «i-a blestemat în numele Domnului, și au ieșit doi urși din pădure» — care au sfâșiat patruzeci și doi de copii dintre ei."},
]};
C["11:5"] = {comm:[
 {author:"Metzudat David (sec. XVIII)", text:"„Și va fi dreptatea brâul coapselor lui” — dreptatea și credința de care se va ține vor fi pentru el ca o putere, precum omul încins cu un brâu la coapse, care e astfel mai sprinten și mai întărit."},
]};
C["11:6"] = {comm:[
 {author:"Radak (1160–1235)", text:"Unii tălmăcesc literal: în zilele lui Mesia se va schimba firea fiarelor și a dobitoacelor, întorcându-se la ceea ce era la începutul creației și în corabia lui Noe, când nimic nu vâna nimic. Alții tălmăcesc totul ca pildă: lupul, leopardul, ursul și leul sunt pildă pentru asupritorii și jefuitorii cei puternici ai lumii, iar mielul, vițelul, iedul sunt pildă pentru cei smeriți și năpăstuiți, și [profetul] spune că în zilele lui Mesia va fi pace în toată lumea, fără ca unul să-l mai nedreptățească pe altul. Cel adevărat [sens], după mine, este că firea fiarelor nu se va schimba și ele vor sfâșia și vor mânca carne cum fac și acum, ci [Domnul] a făgăduit lui Israel că fiarele rele nu vor mai face rău în toată țara lui Israel, fiindcă aceasta se va umple de cunoașterea Domnului, și de aceea nu va mai stăpâni asupra lor fiară rea, așa cum a făgăduit prin Moise, robul Lui: «Voi stârpi fiara cea rea din țară»."},
]};
C["11:8"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Peste vizuina viperei” — peste gaura de țărână în care cuibărește șarpele. „Pāten” — un șarpe care, îmbătrânind, devine surd și se numește «paten», căci nu mai are descântec, cum se spune: «care n-ascultă glasul vrăjitorilor» [Psalmul 58:6]. Ionatan tălmăcește «vizuina viperei» ca «strălucirea globilor ochilor viperei»; iar Menahem o tâlcuiește drept «gaură», ca «Urul caldeenilor» sau «la lumini vor cinsti pe Domnul»."},
 {author:"Radak (1160–1235)", text:"«Vrăjmășia» pusă între șarpe și om la începutul lumii se va stinge în zilele lui Mesia în toată Țara lui Israel, și poporului lui Israel, oriunde va merge, nu-i va mai face rău nici șarpele, nici fiarele cele rele. Iar tălmăcirea lui Ionatan arată de ce copilul nu se ferește: ochiul șarpelui, ascuns în întuneric, strălucește, și pruncul, văzând acea strălucire din afară, o crede o piatră luminoasă sau sticlă, și întinde mâna să o apuce fără să știe că e vizuina viperei — dar vipera nu-i va face rău."},
]};
C["11:9"] = {comm:[
 {author:"Radak (1160–1235)", text:"Toată Țara lui Israel e numită aici «muntele Meu cel sfânt», fiind mai înaltă decât toate celelalte țări [în rang spiritual]; iar motivul pentru care [fiarele] nu vor face rău este că pământul se va umple de cunoașterea Domnului, cum a spus Ieremia profetul: «căci toți Mă vor cunoaște, de la cel mai mic la cel mai mare al lor»."},
]};
C["11:10"] = {comm:[
 {author:"Metzudat David (sec. XVIII)", text:"„Rădăcina lui Ișai” — Mesia, care răsare din rădăcina lui Ișai, va fi atunci în ziua strângerii exilaților. „Ca steag pentru popoare” — el va fi pentru toate popoarele ca un stindard purtat înaintea oștii, pe care toți oamenii de oaste îl urmează; tot așa, toate neamurile vor căuta pe Mesia și vor merge după el, ca să facă ce le va porunci."},
]};
C["11:11"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„A doua oară” — precum i-a dobândit [Israel] din Egipt, când izbăvirea lor a fost deplină, fără nicio supunere rămasă; dar izbăvirea celui de-al Doilea Templu nu se socotește, fiindcă au rămas supuși lui Cirus. „Și din insulele mării” — acestea sunt insulele Kitim, grecii."},
 {author:"Radak (1160–1235)", text:"Pentru că prima dată [Domnul] i-a dobândit din casa robiei, din Egipt, iar în ziua strângerii exilaților Își va adăuga «a doua oară» mâna, ca să-i dobândească din toate neamurile printre care au fost împrăștiați — despre exilul Babilonului nu se spune așa, pentru că nu au ieșit decât Iuda și Beniamin, iar cele zece triburi nu s-au strâns, deci nu se poate numi acea strângere «a doua oară», pentru că din Egipt au ieșit tot Israelul, fără să rămână niciunul."},
]};
C["11:13"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Efraim nu va invidia pe Iuda” — Mesia fiul lui Iosif și Mesia fiul lui David nu se vor invidia unul pe celălalt (Șir haȘirim Zuta 4:11)."},
]};
C["11:15"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Și va seca” — ca să o usuce, pentru ca exilații lui Israel să poată trece prin ea din Egipt. „Peste fluviu” — fluviul Eufrat, pentru trecerea exilaților din Asiria. „În șapte pâraie” — în șapte brațe, pentru trecerea celor șapte grupuri de exilați pomenite mai sus [Isaia 11:11] — din Asiria și din Egipt și celelalte; iar cei din insulele mării nu vin dinspre partea aceasta."},
]};
C["12:1"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Îți voi mulțumi, căci ai fost mânios pe mine” — și m-ai dus în exil, iar exilul meu a ispășit pentru mine; și acum vina mea e primită, și mânia Ta se va întoarce și mă vei mângâia. Ionatan tălmăcește: «Îți voi mulțumi, Doamne, căci am păcătuit înaintea Ta, și de aceea Te-ai mâniat pe mine, și de n-ar fi fost îndurările Tale n-aș fi fost vrednic să-Ți întorci mânia și să mă mângâi; și iată mânia Ta s-a întors de la mine.»"},
]};
C["12:2"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Puterea mea și lauda mea DOAMNE, DUMNEZEU” — până aici Numele Lui era despărțit [incomplet], dar la căderea lui Amalec a devenit deplin, cum se spune: «căci mâna e pe tronul lui Iah» [Exodul 17:16] — tronul nu e deplin și Numele nu e deplin până nu va fi război al Domnului împotriva lui Amalec."},
]};
C["12:3"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Și veți scoate [apă]” — «și veți primi învățătură nouă» [tălmăcire Ionatan]. „Din izvoarele salvării” — pentru că [Domnul] va lărgi inima lor prin izbăvirea ce va veni asupra lor, și li se vor descoperi tainele Torei care fuseseră uitate în Babilon din pricina necazurilor."},
]};

module.exports = { C };
