const C = {};
C["1:1"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Și a fost, în al treizecilea an” — profetul și-a ascuns vorbele, fără să-și arate numele, fără să lămurească după ce socoteală numără. De aceea Duhul Sfânt a întrerupt vorbele lui prin două versete vecine, ca să învățăm cine e profetul și după ce socoteală numără, zicându-se „în a cincea [zi] a lunii, în al cincilea an...” — acestea nu sunt vorbele profetului, căci el spusese deja „în a cincea [zi] a lunii” mai sus; iar la început vorbește el însuși, în persoana întâi: „și eu eram printre exilați și am văzut viziuni ale lui Dumnezeu”, și tot așa la sfârșit: „și am privit, și iată un vânt de vijelie...”. Aceste două versete îi întrerup vorbele, ca și cum altcineva ar vorbi despre el: „a fost cuvântul Domnului către Ezechiel... și a fost asupra lui acolo mâna Domnului”."},
 {author:"Radak (1160–1235)", text:"Tatăl meu, de bună amintire, a scris acest calcul: potrivit sensului simplu al textului, [treizecilea an] se referă la anul treizeci al ciclului de jubileu, iar dovada e că, atunci când Ezechiel a văzut în profeție clădirea viitoare a cetății și a Templului, se spune [acolo]: «în anul douăzeci și cinci al exilului nostru... în ziua de Anul Nou» (Ezechiel 40:1), și înțelepții noștri au zis: care an are Anul Nou în ziua a zecea a lunii [a șaptea]? Acesta e anul de jubileu [care începe la Yom Kipur]. Deci acea viziune [de mai departe] a avut loc în anul douăzeci și cinci al exilului lui Ioiachin, care era anul [următorului] jubileu; iar aceasta, prima viziune, a avut loc în al cincilea an al exilului, cu douăzeci de ani mai devreme — deci în anul treizeci al jubileului precedent."},
]};
C["1:3"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„A fost, a fost cuvântul DOMNULUI” — înțelepții noștri au spus (Moed Katan 25a): „a fost” înseamnă „fusese deja”, pentru că Șechina nu se odihnește asupra unui profet în afara Țării decât prin faptul că s-a odihnit asupra lui mai întâi în Țară. „Mâna DOMNULUI” — orice expresie de „mână” rostită în această carte, și în toată limba profeției, nu e decât o expresie de forță/constrângere, căci profeția constrânge pe profet împotriva voii lui, ca pe un om care și-a pierdut mințile."},
 {author:"Radak (1160–1235)", text:"Au spus înțelepții noștri, de bună amintire: Șechina nu se odihnește asupra profeților în afara Țării [Sfinte]; și când li se vorbește în afara Țării, nu li se vorbește decât într-un loc curat, lângă ape, cum se spune aici «lângă râul Kevar», și despre Daniel «eram lângă râul Ulai», și despre alții «eram lângă marginea râului». Unii spun: prima dată nu se vorbește profetului în afara Țării; a doua dată, da — și spre aceasta înclină și Ionatan în traducerea sa aramaică."},
]};
C["1:4"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Și iată un vânt de vijelie venea de la miazănoapte” — acesta e carul tronului de slavă al Șechinei, cum se spune mai departe în acest capitol; și pentru că vine cu mânie, ca să nimicească pe Israel, de aceea se înfățișează ca un vânt de vijelie și un nor. „Vine de la miazănoapte” — se întorcea din țara caldeenilor, care e la nord, cum se spune «de la miazănoapte se va dezlănțui răul» (Ieremia 1:14). Și de ce a mers acolo? Ca să supună toată lumea sub Nebucadnețar, ca să nu zică babilonienii: în mâna unui neam de nimic a dat [Dumnezeu] pe fiii Săi — căci caldeenii erau un neam de nimic, cum se spune «acest popor n-a existat [ca putere]» (Isaia 23:13), așa au tălmăcit înțelepții noștri în tratatul Hagiga. „Hașmal” — un înger cu acest nume; și-a văzut un fel de culoare a lui din mijlocul focului. Așa au spus înțelepții noștri (Hagiga 13a): s-a întâmplat cu un copil care expunea «lucrarea carului» și pricepea [sensul lui] Hașmal, și a ieșit foc din Hașmal și l-a mistuit; și au mai spus că cuvântul e compus: «ce e Hașmal? a zis Rabi Iuda: ființe de foc care vorbesc»; în altă învățătură: «uneori tăcute, uneori grăitoare — atunci când vorba iese din gura Celui Sfânt, tac; când vorba nu iese din gura Celui Sfânt, grăiesc», adică laudă și slăvesc Numele."},
 {author:"Metzudat David (sec. XVIII)", text:"„Vânt de vijelie venea de la miazănoapte” — e aluzie la regele Babilonului și la caldeeni, care sunt la miazănoapte de Țara lui Israel și vor veni asupra ei cu izbucnire de mânie. „Nor mare” — aluzie la întunericul necazurilor care vor veni asupra ei. „Foc orbitor” — aluzie la arderea Casei Domnului. „Lumină de jur împrejur” — în jurul acestor lucruri a văzut lumină și strălucire, aluzie că după toate necazurile vor fi înconjurați de lumina izbăvirii."},
]};
C["1:5"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Înfățișare de om aveau” — e de mirare, căci și chip de taur, de leu și de vultur le aveau [cf. Ezechiel 10:14]! Mi se pare, totuși, că fiindcă acesta [chipul de om] e temeiul/capul tuturor, profetul a lăudat carul prin el; și el [chipul de om] este chipul feței lui Iacov, patriarhul nostru (Bereșit Rabba 82:2)."},
]};
C["1:7"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Și scânteiau” — din strălucirea lor pare că ies din ele scântei, cum se spune în tratatul Ioma (37b): «și ea [regina Elena] a făcut un sfeșnic de aur...», căci atunci când răsare soarele ies din el scântei. „Kalal” — rafinat și strălucitor; Menahem îl leagă de «copt în foc» [Leviticul 2:14]."},
 {author:"Metzudat David (sec. XVIII)", text:"Picioarele erau strălucitoare și parcă aruncau scântei, ca o aramă rafinată, foarte strălucitoare, care parcă emite scântei."},
]};
C["1:10"] = {comm:[
 {author:"Radak (1160–1235)", text:"Și au mai spus [înțelepții noștri] că aceste patru chipuri corespundeau celor patru steaguri [din tabăra lui Israel în pustie]: la steagul lui Iuda era chip de leu, căci se spune «pui de leu, Iuda»; la steagul lui Ruben, chip de om, căci se spune despre el «a aflat mandragore în câmp», [faptă] proprie oamenilor; la steagul lui Efraim, chip de taur, căci se spune despre el «întâiul lui taur, slava lui»; la steagul lui Dan, chip de vultur, căci se spune «fie Dan șarpe pe drum» și «viperă zburătoare»."},
]};
C["1:15"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„O roată pe pământ” — pe pardoseala cerului. „Pentru cele patru fețe ale sale” — ale fiecărei ființe; sau roata însăși avea patru fețe. Înțelepții noștri au spus (Hagiga 13b): acesta e Sandalfon, care stă pe pământ și capul lui ajunge între ființe; dar, după sensul simplu al textului, învățăm că roțile erau patru."},
]};
C["1:24"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Ca sunetul apelor multe” — s-ar putea crede un sunet slab? De aceea se zice „ca sunetul lui Șadai”, sunetul lămurit în Scriptură: «glasul Domnului în putere, glasul Domnului sfărâmă cedrii» (Psalmul 29:4-5)."},
 {author:"Radak (1160–1235)", text:"„Ca sunetul lui Șadai” — adică puternic și tare; sau se referă la Dumnezeu Însuși, numit Șadai, adică «la grăirea Lui», cum a grăit pe muntele Sinai, unde se spune «glas mare» — și, așa cum acolo glasul, cu toată puterea lui, nu s-a auzit dincolo de tabăra lui Israel, tot așa orice glas de profeție nu se aude decât de cel căruia îi e destinat."},
]};
C["1:26"] = {comm:[
 {author:"Metzudat David (sec. XVIII)", text:"„Am văzut” — adică am văzut un lucru strălucitor ca piatra de safir, având forma unui tron; și pe forma tronului am văzut o înfățișare asemenea unui om, aluzie la Dumnezeu Însuși — dar a spus «înfățișare asemenea», ca să arate auzului că n-are, de fapt, nicio formă, ci [limbajul e doar] ca să se înțeleagă că Șechina se ridică de pe car, din Casa [Templului], ca un rege de pe tronul lui."},
]};
C["1:27"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Și am văzut ca Hașmal” — nu s-a dat îngăduință să se cerceteze acest verset (Hagiga 13a)."},
]};
C["1:28"] = {comm:[
 {author:"Radak (1160–1235)", text:"Au spus învățătorii noștri, de bună amintire, că Israel, în ziua dăruirii Legii, a văzut carul ceresc așa cum l-a văzut Ezechiel — până acolo încât «și cea mai neînsemnată dintre roabele lor a văzut [la Mare] ce a văzut Ezechiel, fiul lui Buzi»; și au spus că au văzut chip de taur în fața taberei lor, de aceea au făcut chipul vițelului [de aur]. Și mai spun că aceste chipuri erau la cele patru steaguri: la steagul lui Iuda chip de leu... [vezi mai sus, 1:10]."},
 {author:"Rashi (1040–1105)", text:"„Și am auzit un glas vorbind” — și ce a vorbit? [Urmează, în continuarea cărții.]"},
]};
C["3:12"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Și un vânt m-a ridicat” — după ce și-a sfârșit vorbele [Dumnezeu, către profet], a poruncit vântului să-l ridice la locul unde erau exilații."},
 {author:"Metzudat David (sec. XVIII)", text:"„Și un vânt m-a ridicat” — vântul m-a ridicat din locul unde stăteam, și am auzit în urma mea un glas, într-un zgomot mare, spunând «binecuvântat e slava DOMNULUI din locul Său» — ca și cum ar spune profetului: să nu crezi că, retrăgându-se Șechina din locul ei din Sfânta Sfintelor, slava Domnului nu va mai fi binecuvântată și slăvită cum era când se afla în locul ei din Sfânta Sfintelor; căci, măcar că s-a retras din locul ei, ea rămâne binecuvântată și slăvită — dar poporul lui Israel e cel care pierde prin retragerea Șechinei din mijlocul lor; slava Domnului Însuși rămâne mereu binecuvântată."},
 {author:"Radak (1160–1235)", text:"„Și am auzit în urma mea un glas, într-un zgomot mare, [spunând] binecuvântat e slava DOMNULUI din locul Său” — când vântul m-a ridicat, am auzit un glas în urma mea, în locul profeției unde mă aflam, și glasul spunea «binecuvântat e slava Domnului din locul Său», adică atunci când Șechina se retrage din locul ei de pe chivot, dintre cei doi cherubini — căci Israel era cel care-și micșora slava [divinei prezențe] fiind printre ei prin chipul gelozirii care provoacă gelozie [idolatria] — și e ca și cum slava Lui ar crește prin retragerea de la ei; iar cuvântul «binecuvântare» înseamnă creștere de bine și de slavă. Marele înțelept Rabi Moșe [Maimonide], de bună amintire, a tălmăcit «din locul Său» drept «potrivit rangului și măsurii existenței Sale [proprii]»."},
]};

module.exports = { C };
