const C = {};
C["2:20"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„DOMNUL este în Sălașul Său cel sfânt” — pregătit să [se] răzbune. „Să amuțească tot pământul înaintea Lui” — „has” e termen de tăcere și de amuțire a nimicirii [doliu]."},
 {author:"Radak (1160–1235)", text:"Nu tot așa e cu Domnul, căci El e Cel care dă duh în tot trupul, și măcar că este în Sălașul Lui cel sfânt — care e cerul — toți locuitorii pământului se tem înaintea Lui, căci El e Cel care veghează asupra lor și vede toate faptele lor, cum s-a spus «din ceruri a privit Domnul, a văzut pe toți fiii oamenilor»."},
]};
C["3:1"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Pentru șigionot” — unii îl tâlcuiesc ca în traducerea aramaică; dar, după cum se înțelege din context, [profetul] a cerut îndurare pentru sine, pentru că a vorbit cuvinte necumpătate, ca «de aceea slăbește Tora» [Habacuc 1:4] — a cârtit împotriva felului de judecată [al lui Dumnezeu]."},
 {author:"Metzudat David (sec. XVIII)", text:"„Pentru șigionot” — adică rugăciunea lui a fost făcută pentru că a greșit și s-a plâns împotriva Domnului, și de aceea s-a întors să se roage înaintea Lui și să-I spună lauda."},
 {author:"Radak (1160–1235)", text:"Această rugăciune e alcătuită pe calea unui psalm din Psalmi, de aceea spune „pentru șigionot”, ca „șigion al lui David” [Psalmul 7], și spune „Dirijorului, cu cântările mele”, și tot aici se folosește cuvântul „sela”, cuvânt care nu se găsește în toată Scriptura decât în această rugăciune și în cartea Psalmilor. Rugăciunea e despre necazul lui Israel în acest exil, povestind minunile și vitejiile pe care Dumnezeu le-a făcut pentru Israel din ziua când i-a izbăvit din Egipt, și se roagă, în chip profetic, ca tot așa să facă cu ei în acest exil, la ieșirea din exil și în războiul lui Gog și Magog."},
]};
C["3:2"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Am auzit veștile Tale și m-am temut” — [spun] că din veac Te-ai răzbunat mereu pe cei care Te-au mâniat, dar pe acest nelegiuit [actual] îl rabzi. „M-am temut” — am zis: cum s-a schimbat felul judecății din pricina păcatului lui Israel? „Lucrarea Ta, în mijlocul anilor, ține-o în viață” — lucrarea Ta cea dintâi, prin care ne-ai răzbunat de vrăjmașii noștri, în mijlocul anilor de necaz în care ne aflăm, adu-o la viață, trezește-o și întoarce-o, și în acești ani s-o faci cunoscută. „La mânie” — ca să Te mânii pe cei răi. „Adu-Ți aminte de îndurare” — adu-Ți aminte să ai milă de Israel."},
 {author:"Radak (1160–1235)", text:"Am auzit cuvântul profeției spunându-mi exilul cel lung care va fi pentru Israel în viitor, și m-am temut: cum va putea să stea atâția ani în mijlocul vrăjmașilor lui? De aceea mă rog înaintea Ta și zic: lucrarea Ta [Israel, pe care Tu l-ai lucrat] — ține-o în viață în mijlocul acestor ani lungi [de exil], ca să nu piară în mijlocul vrăjmașilor lui."},
]};
C["3:3"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Dumnezeu va veni de la Teman” — acum [profetul] Îi aduce aminte de lucrarea Lui cea dintâi, pe care o cere să fie trezită [din nou] — dragostea lui Israel și pedepsirea generațiilor vechi. Când ai venit să dai Tora, ai trecut mai întâi pe la Esau și Ismael, și ei n-au primit-o. „Teman” — Esau. „Paran” — Ismael, cum se spune «și a locuit în pustiul Paran» [Geneza 21:21]. „Gloria Sa a acoperit cerurile” — la Sinai, pentru Israel."},
 {author:"Radak (1160–1235)", text:"Acum povestește măririle și minunile pe care Dumnezeu le-a arătat lui Israel în pustie, ca să facă pentru ei la fel la ieșirea din exil — mai întâi când le-a dat Tora, cum se spune în Tora «și a răsărit din Seir pentru ei» [Deuteronomul 33:2], căci Teman este Seir; și la fel „din Muntele Paran”, cum se spune [acolo] «S-a arătat din Muntele Paran». „Gloria Sa a acoperit cerurile” — acestea sunt torțele văzute în ziua dăruirii Torei, care luminau cerul și pământul."},
]};
C["3:4"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Și strălucirea” — în ziua aceea. „Ca lumina va fi” — ca lumina cea deosebită a celor șapte zile ale creației, așa a fost, așa a tălmăcit și Ionatan. „Raze” [karnaim] — termen de „lumină”: când [lumina] pătrunde și strălucește printr-o deschizătură, pare un fel de raze proeminente, cum se spune «căci strălucea [karan] pielea feței lui» [Exodul 34:29]. „Din mâna Sa” — veneau pentru ei din mâna Celui Sfânt. „Și acolo puterea Lui ascunsă” — după cum tălmăcește: acolo s-a descoperit puterea Lui care fusese ascunsă mai înainte, într-un loc tainic, în înălțime."},
 {author:"Radak (1160–1235)", text:"„Și strălucirea, ca lumina va fi” — acesta e ceea ce s-a spus în Tora «și înfățișarea slavei Domnului era ca un foc mistuitor în vârful muntelui». „Raze din mâna Lui, pentru El” — acesta e faptul că fața lui Moise strălucea, adică acea strălucire venea de la Dumnezeu pentru Moise. Unii tălmăcesc „raze” despre cele două Table date lui Moise, care străluceau văzute și nevăzute. „Și acolo puterea Lui ascunsă” — acolo, la Sinai, s-a descoperit ce fusese ascuns de la puterea Lui până în ziua aceea, căci nu a fost zi ca aceea, înainte sau după, în care Dumnezeu să Se descopere în slava Lui cea mare pe Muntele Sinai, înaintea ochilor întregului Israel. Alții tâlcuiesc „puterea Lui ascunsă” despre Chivot, cum se spune despre el «Tu și Chivotul puterii Tale», și acolo erau tainele Tablelor."},
]};
C["3:5"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Înaintea Lui va merge molima” — am găsit într-un midraș agadic: în clipa când Cel Sfânt a dat Tora lui Israel, a îndepărtat pe Îngerul Morții să-l abată spre alte treburi, ca să nu stea să cârtească și să zică: «un neam care are să Te tăgăduiască la capătul a patruzeci de zile, și Tu le dai Tora?». „Și va ieși flacăra la picioarele Lui” — îngerii de flacără au venit cu El la Sinai."},
]};
C["3:6"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„S-a oprit și a măsurat țara” — a așteptat să cerceteze cu de-amănuntul judecata generației potopului, ca să le măsoare măsură pentru măsură. „A văzut” — generația împrăștierii [Babel], care, pentru că aveau o singură limbă, s-au unit cu toții într-un singur sfat [de răzvrătire], cum se scrie «și tot pământul avea o singură limbă» [Geneza 11:1]. „Și a împrăștiat neamurile” — i-a făcut să salte în șaptezeci de limbi. „Munții cei veșnici” — domnitorii neamurilor idolatre. „Căile lumii sunt ale Lui” — le-a arătat că tot mersul lumii Îi aparține."},
 {author:"Radak (1160–1235)", text:"Ionatan tălmăcește acest verset despre generația potopului și generația împrăștierii [Babel] — aceste generații care nu-L cunoșteau și socoteau că nu există Dumnezeu în lume; [El] le-a arătat că El este Stăpânul tuturor și veghează asupra tuturor. Și prin cuvântul „a măsurat” [se arată] că le-a măsurat măsură pentru măsură, cum au spus înțelepții noștri: cu [ape] clocotite au stricat [lumea], cu [ape] clocotite au fost judecați."},
]};
C["3:9"] = {comm:[
 {author:"Radak (1160–1235)", text:"Ai făcut toate acestea ca să împlinești jurămintele pe care le-ai jurat Patriarhilor, de a da țara triburilor lui Israel — aceasta e „omer sela”, adică spusa/legământul care se păstrează pecetluit pe veci."},
]};
C["3:11"] = {comm:[
 {author:"Radak (1160–1235)", text:"„Soarele, luna, s-au oprit în locul lor” — în zilele lui Iosua, în lupta cu regii [canaaniți], soarele și luna s-au oprit, fiecare în locuința sa, fără să-și urmeze mersul firesc, cum se scrie «și soarele s-a oprit, și luna a stat pe loc, până ce poporul s-a răzbunat pe vrăjmașii lui» [Iosua 10:13]. „La lumina săgeților Tale vor merge” — Iosua și poporul lui au mers la lumina fulgerelor și a pietrelor de grindină pe care Cel Sfânt le-a trimis asupra vrăjmașilor; aceasta a fost o minune în interiorul unei minuni, căci Iosua s-a rugat ca luna să se oprească „până ce se va răzbuna poporul pe vrăjmașii lui”, și astfel luna a luminat noaptea, laolaltă cu grindina, ca israeliții să poată continua lupta."},
]};
C["3:13"] = {comm:[
 {author:"Rashi (1040–1105)", text:"„Pentru izbăvirea unsului Tău” — Saul și David."},
 {author:"Radak (1160–1235)", text:"„Ai ieșit să izbăvești poporul Tău, să izbăvești pe unsul Tău” — precum ai ieșit să izbăvești poporul Tău la intrarea lor în Țară, [biruind] cele șapte neamuri, tot așa vei ieși în viitor să-i izbăvești și să-i scoți din exil și să-i aduci înapoi în țara lor. „Unsul Tău” — acesta este Mesia, fiul lui David."},
]};

module.exports = { C };
