module.exports = {
"55:6": ["Căutați pe Domnul, și când Îl veți găsi, chemați-L; iar când Se va apropia de voi,", "Corespondență strânsă cu Textul Masoretic."],
"55:7": ["să-și lase cel necredincios căile sale, și omul fărădelegii planurile sale, și să se întoarcă la Domnul, și va avea parte de milă, căci din belșug va lăsa [uitate] păcatele voastre.", "Corespondență strânsă cu Textul Masoretic."],
"55:8": ["Căci planurile Mele nu sunt ca planurile voastre, nici căile voastre [nu sunt] ca căile Mele, zice Domnul.", "Corespondență strânsă cu Textul Masoretic."],
"55:9": ["Ci precum e departe cerul de pământ, așa e departe calea Mea de căile voastre, și cugetele voastre de cugetul Meu.", "Corespondență strânsă cu Textul Masoretic."],
"55:10": ["Căci precum coboară ploaia sau zăpada din cer și nu se întoarce, până ce nu îmbată pământul, și îl face să nască și să încolțească, și dă sămânță semănătorului și pâine spre hrană,", "Corespondență strânsă cu Textul Masoretic."],
"55:11": ["așa va fi cuvântul Meu, care va ieși din gura Mea, nu se va întoarce, până ce nu se va împlini tot ce am voit, și voi face să propășească căile Mele și poruncile Mele.", "Corespondență strânsă cu Textul Masoretic."],
"55:12": ["Căci în veselie veți ieși și în bucurie veți fi învățați; căci munții și dealurile vor salta, așteptându-vă cu bucurie, și toți pomii câmpului vor bate din crengi,", "Corespondență apropiată cu Textul Masoretic; „veți fi învățați” (διδαχθήσεσθε) diferă ușor de „veți ajunge/veți fi conduși” (tuvalun) din ebraică."],
"55:13": ["și în locul mărăcinilor va crește chiparosul, iar în locul buruienii amare va crește mirtul; și va fi Domnul spre numele și spre semnul veșnic, și nu va lipsi.", "Divergență reală de subiect: Textul Masoretic spune că acest EVENIMENT va fi pentru Domnul un semn și un nume veșnic; Septuaginta pare să spună că DOMNUL ÎNSUȘI va fi „spre numele și spre semnul veșnic” — o schimbare subtilă a subiectului gramatical al frazei."],
"56:1": ["Așa zice Domnul: păziți judecata și faceți dreptate; căci s-a apropiat mântuirea Mea să vină, și mila Mea să se descopere.", "Divergență reală: Septuaginta are „mila Mea” (τὸ ἔλεός μου) unde Textul Masoretic are „dreptatea Mea” (tzidkati) — o schimbare de accent teologic, de la dreptate la milă."],
"56:2": ["Fericit bărbatul care face acestea, și omul care se ține de ele, și care păzește Sabatele ca să nu le profaneze, și care își păstrează mâinile ca să nu facă nedreptăți.", "Corespondență strânsă cu Textul Masoretic."],
"56:3": ["Să nu zică cel de alt neam, cel alipit de Domnul: mă va separa oare Domnul de poporul Lui; și să nu zică eunucul că sunt un lemn uscat.", "Corespondență strânsă cu Textul Masoretic."],
"56:4": ["Așa zice Domnul eunucilor: câți vor păzi Sabatele Mele și vor alege ce vreau Eu și se vor ține de legământul Meu,", "Corespondență strânsă cu Textul Masoretic."],
"56:5": ["le voi da în casa Mea și în zidul Meu un loc vestit, mai bun decât [cel al] fiilor și fiicelor; nume veșnic le voi da, și nu va lipsi.", "Corespondență strânsă cu Textul Masoretic."],
"56:6": ["și celor de alt neam, alipiți de Domnul ca să-I slujească și să iubească numele Domnului, ca să-I fie robi și roabe, și tuturor celor ce păzesc Sabatele Mele ca să nu le profaneze și se țin de legământul Meu,", "Corespondență strânsă cu Textul Masoretic."],
"56:7": ["îi voi aduce în muntele Meu cel sfânt și-i voi veseli în casa rugăciunii Mele; arderile lor de tot și jertfele lor vor fi primite pe altarul Meu; căci casa Mea casă de rugăciune se va chema pentru toate neamurile,", "Corespondență strânsă cu Textul Masoretic."],
"56:8": ["a zis Domnul, Cel ce adună pe cei risipiți ai lui Israel, că voi mai aduna la el o adunare.", "Corespondență strânsă cu Textul Masoretic."]
};
