// Date capitol 22 (Iom Kipur după-amiază, Iona 1-4 + Mica 7:18-20) - Standard Davar
module.exports = [
{v:"1:1", refs:["2 Împărați 14:25","Matei 12:39"], tok:[]},
{v:"1:2", refs:["Geneza 10:11","Naum 1:1","Țefania 2:13-15"], tok:[]},
{v:"1:3", refs:["Iona 4:2","Exodul 4:13,14","Isaia 23:1"], tok:[]},
{v:"1:4", refs:["Exodul 15:10","Psalmul 107:24-31","Amos 4:13"], tok:[]},
{v:"1:5", refs:["1 Împărați 18:26","Isaia 45:20"], tok:[]},
{v:"1:6", refs:["Psalmul 107:6,12,13","Iona 3:9"], tok:[]},
{v:"1:7", refs:["Iosua 7:14-18","1 Samuel 14:41,42","Proverbe 16:33"], tok:[]},
{v:"1:8", refs:["Iosua 7:19","1 Samuel 14:43"], tok:[]},
{v:"1:9", refs:["Geneza 14:13","Ezra 1:2","Psalmul 146:5,6"],
 tok:[
  ["Sunt evreu", 2, {d:"[sunt] un evreu (ivri).", x:"Metzudat Zion explică originea numelui: așa se numesc fiii lui Israel, pentru că neamul lor își are originea „de peste râu” [Eufrat], de la Avraam care a venit din Mesopotamia. Radak adaugă: prin acest singur răspuns, Iona a lămurit de fapt toate întrebările marinarilor deodată — numindu-și poporul și țara, și, spunând că se teme de Domnul, Dumnezeul cerurilor, a arătat limpede că fuga lui nu are nicio legătură cu vreo faptă rea față de oameni, ci cu porunca lui Dumnezeu Însuși."}],
 ]},
{v:"1:10", refs:["Geneza 31:26","Iona 1:3"], tok:[]},
{v:"1:11", refs:["1 Samuel 6:2,3","Mica 6:6,7"], tok:[]},
{v:"1:12", refs:["2 Samuel 24:17","Ioan 11:50"], tok:[]},
{v:"1:13", refs:["Iov 34:29","Proverbe 21:30"], tok:[]},
{v:"1:14", refs:["Geneza 9:6","Psalmul 115:3","Daniel 4:34"], tok:[]},
{v:"1:15", refs:["Psalmul 89:9","Psalmul 93:3,4","Matei 8:26"], tok:[]},
{v:"1:16", refs:["Isaia 26:9","Daniel 6:26","Eclesiastul 5:4"], tok:[]},
{v:"2:1", refs:["Iona 4:6","Geneza 1:21","Matei 12:40"], tok:[]},
{v:"2:2", refs:["2 Cronici 33:11-13","Psalmul 50:15","Osea 5:15"], tok:[]},
{v:"2:3", refs:["Psalmul 18:5,6","Psalmul 120:1","Psalmul 130:1,2"], tok:[]},
{v:"2:4", refs:["Psalmul 42:7","Psalmul 69:1,2"], tok:[]},
{v:"2:5", refs:["Psalmul 31:22","Isaia 38:10-14","1 Împărați 8:38,39"],
 tok:[
  ["Am fost izgonit", 2, {d:"am fost izgonit/respins (nigrashti).", x:"Rashi explică momentul acestei rugăciuni: atunci când [marinarii] l-au aruncat în mare, Iona a crezut pentru o clipă că moare și că a fost izgonit dinaintea ochilor Domnului, fără scăpare — dar, observând chiar faptul că supraviețuiește în adâncuri, trage concluzia opusă: dacă Domnul l-a ținut în viață atâtea zile, înseamnă că va mai privi din nou spre Templul Său cel sfânt."}],
 ]},
{v:"2:6", refs:["Deuteronomul 32:22","Psalmul 65:6","Habacuc 3:6,10"], tok:[]},
{v:"2:7", refs:["Iov 33:24,28","Psalmul 30:3,9","Psalmul 16:10"], tok:[]},
{v:"2:8", refs:["Psalmul 18:6","Psalmul 42:5,11","Plângerile lui Ieremia 3:21-26"], tok:[]},
{v:"2:9", refs:["1 Samuel 12:21","2 Împărați 17:15","Ieremia 2:13"],
 tok:[
  ["Cei ce veghează asupra deșertăciunilor", [0,1,2], {d:"cei ce păzesc/veghează asupra deșertăciunilor mincinoase (meșamrim havlei șav).", x:"Rashi tâlcuiește: aceștia sunt cei care slujesc idolilor — frica de Cel Sfânt pe care și-ar fi putut-o însuși prin ea se lipsesc singuri de toată bunăvoința pe care Domnul le-ar fi arătat-o. O tradiție din Pirkei de-Rabi Eliezer leagă versetul direct de marinarii corăbiei: văzând minunile petrecute cu Iona, aceștia și-au aruncat în mare, fiecare, idolul lui, și s-au întors la Iafo să se facă prozeliți — ei fiind cei care „au părăsit bunăvoința lor” [idolatria] ca să se întoarcă la adevăr."}],
 ]},
{v:"2:10", refs:["Geneza 35:3","Psalmul 50:14,23","Osea 14:2"], tok:[]},
{v:"2:11", refs:["Geneza 1:3-14","Isaia 50:2","Matei 8:8,9"], tok:[]},
{v:"3:1", refs:["Iona 1:1","Ioan 21:15-17"], tok:[]},
{v:"3:2", refs:["Ieremia 1:17","Ezechiel 3:17","Matei 3:8"], tok:[]},
{v:"3:3", refs:["Geneza 30:8","Psalmul 36:6"], tok:[]},
{v:"3:4", refs:["Iona 3:10","Deuteronomul 18:22","Ieremia 18:7-10"],
 tok:[
  ["va fi răsturnată", 13, {d:"va fi răsturnată/prefăcută (nehefahet).", x:"Rashi observă o ambiguitate intenționată a cuvântului profetic: Iona n-a spus „va fi nimicită”, ci „va fi răsturnată/prefăcută” — un cuvânt care slujește deopotrivă pentru rău și pentru bine. Dacă nu se vor pocăi, cetatea va fi distrusă; dacă se vor pocăi, va fi „prefăcută” din rău în bine — dubla valență a cuvântului ascunzând, de la început, posibilitatea mântuirii pe care Iona însuși se temea s-o vadă împlinită."}],
 ]},
{v:"3:5", refs:["Exodul 9:18-21","Matei 12:41","Ioel 2:12-17"], tok:[]},
{v:"3:6", refs:["Estera 4:1-4","Iov 42:6","Daniel 9:3"], tok:[]},
{v:"3:7", refs:["Iona 3:5","Ezra 8:21","Ioel 2:15,16"], tok:[]},
{v:"3:8", refs:["Isaia 1:16-19","Isaia 55:6,7","Ezechiel 33:11"], tok:[]},
{v:"3:9", refs:["Iona 1:6","2 Samuel 12:22","Ioel 2:13,14"], tok:[]},
{v:"3:10", refs:["1 Împărați 21:27-29","Ieremia 18:8","Amos 7:3,6"], tok:[]},
{v:"4:1", refs:["Iona 4:9","Iacov 4:5,6"], tok:[]},
{v:"4:2", refs:["Exodul 34:6,7","Osea 11:8,9","Mica 7:18"],
 tok:[
  ["Dumnezeu binevoitor și milos", [22,23,24,25,26,27,28], {d:"Dumnezeu [plin de] bunăvoință și milă (El chanun verachum).", x:"Radak notează că Iona citează aici, aproape cuvânt cu cuvânt, formula celor treisprezece atribute ale îndurării divine descoperite lui Moise (Exodul 34:6-7) — exact aceeași bunăvoință pe care o aștepta Israel pentru sine, Iona o vede acum revărsată, din plin, asupra unei cetăți păgâne, și tocmai această generozitate neîngrădită e sursa adevărată a amărăciunii lui."}],
 ]},
{v:"4:3", refs:["Numeri 11:15","1 Împărați 19:4","Eclesiastul 7:1"], tok:[]},
{v:"4:4", refs:["Numeri 20:11,12","Mica 6:3","Iacov 1:19,20"], tok:[]},
{v:"4:5", refs:["Geneza 19:27,28","Ieremia 17:15,16"], tok:[]},
{v:"4:6", refs:["Iov 1:21","Psalmul 102:10","Psalmul 103:10-14"],
 tok:[
  ["vrej", 3, {d:"vrej, plantă cu foi mari și umbrite (kikaion).", x:"Radak descrie planta pe baza unei tradiții primite de la înțelepți: crește rapid, cu ramuri late, dă umbră bună, și din sămânța ei se face untdelemn — numită în arabă „al-kharwa”, folosită de cei bolnavi de răceală; un alt nume citat e „tzlulliva”, un arbust care crește des pe lângă pâraie și pe la porțile prăvăliilor, unde e ridicat special pentru umbra pe care o oferă."}],
 ]},
{v:"4:7", refs:["Psalmul 90:5,6","Isaia 40:6-8","Ioel 1:12"], tok:[]},
{v:"4:8", refs:["Psalmul 121:6","Cântarea cântărilor 1:6","Apocalipsa 7:16"], tok:[]},
{v:"4:9", refs:["Geneza 4:5-14","Iov 18:4","Iov 40:4,5"], tok:[]},
{v:"4:10", refs:["1 Samuel 20:31","Geneza 17:12"], tok:[]},
{v:"4:11", refs:["Isaia 1:18","Deuteronomul 1:39","Luca 15:28-32"],
 tok:[
  ["nu știu dreapta de stânga", [18,19,20], {d:"nu cunosc între dreapta lor și stânga lor (lo iada bein iemino lismolo).", x:"Rashi explică „mici” prin acest termen: sunt copiii din Ninive, prea mici pentru a avea răspundere morală — iar „vite multe” sunt, printr-o lectură mai acidă, chiar oamenii maturi ai cetății, numiți „vite” pentru că, în pofida vârstei, mintea lor rămâne la nivelul unui animal, necunoscând pe Cel care i-a creat; chiar și pentru aceștia, Domnul arată milă."}],
 ]},
{v:"7:18", refs:["Exodul 15:11","Exodul 34:6,7","Mica 2:12"],
 tok:[
  ["Cine-i ca Tine", [0,1,2], {d:"cine [este] Dumnezeu ca Tine (mi El kamocha).", x:"Un ecou direct al numelui profetului însuși — „Mica” fiind o formă abreviată a întrebării „Mi-cha-El” („cine e ca Dumnezeu”) — făcând din acest verset final al cărții un joc de cuvinte intenționat cu propriul nume al profetului, legat totodată de rugăciunea lui Iona despre același atribut divin al îndurării."}],
 ]},
{v:"7:19", refs:["Psalmul 103:12","Isaia 38:17","Daniel 9:24"],
 tok:[
  ["va azvârli în adâncurile mării", [4,5,6], {d:"va azvârli în adâncurile mării (vetașlich bimtzulot iam).", x:"Metzudat David explică sensul figurat: nu se va mai aduce aminte să pedepsească pentru aceste păcate, ca și cum le-ar fi aruncat în fundul mării, de unde nu mai pot fi văzute — această imagine a stat la temelia obiceiului practicat în ziua de Roș Hașana, numit după chiar acest verset, de a privi către o apă curgătoare recitând cuvintele profetului."}],
 ]},
{v:"7:20", refs:["Geneza 17:7,8","Geneza 22:16-18","Luca 1:72-74"],
 tok:[
  ["Dă adevăr lui Iacov", [0,1,2], {d:"dă/împlinește adevărul [promis] lui Iacov (titen emet leIaakov).", x:"Rashi explică dubla structură a versetului: „adevărul” cerut pentru Iacov este împlinirea exactă a făgăduinței de la Betel („nu te voi părăsi”), iar „bunătatea” cerută pentru Avraham este răsplata pentru porunca pe care acesta a lăsat-o fiilor lui, „să păzească calea Domnului, înfăptuind dreptate și judecată” — de aceea nu se spune simplu „bunătate”, ci „bunătatea adevărului”, pentru că adevărul care confirmă făgăduința lui Iacov este chiar plata cuvenită faptei bune a lui Avraham."}],
 ]},
];
