module.exports = {
"8:54": ["Și a fost, când Solomon a încheiat să se roage Domnului toată această rugăciune și cerere, și s-a ridicat de dinaintea altarului Domnului, plecat pe genunchii lui, și mâinile lui întinse spre cer.", "Corespondență strânsă cu Textul Masoretic."],
"8:55": ["și a stat și a binecuvântat toată adunarea lui Israel cu glas mare, spunând:", "Corespondență strânsă cu Textul Masoretic."],
"8:56": ["binecuvântat [este] Domnul, astăzi, care a dat odihnă poporului Său Israel, după toate cele câte a grăit; n-a lipsit niciun cuvânt din toate cuvintele Lui cele bune, pe care le-a grăit prin mâna robului Său Moise.", "Mică divergență prin adăugire: Septuaginta are „astăzi” (σήμερον), absent din Textul Masoretic la acest verset."],
"8:57": ["să fie Domnul Dumnezeul nostru cu noi, precum a fost cu părinții noștri; să nu ne lase și să nu ne întoarcă [fața Lui] de la noi,", "Corespondență strânsă cu Textul Masoretic."],
"8:58": ["ca să ne încline inimile spre El, să mergem în toate căile Lui, și să păzim toate poruncile Lui și orânduirile Lui, pe care le-a poruncit părinților noștri.", "Corespondență strânsă cu Textul Masoretic."],
"8:59": ["și să fie aceste cuvinte, cu care m-am rugat înaintea Domnului Dumnezeului nostru, aproape de Domnul Dumnezeul nostru ziua și noaptea, ca să facă dreptatea robului Tău și dreptatea poporului Israel, cuvântul fiecărei zile, în ziua anului,", "Mică divergență de nuanță: ultima frază, „cuvântul fiecărei zile, în ziua anului”, diferă puțin de Textul Masoretic „nevoia fiecărei zile în acea zi” — traducătorii greci par să fi redat termenul ebraic mai degrabă ca pe un ciclu anual decât ca pe o recurență strict zilnică."],
"8:60": ["ca să cunoască toate popoarele pământului că Domnul [este] Dumnezeu, El [este] Dumnezeu și nu mai este altul.", "Corespondență strânsă cu Textul Masoretic."],
"8:61": ["și inimile noastre să fie desăvârșite către Domnul Dumnezeul nostru, și să mergem cu sfințenie în orânduirile Lui, și să păzim poruncile Lui, ca în ziua aceasta.", "Corespondență strânsă cu Textul Masoretic."],
"8:62": ["Și regele și toți fiii lui Israel au jertfit jertfă înaintea Domnului.", "Corespondență strânsă cu Textul Masoretic."],
"8:63": ["și a jertfit regele Solomon jertfele de pace, pe care le-a jertfit Domnului, douăzeci și două de mii de boi și o sută douăzeci de mii de oi; și a sfințit Casa Domnului regele și toți fiii lui Israel.", "Corespondență strânsă cu Textul Masoretic."],
"8:64": ["în ziua aceea a sfințit regele mijlocul curții, cea dinaintea Casei Domnului; căci acolo a înfăptuit arderea-de-tot și jertfele și grăsimile jertfelor de pace, pentru că altarul de bronz, cel dinaintea Domnului, [era] mic, ca să nu poată duce arderea-de-tot și jertfele de pace.", "Corespondență strânsă cu Textul Masoretic."],
"8:65": ["și a făcut Solomon sărbătoarea în ziua aceea, și tot Israel cu el, o adunare mare, de la intrarea Ematului până la râul Egiptului, înaintea Domnului Dumnezeului nostru, în Casa pe care a zidit-o, mâncând și bând și veselindu-se înaintea Domnului Dumnezeului nostru șapte zile.", "Divergență numerică reală și importantă, discutată în studiile biblice: Septuaginta are o singură perioadă de „șapte zile”, unde Textul Masoretic are „șapte zile și [încă] șapte zile, paisprezece zile [în total]” — mulți cercetători citează această diferență ca dovadă că dubla mențiune din textul ebraic ar putea fi o adăugire ulterioară, menită să armonizeze cele șapte zile de sfințire a Templului cu cele șapte zile ale Sărbătorii Corturilor care le urmează imediat."],
"8:66": ["și în ziua a opta a trimis poporul, și l-au binecuvântat pe rege, și a plecat fiecare la corturile lui, bucurându-se și cu inimă bună pentru bunătățile pe care le-a făcut Domnul lui David, robul Lui, și lui Israel, poporul Lui.", "Corespondență strânsă cu Textul Masoretic."],
"9:1": ["Și a fost, când a încheiat Solomon să zidească Casa Domnului și casa regelui, și toată lucrarea lui Solomon, câte a voit să facă,", "Mică divergență de nuanță: Septuaginta are „lucrarea” (πραγματεία) unde Textul Masoretic are „heșek” (dorința/plăcerea) — un termen mai neutru, administrativ, în loc de nuanța de dorință personală intensă din ebraică."]
};
